sfSandBoxCode/force-app/main/default/objects/Casual__c/Casual__c.object-meta.xml
<CustomObject>
    <description>Casuals</description>
    <label>Contractor</label>
    <nameField>
        <label>Contractor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected should be a vendor account</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Casuals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Contractual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contractual_End_Date__c</fullName>
    <label>Contractual End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Contractual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contractual_Start_Date__c</fullName>
    <label>Contractual Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Laborer</fullName>
            </value>
            <value>
                <fullName>Night Watchman</fullName>
            </value>
            <value>
                <fullName>Driver (Cars &amp; Light Vans)</fullName>
            </value>
            <value>
                <fullName>Driver (Heavy Commercial Vehicle)</fullName>
            </value>
            <value>
                <fullName>Ungraded Artisan</fullName>
            </value>
            <value>
                <fullName>Artisan Grade III</fullName>
            </value>
            <value>
                <fullName>Artisan Grade II</fullName>
            </value>
            <value>
                <fullName>Artisan Grade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <label>ID Number</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/Casual_Job_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contractor Job Specification</label>
    <nameField>
        <displayFormat>JOB-SPEC-{0000}</displayFormat>
        <label>Job Specification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/fields/Casuals_Job__c.field-meta.xml
<CustomField>
    <fullName>Casuals_Job__c</fullName>
    <label>Contractors Job</label>
    <referenceTo>Casuals_Job__c</referenceTo>
    <relationshipName>Casual_Job_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Laborer</fullName>
            </value>
            <value>
                <fullName>Night Watchman</fullName>
            </value>
            <value>
                <fullName>Driver (Cars &amp; Light Vans)</fullName>
            </value>
            <value>
                <fullName>Driver (Heavy Commercial Vehicle)</fullName>
            </value>
            <value>
                <fullName>Ungraded Artisan</fullName>
            </value>
            <value>
                <fullName>Artisan Grade III</fullName>
            </value>
            <value>
                <fullName>Artisan Grade II</fullName>
            </value>
            <value>
                <fullName>Artisan Grade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job__c/Casuals_Job__c.object-meta.xml
<CustomObject>
    <label>Contractors Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractors Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Teamlead__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Contractors Jobs</relationshipLabel>
    <relationshipName>Casuals_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Job end date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Job Start date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/Casuals_Job_Assignment__c.object-meta.xml
<CustomObject>
    <label>Job Spec Assignment</label>
    <nameField>
        <displayFormat>JOB-ASSG-{000000}</displayFormat>
        <label>Job Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor-Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual__c.field-meta.xml
<CustomField>
    <fullName>Casual__c</fullName>
    <label>Contractor Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please ensure this contractor does not have any open jobs</errorMessage>
        <filterItems>
            <field>Casual__c.Grade__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Casual__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Job_Requisitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Night Watchman</fullName>
            </value>
            <value>
                <fullName>Driver (Cars &amp; Light Vans)</fullName>
            </value>
            <value>
                <fullName>Driver (Heavy Commercial Vehicle)</fullName>
            </value>
            <value>
                <fullName>Ungraded Artisan</fullName>
            </value>
            <value>
                <fullName>Artisan Grade III</fullName>
            </value>
            <value>
                <fullName>Artisan Grade II</fullName>
            </value>
            <value>
                <fullName>Artisan Grade</fullName>
            </value>
            <value>
                <fullName>General Laborer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/Casuals_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Assignment Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Developments</fullName>
            </value>
            <value>
                <fullName>By-Product Sales</fullName>
            </value>
            <value>
                <fullName>By-Products Development</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Directors</fullName>
            </value>
            <value>
                <fullName>Engineering Operations</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Government Relations</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Insights and Innovations</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Logistics and Operations</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing and Branding</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Quality Health Safety &amp; Environment</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales and Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <inlineHelpText>End Date</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/fields/Teamlead__c.field-meta.xml
<CustomField>
    <fullName>Teamlead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teamlead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FFA_Config_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CasualTriggersTest.cls
@isTest(seealldata=true)
public class CasualTriggersTest {
    
    static testMethod void testCasualTriggers(){
        
        List<FFA_Config_Object__c> dept=[SELECT ID,Teamlead__c  
                                         FROM FFA_Config_Object__c 
                                         WHERE Type__c='dim1' AND Teamlead__c <> null AND isActive__c=true  
                                         AND Name='Administration'
                                         LIMIT 1];
        
        List<FFA_Config_Object__c> loc=[SELECT ID,Teamlead__c  
                                        FROM FFA_Config_Object__c 
                                        WHERE Type__c='dim2' AND isActive__c=true LIMIT 1];
        
        List<FFA_Config_Object__c> notApp=[SELECT ID,Teamlead__c  
                                           FROM FFA_Config_Object__c 
                                           WHERE Type__c='dim3' AND isActive__c=true LIMIT 1];
        
        List<FFA_Config_Object__c> grant=[SELECT ID,Teamlead__c  
                                          FROM FFA_Config_Object__c 
                                          WHERE Type__c='dim4' AND isActive__c=true AND (not Name like '%XXX') LIMIT 1];
        
        List<Employee__c> empList=[SELECT ID FROM Employee__c WHERE Work_Email__c <> null LIMIT 1]; 
        
        List<Account> ac=[SELECT Id,Name FROM Account WHERE Type='Vendor' LIMIT 1];
        
        if(ac.size()>0){
            
            if(dept.size()>0){  
                
                if(empList.size()>0){
                    
                    if(loc.size()>0){
                        
                        if(notApp.size()>0){
                            
                            if(grant.size()>0){
                                
                                Casual__c cas=new Casual__c();
                                
                                cas.Account__c = ac.get(0).Id;
                                cas.Contractual_Start_Date__c = date.today();
                                cas.Contractual_End_Date__c = date.today();
                                cas.ID_Number__c = '12243543';
                                cas.Grade__c = 'General Laborer';
                                
                                insert cas;
                                
                                Casuals_Job__c cJob=new Casuals_Job__c();
                                
                                cJob.Department__c=dept.get(0).Id;
                                cJob.Start_Date__c=date.today();
                                cJob.End_Date__c=date.today();
                                cJob.Company__c='Sanergy Ltd';
                                
                                insert cJob;
                                
                                FFA_Config_Object__c gla=[SELECT Id FROM FFA_Config_Object__c 
                                                          WHERE Type__c='gla' 
                                                          AND Name='2000 - Accounts Payable Control'
                                                          AND isActive__c=true LIMIT 1];
                                
                                Casual_Job_Line_Item__c spec=new Casual_Job_Line_Item__c();
                                
                                spec.Casuals_Job__c = cJob.Id;
                                spec.Department_Dim_1__c = dept.get(0).Id;
                                spec.Dim3__c = notApp.get(0).Id;
                                spec.Grant_Dim_4__c = grant.get(0).Id;
                                spec.Location_Dim_2__c = loc.get(0).Id;
                                spec.Start_Date__c = date.today();
                                spec.End_Date__c = date.today();
                                spec.Grade__c = 'General Laborer';
                                spec.Number_Of_Casuals__c = 1;
                                spec.Rate__c = 500;
                                spec.Rate_Units__c='Per Day';
                                spec.Quantity__c = 1;
                                spec.Allowance_Per_Person__c = 1000;
                                spec.Allowance_Description__c = 'Lunch';
                                spec.GLA__c = gla.Id;                    
                                insert spec; 
                                
                                Casuals_Job_Assignment__c assign = new Casuals_Job_Assignment__c();
                                
                                assign.Casual_Job_Line_Item__c = spec.Id;
                                assign.Casual__c = cas.Id;
                                
                                insert assign;
                                
                                Casuals_Timesheet__c tSheet = new Casuals_Timesheet__c();
                                
                                tSheet.Job_Requisition__c = assign.Id;
                                tSheet.Start_Date__c = date.today();
                                tSheet.End_Date__c = date.today();
                                tSheet.Total_Allowancess__c = 0;
                                tSheet.Rate_Units_Quantity__c = 1;
                                
                                insert tSheet;
                                
                                tSheet.Total_Allowancess__c = 200;
                                
                                update tSheet;
                                
                                spec.Allowance_Per_Person__c = null;
                                
                                update spec;
                            }
                        }
                    }
                }
            }
        }
    }
}