sfSandBoxCode/force-app/main/default/objects/Casual__c/Casual__c.object-meta.xml
<CustomObject>
    <description>Casuals</description>
    <label>Contractor</label>
    <nameField>
        <label>Contractor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected should be a vendor account</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Casuals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Laborer</fullName>
            </value>
            <value>
                <fullName>Night Watchman</fullName>
            </value>
            <value>
                <fullName>Driver (Cars &amp; Light Vans)</fullName>
            </value>
            <value>
                <fullName>Driver (Heavy Commercial Vehicle)</fullName>
            </value>
            <value>
                <fullName>Ungraded Artisan</fullName>
            </value>
            <value>
                <fullName>Artisan Grade III</fullName>
            </value>
            <value>
                <fullName>Artisan Grade II</fullName>
            </value>
            <value>
                <fullName>Artisan Grade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/Casuals_Job_Assignment__c.object-meta.xml
<CustomObject>
    <label>Job Spec Assignment</label>
    <nameField>
        <displayFormat>JOB-ASSG-{000000}</displayFormat>
        <label>Job Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor-Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Assignment_Department__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Department__c</fullName>
    <formula>Casual_Job_Line_Item__r.Department_Dim_1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment Department</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual__c.field-meta.xml
<CustomField>
    <fullName>Casual__c</fullName>
    <label>Contractor Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please ensure this contractor does not have any open jobs</errorMessage>
        <filterItems>
            <field>Casual__c.Grade__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Casual__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Job_Requisitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual_Job_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Casual_Job_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Specification</label>
    <referenceTo>Casual_Job_Line_Item__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Casual_Job_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Night Watchman</fullName>
            </value>
            <value>
                <fullName>Driver (Cars &amp; Light Vans)</fullName>
            </value>
            <value>
                <fullName>Driver (Heavy Commercial Vehicle)</fullName>
            </value>
            <value>
                <fullName>Ungraded Artisan</fullName>
            </value>
            <value>
                <fullName>Artisan Grade III</fullName>
            </value>
            <value>
                <fullName>Artisan Grade II</fullName>
            </value>
            <value>
                <fullName>Artisan Grade</fullName>
            </value>
            <value>
                <fullName>General Laborer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>Payment rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Payment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/Casuals_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Assignment Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/EPR__c.field-meta.xml
<CustomField>
    <fullName>EPR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EPR</label>
    <referenceTo>Electronic_Payment_Request__c</referenceTo>
    <relationshipLabel>Assignment Timesheets</relationshipLabel>
    <relationshipName>Assignment_Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/EPR_Created__c.field-meta.xml
<CustomField>
    <fullName>EPR_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPR Created</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Job_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Job_Requisition__c</fullName>
    <label>Job Assignment</label>
    <referenceTo>Casuals_Job_Assignment__c</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <formula>Job_Requisition__r.Casual_Job_Line_Item__r.Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Rate_Units__c.field-meta.xml
<CustomField>
    <fullName>Rate_Units__c</fullName>
    <formula>TEXT(  Job_Requisition__r.Casual_Job_Line_Item__r.Rate_Units__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Units</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Rate_Units_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Rate_Units_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Hours, Days, Weeks OR Months within which the Job was done</description>
    <inlineHelpText>Hours, Days, Weeks OR Months within which the Job was done</inlineHelpText>
    <label>Number Of Rate Units</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Actual Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/Electronic_Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Electronic Payment Request</label>
    <nameField>
        <displayFormat>EPR-{0000}</displayFormat>
        <label>Electronic Payment Request name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/department__c.field-meta.xml
<CustomField>
    <fullName>department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>xx</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/EPR_Payable_Item__c.object-meta.xml
<CustomObject>
    <label>EPR Payable Item</label>
    <nameField>
        <displayFormat>EPR ITEM-{0000}</displayFormat>
        <label>EPR Payable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPR Payable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/EPR__c.field-meta.xml
<CustomField>
    <fullName>EPR__c</fullName>
    <label>Electronic Payment Request</label>
    <referenceTo>Electronic_Payment_Request__c</referenceTo>
    <relationshipLabel>EPR Payable Items</relationshipLabel>
    <relationshipName>EPR_Payable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The General Ledger Account</description>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (GLA)</relationshipLabel>
    <relationshipName>EPR_Payable_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateEPRFromContractorAssignment.cls
public class CreateEPRFromContractorAssignment {
    /*
      private ApexPages.StandardController standardController;
      private Casual__c contractor;
      public List<TimesheetWrapper> timesheets {get; set;}
    
        public CreateEPRFromContractorAssignment(ApexPages.StandardController standardController){
            this.standardController = standardController;
            this.contractor = (Casual__c)standardController.getRecord();
            getProducts();
            
        }
        
         public PageReference selectAll() {
            if(timesheets!=null){
                for(TimesheetWrapper ts: timesheets){
                    ts.selected=true;
                }
            }
            return null;
        }
        
        public PageReference unselectAll() {
            if(timesheets!=null){
                for(TimesheetWrapper ts: timesheets){
                    ts.selected=false;
                }
            }
            return null;
        }
        
        public void getProducts() {
        
            timesheets= new List<TimesheetWrapper>();
            
             List<Casuals_Timesheet__c > timeSheetsFetched= [Select name, Job_Requisition__r.Assignment_Department__c,epr__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Company__c,
                                                      Job_Requisition__r.Casual__r.account__c,Rate__c,Rate_Units__c,Rate_Units_Quantity__c,
                                                      Start_Date__c,End_Date__c, Job_Requisition__r.Grade__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.Location_Dim_2__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.Dim3__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.Grant_Dim_4__c,
                                                      Job_Requisition__r.Casual_Job_Line_Item__r.GLA__c,
                                                      Job_Requisition__r.Job_Status__c,Total_Amount__c,EPR_Created__c,
                                                      Job_Requisition__r.name, Job_Requisition__r.Casual_Job_Line_Item__r.General_Description__c
                                                      FROM Casuals_Timesheet__c 
                                                      WHERE Job_Requisition__r.Casual__c = :contractor.Id AND EPR__c=null];
                                                              
            
            for(Casuals_Timesheet__c ts: timeSheetsFetched){
                TimesheetWrapper wrapper = new TimesheetWrapper(ts);
                timesheets.add(wrapper );
            }        
        }
        
        public PageReference createEPR(){        
            
            if(timesheets != null && timesheets.size() > 0){
            
                List<Electronic_Payment_Request__c> eprs=new List<Electronic_Payment_Request__c>();
                List<EPR_Payable_Item__c> eprLines=new List<EPR_Payable_Item__c>();
                List<Casuals_Timesheet__c > tsToUpdate=new List<Casuals_Timesheet__c >();
                
                Integer selected = 0;
                
                for(TimesheetWrapper ts: timesheets){                    
                    if(ts.selected == true ){ 
                                              
                         Electronic_Payment_Request__c epr = new Electronic_Payment_Request__c(
                             
                             department__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c,
                             Vendor_Company__c = ts.timesheet.Job_Requisition__r.Casual__r.account__c,
                             Invoice_Number__c = ts.timesheet.name,
                             Company__c=ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Company__c,
                             Scheduled_Payment_Date__c = date.today(),
                             Notes__c='Payment for Contractor for Timesheet '+ts.timesheet.name+'. ('+ts.timesheet.Rate__c+' '+ts.timesheet.Rate_Units__c+' * '+ts.timesheet.Rate_Units_Quantity__c+')',
                             Payment_Type__c = 'Payment on Invoice'                                 
                          );  
                          
                         insert epr;                          
                         eprs.add(epr);
                            
                        EPR_Payable_Item__c payableItem = new EPR_Payable_Item__c(
                            
                            epr__c=epr.id,
                            Department_dim1__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c,
                            Location_Dim2__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Location_Dim_2__c,
                            Dim_3__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Dim3__c,
                            Grant_Funding_Availale_dim4__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Grant_Dim_4__c, 
                            Item__c = epr.Notes__c,
                            Quantity__c = 1,
                            Unit_Price__c = ts.timesheet.Total_Amount__c,
                            GLA__c = ts.timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.GLA__c
                            
                        );
                        
                         eprLines.add(payableItem); 
                         ts.timesheet.epr__c=epr.id;
                         ts.timesheet.EPR_Created__c=true;
                         tsToUpdate.add(ts.timesheet);                      
                         selected ++;
                      }
                    }                
                
                    if(selected <= 0){
                        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'No timesheet was selected.');
                        ApexPages.addmessage(msg);                    
                        return null;  
                    } else{
                   
                       insert eprLines;
                       update tsToUpdate;
                       return new PageReference('/' + contractor.Id);
                    }
            }
            else{
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'There is not timesheet to process.');
                ApexPages.addmessage(msg);                    
                return null;  
            }
                       
        }
        
         public class TimesheetWrapper{
            public Casuals_Timesheet__c timesheet {get; set;}
            public Boolean selected {get; set;}
           
            public TimesheetWrapper(Casuals_Timesheet__c ts){
                this.timesheet=ts;
                selected = true;
            }
        }      
*/
}