sfSandBoxCode/force-app/main/default/objects/Casual__c/Casual__c.object-meta.xml
<CustomObject>
    <description>Casuals</description>
    <label>Contractor</label>
    <nameField>
        <label>Contractor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected should be a vendor account</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Casuals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <label>ID Number</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/Casual_Job_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contractor Job Specification</label>
    <nameField>
        <displayFormat>JOB-SPEC-{0000}</displayFormat>
        <label>Job Specification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/fields/Location_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Dim_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Casual_Job_Line_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate For Each Contractor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casual_Job_Line_Item__c/fields/Rate_Units__c.field-meta.xml
<CustomField>
    <fullName>Rate_Units__c</fullName>
    <label>Rate Units</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Per Hour</fullName>
            </value>
            <value>
                <fullName>Per Day</fullName>
            </value>
            <value>
                <fullName>Per Week</fullName>
            </value>
            <value>
                <fullName>Per Month</fullName>
            </value>
            <value>
                <fullName>Per Job</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/Casuals_Job_Assignment__c.object-meta.xml
<CustomObject>
    <label>Job Spec Assignment</label>
    <nameField>
        <displayFormat>JOB-ASSG-{000000}</displayFormat>
        <label>Job Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor-Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Amount_Payable__c.field-meta.xml
<CustomField>
    <fullName>Amount_Payable__c</fullName>
    <formula>(Casual_Job_Line_Item__r.Rate__c  *  Casual_Job_Line_Item__r.Quantity__c)+ Casual_Job_Line_Item__r.Allowance_Per_Person__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The total amount that this contractor should be paid</inlineHelpText>
    <label>Amount Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual__c.field-meta.xml
<CustomField>
    <fullName>Casual__c</fullName>
    <label>Contractor Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please ensure this contractor does not have any open jobs</errorMessage>
        <filterItems>
            <field>Casual__c.Grade__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Casual__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Job_Requisitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual_Job_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Casual_Job_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Specification</label>
    <referenceTo>Casual_Job_Line_Item__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Casual_Job_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/End_dDate__c.field-meta.xml
<CustomField>
    <fullName>End_dDate__c</fullName>
    <formula>Casual_Job_Line_Item__r.End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Payment_Rate__c.field-meta.xml
<CustomField>
    <fullName>Payment_Rate__c</fullName>
    <formula>Casual_Job_Line_Item__r.Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>Payment rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Start_dDate__c.field-meta.xml
<CustomField>
    <fullName>Start_dDate__c</fullName>
    <formula>Casual_Job_Line_Item__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>CONTRACT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Contract_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Amount__c</fullName>
    <description>Total Amount Payable to Contractor</description>
    <inlineHelpText>Total Amount Payable to Contractor (Payment amount plus allowances, bonuses, etc)</inlineHelpText>
    <label>Contract Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Casual__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <formula>Contractor__r.ID_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Number</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Job_Spec_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Job_Spec_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Spec Assignment</label>
    <referenceTo>Casuals_Job_Assignment__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Payment_Rate__c.field-meta.xml
<CustomField>
    <fullName>Payment_Rate__c</fullName>
    <label>Payment Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Contract__c/fields/Payment_Rate_Units__c.field-meta.xml
<CustomField>
    <fullName>Payment_Rate_Units__c</fullName>
    <label>Payment Rate Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Hour</fullName>
            </value>
            <value>
                <fullName>Per Day</fullName>
            </value>
            <value>
                <fullName>Per Week</fullName>
            </value>
            <value>
                <fullName>Per Month</fullName>
            </value>
            <value>
                <fullName>Per Job</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateContractFromContractorAssignment.cls
public class CreateContractFromContractorAssignment {
    
      private ApexPages.StandardController standardController;
      public Casuals_Job_Assignment__c assignment {get; set;}
      public Contract__c contract {get; set;}
    
        public CreateContractFromContractorAssignment (ApexPages.StandardController standardController){
            this.standardController = standardController;
            
            this.assignment= (Casuals_Job_Assignment__c )standardController.getRecord();
            this.assignment=getData();
            
            this.contract=new Contract__c();
            contract.Account__c=assignment.Casual__r.account__c;
            contract.Contractor__c=assignment.Casual__c;
            contract.Designation__c=assignment.Casual_Job_Line_Item__r.Location_Dim_2__c;
            contract.Start_Date__c=assignment.Start_dDate__c;
            contract.End_Date__c=assignment.End_dDate__c;
            contract.Payment_Rate__c=assignment.Casual_Job_Line_Item__r.Rate__c;
            contract.Payment_Rate_Units__c=assignment.Casual_Job_Line_Item__r.Rate_Units__c;
            contract.Contract_Amount__c=assignment.Amount_Payable__c;
            
        }
                
        public Casuals_Job_Assignment__c getData() {
            List<Casuals_Job_Assignment__c> assignment=[SELECT Start_dDate__c,Amount_Payable__c, End_dDate__c, Casual_Job_Line_Item__r.Rate__c,
                                                        Casual_Job_Line_Item__r.Rate_Units__c,Casual_Job_Line_Item__r.Location_Dim_2__c,
                                                        Casual__c, Casual__r.name, Casual__r.ID_Number__c,Casual__r.account__c
                                                        FROM Casuals_Job_Assignment__c
                                                        WHERE id=:this.assignment.id ];
                                                        
            Casuals_Job_Assignment__c  conAssignment=null;
            
            if(assignment.size()>0){
                conAssignment=assignment.get(0);
            }
            return conAssignment;
        }
        
        public PageReference createContract(){
            if(contract!=null){
                contract.Job_Spec_Assignment__c=assignment.id;
                insert contract;
            }   
            
            return new PageReference('/' + assignment.Id);      
        }
        
             

}