sfSandBoxCode/force-app/main/default/objects/Currency_Config__c/Currency_Config__c.object-meta.xml
<CustomObject>
    <label>Currency Config</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/Procurement_Tracking_Sheet__c.object-meta.xml
<CustomObject>
    <label>Procurement Request</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Procurement Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Count_all_PR_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Count_all_PR_Line_Items__c</fullName>
    <label>Count all PR Line Items</label>
    <summaryForeignKey>PTS_Line_Item__c.Procurement_Tracking_Sheet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Count_PR_Line_Items_Fully__c.field-meta.xml
<CustomField>
    <fullName>Count_PR_Line_Items_Fully__c</fullName>
    <label>Count PR Line Items Fully</label>
    <summaryFilterItems>
        <field>PTS_Line_Item__c.Status__c</field>
        <operation>equals</operation>
        <value>Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>PTS_Line_Item__c.Procurement_Tracking_Sheet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Count_PR_Line_Items_Waiting_User_Close__c.field-meta.xml
<CustomField>
    <fullName>Count_PR_Line_Items_Waiting_User_Close__c</fullName>
    <label>Count PR Line Items Waiting User Close</label>
    <summaryFilterItems>
        <field>PTS_Line_Item__c.Status__c</field>
        <operation>equals</operation>
        <value>Pending User Closure</value>
    </summaryFilterItems>
    <summaryForeignKey>PTS_Line_Item__c.Procurement_Tracking_Sheet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Next_Step__c.field-meta.xml
<CustomField>
    <fullName>Next_Step__c</fullName>
    <description>The next step in the PR approval process</description>
    <inlineHelpText>The next step in the PR approval process</inlineHelpText>
    <label>Next Step</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Next_Step_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Step_Due_Date__c</fullName>
    <description>The Due Date when the PR should be approved</description>
    <inlineHelpText>The Due Date when the PR should be approved</inlineHelpText>
    <label>Next Step Due Date</label>
    <type>DateTime</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Procurement_Tracking_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>a point, period, or step in a process or development.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Partial Receipt</fullName>
                <label>Items Partially  Received</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Maintenance Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Requesting Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QHSE Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Kenya Shillings (KES)</label>
    <summarizedField>PTS_Line_Item__c.Estimate__c</summarizedField>
    <summaryForeignKey>PTS_Line_Item__c.Procurement_Tracking_Sheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/PTS_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Procurement Request Line Item</label>
    <nameField>
        <displayFormat>PR-LI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Currency_Config__c.field-meta.xml
<CustomField>
    <fullName>Currency_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Currency_Config__c.Current__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Currency_Config__c</referenceTo>
    <relationshipLabel>Procurement Request Line Items (Currency)</relationshipLabel>
    <relationshipName>PTS_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <label>Total Budget Amount In KES</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Procurement_Tracking_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Procurement_Tracking_Sheet__c</fullName>
    <label>Procurement Tracking Sheet</label>
    <referenceTo>Procurement_Tracking_Sheet__c</referenceTo>
    <relationshipName>PTS_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Qty_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Delivered__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Delivered</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Quantity of item being requested</inlineHelpText>
    <label>Inventory Request Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Quantity_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining__c</fullName>
    <formula>Quantity__c - Qty_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Remaining</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Quote_Currency__c.field-meta.xml
<CustomField>
    <fullName>Quote_Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Currency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Currency_Config__c.Current__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Currency_Config__c</referenceTo>
    <relationshipName>PTS_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Specifications__c.field-meta.xml
<CustomField>
    <fullName>Specifications__c</fullName>
    <label>Specifications</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>the position of affairs at a particular time</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Item Request Approval</fullName>
            </value>
            <value>
                <fullName>Pending Sourcing</fullName>
            </value>
            <value>
                <fullName>Pending Quote Approval</fullName>
            </value>
            <value>
                <fullName>Pending Procurement Approval</fullName>
            </value>
            <value>
                <fullName>Pending Director Approval</fullName>
            </value>
            <value>
                <fullName>Requires Re-Approval</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Pending Purchase Order</fullName>
            </value>
            <value>
                <fullName>Purchase Order Created</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending User Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Quantity__c  *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Total_Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Quote_Price__c</fullName>
    <formula>Quote_Net_Total_Amount__c + Quote_Total_VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quote Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/ProcurementRequestTracker.cls
public class ProcurementRequestTracker{
    public List<PrWrapper> wrapperItems{get;set;}
    public List<Procurement_Tracking_Sheet__c> prLines;
    public List<Procurement_Tracking_Sheet__c> prLinesSave;
    Public List<PTS_Line_Item__c>prLineItems;
    public String selectValue{get;set;}
    //   public Boolean  ishide {get;set;}
    
    public ProcurementRequestTracker(){
        //searchText = '';
        getwrapperItems();
        getSelectItems();
        
    }
    
    /* public Boolean getisHide(){
if(selectValue == 'PENDING USER CLOSURE'){
ishide = false;
}
else {
ishide = true;
}
return  ishide;

}
*/
    public PageReference getwrapperItems(){
        system.debug('thePbtrtytyu'+ selectValue);
        wrapperItems = new List<PrWrapper>();
        User u =  [SELECT Email from User WHERE Id = :UserInfo.getUserId()];
        
        prLines = [ SELECT ID,Name,OwnerId,Requestor__c,Requestor__r.Work_Email__c,Requestor__r.Name,
                   Request_Date__c,Required_Date__c,Next_Step__c,Next_Step_Due_Date__c,Total_Amount__c,
                   (SELECT id,Name,Item__c,Specifications__c, Quantity__c,Qty_Delivered__c,Quantity_Remaining__c,
                    Estimate__c, Currency_Config__c, Total_Quote_Price__c, Quote_Currency__c,Status__c,Procurement_Tracking_Sheet__c,Procurement_Tracking_Sheet__r.Name,
                    Procurement_Tracking_Sheet__r.Requestor__c, Procurement_Tracking_Sheet__r.Requestor__r.name, Procurement_Tracking_Sheet__r.Request_Date__c,
                    Procurement_Tracking_Sheet__r.Required_Date__c,Procurement_Tracking_Sheet__r.Next_Step__c,
                    Procurement_Tracking_Sheet__r.Next_Step_Due_Date__c,Closed__c
                    FROM PTS_Line_Items__r
                    WHERE (Procurement_Tracking_Sheet__r.OwnerId = :UserInfo.getUserId()
                           OR Procurement_Tracking_Sheet__r.Requestor__r.Work_Email__c = :u.email)
                    ORDER BY status__c)
                   FROM Procurement_Tracking_Sheet__c
                   WHERE (OwnerId = :UserInfo.getUserId()
                          OR Requestor__r.Work_Email__c = :u.email)
                   ORDER BY Name DESC]; 
        
        if(selectValue == '' ){
            prLines = [ SELECT ID,Name,OwnerId,Requestor__c,Requestor__r.Work_Email__c,Requestor__r.Name,
                       Request_Date__c,Required_Date__c,Next_Step__c,Next_Step_Due_Date__c,Total_Amount__c,
                       (SELECT id,Name,Item__c,Specifications__c, Quantity__c,Qty_Delivered__c,Quantity_Remaining__c,
                        Estimate__c, Currency_Config__c, Total_Quote_Price__c, Quote_Currency__c,Status__c,Procurement_Tracking_Sheet__c,Procurement_Tracking_Sheet__r.Name,
                        Procurement_Tracking_Sheet__r.Requestor__c, Procurement_Tracking_Sheet__r.Requestor__r.name, Procurement_Tracking_Sheet__r.Request_Date__c,
                        Procurement_Tracking_Sheet__r.Required_Date__c,Procurement_Tracking_Sheet__r.Next_Step__c,
                        Procurement_Tracking_Sheet__r.Next_Step_Due_Date__c,Closed__c
                        FROM PTS_Line_Items__r
                        WHERE (Procurement_Tracking_Sheet__r.OwnerId = :UserInfo.getUserId()
                               OR Procurement_Tracking_Sheet__r.Requestor__r.Work_Email__c = :u.email)
                        AND Status__c != 'Received' 
                        AND Status__c != 'Cancelled'
                        ORDER BY status__c)
                       FROM Procurement_Tracking_Sheet__c
                       WHERE (OwnerId = :UserInfo.getUserId()
                              OR Requestor__r.Work_Email__c = :u.email)
                       ORDER BY Name DESC];
            
        }
        
        else if(selectValue == 'ALL'){
            prLines = [ SELECT ID,Name,OwnerId,Requestor__c,Requestor__r.Work_Email__c,Requestor__r.Name,
                       Request_Date__c,Required_Date__c,Next_Step__c,Next_Step_Due_Date__c,Total_Amount__c,
                       (SELECT id,Name,Item__c,Specifications__c, Quantity__c,Qty_Delivered__c,Quantity_Remaining__c,
                        Estimate__c, Currency_Config__c, Total_Quote_Price__c, Quote_Currency__c,Status__c,Procurement_Tracking_Sheet__c,Procurement_Tracking_Sheet__r.Name,
                        Procurement_Tracking_Sheet__r.Requestor__c, Procurement_Tracking_Sheet__r.Requestor__r.name, Procurement_Tracking_Sheet__r.Request_Date__c,
                        Procurement_Tracking_Sheet__r.Required_Date__c,Procurement_Tracking_Sheet__r.Next_Step__c,
                        Procurement_Tracking_Sheet__r.Next_Step_Due_Date__c,Closed__c
                        FROM PTS_Line_Items__r
                        WHERE (Procurement_Tracking_Sheet__r.OwnerId = :UserInfo.getUserId()
                               OR Procurement_Tracking_Sheet__r.Requestor__r.Work_Email__c = :u.email)
                        ORDER BY status__c)
                       FROM Procurement_Tracking_Sheet__c
                       WHERE (OwnerId = :UserInfo.getUserId()
                              OR Requestor__r.Work_Email__c = :u.email)
                       ORDER BY Name DESC];
            system.debug('thePpppppb'+ prLines);
            
        }
        else if(selectValue == 'PENDING USER CLOSURE'){
            system.debug('thePpppppb'+ selectValue);
            prLines = [ SELECT ID,Name,OwnerId,Requestor__c,Requestor__r.Work_Email__c,Requestor__r.Name,Count_PR_Line_Items_Waiting_User_Close__c,
                       Request_Date__c,Required_Date__c,Next_Step__c,Next_Step_Due_Date__c,Total_Amount__c,
                       (SELECT id,Name,Item__c,Specifications__c, Quantity__c,Qty_Delivered__c,Quantity_Remaining__c,
                        Estimate__c, Currency_Config__c, Total_Quote_Price__c, Quote_Currency__c,Status__c,Procurement_Tracking_Sheet__c,Procurement_Tracking_Sheet__r.Name,
                        Procurement_Tracking_Sheet__r.Requestor__c, Procurement_Tracking_Sheet__r.Requestor__r.name, Procurement_Tracking_Sheet__r.Request_Date__c,
                        Procurement_Tracking_Sheet__r.Required_Date__c,Procurement_Tracking_Sheet__r.Next_Step__c,
                        Procurement_Tracking_Sheet__r.Next_Step_Due_Date__c,Closed__c
                        FROM PTS_Line_Items__r
                        WHERE (Procurement_Tracking_Sheet__r.OwnerId = :UserInfo.getUserId()
                               OR Procurement_Tracking_Sheet__r.Requestor__r.Work_Email__c = :u.email)
                        AND Status__c = 'CLOSED'
                        AND Closed__c = false
                        ORDER BY status__c)
                       FROM Procurement_Tracking_Sheet__c
                       WHERE (OwnerId = :UserInfo.getUserId()
                              OR Requestor__r.Work_Email__c = :u.email)
                       ORDER BY Name DESC];
            
        }
        else if(selectValue == 'CLOSED'){
            prLines = [ SELECT ID,Name,OwnerId,Requestor__c,Requestor__r.Work_Email__c,Requestor__r.Name,Count_PR_Line_Items_Waiting_User_Close__c,
                       Request_Date__c,Required_Date__c,Next_Step__c,Next_Step_Due_Date__c,Total_Amount__c,Stage__c,Count_all_PR_Line_Items__c,
                       Count_PR_Line_Items_Fully__c,
                       (SELECT id,Name,Item__c,Specifications__c, Quantity__c,Qty_Delivered__c,Quantity_Remaining__c,
                        Estimate__c, Currency_Config__c, Total_Quote_Price__c, Quote_Currency__c,Status__c,Procurement_Tracking_Sheet__c,Procurement_Tracking_Sheet__r.Name,
                        Procurement_Tracking_Sheet__r.Requestor__c, Procurement_Tracking_Sheet__r.Requestor__r.name, Procurement_Tracking_Sheet__r.Request_Date__c,
                        Procurement_Tracking_Sheet__r.Required_Date__c,Procurement_Tracking_Sheet__r.Next_Step__c,
                        Procurement_Tracking_Sheet__r.Next_Step_Due_Date__c,Closed__c
                        FROM PTS_Line_Items__r
                        WHERE (Procurement_Tracking_Sheet__r.OwnerId = :UserInfo.getUserId()
                               OR Procurement_Tracking_Sheet__r.Requestor__r.Work_Email__c = :u.email)
                        AND Status__c = 'CLOSED'
                        AND Closed__c = true
                        ORDER BY status__c)
                       FROM Procurement_Tracking_Sheet__c
                       WHERE (OwnerId = :UserInfo.getUserId()
                              OR Requestor__r.Work_Email__c = :u.email)
                       AND Stage__c = 'CLOSED'
                       ORDER BY Name DESC];
            //    AND (Count_PR_Line_Items_Waiting_User_Close__c > 0)
        }
        
        for(Procurement_Tracking_Sheet__c line : prLines){
            PrWrapper wrapper = new PrWrapper(line);
            wrapperItems.add(wrapper);
        }
        
        return null;        
    }
    
    public List<SelectOption> getSelectItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));
        options.add(new SelectOption('ALL','ALL'));
        options.add(new SelectOption('PENDING USER CLOSURE','PENDING USER CLOSURE'));
        options.add(new SelectOption('OPEN','OPEN'));
        options.add(new SelectOption('CLOSED','CLOSED'));
        return options;
        
    }
    
    public PageReference save(){
        
      //  for ( Procurement_Tracking_Sheet__c pr:prLines){
           // upsert pr.PTS_Line_Items__r;
        //}
        
        return new PageReference('/home/home.jsp');
    }
    
    public class PrWrapper{
        public Procurement_Tracking_Sheet__c prLine {get; set;}
        public Boolean selected {get; set;}
        
        public PrWrapper(Procurement_Tracking_Sheet__c line){
            this.prLine = line;
            selected = false;
            
        }
    } 
}