sfSandBoxCode/force-app/main/default/objects/Card_Type__c/Card_Type__c.object-meta.xml
<CustomObject>
    <label>Card Type</label>
    <nameField>
        <label>Card Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/SweetSense_Sanergy_Int__c.object-meta.xml
<CustomObject>
    <label>SweetSense Sanergy Int</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>SweetSenseSanergy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SweetSenseSanergy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Card_Id__c.field-meta.xml
<CustomField>
    <fullName>Card_Id__c</fullName>
    <label>Card Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Fill_Level__c.field-meta.xml
<CustomField>
    <fullName>Fill_Level__c</fullName>
    <label>Fill Level</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/timeStamp__c.field-meta.xml
<CustomField>
    <fullName>timeStamp__c</fullName>
    <label>Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Toilet_Id__c.field-meta.xml
<CustomField>
    <fullName>Toilet_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet Id</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>SweetSenseSanergy</relationshipLabel>
    <relationshipName>SweetSenseSanergy</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SweetSense_Sanergy_Int__c/fields/Trigger_Type__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Type__c</fullName>
    <label>Trigger Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_writeSweetSense.cls
@RestResource(urlMapping='/write_sweetSense')
global with sharing class REST_writeSweetSense {
    
    //Incoming data from client
     global class clientRequest {
        public String cardId;
        public String toiletId;
        public Integer cardType;
        public Integer triggerType;
        public Integer fillLevel;
        public Double timestamp;
        public Double id;
        public String status;
        public String comments;
         
     }
     
    //Response to the client
    global class Message {
        public String cardId;
        public String toiletId;
        public Integer cardType;
        public Integer triggerType;
        public Integer fillLevel;
        public Double timestamp;
        public Double id;
        public String message;
        public boolean success;
        public String status;
        public String comments;
        
        
    }

  //Write to SweetSense_Sanergy_Int__c
  @HttpPost
   
   global static Message sweetData(String jsonRequest) {
      
      Message message = new Message();
      clientRequest  request = (clientRequest) System.JSON.deserialize(jsonRequest,	clientRequest.class);
                   if(request!=null){
                       try{
                       SweetSense_Sanergy_Int__c st=new SweetSense_Sanergy_Int__c();
                       st.Card_Id__c=request.cardId;
                       st.Card_Type__c=request.cardType;
                       st.Fill_Level__c=request.fillLevel;
                       st.Id__c=request.id;
                           
                       st.Trigger_Type__c=request.triggerType;
                       st.timeStamp__c=request.timestamp;
                       st.Toilet_Id__c=request.toiletId;
                       st.Comments__c=request.comments;
                       st.Status__c=request.status;
                       insert st;
                       
                   
                    message.cardId=request.cardId;
                    message.toiletId=request.toiletId;
                    message.cardType=request.cardType;
                    message.triggerType=request.triggerType;
                    message.fillLevel=request.fillLevel;
                    message.timestamp=request.timestamp;
                    message.id=request.id;
                    message.success=true; 
                    message.status=request.status;       
                    message.comments=request.comments; 
                           
                  } Catch(exception e){
                   message.success=false;
                   message.message=e.getMessage();
                      system.debug('DEBUG'+e.getMessage());
               		}
               
                   }else{message.message='ERROR: Insert FAILED due to EMPTY REQUEST';
                        message.success=false;
                        }
        return message;
       
  	  }             
      
}