sfSandBoxCode/force-app/main/default/objects/Card_Type__c/Card_Type__c.object-meta.xml
<CustomObject>
    <label>Card Type</label>
    <nameField>
        <label>Card Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Card_Type_Reason__c/Card_Type_Reason__c.object-meta.xml
<CustomObject>
    <label>Card Type Reason</label>
    <nameField>
        <label>Card Type Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Type Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Card_Type_Reason__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Card Type</label>
    <referenceTo>Card_Type__c</referenceTo>
    <relationshipLabel>Card Type Reasons</relationshipLabel>
    <relationshipName>Card_Type_Reasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Card_Type_Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_CardTypeReasons.cls
@RestResource(urlMapping='/card_type_reasons')
global with sharing class REST_CardTypeReasons {
    
    @HttpGet
    global static List<CardTypeReason> getCardReasons() {
    
        List<CardTypeReason> cardReasons = new List<CardTypeReason>();
        
        List<Card_Type_Reason__c> reasons = [SELECT Id, Name, Card_Type__c, Description__c FROM Card_Type_Reason__c];
        
        if(reasons != null && reasons.size()> 0){
            for(Card_Type_Reason__c reason : reasons){
            
                CardTypeReason cr = new CardTypeReason();
                
                cr.guid = reason.Id;
                cr.cardTypeGuid = reason.Card_Type__c;
                cr.name = reason.Name;
                cr.description = reason.Description__c;
            
                cardReasons.add(cr);
            }
        }
        
        return cardReasons;
    }
    
    global class CardTypeReason {
        
        public String guid;
        public String cardTypeGuid;
        public String name;
        public String description;
    }
}