sfSandBoxCode/force-app/main/default/objects/Card_Type__c/Card_Type__c.object-meta.xml
<CustomObject>
    <label>Card Type</label>
    <nameField>
        <label>Card Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Card_Type__c/fields/Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Card_Name__c</fullName>
    <label>Card Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
                <label>red</label>
            </value>
            <value>
                <fullName>Orange</fullName>
                <label>orange</label>
            </value>
            <value>
                <fullName>Green</fullName>
                <label>green</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_Cards_Test.cls
@isTest(seeAllData=true)
public class REST_Cards_Test {

    static testMethod void  saveCardsTest(){
       
          //Get Open toilet
          List<Toilet__c> toilet = [SELECT ID FROM Toilet__c WHERE Operational_Status__c = 'Open' LIMIT 1];
          
         //Create Card Type
         Card_Type__c cardType = new Card_Type__c();         
         cardType.Card_Name__c = 'green';
         cardType.Description__c = 'Collected';
         cardType.name = 'green';         
         insert cardType;
         
         
         REST_Cards.Card card = new REST_Cards.Card(); 
         card.name = 'red';
         card.description = 'desc';
         card.toiletGuid = toilet.get(0).id;
         card.serialNumber = 'xyxyxyxyx';
         card.cardTypeGuid = cardType.id;
         
         List<REST_Cards.Card> cardsList = new List<REST_Cards.Card>();
         cardsList.add(card);
        
        String jsonResponse = JSON.serialize(cardsList);
        
        
        
        REST_Cards.saveCards(jsonResponse);
        REST_Cards.getCards();
        
       
   }
}