sfSandBoxCode/force-app/main/default/objects/Card_Type__c/Card_Type__c.object-meta.xml
<CustomObject>
    <label>Card Type</label>
    <nameField>
        <label>Card Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Card_Type__c/fields/Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Card_Name__c</fullName>
    <label>Card Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
                <label>red</label>
            </value>
            <value>
                <fullName>Orange</fullName>
                <label>orange</label>
            </value>
            <value>
                <fullName>Green</fullName>
                <label>green</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_CardType.cls
@RestResource(urlMapping='/card_type')
global with sharing class REST_CardType {
    
    @HttpGet
    global static List<CardType> getCardTypes() {
    
        List<CardType> cardTypes = new List<CardType>();
        
        List<Card_Type__c> types = [SELECT Id, Name, Card_Name__c, Description__c FROM Card_Type__c];
        
        if(types != null && types.size()> 0){
            for(Card_Type__c type : types){
            
                CardType ct = new CardType();
                
                ct.guid = type.Id;
                ct.name = type.Card_Name__c;
                ct.description = type.Description__c;
            
                cardTypes.add(ct);
            }
        }
        
        return cardTypes;
    }
    
    global class CardType {
        
        public String guid;
        public String name;
        public String description;
        
    }
}