sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/Sanergy_Asset__c.object-meta.xml
<CustomObject>
    <description>Sanergy Assets</description>
    <label>Sanergy Asset</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Sanergy Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Current Status of the Asset</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>Asset_Id__c</fullName>
    <label>Asset Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <description>Asset Name</description>
    <externalId>true</externalId>
    <label>Asset Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Operating_System__c.field-meta.xml
<CustomField>
    <fullName>Operating_System__c</fullName>
    <label>Operating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--None--</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Mac OS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Assets_Issuance__c/Sanergy_Assets_Issuance__c.object-meta.xml
<CustomObject>
    <description>Issuance Register of Sanergy Assets</description>
    <label>Sanergy Assets Issuance</label>
    <nameField>
        <displayFormat>SA{0000000}</displayFormat>
        <label>Sanergy Assets Issuance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets Issuances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Assets_Issuance__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <description>Sanergy Asset ID</description>
    <label>Sanergy Asset</label>
    <referenceTo>Sanergy_Asset__c</referenceTo>
    <relationshipLabel>Sanergy Assets Issuances</relationshipLabel>
    <relationshipName>Sanergy_Assets_Issuances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Assets_Issuance__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <formula>Asset_ID__r.RecordType.Name + &quot;(&quot; +  Asset_ID__r.Asset_Name__c + &quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Name</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/TestValidateSanergyAssetsIssuance.cls
@isTest
public class TestValidateSanergyAssetsIssuance {
    
    static TestMethod void testInsertAssetIssuance(){
        
        Sanergy_Asset__c asset = new Sanergy_Asset__c(Asset_Name__c='Test Asset', Manufacturer__c='Dell', Make__c='Latitude',
                                                      Model__c='E 6400', Operating_System__c = 'Windows',Active__c=true);
        
        insert asset;
        
        Sanergy_Assets_Issuance__c issuance = new Sanergy_Assets_Issuance__c(Asset_ID__c=asset.Id);
        
    }

}