sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/Sanergy_Asset__c.object-meta.xml
<CustomObject>
    <description>Sanergy Assets</description>
    <label>Sanergy Asset</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Sanergy Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Current Status of the Asset</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <description>Asset Name</description>
    <externalId>true</externalId>
    <label>Asset Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inventory</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Out for 3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Inventory-Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Operating_System__c.field-meta.xml
<CustomField>
    <fullName>Operating_System__c</fullName>
    <label>Operating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--None--</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Mac OS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/TestSetAssetStatusOnInsert.cls
@isTest
private class TestSetAssetStatusOnInsert {
   
   @isTest
   private static void TestStatus() {
   
       Sanergy_Asset__c asset = new Sanergy_Asset__c(
           Asset_Name__c = 'Test Asset',
          Manufacturer__c='Dell',
          Make__c='Latitude',
          Model__c='E 6400',
          Operating_System__c = 'Windows',
          Active__c=true
       );
       
       insert asset;
       
       Sanergy_Asset__c savedasset = [SELECT ID, Asset_Name__c, Asset_Status__c FROM Sanergy_Asset__c WHERE ID = :asset.ID];
       
       System.assertEquals(savedasset.Asset_Status__c, 'Inventory');
       
   }
}