sfSandBoxCode/force-app/main/default/objects/Asset_Usage_Reading__c/Asset_Usage_Reading__c.object-meta.xml
<CustomObject>
    <label>Asset Usage Reading</label>
    <nameField>
        <displayFormat>ASU-{000000}</displayFormat>
        <label>Asset Usage Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Usage Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Asset_Usage_Reading__c/fields/Actual_Units__c.field-meta.xml
<CustomField>
    <fullName>Actual_Units__c</fullName>
    <label>Actual Units</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Usage_Reading__c/fields/Current_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Reading__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Reading</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Usage_Reading__c/fields/Sanergy_Asset__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Asset</label>
    <referenceTo>Sanergy_Asset__c</referenceTo>
    <relationshipLabel>Asset Usage Readings</relationshipLabel>
    <relationshipName>Asset_Usage_Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/Sanergy_Asset__c.object-meta.xml
<CustomObject>
    <description>Sanergy Assets</description>
    <label>Sanergy Asset</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Sanergy Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Current Status of the Asset</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <description>Asset Name</description>
    <externalId>true</externalId>
    <label>Asset Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Current_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Current Reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Operating_System__c.field-meta.xml
<CustomField>
    <fullName>Operating_System__c</fullName>
    <label>Operating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--None--</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Mac OS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/UnitsAndDateValidationTest.cls
@isTest(seeAllData = true)
public class UnitsAndDateValidationTest {
    
    static testMethod void testUnitsAndDateValidationTest(){
        Sanergy_Asset__c sanAsset = new Sanergy_Asset__c();
        Asset_Usage_Reading__c usage = new Asset_Usage_Reading__c();
        Asset_Usage_Reading__c usage1 = new Asset_Usage_Reading__c();
        
        sanAsset.Asset_Name__c = 'Laptop'; 
        sanAsset.Manufacturer__c = 'Dell';
        sanAsset.Make__c = 'Dell';
        sanAsset.Model__c = 'Latitude e6430';
        sanAsset.Operating_System__c = 'Ubuntu';
        sanAsset.Active__c = true;
        
        insert sanAsset;
        
        System.debug('asset ---->>>>>>' + sanAsset);
        
        usage.Sanergy_Asset__c = sanAsset.Id;
        usage.Current_Reading__c = true;
        usage.Actual_Units__c = 10;
        usage.Date__c = date.today()-3;
        
        System.debug('test date  ' +  usage.Date__c );
        
        insert usage;
        
        System.debug('usage ---->>>>>>' + usage);
 /**       
        usage1.Sanergy_Asset__c = sanAsset.Id;
        usage1.Current_Reading__c = true;
        usage1.Actual_Units__c = 9;
        usage1.Date__c = date.today();
        
        System.debug('test date1  ' +  usage1.Date__c );
        
        insert usage1;
**/
    }
    
}