sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Item</label>
    <nameField>
        <label>Opportunity Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Deactivate_Item__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to deactivate an item</description>
    <inlineHelpText>Check this box to deactivate an item</inlineHelpText>
    <label>Deactivate Item</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Default Quantity</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <label>Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Structure Package</fullName>
            </value>
            <value>
                <fullName>Paint Package</fullName>
            </value>
            <value>
                <fullName>Toilet Support Package</fullName>
            </value>
            <value>
                <fullName>Location Support Package</fullName>
            </value>
            <value>
                <fullName>Upstructure Package</fullName>
            </value>
            <value>
                <fullName>Pit Conversion Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package - Upstructure</fullName>
            </value>
            <value>
                <fullName>BIB Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Manual_Add__c.field-meta.xml
<CustomField>
    <fullName>Manual_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Items with this value need to be added manually</description>
    <label>Manual Add</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Structure_Version__c.field-meta.xml
<CustomField>
    <fullName>Structure_Version__c</fullName>
    <label>Structure Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V2</fullName>
            </value>
            <value>
                <fullName>V3</fullName>
            </value>
            <value>
                <fullName>V2-V3 Hybrid</fullName>
            </value>
            <value>
                <fullName>Pit Conversion</fullName>
            </value>
            <value>
                <fullName>Basic FLT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Pit_Conversion_Item__c/Pit_Conversion_Item__c.object-meta.xml
<CustomObject>
    <label>Pit Conversion Item</label>
    <nameField>
        <displayFormat>PCI-{0000000000}</displayFormat>
        <label>Pit Conversion Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pit Conversion Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Pit_Conversion_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pit Conversion Items</relationshipLabel>
    <relationshipName>Pit_Conversion_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Pit_Conversion_Item__c/fields/Opportunity_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Item</label>
    <referenceTo>Opportunity_Item__c</referenceTo>
    <relationshipLabel>Pit Conversion Items</relationshipLabel>
    <relationshipName>Pit_Conversion_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Pit_Conversion_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/PitConversionItems.cls
public class PitConversionItems {
    
    private ApexPages.StandardController standardController;
    
    //Pit Conversion Items
    public Opportunity opp {get; set;}    
    
    public PitConversionItems(ApexPages.StandardController standardController){
        this.standardController = standardController;
        opp = (Opportunity)standardController.getRecord(); 
        
        opp = [SELECT Name,AccountId,StageName,Primary_Salesperson__c,
               CloseDate,Pit_Conversion__c,Pit_Conversion_Items_Added__c
               FROM Opportunity
               WHERE Id =: opp.Id];
    }
    
    public PageReference createPitConversionItems() {
        
        //Check if Opportunity is for Pit Conversion
        if(opp.Pit_Conversion__c){            
            
            //Check if Pit Conversion Items have been added
            if(!opp.Pit_Conversion_Items_Added__c){
                
                List<Opportunity_Item__c> opportunityItems = new List<Opportunity_Item__c>();
                
                opportunityItems = [SELECT Id, Grouping__c, Default_Quantity__c
                                    FROM Opportunity_Item__c 
                                    WHERE Structure_Version__c = 'Pit Conversion'
                                    AND Grouping__c = 'Pit Conversion Package'
                                    AND Manual_Add__c = false
                                    AND Deactivate_Item__c=false];
                
                List<Pit_Conversion_Item__c> pitConversionItems = new List<Pit_Conversion_Item__c>();
                
                if(opportunityItems.size() > 0){
                    
                    for(Opportunity_Item__c opportunityItem : opportunityItems){
                        
                        if(opportunityItem.Grouping__c == 'Pit Conversion Package'){
                            
                            // Create Pit Conversion Items
                            Pit_Conversion_Item__c pitConversionItem = new Pit_Conversion_Item__c();
                            pitConversionItem.Opportunity__c = opp.Id;
                            pitConversionItem.Opportunity_Item__c = opportunityItem.Id;
                            pitConversionItem.Quantity__c = opportunityItem.Default_Quantity__c; 
                            
                            //Add Pit Conversion Items to list
                            pitConversionItems.add(pitConversionItem);                     
                        }
                    }
                }
                
                if(pitConversionItems.size() > 0){
                    
                    //Insert Pit Conversion Items
                    INSERT pitConversionItems;
                    
                    // Update Opportunity
                    opp.Pit_Conversion_Items_Added__c = true;
                    UPDATE opp;
                }
                
                // Redirect to the opportunity record
                return new PageReference('/' + opp.Id);
            } else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Pit Conversion Items already exist!'));
            }
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This is not a Pit Conversion Opportunity!'));
        }
        return null;
    }   
}