sfSandBoxCode/force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Inventory_Item__r.Item_Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Po_line_Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Po_line_Receipt_Status__c</fullName>
    <label>Po line Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Items Partially Received</fullName>
            </value>
            <value>
                <fullName>All items Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Purchase_Order_Item__c.Vendor__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining__c</fullName>
    <formula>Quantity_Requested__c -  Quantity_Accepted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <label>Quantity Requested</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Requesting_Company__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items (Company)</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items4</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/Vendor_Invoice_Items__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Item</label>
    <nameField>
        <displayFormat>VII-{0000000}</displayFormat>
        <label>Vendor Invoice Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Line Item</label>
    <referenceTo>Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Pending Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Pending Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Vendor_Invoice_Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice_Purchase_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Invoice Purchase Order Line Item</label>
    <referenceTo>Vendor_Invoice_Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_PO__c/Vendor_Invoice_PO__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice PO</label>
    <nameField>
        <displayFormat>VIPO-{0000000}</displayFormat>
        <label>Vendor Invoice PO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice POs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_PO__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Purchase_Order__c.Firm_Date__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Vendor Invoice POs</relationshipLabel>
    <relationshipName>Vendor_Invoice_POs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_PO__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice POs</relationshipLabel>
    <relationshipName>Vendor_Invoice_POs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/Vendor_Invoice_Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Purchase Order Line Item</label>
    <nameField>
        <displayFormat>VIPOLI-{0000000000}</displayFormat>
        <label>VI PO Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line_Item__c</fullName>
    <label>PO Line Item</label>
    <referenceTo>Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>VIPO Line Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Requested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Requested_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AddVendorInvItemsController.cls
public class AddVendorInvItemsController{
    
    private ApexPages.StandardController standardController;
    private Vendor_Invoice__c invoice;
    private List<ItemWrapper> items {get; set;}
    
    public AddVendorInvItemsController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.invoice = (Vendor_Invoice__c)standardController.getRecord();
    }
    
    public List<ItemWrapper> getItems() {
        
        if(items == null) {
            
            items = new List<ItemWrapper>();
            
            /* List<Vendor_Invoice_PO__c> vendorInvoices = [SELECT Id, Name, Purchase_Order__c
FROM Vendor_Invoice_PO__c
WHERE Vendor_Invoice__c = :invoice.Id
];*/
            List<Vendor_Invoice_Purchase_Order_Line_Item__c> vendorInvoicesPOline = [SELECT Vendor_Invoice__c,	Purchase_Order_Line_Item__c,
                                                                                     Total_Cost__c,Requested_Quantity__c
                                                                                     FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                                                                                     WHERE Vendor_Invoice__c = :invoice.Id
                                                                                    ];
            List<String> poIds = new List<String>();
            
            /*for(Vendor_Invoice_PO__c vendorInvoice: vendorInvoices){
poIds.add(vendorInvoice.Purchase_Order__c);
}*/
            for(Vendor_Invoice_Purchase_Order_Line_Item__c vendorInvoice: vendorInvoicesPOline){
                poIds.add(vendorInvoice.Purchase_Order_Line_Item__c);
            }
            System.debug('poIds = ' + poIds);
            System.debug('poIds = ' + poIds);            
            if(poIds.size() > 0){
                
                List<Purchase_Order_Line_Item__c> lineItems = [Select Id, Name, Purchase_Order_Item__r.Name, Quantity_Requested__c,
                                                               Quantity_Remaining__c, Requesting_Company__r.Name,Po_line_Receipt_Status__c,
                                                               Unit_Net_Price__c, VAT_Amount__c
                                                               From Purchase_Order_Line_Item__c
                                                               WHERE ID IN : poIds 
                                                               AND (Status__c = 'Open'
                                                                    OR  Po_line_Receipt_Status__c = 'Items Partially Received')
                                                               AND Invoice_Assigned__c = false
                                                               AND Purchase_Order__r.Approved__c = true
                                                              ];
             system.debug('LineItems' + lineItems);   
                for(Purchase_Order_Line_Item__c lineItem : lineItems){
                    ItemWrapper wrapper = new ItemWrapper(lineItem);
                    items.add(wrapper);
                }
            }
        }
        return items;
    }
    
    public PageReference selectAll() {
        if(items!=null){
            for(ItemWrapper lg:items){
                lg.selected=true;
                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(items!=null){
            for(ItemWrapper lg:items){
                lg.selected=false; 
            }
        }        
        return null;
    }
    
    public PageReference addInvoiceItems(){
        
        if(items != null && items.size() > 0){
            
            integer selected = 0;
            
            for(ItemWrapper item : items){
                Vendor_Invoice_Purchase_Order_Line_Item__c vipo = [SELECT ID,NAME,Purchase_Order_Line_Item__c
                                                                   FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                                                                   WHERE Purchase_Order_Line_Item__c =: item.item.Id
                                                                  ];
                system.debug('vipo  '+ vipo);
                system.debug('item.item.Id  '+ item.item.Id);
                if(item.selected){
                    
                      Vendor_Invoice_Items__c invoiceLine = new Vendor_Invoice_Items__c(
                        Vendor_Invoice__c = invoice.Id,
                        Purchase_Order_Line_Item__c = item.item.Id,
                        Vendor_Invoice_Purchase_Order_Line_Item__c = vipo.Id,
                        Accepted_Receive_Quantity__c = 0.00,
                        Quantity__c = item.item.Quantity_Remaining__c,
                        Total_Cost__c = (item.item.Quantity_Remaining__c * (item.item.Unit_Net_Price__c + item.item.VAT_Amount__c)),
                        Company__c = item.item.Requesting_Company__c,
                        Status__c = 'Open'                                       
                        
                    ); 
                    
                    insert invoiceLine;
                    system.debug('invoiceLine   ' +invoiceLine); 
        
                    
                    item.item.Invoice_Assigned__c = true;
                    
                    update item.item;
                    
                    selected +=1;
                }
                system.debug('vipo.id   ' +vipo.Id );
                
                
                
                
            }
            
            if(selected > 0){
                return new PageReference('/' + invoice.Id);  
            } else{
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'No Items Were Added');
                ApexPages.addmessage(msg);
            }
        }
        return null;
    }
    
    public class ItemWrapper{
        public Purchase_Order_Line_Item__c item {get; set;}
        public Boolean selected {get; set;}
        
        public ItemWrapper(Purchase_Order_Line_Item__c itm) {
            item = itm;
            selected = true;
        }
    } 
}