sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Company_Division__c.field-meta.xml
<CustomField>
    <fullName>Company_Division__c</fullName>
    <label>Company Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Fresh Life Initiative Limited</fullName>
            </value>
            <value>
                <fullName>Sanergy Limited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_SF_Account__c.field-meta.xml
<CustomField>
    <fullName>Employee_SF_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee SF Account</description>
    <inlineHelpText>Employee SF Account</inlineHelpText>
    <label>Employee SF Account</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_SF_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Primary Phone Contact</description>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department Unit</label>
    <referenceTo>Sanergy_Department_Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Team_Lead_SF_Account__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_SF_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead SF Account</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/fields/Team_Lead_SF_Account__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_SF_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead SF Account</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sanergy_Departments1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <description>Sanergy Department</description>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Team_Lead_SF_Account__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_SF_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead SF Account</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sanergy_Department_Units2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_EmployeeDetails.cls
//GET details for logged in User
@RestResource(urlMapping='/api/employee')
global with sharing class REST_EmployeeDetails {
    
    @HttpGet
    global static List<EmployeeDetails> getLoggedInUserDetails() {
        
        List<EmployeeDetails> employeeInformation = new List<EmployeeDetails>();
        
        List<Employee__c> employee_details = [SELECT Id, Name, Company_Division__c,Sanergy_Department__r.Name,
                                              Sanergy_Department_Unit__r.Name,Primary_Phone__c,
                                              Team_Lead_SF_Account__r.Name
                                              FROM Employee__c 
                                              WHERE Employee_SF_Account__c =: UserInfo.getUserId()
                                              ORDER BY Name ASC];
        
        if(employee_details != null && employee_details.size()> 0){
            
            for(Employee__c employee : employee_details){
                
                EmployeeDetails detail = new EmployeeDetails();
                
                detail.guid = employee.Id;
                detail.name = employee.Name;
                detail.phone = employee.Primary_Phone__c;
                detail.company = employee.Company_Division__c;
                detail.department = employee.Sanergy_Department__r.Name;
                detail.departmentUnit = employee.Sanergy_Department_Unit__r.Name;
                detail.teamLead = employee.Team_Lead_SF_Account__r.Name;
                
                employeeInformation.add(detail);
            }
        }
        
        return employeeInformation;
    }
    
    global class EmployeeDetails {        
        public String guid;
        public String name;
        public String phone;        
        public String company;
        public String department;
        public String departmentUnit;
        public String teamLead;
    }     
  
}