sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Accrual_Start_Date__c</fullName>
    <label>Leave Accrual Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>Date Terminated</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/Leave_Accrual__c.object-meta.xml
<CustomObject>
    <label>Leave Accrual</label>
    <nameField>
        <displayFormat>LAU-{00000000}</displayFormat>
        <label>Leave Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Days_Accrued__c.field-meta.xml
<CustomField>
    <fullName>Days_Accrued__c</fullName>
    <label>Days Accrued</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Accruals</relationshipLabel>
    <relationshipName>Leave_Accruals</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Leave_Entitlement_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Utilization__c</fullName>
    <label>Leave Entitlement Utilization</label>
    <referenceTo>Leave_Entitlement_Utilization__c</referenceTo>
    <relationshipLabel>Leave Accruals</relationshipLabel>
    <relationshipName>Leave_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual_Schedule__c/Leave_Accrual_Schedule__c.object-meta.xml
<CustomObject>
    <label>Leave Accrual Schedule</label>
    <nameField>
        <label>Leave Accrual Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Accrual Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual_Schedule__c/fields/Job_Run__c.field-meta.xml
<CustomField>
    <fullName>Job_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Job Run</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual_Schedule__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <description>Period Start Date for which to run the Job</description>
    <inlineHelpText>Period Start Date for which to run the Job</inlineHelpText>
    <label>Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/Leave_Entitlement_Type_Config__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Type Config</label>
    <nameField>
        <displayFormat>LET-{00000000}</displayFormat>
        <label>Leave Entitlement Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Type Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Days_Accrued_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Days_Accrued_Per_Month__c</fullName>
    <formula>IF( ISPICKVAL( Leave_Type__c , &#39;Annual Leave&#39;) , (Total_No_of_Leave_Days__c / 12) , 0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Accrued Per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Display_to_User__c.field-meta.xml
<CustomField>
    <fullName>Display_to_User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box so that to show this config to the drop down for the user to select when creating leave</description>
    <label>Display to User</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Exam Leave</fullName>
            </value>
            <value>
                <fullName>Compassionate Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Proratable__c.field-meta.xml
<CustomField>
    <fullName>Proratable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Leave Type proratable ?</description>
    <inlineHelpText>Is the Leave Type proratable ?</inlineHelpText>
    <label>Proratable</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/Leave_Entitlement_Utilization__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Utilization</label>
    <nameField>
        <displayFormat>LEU-{00000000}</displayFormat>
        <label>Leave Entitlement Utilization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Utilization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Entitlement_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Type_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Entitlement Type Config</label>
    <referenceTo>Leave_Entitlement_Type_Config__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Annual Leave&#39;) , &#39;Annual Leave&#39;,  IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Sick Leave&#39;) , &#39;Sick Leave&#39;,  
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Maternity Leave&#39;) , &#39;Maternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Paternity Leave&#39;) , &#39;Paternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Exam Leave&#39;) , &#39;Exam Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Compassionate Leave&#39;) , &#39;Compassionate Leave&#39;, NULL))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Year__c.field-meta.xml
<CustomField>
    <fullName>Leave_Year__c</fullName>
    <formula>Leave_Entitlement_Type_Config__r.Year__c</formula>
    <label>Leave Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateLeaveAccrual.cls
public class CreateLeaveAccrual {
    //create standard controller
    private ApexPages.StandardController controller;
    
    public List<Leave_Accrual_Schedule__c> accrualScheduleList {get;set;}
    
    public Leave_Accrual_Schedule__c page{get;set;}
    
    
    public Date empStartDate; //Employee start date
    private Date x;
    private Date empEndDate; //Employee End date
    private Date jobStartDate; //The day the job is starting
    private Date startPreviousMonth;// previous Month start date 
    private Date endPreviousMonth;//Previous Month End date
    private String prevPeriod;//Previous period YYYY-MM format
    private ID Y;
    //Get fullmonths in between
    Double fullMonths = 0.0;
    Double accrualFactor =0.0;
    String periodName;
    
    //leaveAccruals Constructor
    public CreateLeaveAccrual (ApexPages.StandardController controller){
        this.controller = controller;
        page = (Leave_Accrual_Schedule__c)controller.getRecord();
        page = [SELECT Name,Period_Start_Date__c,Comments__c,Job_Run__c 
                FROM Leave_Accrual_Schedule__c LIMIT 1];
        accrualScheduleList = [SELECT Name,Period_Start_Date__c,Comments__c,Job_Run__c 
                               FROM Leave_Accrual_Schedule__c LIMIT 1];       
    }
    
    public PageReference ProcessJob(){   
        
        // x = date.today();// get the date today
        
        List<Leave_Accrual__c> C = new List<Leave_Accrual__c>();
        
        x = accrualScheduleList.get(0).Period_Start_Date__c; //get the set period date
        
        jobStartDate = x.toStartOfMonth(); // get the beginning of that month
        
        startPreviousMonth = jobStartDate.addMonths(-1); // get the beginning of the previous month
        
        endPreviousMonth = jobStartDate.addDays(-1); //get the end date of the previous month
        Integer prevYear = endPreviousMonth.year(); // Getting year for which accruals will be done]
        // DateTime endOfPreviousMonth = (DateTime )
        // 	prevPeriod = Datetime.newInstance(endPreviousMonth).format('YYYY-MM');//get the period name YYYY-MM of the previous month
        prevPeriod =  DateTime.newInstance(endPreviousMonth.year(),endPreviousMonth.month(),endPreviousMonth.day()).format('yyyy-MM');
        periodName = DateTime.newInstance(startPreviousMonth.year(),startPreviousMonth.month(),startPreviousMonth.day()).format('yyyy-MM');
        
        
        
        list<Leave_Accrual__c> listAccrual = [SELECT Leave_Entitlement_Utilization__c,Employee__c,Period__c
                                              FROM Leave_Accrual__c
                                              WHERE Period__c =: prevPeriod ];
        system.debug('listAccrual'+ listAccrual);
        
        List<Leave_Entitlement_Utilization__c> listAll = [SELECT Name,Leave_Type__c, Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c,
                                                          Employee__r.Name, Employee__r.Leave_Accrual_Start_Date__c, Employee__r.Termination_Date__c,
                                                          Leave_Entitlement_Type_Config__r.Proratable__c, Leave_Year__c
                                                          FROM Leave_Entitlement_Utilization__c
                                                          WHERE Leave_Entitlement_Type_Config__r.Proratable__c = true
                                                          AND Employee__r.Leave_Accrual_Start_Date__c <=: endPreviousMonth
                                                          AND Leave_Year__c =: prevYear
                                                          AND Leave_Entitlement_Type_Config__r.Display_to_User__c = true
                                                          AND (Employee__r.Termination_Date__c = null OR Employee__r.Termination_Date__c >: startPreviousMonth)
                                                          AND ID NOT IN (SELECT Leave_Entitlement_Utilization__c  
                                                                         FROM Leave_Accrual__c
                                                                         WHERE Period__c =: prevPeriod 
                                                                        )
                                                         ];
        system.debug('listAll' + listAll);
        
        //loop through the entire list 
        for(Leave_Entitlement_Utilization__c oneEmp: listAll){
            empStartDate = oneEmp.Employee__r.Leave_Accrual_Start_Date__c; //get the employee start date
            empEndDate = oneEmp.Employee__r.Termination_Date__c; // get the employee termination date 
            system.debug('XXX' + oneEmp.Employee__r.Name + '***' +  empStartDate + '***' + empEndDate  + '***' + accrualFactor + '***' + fullMonths  + '***' + oneEmp.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c);
            
            // check if the employee start date is less than the start of the previous month 
            if(empStartDate != null && empStartDate < startPreviousMonth){
                empStartDate =  startPreviousMonth; 
            }
            else if(empStartDate != null && empStartDate > endPreviousMonth){
                empStartDate = endPreviousMonth;
            }
            // check if the employee end date is null or if the employee end date is greater than the end of the previous month            
            if(empEndDate == null || empEndDate > endPreviousMonth ){
                empEndDate = endPreviousMonth;
            }
            else if (empEndDate < startPreviousMonth){
                empEndDate =  startPreviousMonth;   
            }
            //reset to zero
            fullMonths = 0.0;
            accrualFactor =0.0;
            
            //Confirm start and end dates not null
            if(empStartDate != null && empEndDate != null){
                fullMonths = SanergyUtils.monthsBetween(empStartDate,empEndDate);
                System.debug ('in here');
            }
            //Get Accrual Factor and multiply by months between
            accrualFactor = fullMonths*oneEmp.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c;
            
            system.debug('AAA' + oneEmp.Employee__r.Name + '***' +  empStartDate + '***' + empEndDate  + '***' + accrualFactor + '***' + fullMonths  + '***' + oneEmp.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c);
            
            //Create an instance for the leave accruals
            Leave_Accrual__c  accrual = new Leave_Accrual__c();	 
            //accrual.Name = oneEmp.Name;
            accrual.Period__c = periodName;
            accrual.Employee__c = oneEmp.Employee__c;
            accrual.Leave_Entitlement_Utilization__c = oneEmp.Id;
            accrual.Days_Accrued__c = accrualFactor;
            
            //C is a list that you add all the items of the loop, then you do one insert for all the inserted items
            C.add(accrual);
            
            //INSERT accrual;
            
        } 
        INSERT C;
        
        system.debug('ACCRUAL FINISHED' + C);  
        
        return new PageReference('/'+ page.Id);
    }
    
    
    
    
    
    
}