sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <description>Employment Status</description>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Intern</fullName>
            </value>
            <value>
                <fullName>Pending Onboarding</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Probationary Contract</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Fellow</fullName>
            </value>
            <value>
                <fullName>Fixed Term Contract</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
                <default>true</default>
                <label>Pending Activation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Requisition__c/Inventory_Requisition__c.object-meta.xml
<CustomObject>
    <label>Inventory Requisition</label>
    <nameField>
        <displayFormat>IR-{0000000}</displayFormat>
        <label>Inventory Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Requisition__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending Teamlead Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/On_Offboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>On/Offboarding Checklist</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>On/Offboarding Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On/Offboarding Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Onboarding_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/OnboardingTasksControllerTest.cls
@isTest(SeeAllData=true)
public class OnboardingTasksControllerTest {
    static testMethod void TestOnboardingcontroller(){
        /*List<Inventory_Requisition__c> requisition = [SELECT Id,Name,Stage__c From Inventory_Requisition__c
                                                     WHERE Stage__c = 'Approved'];
        If(requisition.size()>0){*/
            List<Employee__c> employee = [SELECT Id,Name,Employment_Status__c FROM Employee__c
                                                        WHERE Employment_Status__c  = 'Contract' ];
            if(employee.size()>0){
                
                employee.get(0).Employment_Status__c = 'Pending Onboarding';
                update employee;
                
                On_Offboarding_Checklist__c task = new On_Offboarding_Checklist__c();
                task.Employee__c = employee.get(0).Id;
                task.Task_Name__c = 'trial';
                
                insert task;
                
                PageReference pageRef = Page.InventoryItemIssue;
            
                Test.setCurrentPage(pageRef);
                ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(employee.get(0));
                OnboardingTasksController controller = new OnboardingTasksController(sc);
                controller.selectAll();
                controller.processSelected();
                controller.unselectAll();
            }

        //}
    }


}