sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts Clerk</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant 1</fullName>
            </value>
            <value>
                <fullName>Assistant Manager</fullName>
            </value>
            <value>
                <fullName>Assistant Supervisor</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Chief Financial Officer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Design Specialist</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Driver 1</fullName>
            </value>
            <value>
                <fullName>Driver 2</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Engineer 1</fullName>
            </value>
            <value>
                <fullName>Engineer 3</fullName>
            </value>
            <value>
                <fullName>Fellow</fullName>
            </value>
            <value>
                <fullName>IT Help Desk Technician</fullName>
            </value>
            <value>
                <fullName>Junior Accountant</fullName>
            </value>
            <value>
                <fullName>Junior Systems Administrator</fullName>
            </value>
            <value>
                <fullName>Laboratory Coordinator</fullName>
            </value>
            <value>
                <fullName>Maintenance Partner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Monitoring &amp; Evaluation Assistant</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Partner 1</fullName>
            </value>
            <value>
                <fullName>Partner 2</fullName>
            </value>
            <value>
                <fullName>Partner 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Accrual_Start_Date__c</fullName>
    <label>Leave Accrual Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Group</label>
    <referenceTo>Leave_Group__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>Date Terminated</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/Employee_Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Employee Leave Request</label>
    <nameField>
        <displayFormat>ELR-{00000000}</displayFormat>
        <label>Employee Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Leave Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Time_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Leave_Entitlement_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Utilization__c</fullName>
    <label>Leave Entitlement Utilization</label>
    <referenceTo>Leave_Entitlement_Utilization__c</referenceTo>
    <relationshipLabel>Employee Leave Requests</relationshipLabel>
    <relationshipName>Employee_Time_Offs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>Leave_Entitlement_Utilization__r.Leave_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/Leave_Entitlement_Type_Config__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Type Config</label>
    <nameField>
        <displayFormat>LET-{00000000}</displayFormat>
        <label>Leave Entitlement Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Type Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Days_Accrued_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Days_Accrued_Per_Month__c</fullName>
    <formula>IF( ISPICKVAL( Leave_Type__c , &#39;Annual Leave&#39;) , (Total_No_of_Leave_Days__c / 12) , 0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Accrued Per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Group</label>
    <referenceTo>Leave_Group__c</referenceTo>
    <relationshipLabel>Leave Entitlement Type Configs</relationshipLabel>
    <relationshipName>Leave_Entitlement_Type_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Exam Leave</fullName>
            </value>
            <value>
                <fullName>Compassionate Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Total_No_of_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_Leave_Days__c</fullName>
    <label>Total No. of Leave Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/Leave_Entitlement_Utilization__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Utilization</label>
    <nameField>
        <displayFormat>LEU-{00000000}</displayFormat>
        <label>Leave Entitlement Utilization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Utilization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Accrued_To_Date_Selected__c.field-meta.xml
<CustomField>
    <fullName>Accrued_To_Date_Selected__c</fullName>
    <label>Accrued To Date Selected</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Days_Accrued__c.field-meta.xml
<CustomField>
    <fullName>Leave_Days_Accrued__c</fullName>
    <label>Leave Days Accrued</label>
    <summarizedField>Leave_Accrual__c.Days_Accrued__c</summarizedField>
    <summaryForeignKey>Leave_Accrual__c.Leave_Entitlement_Utilization__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Days_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Leave_Days_Remaining__c</fullName>
    <formula>Leave_Days_Accrued__c   -  Leave_Days_Used__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Days Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Days_Used__c.field-meta.xml
<CustomField>
    <fullName>Leave_Days_Used__c</fullName>
    <label>Leave Days Used</label>
    <summarizedField>Employee_Leave_Request__c.No_Of_Approved_Leave_Days__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Leave_Request__c.Leave_Approved__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Employee_Leave_Request__c.Leave_Started__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Leave_Request__c.Leave_Entitlement_Utilization__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Entitlement_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Type_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Entitlement Type Config</label>
    <referenceTo>Leave_Entitlement_Type_Config__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Annual Leave&#39;) , &#39;Annual Leave&#39;,  IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Sick Leave&#39;) , &#39;Sick Leave&#39;,  
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Maternity Leave&#39;) , &#39;Maternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Paternity Leave&#39;) , &#39;Paternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Exam Leave&#39;) , &#39;Exam Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Compassionate Leave&#39;) , &#39;Compassionate Leave&#39;, NULL))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Total_No_of_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_Leave_Days__c</fullName>
    <label>Total No. of Leave Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/Leave_Group__c.object-meta.xml
<CustomObject>
    <label>Leave Group</label>
    <nameField>
        <label>Leave Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <label>Leave Group Comments</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/LeaveUtlizationReport.cls
public class LeaveUtlizationReport {
    
    private ApexPages.StandardController standardController;
    
    //Employee
    public Employee__c employee {get; set;} 
    public Leave_Entitlement_Utilization__c  leaveEntilementUtilization {get;set;}
    //create disabled
    public Boolean  ishide {get; set;}
    public Date mystartdate = system.today();
    public Date lastdayofyear = Date.newinstance(mystartdate.year(), 12, 31);
    //Employee Leave Request
    public Employee_Leave_Request__c leaveRequest {get; set;}
    public List<LeaveRequestUtilization> leaveUtilizationList {get; set;}
    public String dptUnitApprover;
    public Date EndYear;
    public Double accruedToEndDate{get;set;}
    public Date StartDate{get;set;}
    public Date EndDate{get;set;}
    public Double accruedToEoY{get;set;}
    public Double BalToEndYear{get;set;}
    
    
    public LeaveUtlizationReport(ApexPages.StandardController controller){
        // this.controller = controller;
        
        ishide = false;
        //leaveRequest = new Employee_Leave_Request__c();
        leaveEntilementUtilization = (Leave_Entitlement_Utilization__c)controller.getRecord();
        // employee = (Employee__c)controller.getRecord();       
        
        System.debug('EMPLOYEE: ' + employee);
        
        
    }  
    
    public PageReference getLeaveRequestUtilizations(){
        
        leaveUtilizationList = new List<LeaveRequestUtilization>();
        
        if(StartDate != null && EndDate != null){ 
            
            List<Leave_Entitlement_Utilization__c> utilizationLineItems = [SELECT Name,Leave_Entitlement_Type_Config__c,
                                                                           Leave_Entitlement_Type_Config__r.Name,Employee__c,
                                                                           Leave_Entitlement_Type_Config__r.Leave_Group__r.Name,
                                                                           Employee__r.Name,Leave_Type__c,Total_No_of_Leave_Days__c,
                                                                           Leave_Days_Accrued__c,Leave_Days_Used__c,
                                                                           Employee__r.Termination_Date__c,
                                                                           Employee__r.Job_Title__c,
                                                                           Employee__r.Leave_Group__r.Name,
                                                                           Accrued_To_Date_Selected__c,
                                                                           Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c,
                                                                           Leave_Days_Remaining__c,Employee__r.Leave_Accrual_Start_Date__c  
                                                                           FROM Leave_Entitlement_Utilization__c 
                                                                           WHERE Leave_Type__c = 'Annual Leave'
                                                                           ORDER BY Leave_Type__c ASC];
            
            Double fullMonths = 0.0;
            
            for(Leave_Entitlement_Utilization__c itm: utilizationLineItems){
                
               // fullMonths = SanergyUtils.monthsBetween(itm.Employee__r.Leave_Accrual_Start_Date__c,lastdayofyear);
              //  accruedToEoY = fullMonths * itm.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c;
              //  BalToEndYear = accruedToEoY - itm.Leave_Days_Used__c;
                
               // Date StartDateInput = date.parse(StDate);
               // Date EndDateInput = date.parse(EdDate);
                
                // StartDate = Date.valueOf(StartDateInput);
               //  EndDate = date.valueOf(EndDateInput);
              system.debug('Date' + StartDate); 
              system.debug('lSd'+itm.Employee__r.Leave_Accrual_Start_Date__c );
                
                if((itm.Employee__r.Leave_Accrual_Start_Date__c < StartDate)){
                    fullMonths = SanergyUtils.monthsBetween(StartDate,EndDate);
                    system.debug('fullMonths' + fullMonths); 
                    accruedToEndDate = fullMonths * itm.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c;
                    itm.Accrued_To_Date_Selected__c = accruedToEndDate;
                }
                
                else if((itm.Employee__r.Leave_Accrual_Start_Date__c >  StartDate)){
                    fullMonths = SanergyUtils.monthsBetween(itm.Employee__r.Leave_Accrual_Start_Date__c,EndDate); 
                     system.debug('fullMonthsTwo' + fullMonths); 

                    accruedToEndDate = fullMonths * itm.Leave_Entitlement_Type_Config__r.Days_Accrued_Per_Month__c; 
                    itm.Accrued_To_Date_Selected__c = accruedToEndDate;
                } 
                leaveUtilizationList.add(new LeaveRequestUtilization(itm));
                system.debug('List' + itm.Accrued_To_Date_Selected__c);
            }
            
            
        }
        
        return null;  
        
    }
    public pageReference Export(){
        ishide = true;
        system.debug('ishide'+ ishide);
        return null;
    }
    
    // Leave Request wrapper class
    public class LeaveRequestUtilization{
        public Leave_Entitlement_Utilization__c  utilization {get; set;}
        public Double accruedToEndDate{get;set;}

        
        //Constructor
        public LeaveRequestUtilization(Leave_Entitlement_Utilization__c leaveUtilization) {
            utilization = leaveUtilization;	
            accruedToEndDate = accruedToEndDate;
        }        
    }    
    
    
    
    
}