sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/On_Offboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>On/Offboarding Checklist</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>On/Offboarding Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On/Offboarding Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Done__c.field-meta.xml
<CustomField>
    <fullName>Done__c</fullName>
    <label>Done</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Onboarding_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <label>Scheduled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/On_Offboarding_Checklist__c/fields/Trained_By__c.field-meta.xml
<CustomField>
    <fullName>Trained_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To:</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>On/Offboarding Checklists (Trained By:)</relationshipLabel>
    <relationshipName>Onboarding_Trainings1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/OnboardingTasksController.cls
public class OnboardingTasksController {
    
    private ApexPages.StandardController standardController;
    public Employee__c employee{get; set;}
    public List<OnboardingTasks> onboardingTasks {get; set;}
    
    public OnboardingTasksController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.employee = (Employee__c)standardController.getRecord();
        onboardingTasks = new List<OnboardingTasks>();
        
        List<On_Offboarding_Checklist__c> items = [SELECT Id,Name,Employee__c,Task_Name__c,Schedule_Date__c,Scheduled__c,Trained_By__c,Done__c
                                                     FROM On_Offboarding_Checklist__c 
                                                     WHERE Employee__c =: this.employee.Id
                                                    ];
        
        for(On_Offboarding_Checklist__c item:items){
            OnboardingTasks wr = new OnboardingTasks(item);
            onboardingTasks.add(wr);
        }
    } 
    
       public PageReference selectAll() {
        if(onboardingTasks != null){
            for(OnboardingTasks lg:onboardingTasks){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(onboardingTasks != null){
            for(OnboardingTasks lg:onboardingTasks){
                lg.selected=false;                
            }
        }
        return null;
    }
    
    public PageReference  processSelected() {
        
         if(onboardingTasks != null && onboardingTasks.size() > 0){
            
            integer issued = 0;
            integer expected = 0;
            
            for(OnboardingTasks item : onboardingTasks){
                
                if(item.selected ){
                    
                    expected +=1;
                    update item.item;
                  
                } issued +=1;
            }
        
            if(expected == issued){
                return new PageReference('/' + this.employee.Id);
            } else {
                return new PageReference('/' + this.employee.Id);
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'Some Tasks were not edited');
                ApexPages.addmessage(msg);
                return null;
            }
            
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Kindly confirm that the selected Employee has Tasks'));
            return null;
        }
        return null;
    }
    
    public class OnboardingTasks{
        
        public On_Offboarding_Checklist__c item {get; set;}
        public On_Offboarding_Checklist__c onboardingItem {get; set;}
        public Boolean selected {get; set;}
        public OnboardingTasks(On_Offboarding_Checklist__c onboardingItem) {
            item = onboardingItem;

           // onboardingItem.Task_Name__c = line.Task_Name__c;
            this.selected = true;
        }
    }

}