sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_First_Name__c</fullName>
    <label>Employee First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Last_Name__c</fullName>
    <label>Employee Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Middle_Name__c</fullName>
    <label>Employee Middle Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Employment_Start_Date__c</fullName>
    <description>Employment Start Date</description>
    <label>Employment Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <description>Employment Status</description>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Intern</fullName>
            </value>
            <value>
                <fullName>Pending Onboarding</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Probationary Contract</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Fellow</fullName>
            </value>
            <value>
                <fullName>Fixed Term Contract</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
                <default>true</default>
                <label>Pending Activation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/HR_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>HR_Employee_ID__c</fullName>
    <label>HR Employee ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/HR_Unique_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>HR_Unique_Record_ID__c</fullName>
    <label>HR Unique Record ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Identification_Document__c.field-meta.xml
<CustomField>
    <fullName>Identification_Document__c</fullName>
    <description>Type of Identification Document</description>
    <label>Identification Document</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National ID</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <description>Identification Number</description>
    <label>Identification Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts Clerk</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant 1</fullName>
            </value>
            <value>
                <fullName>Assistant Manager</fullName>
            </value>
            <value>
                <fullName>Assistant Supervisor</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Chief Financial Officer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Design Specialist</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Driver 1</fullName>
            </value>
            <value>
                <fullName>Driver 2</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Engineer 1</fullName>
            </value>
            <value>
                <fullName>Engineer 3</fullName>
            </value>
            <value>
                <fullName>Fellow</fullName>
            </value>
            <value>
                <fullName>IT Help Desk Technician</fullName>
            </value>
            <value>
                <fullName>Junior Accountant</fullName>
            </value>
            <value>
                <fullName>Junior Systems Administrator</fullName>
            </value>
            <value>
                <fullName>Laboratory Coordinator</fullName>
            </value>
            <value>
                <fullName>Maintenance Partner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Monitoring &amp; Evaluation Assistant</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Partner 1</fullName>
            </value>
            <value>
                <fullName>Partner 2</fullName>
            </value>
            <value>
                <fullName>Partner 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Line Manager</description>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Line_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Location__c</fullName>
    <label>Primary Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Primary Phone Contact</description>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department Unit</label>
    <referenceTo>Sanergy_Department_Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>Date Terminated</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <description>Sanergy Department</description>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_Employees.cls
@RestResource(urlMapping='/employees')
global with sharing class REST_Employees {

    @HttpPost
    global static List<Employee> getAllEmployees() {
        
        List<Employee> employees = new List<Employee>();
        
        List<Employee__c> sanEmployees = [SELECT Id, Name, Employee_Active__c, Employee_First_Name__c, Employee_Last_Name__c,
                                            Employee_Middle_Name__c, Employment_Start_Date__c, Employment_Status__c,
                                            HR_Employee_ID__c, HR_Unique_Record_ID__c, Identification_Document__c, Identification_Number__c,
                                            Job_Title__c, Line_Manager__c, Line_Manager__r.Work_Email__c, Primary_Location__c, Primary_Phone__c,   Sanergy_Department__c,
                                            Sanergy_Department_Unit__c, Termination_Date__c, Work_Email__c FROM Employee__c
                                            WHERE Employee_First_Name__c != NULL
                                            AND Employee_Last_Name__c != NULL
                                            AND Job_Title__c != NULL];
        
        if(sanEmployees != null && sanEmployees.size()> 0){
        
            for(Employee__c sanEmployee : sanEmployees){
            
                Employee employee = new Employee();
                
                employee.guid = sanEmployee.Id;
                employee.name = sanEmployee.Name;
                employee.department = sanEmployee.Sanergy_Department__c; 
                employee.departmentUnit = sanEmployee.Sanergy_Department_Unit__c;
                employee.isActive = sanEmployee.Employee_Active__c;
                employee.firstName = sanEmployee.Employee_First_Name__c;   
                employee.otherNames = sanEmployee.Employee_Middle_Name__c;
                employee.lastName = sanEmployee.Employee_Last_Name__c;
                employee.startDate = sanEmployee.Employment_Start_Date__c;
                employee.employmentStatus = sanEmployee.Employment_Status__c;
                employee.employeeId = sanEmployee.HR_Employee_ID__c;
                employee.employmentNumber = sanEmployee.HR_Employee_ID__c;
                employee.identificationDocument = sanEmployee.Identification_Document__c;
                employee.identificationNumber = sanEmployee.Identification_Number__c;
                employee.jobTitle = sanEmployee.Job_Title__c;
                employee.lineManager = sanEmployee.Line_Manager__c;
                employee.primaryLocation = sanEmployee.Primary_Location__c;
                employee.primaryPhone = sanEmployee.Primary_Phone__c;
                employee.terminationDate = sanEmployee.Termination_Date__c;
                employee.workEmail = sanEmployee.Work_Email__c;
                employee.managerEmail= sanEmployee.Line_Manager__r.Work_Email__c;
            
                employees.add(employee);
            }
        }
        
        return employees;
    }
    
    global class Employee {
    
        public String guid;
        public String name;
        public String department;
        public String departmentUnit;
        public Boolean isActive;
        public String firstName;
        public String otherNames;
        public String lastName;
        public Date startDate;
        public String employmentStatus;
        public String employeeId;
        public String employmentNumber;
        public String identificationDocument;
        public String identificationNumber;
        public String jobTitle;
        public String lineManager;
        public String primaryLocation;
        public String primaryPhone;
        public Date terminationDate;
        public String workEmail;
        public String managerEmail;
    
    }
}