sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_First_Name__c</fullName>
    <label>Employee First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Last_Name__c</fullName>
    <label>Employee Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Employment_Start_Date__c</fullName>
    <description>Employment Start Date</description>
    <label>Employment Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Group</label>
    <referenceTo>Leave_Group__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Primary Phone Contact</description>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees (Team Lead)</relationshipLabel>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/Employee_Role__c.object-meta.xml
<CustomObject>
    <label>Employee Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <formula>Sanergy_Department_Unit__r.Sanergy_Department__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sanergy Department</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Roles (Team Lead)</relationshipLabel>
    <relationshipName>Employee_Roles2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/Leave_Group__c.object-meta.xml
<CustomObject>
    <label>Leave Group</label>
    <nameField>
        <label>Leave Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <label>Leave Group Comments</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/Onboarding_Task_Config__c.object-meta.xml
<CustomObject>
    <label>Onboarding Task Config</label>
    <nameField>
        <displayFormat>OT-{00000000}</displayFormat>
        <label>Onboarding Tasks Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Tasks Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Bamboo HR Tasks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/No_of_Days_After_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days_After_Hire_Date__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The on-boarding will be done after &#39;X&#39; number of days from the date of hiring an Employee</description>
    <inlineHelpText>The on-boarding will be done after &#39;X&#39; number of days from the date of hiring an Employee</inlineHelpText>
    <label>No. of Days After Hire Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/On_boarding_Done_By__c.field-meta.xml
<CustomField>
    <fullName>On_boarding_Done_By__c</fullName>
    <label>On-boarding Done By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Line Manager</fullName>
            </value>
            <value>
                <fullName>Talent Partner</fullName>
            </value>
            <value>
                <fullName>Specific User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/Onboarding_for__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_for__c</fullName>
    <description>On-boarding for which role(s)</description>
    <inlineHelpText>On-boarding for which role(s)</inlineHelpText>
    <label>On-boarding for ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All roles</fullName>
            </value>
            <value>
                <fullName>All roles in a department</fullName>
            </value>
            <value>
                <fullName>Specific role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Onboarding_Task_Config__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/Recruitment_Requisition__c.object-meta.xml
<CustomObject>
    <label>Recruitment Requisition</label>
    <nameField>
        <label>Recruitment Requisition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Recruitment Requisitions</relationshipLabel>
    <relationshipName>Recruitment_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead (Employee A/c)</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sanergy Departments</relationshipLabel>
    <relationshipName>Sanergy_Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateOnboardingTasksFromEmployee.cls
public class CreateOnboardingTasksFromEmployee {
    
    //create standard controller
    private ApexPages.StandardController controller;
    
    //User
    private List<User> users {get; set;}
    
    //Employee
    public Employee__c employee {get; set;}
    
    //On-boarding Task
    public Onboarding_Task_Config__c onboardingTaskConfig {get; set;}
    
    //On-boarding Tasks
    public List<OnboardingTask> onboardingTaskList {get; set;}      
    
    // Constructor
    public CreateOnboardingTasksFromEmployee(ApexPages.StandardController controller){               
        this.controller = controller;                
        employee = (Employee__c)controller.getRecord();
        
        employee = [SELECT Name,Employee_First_Name__c,Employee_Last_Name__c,Sanergy_Department__c,
                    Sanergy_Department__r.Name,Sanergy_Department__r.Team_Lead__r.Name,Primary_Phone__c,
                    Recruitment_Requisition__c,Recruitment_Requisition__r.Name,Leave_Group__c,Leave_Group__r.Name,
                    Employee_Role__c,Employee_Role__r.Name,Employment_Start_Date__c 
                    FROM Employee__c 
                    WHERE Employee_Role__c != NULL
                    AND Id =: employee.Id
                    ORDER BY Name DESC];       
        
        System.debug('EMPLOYEE: ' + employee);
    }
    
    // Get On-boarding Tasks
    public List<OnboardingTask> getItems() {        
        
        if(onboardingTaskList == null){
            
            onboardingTaskList = new List<OnboardingTask>();
            
            //Get On-boarding Task
            List<Onboarding_Task_Config__c> onboardingItems = [SELECT Name,Employee_Role__c,Employee_Role__r.Name,Task_Name__c,
                                                               Assigned_To__c,Assigned_To__r.Name,No_of_Days_After_Hire_Date__c,
                                                               Category__c,Description__c,On_boarding_Done_By__c,
                                                               Onboarding_for__c
                                                               FROM Onboarding_Task_Config__c
                                                               WHERE Employee_Role__c =: employee.Employee_Role__c
                                                               OR Onboarding_for__c = 'All roles'
                                                               OR Onboarding_for__c = 'All roles in a department'];
            
            for(Onboarding_Task_Config__c onboardingItem : onboardingItems){                              
                onboardingTaskList.add(new OnboardingTask(onboardingItem));
            }
            System.debug('ON-BOARDING TASK: ' + onboardingTaskList);
        }
        return onboardingTaskList;
    }
    
    //Create Task
    public PageReference createTask(){
        
        if(onboardingTaskList!= null  && onboardingTaskList.size() > 0){
            for(OnboardingTask item : onboardingTaskList){
                
                System.debug('TASK NAME SELECTED = ' + item.onboardingTask.Task_Name__c);
                
                if(item.selected == true){
                    
                    //No. of days after hiring an employee
                    Decimal daysAfterHire = item.onboardingTask.No_of_Days_After_Hire_Date__c;                        
                    
                    //if NULL set to 0
                    daysAfterHire = daysAfterHire == NULL ? 0:daysAfterHire;
                    
                    //Convert daysAfterHire to Integer
                    Integer days = daysAfterHire.intValue();                        
                    
                    //Create a task
                    Task task = new Task();
                    task.OwnerId = item.onboardingTask.Assigned_To__c;
                    task.Subject = item.onboardingTask.Category__c;
                    task.Employee__c = employee.Id;
                    task.Goals__c = item.onboardingTask.Task_Name__c;
                    task.Outcomes__c = item.onboardingTask.Description__c;
                    task.WhatId = item.onboardingTask.Id;
                    task.ActivityDate = employee.Employment_Start_Date__c + days;                        
                    INSERT task;
                    
                    System.debug('TASK UPSERT = ' + task);
                } 
            }              
        }
        
        return new PageReference('/'+ employee.Id);
    }
    
    
    // Wrapper class
    public class OnboardingTask{        
        public Onboarding_Task_Config__c onboardingTask {get; set;}
        public Boolean selected {get; set;}
        
        //Constructor
        public OnboardingTask(Onboarding_Task_Config__c ot) {
            onboardingTask = ot;
            selected = true;
        }        
    }    
}