sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/Special_Procurement__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request</label>
    <nameField>
        <displayFormat>SPR-{00000000}</displayFormat>
        <label>Special Procurement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>a condition set following approval steps</description>
    <inlineHelpText>a condition set following approval steps</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Declined By Finance</fullName>
            </value>
            <value>
                <fullName>Approved By Team Lead</fullName>
            </value>
            <value>
                <fullName>Declined By Team Lead</fullName>
            </value>
            <value>
                <fullName>Approved By Director</fullName>
            </value>
            <value>
                <fullName>Declined By Director</fullName>
            </value>
            <value>
                <fullName>Approved by PP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Dim_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup from the FFA confic_dim1 object</description>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Teamlead__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Required_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_Date__c</fullName>
    <description>The date these items are required</description>
    <inlineHelpText>The date these items are required</inlineHelpText>
    <label>Required Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Advance</fullName>
            </value>
            <value>
                <fullName>Employee Reimbursement</fullName>
            </value>
            <value>
                <fullName>Special Procurement</fullName>
            </value>
            <value>
                <fullName>Consultancy Agreements</fullName>
            </value>
            <value>
                <fullName>FLT Commissions</fullName>
            </value>
            <value>
                <fullName>FLO Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/Special_Procurement_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request Line Item</label>
    <nameField>
        <displayFormat>SPR-LI-{0000000}</displayFormat>
        <label>Special Procurement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Special_Procurement__c.field-meta.xml
<CustomField>
    <fullName>Special_Procurement__c</fullName>
    <description>Relationship between Special Procurement  &amp; Special Procurement Line Item</description>
    <label>Special Procurement</label>
    <referenceTo>Special_Procurement__c</referenceTo>
    <relationshipName>Special_Procurement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/Vendor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Vendor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Add a comment explaining why the Actual Date was changed</description>
    <inlineHelpText>Add a comment explaining why the Actual Date was changed</inlineHelpText>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Vendor Invoice stages</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Items Received</fullName>
            </value>
            <value>
                <fullName>Pin Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Toilet Sale - FLO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Invoices</relationshipLabel>
    <relationshipName>Vendor_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/Vendor_Invoice_Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Purchase Order Line Item</label>
    <nameField>
        <displayFormat>VIPOLI-{0000000000}</displayFormat>
        <label>VI PO Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>AP Matched</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateEPRFromSpecialProcurementTrigger.cls
@isTest(seeAllData = true)
public class CreateEPRFromSpecialProcurementTrigger {
    static testMethod void testCreateEPRFromSpecialProcurement(){
        
        //Get dim1                              
        List<FFA_Config_Object__c> department = [SELECT Id,Name,Type__c,isActive__c 
                                                 FROM FFA_Config_Object__c 
                                                 WHERE Type__c = 'dim1' 
                                                 AND Name = 'Information Technology'
                                                 AND isActive__c = true LIMIT 1];
        System.debug('' + department);
        //Get dim2                                    
        List<FFA_Config_Object__c> dim2 = [SELECT Id,Name,Type__c,isActive__c 
                                           FROM FFA_Config_Object__c 
                                           WHERE Type__c = 'dim2' 
                                           AND isActive__c = true LIMIT 1];
        
        //Get dim3                                   
        List<FFA_Config_Object__c> dim3 = [SELECT Id,Name,Type__c,isActive__c 
                                           FROM FFA_Config_Object__c 
                                           WHERE Type__c = 'dim3' 
                                           AND isActive__c = true LIMIT 1];
        
        //Get dim4                                     
        List<FFA_Config_Object__c> dim4 = [SELECT Id,Name,Type__c,isActive__c 
                                           FROM FFA_Config_Object__c 
                                           WHERE Type__c = 'dim4' 
                                           AND isActive__c = true LIMIT 1];
        
        //Get GLA
        List<FFA_Config_Object__c> gla = [SELECT Id,Name,Type__c,isActive__c 
                                          FROM FFA_Config_Object__c 
                                          WHERE Type__c = 'gla' 
                                          AND isActive__c = true LIMIT 1];
        
        //Get Company
        FFA_Config_Object__c company= [SELECT Id,Name,Type__c,isActive__c 
                                       FROM FFA_Config_Object__c 
                                       WHERE type__c = 'company' 
                                       AND isActive__c = true 
                                       AND Name = 'Sanergy Limited'
                                       LIMIT 1];
        //Get employee
        //James ID - need to make sure emp selected has a TL for the sharing reasons to work 
        List<Employee__c> employee = [SELECT Id,Name,Employee_Active__c,Work_Email__c 
                                      FROM Employee__c 
                                      WHERE Employee_Active__c=true 
                                      AND Id = 'aAsD0000000GmgM' LIMIT 1];         
        
        //Get a vendor
        List<Account> vendor = [SELECT Id FROM Account WHERE RecordType.Name = 'Sanergy Vendor' LIMIT 1];
        
        //Create Special Procurement               
        Special_Procurement__c spr = new Special_Procurement__c();
        spr.Requestor__c = 'aAsD0000000GmgM';
        spr.Type__c = 'Cash Advance';
        spr.Required_Date__c = date.today();
        spr.Comments__c = 'Two tyres for Toyota Corolla';         
        spr.Requesting_Department__c = department.get(0).Id;
        spr.Vendor__c = vendor.get(0).Id;       
        spr.Approval_Status__c = 'Approved By Team Lead';
        spr.Dim_2__c = dim2.get(0).Id;
        spr.Dim_3__c = dim3.get(0).Id;
        spr.GLA__c = gla.get(0).Id;
        spr.Grant__c = dim4.get(0).Id;
        spr.Requesting_Company__c = company.Id;
        INSERT spr;
        
        System.debug('SPR: ' + spr.Requesting_Company__c);
        
        //Create Special Procurement Line Items
        Special_Procurement_Line_Item__c spLineItems = new Special_Procurement_Line_Item__c();
        spLineItems.Special_Procurement__c = spr.Id;
        spLineItems.Item__c = 'Two 18 Inch Car Tyress';
        spLineItems.Specifications__c = 'Two 18 Inch car tyres for Toyota Corollas';                  
        spLineItems.Quantity_Requested__c = 2;
        spLineItems.Unit_Price__c = 600;
        spLineItems.Status__c = 'Approved';
        INSERT spLineItems;
        
        //Update SPR
        spr.Stage__c='SPR Approved';
        UPDATE spr;
        
        //test to UPDATE a VI
        Vendor_Invoice__c vi = new Vendor_Invoice__c();
        vi = [SELECT Id, Name FROM Vendor_Invoice__c WHERE Count_VIPOLI__c > 1 ORDER BY CreatedDate DESC LIMIT 1];
        if(vi != NULL){
            vi.Status__c = 'Closed';
            UPDATE vi;
            vi.Status__c = 'AP Matched';
            UPDATE vi;
        }
        
        //test to delete a VI
        Vendor_Invoice__c viDEL = new Vendor_Invoice__c();
        viDEL.Vendor__c = vendor.get(0).Id;
        viDEL.Status__c = 'Open';
        INSERT viDEL;
        DELETE viDEL;
        
        Vendor_Invoice_Purchase_Order_Line_Item__c vipoli = new Vendor_Invoice_Purchase_Order_Line_Item__c();
        vipoli = [SELECT Id FROM Vendor_Invoice_Purchase_Order_Line_Item__c
		WHERE Vendor_Invoice__r.VI_Status__c = 'Open' LIMIT 1];
        if(vipoli != NULL){
            DELETE vipoli;
        }
    } 
}