sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Employment_Start_Date__c</fullName>
    <description>Employment Start Date</description>
    <label>Employment Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender</description>
    <inlineHelpText>Gender</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Group</label>
    <referenceTo>Leave_Group__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/Leave_Accrual__c.object-meta.xml
<CustomObject>
    <label>Leave Accrual</label>
    <nameField>
        <displayFormat>LAU-{00000000}</displayFormat>
        <label>Leave Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Days_Accrued__c.field-meta.xml
<CustomField>
    <fullName>Days_Accrued__c</fullName>
    <label>Days Accrued</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Accruals</relationshipLabel>
    <relationshipName>Leave_Accruals</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Accrual__c/fields/Leave_Entitlement_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Utilization__c</fullName>
    <label>Leave Entitlement Utilization</label>
    <referenceTo>Leave_Entitlement_Utilization__c</referenceTo>
    <relationshipLabel>Leave Accruals</relationshipLabel>
    <relationshipName>Leave_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/Leave_Entitlement_Type_Config__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Type Config</label>
    <nameField>
        <displayFormat>LET-{00000000}</displayFormat>
        <label>Leave Entitlement Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Type Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Group</label>
    <referenceTo>Leave_Group__c</referenceTo>
    <relationshipLabel>Leave Entitlement Type Configs</relationshipLabel>
    <relationshipName>Leave_Entitlement_Type_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Exam Leave</fullName>
            </value>
            <value>
                <fullName>Compassionate Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Proratable__c.field-meta.xml
<CustomField>
    <fullName>Proratable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Leave Type proratable ?</description>
    <inlineHelpText>Is the Leave Type proratable ?</inlineHelpText>
    <label>Proratable</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Total_No_of_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_Leave_Days__c</fullName>
    <label>Total No. of Leave Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Year_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Year_End_Date__c</fullName>
    <label>Year End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Type_Config__c/fields/Year_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Year_Start_Date__c</fullName>
    <label>Year Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/Leave_Entitlement_Utilization__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Utilization</label>
    <nameField>
        <displayFormat>LEU-{00000000}</displayFormat>
        <label>Leave Entitlement Utilization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Utilization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Entitlement_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Type_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Entitlement Type Config</label>
    <referenceTo>Leave_Entitlement_Type_Config__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Annual Leave&#39;) , &#39;Annual Leave&#39;,  IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Sick Leave&#39;) , &#39;Sick Leave&#39;,  
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Maternity Leave&#39;) , &#39;Maternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Paternity Leave&#39;) , &#39;Paternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Exam Leave&#39;) , &#39;Exam Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Compassionate Leave&#39;) , &#39;Compassionate Leave&#39;, NULL))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Year__c.field-meta.xml
<CustomField>
    <fullName>Leave_Year__c</fullName>
    <formula>Leave_Entitlement_Type_Config__r.Year__c</formula>
    <label>Leave Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Total_No_of_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_Leave_Days__c</fullName>
    <label>Total No. of Leave Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/Leave_Group__c.object-meta.xml
<CustomObject>
    <label>Leave Group</label>
    <nameField>
        <label>Leave Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Group__c/fields/Leave_Group__c.field-meta.xml
<CustomField>
    <fullName>Leave_Group__c</fullName>
    <label>Leave Group Comments</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateLeaveEntitlementUtilization.cls
public class CreateLeaveEntitlementUtilization {
    private Leave_Entitlement_Type_Config__c typeConfig;
    private ApexPages.StandardController standardController;
    public  List<empWrapper> emps{get; set;}
    public List<empWrapper>employeeList{get;set;}
    private List<String> genderFilter = new List<String>{'male','female'};
    public  Leave_Entitlement_Type_Config__c config{get; set;}
    public List<Leave_Entitlement_Utilization__c> utilizationList;
    public List<Leave_Accrual__c> accrualsList;
    
    public CreateLeaveEntitlementUtilization(ApexPages.StandardController standardController){
        this.standardController = standardController;
        //  standardController.addFields(new List<String> {'Leave_Type__c'});
        this.typeConfig = (Leave_Entitlement_Type_Config__c)standardController.getRecord();
        

    } 
    
    
    
    public List<empWrapper> getEmployees() {
        
      Leave_Entitlement_Type_Config__c config = [SELECT id,Leave_Type__c,Total_No_of_Leave_Days__c,Leave_Group__c,Proratable__c,Year_Start_Date__c,Year_End_Date__c,Year__c 
                                                   FROM Leave_Entitlement_Type_Config__c
                                                   WHERE id =: typeConfig.Id
                                                  ];
        system.debug ('Configdddd' + config);
        system.debug('typeconfig' + typeConfig.Id);
        if(emps== null) {
            employeeList= new List<empWrapper>();
            
            if(config.Leave_Type__c =='Paternity Leave'){
                genderFilter.clear();
                genderFilter.add('male');
            }else if (config.Leave_Type__c == 'Maternity Leave') {
                genderFilter.clear();
                genderFilter.add('female'); 
            }else {
                genderFilter.clear();
                genderFilter.add('male');
                genderFilter.add('female');
            }
            
            system.debug ('List Values : ' + genderFilter );
            
            
            List<Leave_Entitlement_Utilization__c> vv= [SELECT Employee__c, Name, Leave_Entitlement_Type_Config__c 
                                                        FROM Leave_Entitlement_Utilization__c
                                                        WHERE Leave_Type__c =: config.Leave_Type__c 
                                                        AND Leave_Year__c =: config.Year__c  
                                                        AND Leave_Entitlement_Type_Config__r.Leave_Group__c =: config.Leave_Group__c
                                                        ];
            system.debug('ccvvvvv' + vv);
            
            
            List<Employee__c> empsItems=[SELECT Id, Name, Leave_Group__c,Employment_Start_Date__c, Gender__c , Employee_Active__c FROM Employee__c
                                         WHERE Leave_Group__c =: config.Leave_Group__c  AND id NOT IN (SELECT Employee__c FROM Leave_Entitlement_Utilization__c
                                                                                                       WHERE Leave_Type__c =: config.Leave_Type__c 
                                                                                                       AND Leave_Year__c =: config.Year__c  
                                                                                                       AND Leave_Entitlement_Type_Config__r.Leave_Group__c =: config.Leave_Group__c
                                                                                                      )
                                        AND Employee_Active__c = TRUE  
                                        AND (Employment_Start_Date__c <=: config.Year_Start_Date__c OR (Employment_Start_Date__c >=: config.Year_Start_Date__c  AND Employment_Start_Date__c <=: config.Year_End_Date__c))
                                        AND Gender__c IN : genderFilter
                                         ORDER BY NAME
                                        ];
               system.debug('employeeListIIIIIIII' + empsItems);     
            
            for(Employee__c empItem : empsItems){
                empWrapper itm = new empWrapper(empItem);
                employeeList.add(itm);
            }
            
        }
        system.debug('employeeList' + employeeList);
        return employeeList;
        
    }
    
    public PageReference createUtilizations(){
                
      Leave_Entitlement_Type_Config__c config = [SELECT id,Leave_Type__c,Total_No_of_Leave_Days__c,Leave_Group__c,Proratable__c,Year_Start_Date__c,Year_End_Date__c,Year__c 
                                                   FROM Leave_Entitlement_Type_Config__c
                                                   WHERE id =: typeConfig.Id
                                                  ];
        
        if(employeeList != null && employeeList.size() > 0){
            
            utilizationList = new List<Leave_Entitlement_Utilization__c>();

            for(empWrapper empItem : employeeList){
                if(empItem.selected == true){
                     //Create Leave Entitlement Utilizations for the Employee
                    Leave_Entitlement_Utilization__c leaveUtilization = new Leave_Entitlement_Utilization__c();
                    leaveUtilization.Leave_Entitlement_Type_Config__c = typeConfig.Id;
                    leaveUtilization.Employee__c = empItem.emp.Id;
                    utilizationList.add(leaveUtilization);
                }
            }
            INSERT utilizationList;    
            
            accrualsList = new List<Leave_Accrual__c>();
            //Create Leave Accruals for inserted LEUs
            for(Leave_Entitlement_Utilization__c lvutl: utilizationList){
                Leave_Accrual__c leaveAccrual = new Leave_Accrual__c();
                //leaveAccrual.Name = leaveTypeConfig.Leave_Type__c;
                leaveAccrual.Leave_Entitlement_Utilization__c = lvutl.Id;
                leaveAccrual.Employee__c = lvutl.Employee__c;
                //leaveAccrual.Period__c = System.today().year() + ' - ' + System.today().month();
                leaveAccrual.Period__c = DateTime.newInstance(System.today().year(),System.today().month(),System.today().day()).format('yyyy-MM');
                
                if(config.Proratable__c==true){
                    leaveAccrual.Days_Accrued__c = 0.0;
                }else{
                    leaveAccrual.Days_Accrued__c = config.Total_No_of_Leave_Days__c;
                }    
                accrualsList.add(leaveAccrual);
            }
            //Insert Leave Accruals List
            INSERT accrualsList;
        }

         return new PageReference('/' + typeConfig.Id); 
    }
    
    public PageReference selectAll() {
        if(emps!= null){
            for(empWrapper lg:employeeList){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(emps!= null){
            for(empWrapper lg:employeeList){
                lg.selected=false;                
            }
        }
        return null;
    }
    
    
    public class empWrapper{
        public Boolean selected {get; set;}
        public Employee__c emp {get; set;}
        
        public empWrapper(Employee__c em) {
            emp = em;
            selected = true;
        }
    }
    
}