sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/fields/Delegate_s_Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Delegate_s_Threshold_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delegate&#39;s Threshold Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/Fleet_Request__c.object-meta.xml
<CustomObject>
    <label>Fleet Request</label>
    <nameField>
        <displayFormat>Fleet-{0000}</displayFormat>
        <label>Fleet Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Reason_For_Trip__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Trip__c</fullName>
    <label>Reason For Trip</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Fleet Requests</relationshipLabel>
    <relationshipName>Fleet_Requests3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Requesting_Employee__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Fleet Requests</relationshipLabel>
    <relationshipName>Fleet_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Quote</fullName>
            </value>
            <value>
                <fullName>Pending Team Lead Approval</fullName>
            </value>
            <value>
                <fullName>Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Bookings Confirmed</fullName>
            </value>
            <value>
                <fullName>Request Competed</fullName>
            </value>
            <value>
                <fullName>Request Cancelled</fullName>
                <isActive>false</isActive>
                <label>Request Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/Fleet_Requests__c.object-meta.xml
<CustomObject>
    <description>Trip legs for fleet requests</description>
    <label>Trip Leg</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Trip Leg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trip Legs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <description>Date of Departure</description>
    <label>Departure Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request__c</fullName>
    <label>Fleet Request</label>
    <referenceTo>Fleet_Request__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request_Status__c</fullName>
    <label>Fleet Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Open</fullName>
                <default>true</default>
                <label>Request Open</label>
            </value>
            <value>
                <fullName>Quote in Progress</fullName>
            </value>
            <value>
                <fullName>Pending TL Approval</fullName>
            </value>
            <value>
                <fullName>TL Approved</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Trip Completed</fullName>
            </value>
            <value>
                <fullName>Trip Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Grant_Funding_Availale_Dim_4__c.field-meta.xml
<CustomField>
    <fullName>Grant_Funding_Availale_Dim_4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grant Funding Availale (Dim 4)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Location_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Dim_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location (Dim 2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Nairobi</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Reason_for_Trip__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Trip__c</fullName>
    <label>Reason for Trip</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Requesting_Department</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Employee__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Requesting_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateFleetRequestForFarmstarTest.cls
@isTest(seeAllData=true)
private class CreateFleetRequestForFarmstarTest{


     /*------------------Test Class for the ValidateEPR Trigger------------------------- */  
      static testMethod void CreateFleetRequestForFarmstarDeliveryTester() {
      
         List<Employee__c> employee=[SELECT ID FROM Employee__c WHERE Employee_Active__c=true LIMIT 1];
         List<Account> vendor=[SELECT ID FROM Account WHERE RecordType.Name='Sanergy Vendor' LIMIT 1];
         List<Opportunity> op=[SELECT id,Purchase_Tons__c,Delivery__c FROM Opportunity WHERE RecordType.name='Agricultural Product Sales - Closing' LIMIT 1];


          //get the department
          FFA_Config_Object__c department=[SELECT id, Delegate_s_Threshold_Amount__c FROM FFA_Config_Object__c WHERE Type__c='dim1' AND isActive__c=true AND Delegate_s_Threshold_Amount__c > 0 LIMIT 1];
          
           //get the location
          FFA_Config_Object__c location=[SELECT id FROM FFA_Config_Object__c WHERE Type__c='dim2'  AND isActive__c=true LIMIT 1];


         //get the dim3
          FFA_Config_Object__c dim3=[SELECT id FROM FFA_Config_Object__c WHERE Type__c='dim3'  AND isActive__c=true LIMIT 1];


         //get the dim4
          FFA_Config_Object__c grant=[SELECT id FROM FFA_Config_Object__c WHERE Type__c='dim4'  AND isActive__c=true LIMIT 1];

            //create fleet request
         Fleet_Request__c request=new Fleet_Request__c(
             Company__c='Sanergy Ltd',
             Reason_For_Trip__c='Reason',
             Requesting_Department__c=department.id,
             Requesting_Employee__c=employee.get(0).id,
             Status__c='Open'
         );
         
         
          Fleet_Requests__c tripLeg=new Fleet_Requests__c(
            Fleet_Request_Status__c='Request Open',
            Reason_for_Trip__c='some reason goes here...',
            Company__c='Sanergy Ltd',
            Location_Dim_2__c=location.ID,
            Dim_3__c=dim3.ID,
            Grant_Funding_Availale_Dim_4__c=grant.ID,
            Pickup_Location__c='Kilimani',
            Destination__c='Mukuru',
            Departure_Date__c= Date.today()+30,
            Departure_Time__c='09:00',
            Cargo__c='Yes',
            Number_of_Passengers__c=2,
            Driver_Required__c='Yes',
            Cargo_Details__c='Materials',
            Vehicle_Type__c='Double Cab',
            Fleet_Request__c=request.id
        );
        
          
          
          
          test.StartTest();
          PageReference pageRef = Page.Create_Fleet_Request_for_Farmstar;
          Test.setCurrentPage(pageRef);
          ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(op.get(0));
          CreateFleetRequestForFarmstarDelivery controller = new CreateFleetRequestForFarmstarDelivery(sc);
          controller.fleet=request;
          controller.leg=tripLeg;
          controller.createRequest();
          test.StopTest(); 
    } 
  }