sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Leave_Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Accrual_Start_Date__c</fullName>
    <label>Leave Accrual Start Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/Employee_Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Employee Leave Request</label>
    <nameField>
        <displayFormat>ELR-{00000000}</displayFormat>
        <label>Employee Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Leave Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>a condition set following approval steps</description>
    <inlineHelpText>a condition set following approval steps</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Team Lead</fullName>
            </value>
            <value>
                <fullName>Declined by Team Lead</fullName>
            </value>
            <value>
                <fullName>Approved by HR</fullName>
            </value>
            <value>
                <fullName>Declined by HR</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Time_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Employee_s_Department__c.field-meta.xml
<CustomField>
    <fullName>Employee_s_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee&#39;s Department</label>
    <referenceTo>Sanergy_Department_Unit__c</referenceTo>
    <relationshipLabel>Employee Leave Requests</relationshipLabel>
    <relationshipName>Employee_Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Leave_Approved__c.field-meta.xml
<CustomField>
    <fullName>Leave_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The checkbox is checked if Leave has been approved otherwise it&#39;s unchecked</inlineHelpText>
    <label>Leave Approved ?</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Leave_Entitlement_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Leave_Entitlement_Utilization__c</fullName>
    <label>Leave Entitlement Utilization</label>
    <referenceTo>Leave_Entitlement_Utilization__c</referenceTo>
    <relationshipLabel>Employee Leave Requests</relationshipLabel>
    <relationshipName>Employee_Time_Offs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>Leave_Entitlement_Utilization__r.Leave_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/No_Of_Approved_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Approved_Leave_Days__c</fullName>
    <label>No. Of Approved Leave Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Leave_Request__c/fields/No_Of_Leave_Days_Requested__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Leave_Days_Requested__c</fullName>
    <label>No. Of Leave Days Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/Leave_Entitlement_Utilization__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement Utilization</label>
    <nameField>
        <displayFormat>LEU-{00000000}</displayFormat>
        <label>Leave Entitlement Utilization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement Utilization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Entitlement Utilization</relationshipLabel>
    <relationshipName>Leave_Entitlement_Utilization</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Leave_Entitlement_Utilization__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <formula>IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Annual Leave&#39;) , &#39;Annual Leave&#39;,  IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Sick Leave&#39;) , &#39;Sick Leave&#39;,  
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Maternity Leave&#39;) , &#39;Maternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Paternity Leave&#39;) , &#39;Paternity Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Exam Leave&#39;) , &#39;Exam Leave&#39;,
IF( ISPICKVAL(Leave_Entitlement_Type_Config__r.Leave_Type__c, &#39;Compassionate Leave&#39;) , &#39;Compassionate Leave&#39;, NULL))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <description>Sanergy Department</description>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/EmployeesWhoAreOnLeave.cls
public class EmployeesWhoAreOnLeave {
    
    //create standard controller
    private ApexPages.StandardController controller;
    
    // Leave in between list
    public List<Employee_Leave_Request__c> leaveBetweenList{get;set;}
    
    // Employees going on leave in the next 30 days
    public List<Employee_Leave_Request__c> employeesOnLeave{get;set;}
    
    //Get the id of the Employee_Leave_Request_c 
    public Employee_Leave_Request__c leaveRequest{get; set;}
    
    //Get Employees  
    public Date leaveStartDate;
    public Date leaveEndDate;

    // Constructor
    public EmployeesWhoAreOnLeave(){ 
        leaveStartDate = date.today();
		leaveEndDate = date.today() + 30;
        getEmployeesOnLeave();
    }
    
    // Constructor
    public EmployeesWhoAreOnLeave(ApexPages.StandardController controller){               
        this.controller = controller;
        leaveRequest = (Employee_Leave_Request__c)controller.getRecord();
        System.debug('EEEE' + leaveRequest);
        leaveRequest= [SELECT Id, Name,Leave_Entitlement_Utilization__c,Employee__c,Employee__r.Name,Leave_Start_Date__c,Leave_End_Date__c,
                       Employee_s_Department__c,Employee_s_Department__r.Name,Approval_Status__c,Leave_Approved__c,Leave_Type__c,No_Of_Leave_Days_Requested__c,No_Of_Approved_Leave_Days__c,
                       Employee__r.Leave_Accrual_Start_Date__c 
                       FROM Employee_Leave_Request__c														
                       WHERE ID =: leaveRequest.Id
                      ];
        
        
    }
    
    //Get the People On leave in Between the days the days the Employee is Requesting for Leave 
    public List<Employee_Leave_Request__c> getLeaveBetween(){
        leaveBetweenList = [SELECT Id, Name,Leave_Entitlement_Utilization__c,Employee__c,Employee__r.Name,Leave_Start_Date__c,Leave_End_Date__c,Employee__r.Employee_active__c,
                            Employee_s_Department__c,Employee__r.Sanergy_Department__r.Name,Approval_Status__c,Leave_Approved__c,Leave_Type__c,No_Of_Leave_Days_Requested__c,
                            No_Of_Approved_Leave_Days__c,Employee__r.Leave_Accrual_Start_Date__c 
                            FROM Employee_Leave_Request__c														
                            WHERE ((Leave_Start_Date__c >=: leaveRequest.Leave_Start_Date__c AND Leave_Start_Date__c <=: leaveRequest.Leave_End_Date__c) 
                                   OR (Leave_End_Date__c >=: leaveRequest.Leave_Start_Date__c AND Leave_Start_Date__c <=: leaveRequest.Leave_End_Date__c)) 
                            AND (Approval_Status__c = 'Approved by HR' OR Approval_Status__c = 'Pending Approval')
                            AND (Employee__r.Employee_active__c = true)
                            ORDER BY Leave_Start_Date__c DESC
                           ];
        System.debug('LEAVE BETWEEN: ' + leaveBetweenList);
        return leaveBetweenList;
        
    }
    
    //Employees going on leave in the next 30 days
    public List<Employee_Leave_Request__c> getEmployeesOnLeave(){
        employeesOnLeave = [SELECT Id, Name,Leave_Entitlement_Utilization__c,Employee__c,Employee__r.Name,Leave_Start_Date__c,Leave_End_Date__c,Employee__r.Employee_active__c,
                            Employee_s_Department__c,Employee__r.Sanergy_Department__r.Name,Approval_Status__c,Leave_Approved__c,Leave_Type__c,No_Of_Leave_Days_Requested__c,
                            No_Of_Approved_Leave_Days__c,Employee__r.Leave_Accrual_Start_Date__c 
                            FROM Employee_Leave_Request__c														
                            WHERE ((Leave_Start_Date__c >=: leaveStartDate AND Leave_Start_Date__c <=: leaveEndDate) 
                                   OR (Leave_End_Date__c >=: leaveStartDate AND Leave_End_Date__c <=: leaveEndDate)) 
                            AND (Approval_Status__c = 'Approved by HR' AND Employee__r.Employee_active__c = true)                            
                            ORDER BY Leave_Start_Date__c ASC
                           ];
        
        System.debug('EMPLOYEES ON LEAVE: ' + employeesOnLeave);
        return employeesOnLeave;
    }    
}