sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/Special_Procurement__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request</label>
    <nameField>
        <displayFormat>SPR-{00000000}</displayFormat>
        <label>Special Procurement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>a condition set following approval steps</description>
    <inlineHelpText>a condition set following approval steps</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Declined By Finance</fullName>
            </value>
            <value>
                <fullName>Approved By Team Lead</fullName>
            </value>
            <value>
                <fullName>Declined By Team Lead</fullName>
            </value>
            <value>
                <fullName>Approved By Director</fullName>
            </value>
            <value>
                <fullName>Declined By Director</fullName>
            </value>
            <value>
                <fullName>Approved by PP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Dim_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements5</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requesting_Company__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requesting Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup from the FFA confic_dim1 object</description>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Teamlead__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Required_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_Date__c</fullName>
    <description>The date these items are required</description>
    <inlineHelpText>The date these items are required</inlineHelpText>
    <label>Required Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Advance</fullName>
            </value>
            <value>
                <fullName>Employee Reimbursement</fullName>
            </value>
            <value>
                <fullName>Special Procurement</fullName>
            </value>
            <value>
                <fullName>Consultancy Agreements</fullName>
            </value>
            <value>
                <fullName>FLT Commissions</fullName>
            </value>
            <value>
                <fullName>FLO Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/Special_Procurement_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request Line Item</label>
    <nameField>
        <displayFormat>SPR-LI-{0000000}</displayFormat>
        <label>Special Procurement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <description>Quantity to be requested</description>
    <inlineHelpText>Quantity to be requested</inlineHelpText>
    <label>Quantity Requested</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Special_Procurement__c.field-meta.xml
<CustomField>
    <fullName>Special_Procurement__c</fullName>
    <description>Relationship between Special Procurement  &amp; Special Procurement Line Item</description>
    <label>Special Procurement</label>
    <referenceTo>Special_Procurement__c</referenceTo>
    <relationshipName>Special_Procurement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Specifications__c.field-meta.xml
<CustomField>
    <fullName>Specifications__c</fullName>
    <inlineHelpText>State a precise requirement.</inlineHelpText>
    <label>Specifications</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/GenerateSPRLineItemsTest.cls
@isTest(seeAllData = true)
public class GenerateSPRLineItemsTest {
    static testMethod void GenerateSPRLineItemsTest(){
        List<User> userFFA=[Select Name, ID  From User WHERE name='Temp RS Account'];
        if(userFFA.size()>0){
            System.runAs(userFFA.get(0)){
                //Get dim1                              
                List<FFA_Config_Object__c> department = [SELECT Id,Name,Type__c,isActive__c 
                                                         FROM FFA_Config_Object__c 
                                                         WHERE Type__c = 'dim1' 
                                                         AND Name = 'Information Technology'
                                                         AND isActive__c = true LIMIT 1];
                System.debug('' + department);
                //Get dim2                                    
                List<FFA_Config_Object__c> dim2 = [SELECT Id,Name,Type__c,isActive__c 
                                                   FROM FFA_Config_Object__c 
                                                   WHERE Type__c = 'dim2' 
                                                   AND isActive__c = true LIMIT 1];
                
                //Get dim3                                   
                List<FFA_Config_Object__c> dim3 = [SELECT Id,Name,Type__c,isActive__c 
                                                   FROM FFA_Config_Object__c 
                                                   WHERE Type__c = 'dim3' 
                                                   AND isActive__c = true LIMIT 1];
                
                //Get dim4                                     
                List<FFA_Config_Object__c> dim4 = [SELECT Id,Name,Type__c,isActive__c 
                                                   FROM FFA_Config_Object__c 
                                                   WHERE Type__c = 'dim4' 
                                                   AND isActive__c = true LIMIT 1];
                
                //Get GLA
                List<FFA_Config_Object__c> gla = [SELECT Id,Name,Type__c,isActive__c 
                                                  FROM FFA_Config_Object__c 
                                                  WHERE Type__c = 'gla' 
                                                  AND isActive__c = true LIMIT 1];
                
                //Get Company
                FFA_Config_Object__c company= [SELECT Id,Name,Type__c,isActive__c 
                                               FROM FFA_Config_Object__c 
                                               WHERE type__c = 'company' 
                                               AND isActive__c = true 
                                               AND Name = 'Sanergy Limited'
                                               LIMIT 1];
                /*Get employee
                List<Employee__c> employee = [SELECT Id,Name,Employee_Active__c,Work_Email__c 
                                              FROM Employee__c 
                                              WHERE id = 'aAsD0000000GmgM' LIMIT 1];*/ //James ID - need to make sure emp selected has a TL for the sharing reasons to work    
                
                //Get a vendor
                List<Account> vendor = [SELECT Id FROM Account WHERE RecordType.Name = 'Sanergy Vendor' LIMIT 1];      
                
                //Create Special Procurement               
                Special_Procurement__c sp1 = new Special_Procurement__c();
                sp1.Requestor__c = 'aAsD0000000GmgM';
                sp1.Type__c = 'Special Procurement';
                sp1.Required_Date__c = date.today();
                sp1.Comments__c = 'Two tyres for Toyota Corolla';         
                sp1.Requesting_Department__c = department.get(0).Id;
                sp1.Vendor__c = vendor.get(0).Id;       
                sp1.Approval_Status__c = 'Approved By Team Lead';
                sp1.Dim_2__c = dim2.get(0).Id;
                sp1.Dim_3__c = dim3.get(0).Id;
                sp1.GLA__c = gla.get(0).Id;
                sp1.Grant__c = dim4.get(0).Id;
                sp1.Requesting_Company__c = company.Id;
                INSERT sp1;
                
                System.debug('SPR: ' + sp1.Requesting_Company__c);
                
                //Create Special Procurement Line Items
                Special_Procurement_Line_Item__c spLineItems1 = new Special_Procurement_Line_Item__c();
                spLineItems1.Special_Procurement__c = sp1.Id;
                spLineItems1.Item__c = 'Two 18 Inch Car Tyress';
                spLineItems1.Specifications__c = 'Two 18 Inch car tyres for Toyota Corollas';                  
                spLineItems1.Quantity_Requested__c = 2;
                spLineItems1.Unit_Price__c = 600;
                spLineItems1.Status__c = 'Approved';
                INSERT spLineItems1;
                
                GenerateSPRLineItemsTest gen = new GenerateSPRLineItemsTest();
            }
        }
    }
}