sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Active__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Employee Status</description>
    <label>Employee Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/HR_Unique_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>HR_Unique_Record_ID__c</fullName>
    <label>HR Unique Record ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Location__c</fullName>
    <label>Primary Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Primary Phone Contact</description>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <formula>IMAGE(&quot;https://26d2cfa1970920cb0c9f-e476f77643361d94b1af81fa4ffb5ea7.ssl.cf1.rackcdn.com/photos/&quot;  &amp;  HR_Unique_Record_ID__c  &amp; &quot;-0-4.jpg&quot;, &quot;Missing&quot;,150,150)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Picture</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Sanergy_Department_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Department Unit</label>
    <referenceTo>Sanergy_Department_Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Work Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/Employee_Role__c.object-meta.xml
<CustomObject>
    <label>Employee Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <formula>Sanergy_Department_Unit__r.Sanergy_Department__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sanergy Department</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Sanergy_Department_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department_Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Unit</label>
    <referenceTo>Sanergy_Department_Unit__c</referenceTo>
    <relationshipLabel>Employee Roles</relationshipLabel>
    <relationshipName>Employee_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <description>Sanergy Department</description>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/EmployeeDirectory.cls
public class EmployeeDirectory {
    
    public List <Employee__c> employees {get;set;}
    public String searchText {get;set;}
    public String filterValue {get;set;}
    public Boolean active;
    
    //constructor
    public EmployeeDirectory(){
        //get employeeDetails when the method is called
        getEmployeeDetails();
        searchText = '';
        filterValue = '';
    } 
    
    public List<SelectOption> getdynamiclist() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Active','Active Employees'));
        options.add(new SelectOption('Inactive','Inactive Employees'));
        //options.add(new SelectOption('%%','All Employees'));
        return options;
    }
    
    public void getEmployeeDetails(){
        
        //Select employee details from the employee table
        
        if(searchText == '' ){
            employees = [SELECT Id, Name, Profile_Picture__c, Employee_Role__c, Employee_Role__r.Name,Sanergy_Department_Unit__r.Name,HR_Unique_Record_ID__c,
                         Primary_Location__c, Sanergy_Department__c,Sanergy_Department__r.Name,Work_Email__c,Primary_Phone__c
                         FROM Employee__c
                         ORDER BY Name ASC];
            
            System.debug('filter : '+filterValue);
            
        }else{
            searchText = '%'+ searchText + '%';
            if(filterValue != null){
                if(filterValue == 'Active'){
                    active = true;
                }else if(filterValue == 'Inactive'){
                    active = false;
                }else{
                    active = true;
                }
            }
            employees = [SELECT Id, Name, Profile_Picture__c, Employee_Role__c, Employee_Role__r.Name,Sanergy_Department_Unit__r.Name,HR_Unique_Record_ID__c,
                         Primary_Location__c, Sanergy_Department__c,Sanergy_Department__r.Name,Work_Email__c,Primary_Phone__c
                         FROM Employee__c
                         WHERE (Name LIKE : searchText 
                         OR Sanergy_Department__r.Name LIKE : searchText
                         OR Sanergy_Department_Unit__r.Name LIKE : searchText
                         OR Employee_Role__r.Name LIKE : searchText)
                         AND Employee_Active__c  =: active
                         ORDER BY Name ASC];
            
            System.debug('employee ' + employees);
            
            //after fetching the employees clear the % sign on the searchText
            searchText = searchText.replaceAll('%','');
            
            System.debug('filter : '+filterValue);
        }
        System.debug('EMPLOYEE: ' + employees);
        
    }

}