sfSandBoxCode/force-app/main/default/objects/Ussd_Cate_C__c/Ussd_Cate_C__c.object-meta.xml
<CustomObject>
    <label>USSD Case Categories</label>
    <nameField>
        <displayFormat>USSD-CAT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>USSD Case Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Ussd_Cate_C__c/fields/category_name__c.field-meta.xml
<CustomField>
    <fullName>category_name__c</fullName>
    <label>category name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Ussd_Cate_C__c/fields/USSD_Row_Number__c.field-meta.xml
<CustomField>
    <fullName>USSD_Row_Number__c</fullName>
    <description>Row Number to be displayed on USSD</description>
    <inlineHelpText>Row Number to be displayed on USSD</inlineHelpText>
    <label>USSD Row Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_CaseCategories.cls
//Get all Case Categories
@RestResource(urlMapping='/api/casecategory')
global with sharing class REST_CaseCategories {
    
    @HttpGet
    global static List<CaseCategory> getCaseCategory() {
        
        List<CaseCategory> caseCategories = new List<CaseCategory>();
        
        List<Ussd_Cate_C__c> ussdCaseCategories = [SELECT Id, Name, category_name__c, USSD_Row_Number__c
                                                   FROM Ussd_Cate_C__c ORDER BY USSD_Row_Number__c ASC];
        
        if(ussdCaseCategories != null && ussdCaseCategories.size()> 0){
            
            for(Ussd_Cate_C__c ussdCaseCategory : ussdCaseCategories){
                
                CaseCategory category = new CaseCategory();
                
                category.guid = ussdCaseCategory.Id;
                category.caseCategoryName = ussdCaseCategory.category_name__c;
                category.rowNumber = ussdCaseCategory.USSD_Row_Number__c;
                
                caseCategories.add(category);
            }
        }
        
        System.debug('CASE CATEGORIES: = ' + caseCategories);
        
        return caseCategories;
    }
    
    global class CaseCategory {        
        public String guid;
        public String caseCategoryName;
        public Decimal rowNumber;
    }  
    
}