sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/Farmstar_C2C_Visit__c.object-meta.xml
<CustomObject>
    <label>Farmstar C2C Visit</label>
    <nameField>
        <displayFormat>FS-C2C-{0000}</displayFormat>
        <label>Farmstar C2C Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmstar C2C Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Agricultural Products Customers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Farmstar C2C Visits</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Bigger_fruits__c.field-meta.xml
<CustomField>
    <fullName>Bigger_fruits__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bigger fruits</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Collected_renewal_order__c.field-meta.xml
<CustomField>
    <fullName>Collected_renewal_order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collected renewal order</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Create_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Create_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Opportunity</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Delivery_instructions__c.field-meta.xml
<CustomField>
    <fullName>Delivery_instructions__c</fullName>
    <label>Delivery instructions</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product already sold &amp; delivered</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Customer Pick-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Deposit_Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount_Received__c</fullName>
    <label>Deposit Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Earlier_fruit_pod_formation__c.field-meta.xml
<CustomField>
    <fullName>Earlier_fruit_pod_formation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Earlier fruit/pod formation</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Evergrow_25Kg_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Evergrow_25Kg_Quantity__c</fullName>
    <label>Evergrow - [25Kg]-Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Evergrow_35Kg_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Evergrow_35Kg_Quantity__c</fullName>
    <label>Evergrow - [35Kg]-Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Evergrow_50Kg_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Evergrow_50Kg_Quantity__c</fullName>
    <label>Evergrow - [50Kg]-Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Evergrow_5Kg_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Evergrow_5Kg_Quantity__c</fullName>
    <label>Evergrow - [5Kg]-Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Free_or_Discounted_Trial__c.field-meta.xml
<CustomField>
    <fullName>Free_or_Discounted_Trial__c</fullName>
    <label>Free or Discounted Trial?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Farmstar C2C Visits</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity_Product2__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evergrow - [35Kg]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <value>Evergrow - [35Kg],Evergrow Sample - 35kg - FREE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Farmstar C2C Visits (Opportunity Product)</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity_Product3__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evergrow - [25KG]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <value>EVERGROW - [25KG]</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Farmstar C2C Visits (Opportunity Product)</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity_Product4__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evergrow - [5Kg]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <value>Evergrow - [5Kg],Evergrow Sample - 5kg - 20% DISCOUNT,Evergrow Sample - 5kg - 50% DISCOUNT,Evergrow Sample - 5kg - FREE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Farmstar C2C Visits (Opportunity Product)</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evergrow - [50Kg]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <value>Evergrow - [50Kg],Evergrow Sample - 50kg - FREE,Evergrow Sample - 50kg - 50% DISCOUNT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Farmstar C2C Visits</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Sale Confirmed</fullName>
            </value>
            <value>
                <fullName>Presented Sale Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Mobile Money</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upfront</fullName>
            </value>
            <value>
                <fullName>50% Down, 50% on Delivery</fullName>
            </value>
            <value>
                <fullName>Other - Discussed with Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Preferred_Delivery_Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Delivery_Pickup_Date_Time__c</fullName>
    <label>Preferred Delivery/ Pickup Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Primary_Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Primary_Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Salesperson</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Farmstar C2C Visits</relationshipLabel>
    <relationshipName>Farmstar_C2C_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Sales_Order_Signed__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Signed__c</fullName>
    <label>Sales Order Signed?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Very_Next_Step__c.field-meta.xml
<CustomField>
    <fullName>Very_Next_Step__c</fullName>
    <label>Very Next Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Farmstar_C2C_Visit__c/fields/Very_Next_Step_Date__c.field-meta.xml
<CustomField>
    <fullName>Very_Next_Step_Date__c</fullName>
    <label>Very Next Step Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Stage__c/Opportunity_Stage__c.object-meta.xml
<CustomObject>
    <label>Opportunity Stage History</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Opportunity Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Stage History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Stage__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>From</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/TestCountC2CforAgriculturalSaleOpp.cls
@isTest(SeeAllData=true)
public class TestCountC2CforAgriculturalSaleOpp {
    static testMethod void testCountC2C(){
         /*(RecordTypeId ='012D0000000KGCKIA4' OR RecordTypeId ='012D0000000KGBlIAO'
                                        OR RecordTypeId ='012D0000000KGCtIAO' OR RecordTypeId ='012D0000000KGB7IAO' 
                                        OR RecordTypeId ='012D0000000KFz6IAG')*/
       /* List<Farmstar_C2C_Visit__c> c22 = [SELECT Id,Name,Opportunity__c,Opportunity_Stage__c,Close_Date__c,Delivery_Method__c,
                                           Sales_Order_Signed__c,Create_Opportunity__c,
                                           Delivery_instructions__c,Payment_Method__c,Payment_Schedule__c,Primary_Salesperson__c,
                                           Preferred_Delivery_Pickup_Date_Time__c,Deposit_Amount_Received__c,Free_or_Discounted_Trial__c
                                          FROM Farmstar_C2C_Visit__c WHERE Opportunity__c != null 
                                          // AND Create_Opportunity__c = false
                                          AND Sales_Order_Signed__c != 'Yes'];
        if(c22.size()>0){
            //c22.get(0).Opportunity_Stage__c = 'Closing';
            c22.get(0).Opportunity__c = null;
            c22.get(0).Close_Date__c = Date.today()+90;
            c22.get(0).Delivery_Method__c = 'Delivery';
            c22.get(0).Delivery_instructions__c = 'assds';
            c22.get(0).Payment_Method__c = 'Cash';
            c22.get(0).Payment_Schedule__c = 'Upfront';
			
            c22.get(0).Preferred_Delivery_Pickup_Date_Time__c = dateTime.now();
            c22.get(0).Deposit_Amount_Received__c = 100000;
            c22.get(0).Free_or_Discounted_Trial__c = 'No';
           // c22.get(0).Sales_Order_Signed__c = 'Yes'; 
            //update c22;
            
            c22.get(0).Create_Opportunity__c = true;
            c22.get(0).Opportunity_Stage__c = 'Sale Confirmed';
            update c22;
        }*/
        
        Opportunity opportunity = [SELECT Id,AccountId, StageName,Primary_Salesperson__c 
                                   FROM Opportunity
                                   WHERE RecordTypeId = '012D0000000KGBlIAO' 
                                   AND StageName = 'Sale Confirmed'
                                   Limit 1];
        
        opportunity.Opportunity_Type__c = 'KuzaPro Sale'; 
        UPDATE opportunity;
        
        if(opportunity!= null){
            
            List<Product2> product = [SELECT Id,Name FROM Product2 WHERE Name = 'EVERGROW - [25KG]'];
            if(product.size()>0){
                List<Product2> product2 = [SELECT Id,Name FROM Product2 WHERE Name = 'Evergrow - [35Kg]'];
                if(product2.size()>0){
                    List<Product2> product3 = [SELECT Id,Name FROM Product2 WHERE Name = 'Evergrow - [50Kg]'];
                    if(product3.size()>0){
                        List<Product2> product4 = [SELECT Id,Name FROM Product2 WHERE Name = 'Evergrow - [5Kg]'];
                        if(product4.size()>0){
                            
                            Farmstar_C2C_Visit__c c2c = new Farmstar_C2C_Visit__c();
                            c2c.Account__c = opportunity.AccountId;
                            c2c.Earlier_fruit_pod_formation__c = true;
                            c2c.Collected_renewal_order__c = true;
                            c2c.Close_Date__c = date.today()+90;
                            c2c.Sales_Order_Signed__c = 'Yes';
                            
                            c2c.Bigger_fruits__c = true;
                            c2c.Opportunity_Product__c = product3.get(0).Id;
                            c2c.Opportunity_Product2__c = product2.get(0).Id;
                            c2c.Opportunity_Product3__c = product.get(0).Id;
                            c2c.Opportunity_Product4__c = product4.get(0).Id;
                            c2c.Evergrow_25Kg_Quantity__c = 1;
                            c2c.Evergrow_35Kg_Quantity__c = 1;
                            c2c.Evergrow_50Kg_Quantity__c = 1;
                            c2c.Evergrow_5Kg_Quantity__c = 1;
                            c2c.Create_Opportunity__c = true;
                            c2c.Very_Next_Step__c = 'wer';
                            c2c.Very_Next_Step_Date__c = date.today() +1;
                            c2c.Opportunity_Stage__c = 'Sale Confirmed';
                            c2c.Close_Date__c = Date.today()+90;
                            c2c.Delivery_Method__c = 'Delivery';
                            c2c.Delivery_instructions__c = 'assds';
                            
                            c2c.Opportunity__c = opportunity.Id;
                            c2c.Payment_Method__c = 'Cash';
                            c2c.Payment_Schedule__c = 'Upfront';
                            c2c.Primary_Salesperson__c = opportunity.Primary_Salesperson__c;
                            c2c.Preferred_Delivery_Pickup_Date_Time__c = dateTime.now();
                            c2c.Deposit_Amount_Received__c = 100000;
                            c2c.Free_or_Discounted_Trial__c = 'No';
                            insert c2c;                
                            
                            
                            Farmstar_C2C_Visit__c c2 = new Farmstar_C2C_Visit__c();
                            c2.Account__c = opportunity.AccountId;
                            c2.Earlier_fruit_pod_formation__c = true;
                            c2.Collected_renewal_order__c = true;
                            c2.Close_Date__c = date.today()+90;
                            c2.Sales_Order_Signed__c = 'Yes';
                            
                            c2.Bigger_fruits__c = true;
                            c2.Opportunity_Product__c = product3.get(0).Id;
                            c2.Opportunity_Product2__c = product2.get(0).Id;
                            c2.Opportunity_Product3__c = product.get(0).Id;
                            c2.Opportunity_Product4__c = product4.get(0).Id;
                            c2.Evergrow_25Kg_Quantity__c = 1;
                            c2.Evergrow_35Kg_Quantity__c = 1;
                            c2.Evergrow_50Kg_Quantity__c = 1;
                            c2.Evergrow_5Kg_Quantity__c = 1;
                            c2.Create_Opportunity__c = true;
                            c2.Very_Next_Step__c = 'wer';
                            c2.Very_Next_Step_Date__c = date.today() +1;
                            c2.Opportunity_Stage__c = 'Closing';
                            c2.Close_Date__c = Date.today()+90;
                            c2.Delivery_Method__c = 'Delivery';
                            c2.Delivery_instructions__c = 'assds';
                            
                            c2.Opportunity__c = null;
                            c2.Payment_Method__c = 'Cash';
                            c2.Payment_Schedule__c = 'Upfront';
                            c2.Primary_Salesperson__c = opportunity.Primary_Salesperson__c;
                            c2.Preferred_Delivery_Pickup_Date_Time__c = dateTime.now();
                            c2.Deposit_Amount_Received__c = 100000;
                            c2.Free_or_Discounted_Trial__c = 'No';
                            
                            insert c2;
                            c2.Very_Next_Step__c = 'true';
                            c2.Very_Next_Step_Date__c = date.today();
                            update c2;
                            
                            c2.Create_Opportunity__c = false;
                            update c2; 
                            
                            c2.Create_Opportunity__c = true;
                            update c2; 
                            
                            c2.Create_Opportunity__c = false;
                            update c2; 
                            
                            /*c2.Create_Opportunity__c = true;
c2.Opportunity_Stage__c = 'Sale Confirmed';
update c2;*/
                            
                            opportunity.Sale_Made__c = 'No';
                            opportunity.Ag_Sales_Dummy_Stage__c  = 'Close Sale';
                            Update opportunity;
                            
                            
                            
                            opportunity.Sale_Made__c = 'Yes';
                            opportunity.Ag_Sales_Dummy_Stage__c  = 'Schedule Followup';
                            Update opportunity;
                            
                            opportunity.Ag_Sales_Dummy_Stage__c  = 'Collect Deposit Balance';
                            Update opportunity;
                            
                            opportunity.Ag_Sales_Dummy_Stage__c  = 'Lost';
                            Update opportunity;
                            
                            c2c.Opportunity_Stage__c = 'Closing';
                            
                            
                            update c2c;
                        }
                    }
                }
            }
        }
        
    }
    
}