sfSandBoxCode/force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Area__c/fields/Area_Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Area_Abbreviation__c</fullName>
    <description>Area Abbreviation e.g KR , KN ,VW</description>
    <inlineHelpText>Area Abbreviation e.g KR , KN ,VW</inlineHelpText>
    <label>Area Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Area__c/fields/Last_Location_No__c.field-meta.xml
<CustomField>
    <fullName>Last_Location_No__c</fullName>
    <label>Last Location No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT( Sub_Area__r.Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Area_Name__c.field-meta.xml
<CustomField>
    <fullName>Area_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area Name</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Type__c</fullName>
    <description>Type of franchise that the FLO runs.</description>
    <inlineHelpText>Type of franchise that the FLO runs. Selected by the marketing team after the toilet is launched.</inlineHelpText>
    <label>Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial-Open market</fullName>
            </value>
            <value>
                <fullName>Commercial-Residential</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Plot</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-School</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Plot</fullName>
            </value>
            <value>
                <fullName>Hybrid-School</fullName>
            </value>
            <value>
                <fullName>Competitor Location</fullName>
            </value>
            <value>
                <fullName>Demo Toilet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Last_FLT__c.field-meta.xml
<CustomField>
    <fullName>Last_FLT__c</fullName>
    <label>Last FLT</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Area</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Waste_User_Ratio__c.field-meta.xml
<CustomField>
    <fullName>Waste_User_Ratio__c</fullName>
    <defaultValue>0.302</defaultValue>
    <inlineHelpText>Please enter the waste to user ratio for this particular location</inlineHelpText>
    <label>Waste:User Ratio</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub-Area</label>
    <nameField>
        <label>Sub-Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kwa Ruben</fullName>
            </value>
            <value>
                <fullName>Kwa Njenga</fullName>
            </value>
            <value>
                <fullName>Viwandani</fullName>
            </value>
            <value>
                <fullName>Imara Daima</fullName>
            </value>
            <value>
                <fullName>Kware</fullName>
            </value>
            <value>
                <fullName>Gikomba</fullName>
            </value>
            <value>
                <fullName>Makadara</fullName>
            </value>
            <value>
                <fullName>Kamkunji</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Kayaba</fullName>
            </value>
            <value>
                <fullName>Mabroukie</fullName>
            </value>
            <value>
                <fullName>Mathare</fullName>
            </value>
            <value>
                <fullName>Embakasi West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/fields/Area_Name__c.field-meta.xml
<CustomField>
    <fullName>Area_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area Name</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Sub-Areas</relationshipLabel>
    <relationshipName>Sub_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(  Location__r.Sub_Area__r.Area__c  )</formula>
    <label>Area</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <description>Date of first day of business</description>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When new Toilet records are created via Opportunity Product Line Items, this field is automatically populated.</description>
    <label>Sub-Area (del)</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/recordTypes/Sanergy.recordType-meta.xml
<RecordType>
    <fullName>Sanergy</fullName>
    <active>true</active>
    <description>Sanergy Toilet</description>
    <label>Sanergy</label>
</RecordType>

sfSandBoxCode/force-app/main/default/classes/CreateLocation.cls
public class CreateLocation {
    
    //Create Standard Controller
    @TestVisible private ApexPages.StandardController controller;
    
    //Opportunity
    @TestVisible public Opportunity opportunity {get; set;}
    
    //Location
    @TestVisible public Location__c location {get; set;}   
    
    //Toilet
    @TestVisible public List<Toilet> toiletList {get; set;}
    @TestVisible public List<Toilet> toiletsToLaunch {get; set;}     

    //Variables
    @TestVisible public Boolean checkLocationExists {get; set;}
    @TestVisible public Boolean showLocationButton {get; set;}    
    @TestVisible public Boolean showToiletButton {get; set;}
    @TestVisible public Boolean showToiletPendingLaunchButton {get; set;} 
    @TestVisible public Decimal numberOfFLTSToCreate {get; set;}
    //@TestVisible public Boolean selectAllCheckbox {get; set;}
    
    public CreateLocation(ApexPages.StandardController controller){
        this.controller = controller;
        this.opportunity = (Opportunity)controller.getRecord();
        
        this.opportunity =[SELECT Id,Name,Area__c,Sub_Area_Lookup__c,Sub_Area_Lookup__r.Name,Area_Name__c,
                           Area_Name__r.Last_Location_No__c,StageName,Franchise_Type__c,Next_Stage__c,FLTs_Approved__c,
                           Primary_Salesperson__c,Primary_Salesperson__r.Name,Account.Name,Location__c,Location__r.Name,
                           Sub_Area_Lookup__r.Area_Name__r.Area_Abbreviation__c,Location__r.Last_FLT__c,
                           Sub_Area_Lookup__r.Area_Name__r.Last_Location_No__c,No_of_FLTs__c,OwnerId
                           FROM Opportunity
                           WHERE Id =: this.opportunity.Id ];
        
        //Check if Location is provided
        this.checkLocationExists = String.isNotBlank(this.opportunity.Location__c) ? true : false;
        
        System.debug('this.checkLocationExists: - On Page Load: ' + this.checkLocationExists);
        
        //Activate/Deactivate Buttons
        activateDeactivateButton();
        
        //Get all Toilets
        getAllToilets();
        
        //Get toilets pending launch
        getToiletsPendingLaunch();
        
    }
    
    public void activateDeactivateButton(){
        
        //Check if Location is provided
        if(this.checkLocationExists==true){
            //Hide the Create Location button
            this.showLocationButton = false;
            
            //Show the Create Toilet button if Location exists
            this.showToiletButton = true;
        }else{
            
            //Show the Create Location button
            this.showLocationButton = true;
            
            //Hide the Create Toilet button
            this.showToiletButton = false;
        }
        
        // Check if there are any toilets pending launch
        if(toiletsToLaunch != null ){
            showToiletPendingLaunchButton = true;
        }else{
            showToiletPendingLaunchButton = false;
        }        
    }     

    //Create Location
    public PageReference createNewLocation(){
        System.debug('LAST LOCATION NO: = ' + opportunity.Sub_Area_Lookup__r.Area_Name__r.Last_Location_No__c + 1);
        Decimal newLocationNumber = opportunity.Sub_Area_Lookup__r.Area_Name__r.Last_Location_No__c + 1;
        String locationName = opportunity.Sub_Area_Lookup__r.Area_Name__r.Area_Abbreviation__c + '-' + newLocationNumber;
        
        //Create Location
        Location__c location = new Location__c();
        location.Name = locationName;
        location.Sub_Area__c = opportunity.Sub_Area_Lookup__c;
        location.Last_FLT__c = 0;
        
        if(opportunity.Franchise_Type__c == 'Residential'){
            location.Franchise_Type__c = 'Non-Commercial-Plot';            
            location.Waste_User_Ratio__c = 0.3020;
        }else if(opportunity.Franchise_Type__c == 'School'){
            location.Franchise_Type__c = 'Non-Commercial-School';
            location.Waste_User_Ratio__c = 0.2236;
        }else if(opportunity.Franchise_Type__c == 'Institution'){
            location.Franchise_Type__c = 'Non-Commercial-Institution';
            location.Waste_User_Ratio__c = 0.3020;
        }
        
        INSERT location;
        
        //Update Opportunity
        opportunity.Location__c = location.Id;
        opportunity.Sub_Area_Lookup__r.Area_Name__r.Last_Location_No__c = newLocationNumber;
        UPDATE opportunity;
        
        System.debug('opportunity.Location__c: ' + opportunity.Location__c);
        
        //Get Area__c
        Area__c area = [SELECT ID,Name,
                        Last_Location_No__c
                        FROM Area__c
                        WHERE Id=: opportunity.Sub_Area_Lookup__r.Area_Name__c];
        
        //Update Area 
        area.Last_Location_No__c = newLocationNumber;
        UPDATE area;        
        
        System.debug('area.Last_Location_No__c: ' + area.Last_Location_No__c);
        
        //return null;
        return new PageReference('/'+ opportunity.Id);
    }

    // Get all toilets in current location
    public List<Toilet> getAllToilets(){
        System.debug('opportunity.Location__c: '+ opportunity.Location__c);
        
        if(this.checkLocationExists == true){
            
            toiletList = new List<Toilet>();
            
            List<Toilet__c> freshLifeToilets = [SELECT Id,Name,Location__c,Opportunity__c,Operational_Status__c,
                                                Collection_Route__c,Current_Specific_Status__c,Opportunity__r.Name,
                                                Location__r.Name,Opening_Date__c
                                                FROM Toilet__c
                                                WHERE Location__c =: opportunity.Location__c
                                                AND Opportunity__c =: opportunity.Id
                                                ORDER BY Name ASC];     
            
            for(Toilet__c flt : freshLifeToilets){                
                //Add all records to the list
                toiletList.add(new Toilet(flt));
            }//End for(Toilet__c flt : freshLifeToilets)
            
        }//End if(opportunity.Location__c != null)        
        
        
        return toiletList;
    }

    // Get all toilets Pending Launch in current location
    public List<Toilet> getToiletsPendingLaunch(){
        System.debug('opportunity.Location__c: '+ opportunity.Location__c);
        
        if(this.checkLocationExists == true){
            
            toiletsToLaunch = new List<Toilet>();
            
            List<Toilet__c> freshLifeToilets = [SELECT Id,Name,Location__c,Opportunity__c,Operational_Status__c,
                                                Collection_Route__c,Current_Specific_Status__c,Opportunity__r.Name,
                                                Location__r.Name,Opening_Date__c
                                                FROM Toilet__c
                                                WHERE Location__c =: opportunity.Location__c
                                                AND Opportunity__c =: opportunity.Id
                                                AND Operational_Status__c = 'Pending Launch'
                                                ORDER BY Name ASC];     
            
            for(Toilet__c flt2 : freshLifeToilets){                
                //Add all records to the list
                toiletsToLaunch.add(new Toilet(flt2));
            }//End for(Toilet__c flt2 : freshLifeToilets)
            
        }//End if(opportunity.Location__c != null)        
        
        
        return toiletsToLaunch;
    }    
    
    //Create Toilet
    public PageReference createNewToilet(){
        
        Decimal newToiletNumber;
        String toiletName;
        
        //No. of Existing FLTS in this location
        Integer numberOfFLTsInThisLocation = toiletList.size();
        
        System.debug('numberOfFLTsInThisLocation: = ' + numberOfFLTsInThisLocation);
        System.debug(' opportunity.No_of_FLTs__c: = ' +  opportunity.No_of_FLTs__c);
        
        //Maximum No. of FLTS you can create should be less than or equal to No. of FLTS requested
        Decimal maxNumberOfToiletsToCreate = opportunity.No_of_FLTs__c - numberOfFLTsInThisLocation;
        
        System.debug('maxNumberOfToiletsToCreate: = ' + maxNumberOfToiletsToCreate);
        
        if(opportunity.StageName == 'Pending Launch'){
            
            if(numberOfFLTSToCreate <= maxNumberOfToiletsToCreate && this.checkLocationExists == true){
                
                //Get Location
                Location__c loc = [SELECT Id,Name,Last_FLT__c,
                                   Area__c,Area_Name__c
                                   FROM Location__c
                                   WHERE Id =: opportunity.Location__c
                                   LIMIT 1];
                
                //Create no. of toilets specified
                for(Integer i=0; i<numberOfFLTSToCreate; i++){
                    
                    newToiletNumber = loc.Last_FLT__c + 1;
                    toiletName = loc.Name + '.' + newToiletNumber;
                    
                    //Create Toilet
                    Toilet__c toilet = new Toilet__c();
                    toilet.RecordTypeId = '012D0000000K64jIAC'; //Sanergy
                    toilet.Name = toiletName;
                    toilet.Location__c = opportunity.Location__c;
                    toilet.Opportunity__c = opportunity.Id;
                    toilet.Operational_Status__c = 'Pending Launch';
                    toilet.Collection_Route__c = 'CLOSED';
                    toilet.Current_Specific_Status__c = 'Pending Launch';
                    INSERT toilet;
                    
                    //Update Location 
                    loc.Last_FLT__c =  newToiletNumber;
                    UPDATE loc;                 
                }
                
                
            }else{
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR,'You have reached the maximum no. of toilets allowed in this location!');
                ApexPages.addmessage(errorMessage);             
            }// End if(numberOfFLTSToCreate <= maxNumberOfToiletsToCreate && this.checkLocationExists == true)            
            
        }else{
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR,'You can\'t create a toilet if Opportunity Stage is not "Pending Launch"!');
            ApexPages.addmessage(errorMessage);               
        }
        
        return null;        
    }
    
    //Toilet Pending Launch Notification
    public PageReference toiletPendingLaunchNotification(){
        
        //Get FLT Launch RecordType
        RecordType fltLaunchRecordType = [SELECT Id,Name 
                                          FROM RecordType 
                                          WHERE Name ='FLT Launches' 
                                          LIMIT 1];        
        
        for(Toilet t: toiletsToLaunch){
            
            //Check if toilet is selected
            if(t.selected==true){
            
                //Create a task for Sales Associate
                Task task = new Task();
                task.RecordTypeId = fltLaunchRecordType.Id;//FLT Launches
                task.OwnerId = opportunity.OwnerId;//Task assigned to who
                task.Subject = t.toilets.Name + ' is ' + t.toilets.Operational_Status__c;
                task.Goals__c = 'Launch ' + t.toilets.Name;
                task.WhatId = t.toilets.Id;
                task.Related_To_Text__c = t.toilets.Name;
                task.Opportunity__c = opportunity.Id;
                task.ActivityDate = date.today(); //Due Date
                task.Description = t.toilets.Name + ' is ' + t.toilets.Operational_Status__c;//	Comments
                task.Status  = 'Not Started';
                task.Priority = 'Normal';
                task.Task_Source__c = 'Visualforce Page';
                INSERT task;
                
                System.debug('Create Task ' + task); 
            }
            
        }
        
        return null;
        
    }
    
    /*public void selectUnselectAll() {
        System.debug('toiletsToLaunch 1: ' + toiletsToLaunch);
        
        if(toiletsToLaunch != null){
            System.debug('toiletsToLaunch 2: ' + toiletsToLaunch);	
            for(Toilet t: toiletsToLaunch){
                System.debug('toiletsToLaunch 3: ' + toiletsToLaunch);
                System.debug('selectAllCheckbox 3: ' + selectAllCheckbox);
                if(selectAllCheckbox==true){
                    System.debug('selectAllCheckbox 4: ' + selectAllCheckbox);
                    t.selected=true;
                }else{
                    System.debug('selectAllCheckbox 5: ' + selectAllCheckbox);
                    t.selected=false;
                }                             
            }
        }               
    }*/       
    
    // Toilet wrapper class
    public class Toilet{        
    @TestVisible public Toilet__c toilets {get; set;}
    //@TestVisible public Boolean showToiletLaunchButton {get; set;}
    @TestVisible public Boolean selected {get; set;}
        
        //Constructor
        public Toilet(Toilet__c toilet) {
            toilets = toilet;
            selected = false;            	
            
            /*if(toilets.Operational_Status__c == 'Pending Launch'){
                showToiletLaunchButton = true;
            }else{
                showToiletLaunchButton = false;
            }*/
        }
    }    
}