sfSandBoxCode/force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/Fleet_Request__c.object-meta.xml
<CustomObject>
    <label>Fleet Request</label>
    <nameField>
        <displayFormat>Fleet-{0000}</displayFormat>
        <label>Fleet Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Reason_For_Trip__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Trip__c</fullName>
    <label>Reason For Trip</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Fleet Requests</relationshipLabel>
    <relationshipName>Fleet_Requests3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Quote</fullName>
            </value>
            <value>
                <fullName>Pending Team Lead Approval</fullName>
            </value>
            <value>
                <fullName>Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Bookings Confirmed</fullName>
            </value>
            <value>
                <fullName>Request Competed</fullName>
            </value>
            <value>
                <fullName>Request Cancelled</fullName>
                <isActive>false</isActive>
                <label>Request Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/Fleet_Requests__c.object-meta.xml
<CustomObject>
    <description>Trip legs for fleet requests</description>
    <label>Trip Leg</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Trip Leg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trip Legs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <description>Cargo to be carried</description>
    <label>Cargo?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Cargo_Details__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Details__c</fullName>
    <description>Weight, Vol, Dimensions  etc</description>
    <inlineHelpText>Weight, Vol, Dimensions  etc</inlineHelpText>
    <label>Cargo Details</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Driver_Required__c.field-meta.xml
<CustomField>
    <fullName>Driver_Required__c</fullName>
    <inlineHelpText>If would prefer a driver</inlineHelpText>
    <label>Driver Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Would not mind one</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request__c</fullName>
    <label>Fleet Request</label>
    <referenceTo>Fleet_Request__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request_Status__c</fullName>
    <label>Fleet Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Open</fullName>
                <default>true</default>
                <label>Request Open</label>
            </value>
            <value>
                <fullName>Quote in Progress</fullName>
            </value>
            <value>
                <fullName>Pending TL Approval</fullName>
            </value>
            <value>
                <fullName>TL Approved</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Trip Completed</fullName>
            </value>
            <value>
                <fullName>Trip Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Grant_Funding_Availale_Dim_4__c.field-meta.xml
<CustomField>
    <fullName>Grant_Funding_Availale_Dim_4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grant Funding Availale (Dim 4)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Location_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Dim_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location (Dim 2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip Legs</relationshipLabel>
    <relationshipName>Trip_Legs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Other_Destination__c.field-meta.xml
<CustomField>
    <fullName>Other_Destination__c</fullName>
    <label>Other Destination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Nairobi</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Reason_for_Trip__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Trip__c</fullName>
    <label>Reason for Trip</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Requesting_Department</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/Sanergy_Settings_Fleet__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sanergy Settings - Fleet</label>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/fields/company__c.field-meta.xml
<CustomField>
    <fullName>company__c</fullName>
    <label>company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/fields/Dimension_1_id__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1_id__c</fullName>
    <label>Dimension 1 id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/fields/Dimension_2_id__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2_id__c</fullName>
    <label>Dimension 2 id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/fields/Dimension_3_id__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3_id__c</fullName>
    <label>Dimension 3 id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings_Fleet__c/fields/Dimension_4_id__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4_id__c</fullName>
    <label>Dimension 4 id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateFleetRequestForLaunchItems.cls
public class CreateFleetRequestForLaunchItems{
  
    private ApexPages.StandardController standardController;
    public Fleet_Request__c fleet{ get; set;}
    public Fleet_Requests__c leg{ get; set;}
    Map<String,Sanergy_Settings_Fleet__c> settings;
    
    public CreateFleetRequestForLaunchItems(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        //Fleet information
        fleet=new Fleet_Request__c();
        
        //leg information
        leg=new Fleet_Requests__c();
        leg.Cargo_Details__c='Business in a Box Materials';
        
        settings=Sanergy_Settings_Fleet__c.getAll();
    }
    
    public PageReference createRequest() {
        //get opportunity
        Opportunity opp = (Opportunity) standardController.getRecord();
        
        //create fleet header
         fleet.Company__c=settings.get('launch').company__c;
         fleet.Reason_For_Trip__c='Delivery of FLT Launch Materials';
         fleet.Requesting_Department__c=settings.get('launch').Dimension_1_id__c;
         fleet.Status__c='Open';
         
         insert fleet;
         
        
        //create trip lep
        leg.Reason_for_Trip__c=fleet.Reason_For_Trip__c;
        leg.Fleet_Request_Status__c='Request Open';
        leg.Company__c=settings.get('launch').company__c;
        leg.Location_Dim_2__c=settings.get('launch').Dimension_2_id__c;
        leg.Dim_3__c=settings.get('launch').Dimension_3_id__c;
        leg.Grant_Funding_Availale_Dim_4__c=settings.get('launch').Dimension_4_id__c;
        leg.Pickup_Location__c='Mukuru';
        leg.Destination__c='Other';
        leg.Other_Destination__c=opp.Area__c+'-'+opp.Sub_Area_Lookup__r.name+' (Long:'+opp.GPS_Longitude__c+' Lat:'+opp.GPS_Latitude__c+')';
        leg.Cargo__c='Yes';
        leg.Driver_Required__c='Yes';
        leg.Fleet_Request__c=fleet.id;
        leg.Opportunity__c=opp.id;
        
        insert leg;
        
         return new PageReference('/' + fleet.Id);
    }
    
  
}