sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Sanergy_Department__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Department__c</fullName>
    <description>Sanergy Department</description>
    <label>Sanergy Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Sanergy Department Units</relationshipLabel>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_DepartmentUnits.cls
@RestResource(urlMapping='/department_units')
global with sharing class REST_DepartmentUnits {

    @HttpPost
    global static List<DepartmentUnit> getAllDepartmentUnits() {
    
        List<DepartmentUnit> departmentunits = new List<DepartmentUnit>();
        
        List<Sanergy_Department_Unit__c> sanDeptUnits = [SELECT Id, Name, Sanergy_Department__c, Line_Manager__c FROM Sanergy_Department_Unit__c];
        
        if(sanDeptUnits != null && sanDeptUnits.size()> 0){
        
            for(Sanergy_Department_Unit__c sanDeptUnit: sanDeptUnits){
            
                DepartmentUnit unit = new DepartmentUnit();
                
                unit.setGuid(sanDeptUnit.Id);
                unit.setDepartment(sanDeptUnit.Sanergy_Department__c);
                unit.setName(sanDeptUnit.Name);
                unit.setLineManager(sanDeptUnit.Line_Manager__c );
            
                departmentunits.add(unit);
            }
        }
        
        return departmentunits;
    }
    
    global class DepartmentUnit {
        
        String guid;
        String department;
        String name;
        String lineManager;
    
        public String getGuid() {
            return guid;
        }
    
        public void setGuid(String guid) {
            this.guid = guid;
        }
    
        public String getDepartment() {
            return department;
        }
    
        public void setDepartment(String department) {
            this.department = department;
        }
    
        public String getName() {
            return name;
        }
    
        public void setName(String name) {
            this.name = name;
        }
    
        public String getLineManager() {
            return lineManager;
        }
    
        public void setLineManager(String lineManager) {
            this.lineManager = lineManager;
        }
        
    }
}