sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead (Employee A/c)</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sanergy Departments</relationshipLabel>
    <relationshipName>Sanergy_Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_Departments.cls
@RestResource(urlMapping='/departments')
global with sharing class REST_Departments {

    @HttpPost
    global static List<Department> getAllDepartments() {
    
        List<Department> departments = new List<Department>();
        
        List<Sanergy_Department__c> sanDepts = [SELECT Id, Name, RecordTypeId, Team_Lead__c FROM Sanergy_Department__c];
        
        if(sanDepts != null && sanDepts.size()> 0){
            for(Sanergy_Department__c sanDept : sanDepts){
            
                Department department = new Department();
                
                department.setGuid(sanDept.Id);
                department.setDivisionId(sanDept.RecordTypeId);
                department.setName(sanDept.Name);
                department.setTeamLead(sanDept.Team_Lead__c);
            
                departments.add(department);
            }
        }
        
        return departments;
    }
    
    global class Department {
        
        String guid;
        String divisionId;
        String name;
        String teamLead;
    
        public String getGuid() {
            return guid;
        }
    
        public void setGuid(String guid) {
            this.guid = guid;
        }
        
        public String getDivisionId() {
            return divisionId;
        }
    
        public void setDivisionId(String divisionId) {
            this.divisionId = divisionId;
        }
        
        public String getName() {
            return name;
        }
    
        public void setName(String name) {
            this.name = name;
        }
    
        public String getTeamLead() {
            return teamLead;
        }
    
        public void setTeamLead(String teamLead) {
            this.teamLead = teamLead;
        }
                
    }
}