sfSandBoxCode/force-app/main/default/objects/Opportunity_BIB_Item__c/Opportunity_BIB_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity BIB Item</label>
    <nameField>
        <displayFormat>OBIB-{0000}</displayFormat>
        <label>Opportunity BIB Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity BIB Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_BIB_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity BIB Items</relationshipLabel>
    <relationshipName>Opportunity_BIB_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_BIB_Item__c/fields/Opportunity_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Item</label>
    <referenceTo>Opportunity_Item__c</referenceTo>
    <relationshipLabel>Opportunity BIB Items</relationshipLabel>
    <relationshipName>Opportunity_BIB_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Item</label>
    <nameField>
        <label>Opportunity Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Add_Item_Linearly__c.field-meta.xml
<CustomField>
    <fullName>Add_Item_Linearly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Add this item linearly based on no. of approved toilets/upstructure</description>
    <inlineHelpText>Add this item linearly based on no. of approved toilets/upstructure</inlineHelpText>
    <label>Add Item Linearly</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Deactivate_Item__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to deactivate an item</description>
    <inlineHelpText>Check this box to deactivate an item</inlineHelpText>
    <label>Deactivate Item</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Default Quantity</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Type__c</fullName>
    <label>Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <label>Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Structure Package</fullName>
            </value>
            <value>
                <fullName>Paint Package</fullName>
            </value>
            <value>
                <fullName>Toilet Support Package</fullName>
            </value>
            <value>
                <fullName>Location Support Package</fullName>
            </value>
            <value>
                <fullName>Upstructure Package</fullName>
            </value>
            <value>
                <fullName>Pit Conversion Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package - Upstructure</fullName>
            </value>
            <value>
                <fullName>BIB Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Manual_Add__c.field-meta.xml
<CustomField>
    <fullName>Manual_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Items with this value need to be added manually</description>
    <label>Manual Add</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Secondary_Toilet__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Toilet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Toilet</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AddLaunchItemsController.cls
public class AddLaunchItemsController{
    
    private ApexPages.StandardController standardController; 
    
    public AddLaunchItemsController(ApexPages.StandardController standardController){
        this.standardController = standardController;       
    }
    
    public PageReference createItems() {
        
        Opportunity opp = (Opportunity) standardController.getRecord();
        Decimal fltCount = opp.FLTs_Approved__c;
        String franchise = opp.Franchise_Type__c;
        boolean allAddons = opp.Existing_Location__c;
        
        
        if(!opp.BIB_Items_Added__c){
            List<Opportunity_Item__c> oppItems = [SELECT Id, Grouping__c, Default_Quantity__c, 
                                                  Secondary_Toilet__c,Add_Item_Linearly__c
                                                  FROM Opportunity_Item__c 
                                                  WHERE (Grouping__c = 'Location Support Package' AND Franchise_Type__c = :franchise AND Manual_Add__c = false AND Deactivate_Item__c=false AND Description__c != 'Supplementary Item')
                                                  OR (Grouping__c = 'Toilet Support Package' AND Franchise_Type__c = :franchise AND Manual_Add__c = false AND Deactivate_Item__c=false AND Description__c != 'Supplementary Item')
                                                  OR (Grouping__c = 'Location Support Package' AND Franchise_Type__c = null AND Manual_Add__c = false AND Deactivate_Item__c=false AND Description__c != 'Supplementary Item')
                                                  OR (Grouping__c = 'Toilet Support Package' AND Franchise_Type__c = null AND Manual_Add__c = false AND Deactivate_Item__c=false AND Description__c != 'Supplementary Item')];
            
            List<Opportunity_BIB_Item__c> woItemList = new List<Opportunity_BIB_Item__c>();
            
            if(oppITems.size() > 0 && fltCount > 0){
                
                //decimal primaryFlt = 0;
                //decimal secondaryFlt = 0;
                
                //secondaryFlt = fltCount;
                // Check if this is an existing location
                /*if(allAddons){
                secondaryFlt = fltCount;
                } else {
                
                //primaryFlt = 1;
                
                if(fltCount > 1){
                secondaryFlt = fltCount - 1;
                } 
                }*/
                
                for(Opportunity_Item__c item : oppItems){
                    
                    // Check if this is an existing location
                    if(fltCount > 0 && allAddons==true){
                        // Check if Item is Linear
                        if(item.Add_Item_Linearly__c==true){
                            
                            // Create Opportunity_BIB_Item__c
                            Opportunity_BIB_Item__c woItem2 = new Opportunity_BIB_Item__c();
                            woItem2.Opportunity__c = opp.Id;
                            woItem2.Opportunity_Item__c = item.Id;                            
                            woItem2.Quantity__c = item.Default_Quantity__c * fltCount;
                            
                            woItemList.add(woItem2);
                        }
                    }
                    
                    /*if(item.Secondary_Toilet__c){
                    if(secondaryFlt > 0){
                    Opportunity_BIB_Item__c secFlt = new Opportunity_BIB_Item__c(
                    Opportunity__c = opp.Id,
                    Opportunity_Item__c = item.Id,
                    Quantity__c = (item.Default_Quantity__c * secondaryFlt)
                    );   
                    woItemList.add(secFlt);
                    }
                    
                    }*/ //else {
                    //if(primaryFlt > 0){
                    if(fltCount > 0 && allAddons==false){
                        // Create Opportunity_BIB_Item__c
                        Opportunity_BIB_Item__c woItem = new Opportunity_BIB_Item__c();
                        woItem.Opportunity__c = opp.Id;
                        woItem.Opportunity_Item__c = item.Id;                           
                        
                        // Check if Item is Linear
                        if(item.Add_Item_Linearly__c){
                            woItem.Quantity__c = item.Default_Quantity__c * fltCount;
                        }else{
                            woItem.Quantity__c = item.Default_Quantity__c;
                        }
                        
                        woItemList.add(woItem);
                    }
                    //}//End if(item.Secondary_Toilet__c)
                }// End for(Opportunity_Item__c item : oppItems)
            }
            
            if(woItemList.size() > 0){
                INSERT woItemList;
                
                opp.BIB_Items_Added__c = true;
                UPDATE opp;
            }
            
            // Redirect to the opportunity Record
            return new PageReference('/' + opp.Id);
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This process has already been run'));
        }
        return null;
    }
    
}