sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/Asset_Maintenance_Schedule__c.object-meta.xml
<CustomObject>
    <label>Asset Maintenance Schedule</label>
    <nameField>
        <label>Asset Maintenance Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Maintenance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Checkpoint__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint__c</fullName>
    <label>Checkpoint</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before Operation</fullName>
            </value>
            <value>
                <fullName>During Operation</fullName>
            </value>
            <value>
                <fullName>After Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Maintenance Schedules</relationshipLabel>
    <relationshipName>Asset_Maintenance_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Maintenance_Type__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Type__c</fullName>
    <label>Maintenance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BM(Break Down Maintenance)</fullName>
            </value>
            <value>
                <fullName>AM(Autonomous Maintenance)</fullName>
            </value>
            <value>
                <fullName>PM(Preventive Maintenance)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Sanergy_Asset__c.field-meta.xml
<CustomField>
    <fullName>Sanergy_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sanergy Asset</label>
    <referenceTo>Sanergy_Asset__c</referenceTo>
    <relationshipLabel>Asset Maintenance Schedules</relationshipLabel>
    <relationshipName>Asset_Maintenance_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Schedule__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asset_Maintenance_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/Sanergy_Asset__c.object-meta.xml
<CustomObject>
    <description>Sanergy Assets</description>
    <label>Sanergy Asset</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Sanergy Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Current Status of the Asset</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Sanergy Assets</relationshipLabel>
    <relationshipName>Sanergy_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AssetMaintenanceScheduler.cls
global class AssetMaintenanceScheduler implements Schedulable {


    public date myDate = date.today();		
	public Integer day = myDate.day();		
	static Datetime dt = DateTime.newInstance(Date.today(), Time.newInstance(0, 0, 0, 0));
	public String dayOfWeek = dt.format('EEEE');
	
	   
           global void execute(SchedulableContext sc)
        {
            getTasks();
        }

    public void getTasks(){
              	        
        List<Asset_Maintenance_Schedule__c> listAMS = [SELECT ID,Employee__c,OwnerId,Active__c,User__c,User__r.Id,Checkpoint__c,Name,Comments__c,Date__c,
                                                       Frequency__c,Maintenance_Type__c,Owner__c,Sanergy_Asset__c,
                                                       Status__c,Task_Name__c,Tool__c
                                                       FROM Asset_Maintenance_Schedule__c 
                                                       WHERE Active__c = true AND Status__c = 'Confirmed' AND
                                                      Frequency__c = 'Daily' AND User__c != null];

        for(Asset_Maintenance_Schedule__c AMS : listAMS)
            {
                Task task = new Task();
                task.Employee__c = AMS.Employee__c;
                task.OwnerId = AMS.User__r.Id;
                task.Subject = 'Other';
                task.WhatId = AMS.Sanergy_Asset__c;
                task.ActivityDate = Date.today();
                task.Goals__c = AMS.Name;
                task.Description = AMS.Task_Name__c;
                //task.WhoId = AMS.;
                insert task;
            }
        
        if(dayOfWeek == 'Monday'){
            
             List<Asset_Maintenance_Schedule__c> listAMS2 = [SELECT ID,OwnerId,User__r.Id, User__c,Active__c,Checkpoint__c,Name,Comments__c,Date__c,
                                                       Employee__c,Frequency__c,Maintenance_Type__c,Owner__c,Sanergy_Asset__c,
                                                       Status__c,Task_Name__c,Tool__c
                                                       FROM Asset_Maintenance_Schedule__c 
                                                       WHERE Active__c = true AND Status__c = 'Confirmed' AND
                                                      Frequency__c = 'Weekly' AND User__c != null];

        for(Asset_Maintenance_Schedule__c AMS : listAMS2)
            {
                Task task = new Task();
                task.Employee__c = AMS.Employee__c;
                task.OwnerId = AMS.User__r.Id;
                task.Subject = 'Other';
                task.WhatId = AMS.Sanergy_Asset__c;
                task.ActivityDate = Date.today();
                task.Goals__c = AMS.Name;
                task.Description = AMS.Task_Name__c;
                //task.WhoId = AMS.id;
                insert task;
            }
        	}
        if(day == 1 ){
            
             List<Asset_Maintenance_Schedule__c> listAMS3 = [SELECT ID,OwnerId,User__r.Id,User__c,Active__c,Checkpoint__c,Name,Comments__c,Date__c,
                                                       Frequency__c,Maintenance_Type__c,Owner__c,Sanergy_Asset__c,
                                                       Status__c,Task_Name__c,Tool__c
                                                       FROM Asset_Maintenance_Schedule__c 
                                                       WHERE Active__c = true AND Status__c = 'Confirmed' AND
                                                       Frequency__c = 'Monthly' AND User__c != null];

        for(Asset_Maintenance_Schedule__c AMS : listAMS3)
            {
                Task task = new Task();
                task.Employee__c = AMS.Employee__c;
                task.OwnerId = AMS.User__r.Id;
                task.Subject = 'Other';
                task.WhatId = AMS.Sanergy_Asset__c;
                task.ActivityDate = Date.today();
                task.Goals__c = AMS.Name;
                task.Description = AMS.Task_Name__c;
                //task.WhoId = AMS.;
                insert task;
            }
        	}


        }
         
}