sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Group__c/Inventory_Item_Group__c.object-meta.xml
<CustomObject>
    <label>Inventory Commodity Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Commodity Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Requires_Contract__c.field-meta.xml
<CustomField>
    <fullName>Requires_Contract__c</fullName>
    <formula>Inventory_Item__r.Item_Group__r.Requires_Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requires Contract</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Created&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Contract Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/ActivatePurchaseOrderItem.cls
public class ActivatePurchaseOrderItem{

    ApexPages.Standardcontroller controller;
    public Purchase_Order_Item__c poItem {get; set;}
    
    public ActivatePurchaseOrderItem(ApexPages.Standardcontroller controller){
        this.controller = controller;
        this.poItem = (Purchase_Order_Item__c)controller.getRecord();
    }
      /*
    public PageReference activate(){
      List<Purchase_Order_Item__c> poItemList = [SELECT Inventory_Item__r.Item_Group__r.Requires_Contract__c FROM Purchase_Order_Item__c
                                               WHERE id = :this.poItem.id];
                                               
        //if(poItemList.size() > 0 && poItemList.get(0).Inventory_Item__r.Item_Group__r.Requires_Contract__c == true){
           if(poItemList.size() > 0){
            // Create an approval request for the account
            Approval.ProcessSubmitRequest req1 = 
                new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(this.poItem.id);
            
            // Submit on behalf of a specific submitter
            req1.setSubmitterId(UserInfo.getUserId()); 
            
            req1.setProcessDefinitionNameOrId('Purchase_Order_Item_Approval_V3');

            
            // Submit the approval request for the account
            Approval.ProcessResult result = Approval.process(req1);
            
            if(result.isSuccess()){
                 this.poItem.Status__c = 'Pending Contract';
                 update this.poItem;
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Could not submit record for approval'));
                return null;
            }
        }
        
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Could not submit record for approval'));
                return null;
            }
        
        /*else{
            this.poItem.Status__c = 'Active';
            update this.poItem;
        }*/
        
        
        
     /*   return new PageReference('/'+this.poItem.id);
    }*/
}