sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/Rootstock_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>A copy of rootstock items to be used in SF opportunity</description>
    <label>Rootstock Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rootstock Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Master</label>
    <referenceTo>rstk__icitem__c</referenceTo>
    <relationshipLabel>Opportunity Inventory ItemsRootstock</relationshipLabel>
    <relationshipName>Opportunity_Inventory_ItemsRootstock</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/SyncCaseOppInventoryItems.cls
public class SyncCaseOppInventoryItems{

    public static void syncItems(){
       
        
        //create list of new Items to add
        List<Rootstock_Inventory_Item__c> oppItemsInsert=new List<Rootstock_Inventory_Item__c>();
        
        //get new inventory items
        List<rstk__icitem__c> newItems=[SELECT id FROM rstk__icitem__c WHERE ID NOT IN (SELECT Inventory_Item__c FROM Rootstock_Inventory_Item__c)];
        
        for(rstk__icitem__c newItem:newItems){
            Rootstock_Inventory_Item__c rItem=new Rootstock_Inventory_Item__c(
               Inventory_Item__c=newItem.id,
               isActive__c=true
            );
            
            oppItemsInsert.add(rItem);
        }
        
        
        
        //get items which have been deleted
        List<Rootstock_Inventory_Item__c> removedItems=[SELECT Inventory_Item__c, isActive__c FROM Rootstock_Inventory_Item__c
                                                       WHERE Inventory_Item__c NOT IN (SELECT ID FROM rstk__icitem__c)];
        for(Rootstock_Inventory_Item__c rItem:removedItems){
            rItem.isActive__c=false;
        }
        
        insert oppItemsInsert;
        update removedItems;
        
       // EmailSender email=new EmailSender(new String[]{'brian.onyando@saner.gy'}, 'Case opportunity Items Sync','Sync Successfull');
       //email.sendMessage();
            
            
    }
}