sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Currency_Config__c.field-meta.xml
<CustomField>
    <fullName>Currency_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency_Config__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Default_Site__c.field-meta.xml
<CustomField>
    <fullName>Default_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <inlineHelpText>Count of items in stock In all locations</inlineHelpText>
    <label>Inventory Stock</label>
    <summarizedField>Inventory_Item_Location__c.Location_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Company__c.field-meta.xml
<CustomField>
    <fullName>Item_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <description>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</description>
    <inlineHelpText>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</inlineHelpText>
    <label>Item Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stock</fullName>
            </value>
            <value>
                <fullName>Non Stock</fullName>
                <default>true</default>
                <label>Non Stock</label>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/unit_cost__c.field-meta.xml
<CustomField>
    <fullName>unit_cost__c</fullName>
    <label>unit cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/Inventory_Item_BOM__c.object-meta.xml
<CustomObject>
    <label>Inventory Item BOM</label>
    <nameField>
        <displayFormat>BOM-{0000}</displayFormat>
        <label>BOM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Item BOM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/BOM_Item__c.field-meta.xml
<CustomField>
    <fullName>BOM_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BOM Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item BOM (BOM Item)</relationshipLabel>
    <relationshipName>Inventory_BOM_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/Inventory_Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Item BOM</relationshipLabel>
    <relationshipName>Inventory_Item_BOM</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Item__c</fullName>
    <label>Parent Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item BOM</relationshipLabel>
    <relationshipName>Inventory_Item_BOM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/Inventory_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Item Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Inventory Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Item_Company__c.field-meta.xml
<CustomField>
    <fullName>Item_Company__c</fullName>
    <formula>Item__r.Item_Company__r.lookup_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Item_Location__c.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Location_Lot__c.field-meta.xml
<CustomField>
    <fullName>Location_Lot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item_Location_Lot__c.Item_Location__r.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>$Source.Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <description>Indicates what transaction this is i.e. Inventory Adjust, Work Order Issue, Purchase Order Receipt</description>
    <inlineHelpText>INVLOCADJ (Inventory Adjust), WOISS (Work Order Issue), PORCPT (Purchase Order Receipt) , SOSHIP (Sales Order Shipment), LOCMOVE (Location Move), CYCLECNT (Cycle Count), INVLOCADD (Inventory Location Add), INVLOCSCRP (Inventory Location Scrap)</inlineHelpText>
    <label>Transaction ID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVLOCADJ</fullName>
            </value>
            <value>
                <fullName>LOCMOVE</fullName>
            </value>
            <value>
                <fullName>PORCPT</fullName>
            </value>
            <value>
                <fullName>PORCPTRVS</fullName>
            </value>
            <value>
                <fullName>PORVRS</fullName>
            </value>
            <value>
                <fullName>SOSHIP</fullName>
            </value>
            <value>
                <fullName>SORVRS</fullName>
            </value>
            <value>
                <fullName>WOISS</fullName>
            </value>
            <value>
                <fullName>WOISSRVS</fullName>
            </value>
            <value>
                <fullName>WORVRS</fullName>
            </value>
            <value>
                <fullName>CYCLECNT</fullName>
            </value>
            <value>
                <fullName>INVLOCADD</fullName>
            </value>
            <value>
                <fullName>INVLOCSCRP</fullName>
            </value>
            <value>
                <fullName>WORCPT</fullName>
            </value>
            <value>
                <fullName>WORCPTRVS</fullName>
            </value>
            <value>
                <fullName>WOISSEXP</fullName>
            </value>
            <value>
                <fullName>WOISSEXPRVS</fullName>
            </value>
            <value>
                <fullName>WOCLOSE</fullName>
            </value>
            <value>
                <fullName>INVISSUE</fullName>
            </value>
            <value>
                <fullName>UNITPRICECHANGE</fullName>
            </value>
            <value>
                <fullName>SOISS</fullName>
                <isActive>false</isActive>
                <label>SOISS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Transaction_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Quantity__c</fullName>
    <inlineHelpText>The quantity affecting the transaction</inlineHelpText>
    <label>Transaction Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/Item_Location_Lot__c.object-meta.xml
<CustomObject>
    <label>Item Location Lot</label>
    <nameField>
        <label>Inventory Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Location Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Item_Location__c</fullName>
    <label>Inventory Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Item Location Lots (Batches)</relationshipLabel>
    <relationshipName>Item_Location_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/InventoryUnitPriceChange.cls
public class InventoryUnitPriceChange {
    //create standard controller
    private ApexPages.StandardController controller;
    
    private Inventory_Item__c inv{get;set;}
    private Inventory_Item_BOM__c invBom{get;set;}
    private List<WrapperItems>items{get;set;}
    public Decimal newPrice{get;set;}
    public String Comments{get;set;}
    private List<BOMWrapper>listBOMItems{get;set;}
    
    // Constructor
    public InventoryUnitPriceChange(ApexPages.StandardController controller){               
        this.controller = controller;
        inv = (Inventory_Item__c)controller.getRecord();
        

    }
    
    public List<WrapperItems> getItems(){
        items = new List<WrapperItems>();
        
        List<Inventory_Item__c> InventoryItems = [SELECT Id,Name, Item_Type__c,Inventory_Stock__c,Currency_Config__c,Currency_Config__r.Name,
                                                  Item_Company__c,Item_Company__r.lookup_ID__c,Item_Company__r.Name,Default_Site__c,unit_cost__c
                                                  FROM Inventory_Item__c
                                                  WHERE Id =:inv.Id
                                                 ];
        
        for(Inventory_Item__c itm: InventoryItems){
            WrapperItems itms = new WrapperItems(itm);
            items.add(itms);
            
        }
        
        system.debug('Items' + items); 
        getBom();
        return items; 
        
    }
    
    public List<BOMWrapper>getBom(){
        listBOMItems = new List<BOMWrapper>();
        
        List<Inventory_Item_BOM__c> listBOM =[SELECT Parent_Item__c,Parent_Item__r.Name,Parent_Item__r.Inventory_Stock__c,Parent_Item__r.unit_cost__c
                                              FROM Inventory_Item_BOM__c
                                              WHERE BOM_Item__c =: inv.ID
                                             ];
        
        for(Inventory_Item_BOM__c bom:listBOM){
           BOMWrapper bomwrap = new BOMWrapper(bom);
            listBOMItems.add(bomwrap);
        }
        return listBOMItems;
    }
    
    
    public pageReference CreateInventoryTransaction(){
        
        List<Inventory_Item_Location__c> ItemLocations = [Select id,Name,Inventory_Item__c	 
                                                          From Inventory_Item_Location__c 
                                                          WHERE Inventory_Item__c =: inv.id
                                                         ];
        
        List<Item_Location_Lot__c> ItemLoc = [SELECT ID,Name,Item_Location__c 
                                              FROM Item_Location_Lot__c 
                                              WHERE Item_Location__c =: ItemLocations.get(0).Id
                                             ];
        
        //Create  a Transaction when one tries to edit the unit value of an item 
        Inventory_Transaction__c trans = new Inventory_Transaction__c(
            Item__c = inv.id,
            Transaction_ID__c = 'UNITPRICECHANGE',
            Location__c = ItemLocations.get(0).Id,
            Location_Lot__c = ItemLoc.get(0).Id,
            Transaction_Quantity__c = 0.00,
            Item_Unit_Price__c = newPrice,
            Comments__c = Comments,
            Quantity_Impact__c = 'U'
        );
        insert trans;  
        system.debug('Transaction Created' + trans);
        
        return new PageReference('/' + inv.Id); 
    }
    
    public Class WrapperItems{
        public Inventory_Item__c item{get;set;}
        
        public WrapperItems(Inventory_Item__c itm){
            item = itm;
        }
    }
    
    public Class BOMWrapper{
        
        public Inventory_Item_BOM__c BomItem{get;set;}
        
        public BOMWrapper(Inventory_Item_BOM__c Bomitm){
            BomItem = Bomitm;
        }
    }
    
    
}