sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>c2g__codaCompany__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_UoM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Inventory Items (Inventory UoM)</relationshipLabel>
    <relationshipName>Inventory_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Inventory_Item__r.Item_Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_UOM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UOM__c</fullName>
    <formula>Inventory_Item__r.Inventory_UoM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>The description of the Item</description>
    <inlineHelpText>The description of the Item. This is the name that will be displayed on Purchase Order Documents, etc</inlineHelpText>
    <label>Item Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_UoM__c.field-meta.xml
<CustomField>
    <fullName>Purchase_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Purchase Order Items (Purchase UoM)</relationshipLabel>
    <relationshipName>Purchase_Order_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items (Dimension 2)</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/Vendor_Invoice_Items__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Item</label>
    <nameField>
        <displayFormat>VII-{0000000}</displayFormat>
        <label>Vendor Invoice Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Complete_Order__c.field-meta.xml
<CustomField>
    <fullName>Complete_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Complete order even though it is partially received</description>
    <inlineHelpText>Complete order even though it is partially received</inlineHelpText>
    <label>Complete Order</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Item_Group__r.Dimension_1__r.lookup_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 1</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Item_Group__r.Dimension_2__r.lookup_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 2</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Item</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Inventory_UOM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UOM__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Inventory_UoM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Item__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Description</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Item_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Unit_Price__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Unit_Price__c</formula>
    <label>Item Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Purchase_UOM__c.field-meta.xml
<CustomField>
    <fullName>Purchase_UOM__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Purchase_UoM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Pending Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Receive_Batch__c.field-meta.xml
<CustomField>
    <fullName>Receive_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receive Lot</label>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Receive_Location__c.field-meta.xml
<CustomField>
    <fullName>Receive_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receive Location</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Receive_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Receive_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Receive Quantity</label>
    <precision>13</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Requires_Batch__c.field-meta.xml
<CustomField>
    <fullName>Requires_Batch__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Batch_Item__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requires Batch</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Total_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Received__c</fullName>
    <formula>Purchase_Order_Line_Item__r.Quantity_Accepted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/QHSECheckController.cls
public class QHSECheckController {
    
    private ApexPages.StandardController standardController;
    private Vendor_Invoice__c invoice;
    private List<ItemWrapper> items {get; set;}
    
    public QHSECheckController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.invoice = (Vendor_Invoice__c)standardController.getRecord();
    }
    
    public List<ItemWrapper> getItems() {
        
        if(items == null) {
            items= new List<ItemWrapper>();
            
            List<Vendor_Invoice_Items__c> lineItems = [Select Id, Name,Company__c, Item_Description__c, Vendor_Invoice__c,
                                                                    Quantity__c, Total_Received__c, Receive_Location__c,
                                                                    Receive_Batch__c, Inventory_UOM__c, Purchase_UOM__c, 
                                                                    Receive_Quantity__c, Closed__c, Item_Unit_Price__c,
                                                                    Requires_Batch__c, Inventory_Item__c, Complete_Order__c, 
                                                                    Dimension_1__c, Dimension_2__c, Dimension_3__c, Dimension_4__c,
                                                                    Rejected_Quantity__c,
                                                                    Purchase_Order_Line_Item__c,Invoice_Assigned__c,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.UOM_Conversion_Factor__c,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.name,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Default_Receive_Location__c, 
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Default_Receive_Lot__c,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Item_Group__c,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Name,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Item_Type__c,
                                                                    Accepted_Receive_Quantity__c,Status__c,Vendor_Invoice__r.Name,
                                                                    Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Inventory_Item__r.Inventory_UoM__r.Name
                                                                    From Vendor_Invoice_Items__c
                                                                    WHERE Vendor_Invoice__c = :invoice.Id 
                                                                    AND Status__c = 'Pending GIGO Check' 
                                                                    AND Invoice_Assigned__c = true 
                                                                    AND Closed__c = false
                                                                   ];
            
            for(Vendor_Invoice_Items__c lineItem : lineItems){
                ItemWrapper itm = new ItemWrapper(lineItem);
                items.add(itm);
            }
            
        }
        return items;
    }
    
    public PageReference selectAll() {
        if(items != null){
            for(ItemWrapper lg:items){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(items != null){
            for(ItemWrapper lg:items){
                lg.selected=false;                
            }
        }
        return null;
    }
  
    public PageReference receiveToInventory(){
        
        if(items != null && items.size() > 0){

            integer received = 0;
            
            for(ItemWrapper item : items){
                if(item.selected == true){
                    if(item.item.Accepted_Receive_Quantity__c <= item.item.Quantity__c){
                        item.item.Status__c = 'GIGO Checked';
                        update item.item;
                        received +=1;
                    }else {
                       ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You have exceeded the Pending Quantity')); 
                       return null;
                    }
              
                }
            }
            
            if(received > 0 ){
                return new PageReference('/' + invoice.Id); 
            } else {
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No Items were Received')); 
               return null;
            }
        }
         return null;
    }
    
    public class ItemWrapper{
        public Boolean selected {get; set;}
        public Vendor_Invoice_Items__c item {get; set;}
        
        public ItemWrapper(Vendor_Invoice_Items__c itm) {
            item = itm;
        }
    }
}