sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <inlineHelpText>Count of items in stock In all locations</inlineHelpText>
    <label>Inventory Stock</label>
    <summarizedField>Inventory_Item_Location__c.Location_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Company__c.field-meta.xml
<CustomField>
    <fullName>Item_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Minimum_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Quantity__c</fullName>
    <label>Minimum Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/Inventory_Replenishment_Tracker__c.object-meta.xml
<CustomObject>
    <description>Object for tracking replenishment requests for stock items. Tracks using Work Orders and PRs</description>
    <label>Inventory Replenishment Tracker</label>
    <nameField>
        <displayFormat>IRT-{000000}</displayFormat>
        <label>Inventory Replenishment Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Replenishment Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Firm_Date__c.field-meta.xml
<CustomField>
    <fullName>Firm_Date__c</fullName>
    <label>Firm Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Replenishment Trackers</relationshipLabel>
    <relationshipName>Inventory_Replenishment_Trackers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Quantity_Pending__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Pending__c</fullName>
    <label>Quantity Pending</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Inventory Replenishment Trackers</relationshipLabel>
    <relationshipName>Inventory_Replenishment_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Firm_Date__c.field-meta.xml
<CustomField>
    <fullName>Firm_Date__c</fullName>
    <label>Firm Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inventory Item doesn&#39;t have BOM</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Has_BOM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity to Manufacture</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Work in progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
                <isActive>false</isActive>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Picklist Generated</fullName>
                <isActive>false</isActive>
                <label>Picklist Generated</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>received_partially</fullName>
                <isActive>false</isActive>
                <label>Received Partially</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/WorkOrderWorkBenchController.cls
public class WorkOrderWorkBenchController{
    
    public List<ReplenishmentTracker> rList {get; set;}
    public String selectedStatus {get; set;}
    
    public WorkOrderWorkBenchController(){
        
        rList = new List<ReplenishmentTracker>();
        List<Inventory_Replenishment_Tracker__c> replenishmentList = [SELECT Inventory_Item__c, Inventory_Item__r.Item_Company__c, Inventory_Item__r.Inventory_Stock__c,
                                                                     Inventory_Item__r.Minimum_Quantity__c, Quantity_Pending__c, Work_Order__c, 
                                                                     Work_Order__r.Inventory_Item_Quantity__c,
                                                                     RecordType.name,Status__c,CreatedDate,Firm_Date__c,Approved_Date__c
                                                                     FROM  Inventory_Replenishment_Tracker__c
                                                                     WHERE Status__c != 'Cancelled'
                                                                     AND Status__c!= 'Closed'
                                                                     AND RecordType.name = 'Work Order Replenishment'];
                                                                     
        for(Inventory_Replenishment_Tracker__c irt : replenishmentList){
           
            ReplenishmentTracker rt = new ReplenishmentTracker();            
            rt.tracker = irt;
            
            rList.add(rt);
        }
    }
    
    public void refreshList(){
        if(this.selectedStatus != null){
            this.rList = new List<ReplenishmentTracker>();
            
            List<Inventory_Replenishment_Tracker__c> replenishmentList = [SELECT Inventory_Item__c, Inventory_Item__r.Item_Company__c, Inventory_Item__r.Inventory_Stock__c,
                                                                         Inventory_Item__r.Minimum_Quantity__c, Quantity_Pending__c, Work_Order__c,
                                                                         Work_Order__r.Inventory_Item_Quantity__c, 
                                                                         RecordType.name,Status__c,CreatedDate,Firm_Date__c,Approved_Date__c 
                                                                         FROM  Inventory_Replenishment_Tracker__c
                                                                         WHERE Status__c != 'Cancelled'
                                                                         AND Status__c!= 'Closed'
                                                                         AND RecordType.name = 'Work Order Replenishment'
                                                                         AND Status__c = :this.selectedStatus ];
                                                                     
            for(Inventory_Replenishment_Tracker__c irt : replenishmentList){
               
                ReplenishmentTracker rt = new ReplenishmentTracker();            
                rt.tracker = irt;
                
                this.rList.add(rt);
            }        
        }
    }
    
    public PageReference firmRequests(){
        List<ReplenishmentTracker> selected = getSelected();
               
        List<Inventory_Replenishment_Tracker__c> irtList = new List<Inventory_Replenishment_Tracker__c>();
        List<Work_Order__c> woList = new List<Work_Order__c>();
        
        Set<id> woIds =  new Set<id>();
        
        for(ReplenishmentTracker t : selected){
            woIds.add(t.tracker.Work_Order__c);
            t.tracker.Status__c = 'Firmed';
            t.tracker.Firm_Date__c = Date.today();
            
            irtList.add(t.tracker);
        }
                
        Map<id,Work_Order__c> woLinesMap = new Map<id,Work_Order__c>([SELECT Inventory_Item_Quantity__c,Status__c  FROM Work_Order__c WHERE id IN :woIds]);
        
        for(ReplenishmentTracker t : selected){
            woLinesMap.get(t.tracker.Work_Order__c).Inventory_Item_Quantity__c = t.tracker.Work_Order__r.Inventory_Item_Quantity__c;
            woLinesMap.get(t.tracker.Work_Order__c).Status__c = 'Firmed';
            
            woList.add(woLinesMap.get(t.tracker.Work_Order__c));
        }
        
        update irtList;
        update woList;
        
        refreshList();
        
        return Page.WorkOrderWorkbench;
    }
    
    
    public PageReference cancelRequests(){
        List<ReplenishmentTracker> selected = getSelected();
               
        List<Inventory_Replenishment_Tracker__c> irtList = new List<Inventory_Replenishment_Tracker__c>();
        List<Work_Order__c> woList = new List<Work_Order__c>();
        
        Set<id> woIds =  new Set<id>();
        
        for(ReplenishmentTracker t : selected){
            woIds.add(t.tracker.Work_Order__c);
            t.tracker.Status__c = 'Cancelled';
            
            irtList.add(t.tracker);
        }
                
        Map<id,Work_Order__c> woLinesMap = new Map<id,Work_Order__c>([SELECT Inventory_Item_Quantity__c,Status__c  FROM Work_Order__c WHERE id IN :woIds]);
        
        for(ReplenishmentTracker t : selected){
            
            woLinesMap.get(t.tracker.Work_Order__c).Status__c = 'Closed';
            
            woList.add(woLinesMap.get(t.tracker.Work_Order__c));
        }
        
        update irtList;
        update woList;
        
        refreshList();
        
        return Page.WorkOrderWorkbench;
    }
    
    
    private List<ReplenishmentTracker> getSelected(){       
        List<ReplenishmentTracker> selected = new List<ReplenishmentTracker>();
                
        for(ReplenishmentTracker tracker : rList){
            if(tracker.selected == true){
                 selected.add(tracker);
            }
        }
        return selected;
    }
    
    
    public List<SelectOption> getStatuses() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('------','--Select Status---'));
        options.add(new SelectOption('Planned','Planned'));
        options.add(new SelectOption('Firmed','Firmed'));
        return options;
    }
    
    public Class ReplenishmentTracker{
        public Inventory_Replenishment_Tracker__c tracker {get; set;}
        public Boolean selected {get; set;}
    
    }
}