sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Count_of_non_empty_Recipes__c.field-meta.xml
<CustomField>
    <fullName>Count_of_non_empty_Recipes__c</fullName>
    <label>Count of non-empty Recipes</label>
    <summaryFilterItems>
        <field>Inventory_Item_Recipe__c.Count_of_Items__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Item_Recipe__c.Parent_Item__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Currency_Config__c.field-meta.xml
<CustomField>
    <fullName>Currency_Config__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency_Config__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Has_BOM__c.field-meta.xml
<CustomField>
    <fullName>Has_BOM__c</fullName>
    <formula>OR(
  BOM_Count__c  &gt; 0,
  Count_of_non_empty_Recipes__c &gt; 0
 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has BOM</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/unit_cost__c.field-meta.xml
<CustomField>
    <fullName>unit_cost__c</fullName>
    <label>unit cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/Inventory_Item_BOM__c.object-meta.xml
<CustomObject>
    <label>Inventory Item BOM</label>
    <nameField>
        <displayFormat>BOM-{0000}</displayFormat>
        <label>BOM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Item BOM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/BOM_Factor__c.field-meta.xml
<CustomField>
    <fullName>BOM_Factor__c</fullName>
    <label>BOM Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Linear</fullName>
                <default>true</default>
                <label>Linear</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/BOM_Item__c.field-meta.xml
<CustomField>
    <fullName>BOM_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BOM Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item BOM (BOM Item)</relationshipLabel>
    <relationshipName>Inventory_BOM_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Item__c</fullName>
    <label>Parent Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item BOM</relationshipLabel>
    <relationshipName>Inventory_Item_BOM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_BOM__c/fields/Quantity_Per__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Per__c</fullName>
    <label>Quantity Per</label>
    <precision>17</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe__c/Inventory_Item_Recipe__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Recipe</label>
    <nameField>
        <displayFormat>RECIPE-{0000}</displayFormat>
        <label>Recipe Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Item Recipes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe__c/fields/Count_of_Items__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Items__c</fullName>
    <label>Count of Items</label>
    <summaryForeignKey>Inventory_Item_Recipe_Item__c.Inventory_Item_Recipe__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe__c/fields/Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Item__c</fullName>
    <label>Parent Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item Recipes</relationshipLabel>
    <relationshipName>Inventory_Item_Recipes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe_Item__c/Inventory_Item_Recipe_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Recipe Item</label>
    <nameField>
        <displayFormat>RECIPE-ITM-{0000}</displayFormat>
        <label>Inventory Item Recipe Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Item Recipe Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item Recipe Items</relationshipLabel>
    <relationshipName>Inventory_Item_Recipe_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe_Item__c/fields/Inventory_Item_Recipe__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Recipe__c</fullName>
    <label>Inventory Item Recipe</label>
    <referenceTo>Inventory_Item_Recipe__c</referenceTo>
    <relationshipLabel>Inventory Item Recipe Items</relationshipLabel>
    <relationshipName>Inventory_Item_Recipe_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Recipe_Item__c/fields/Quantity_Per__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Per__c</fullName>
    <label>Quantity Per</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Expected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_End_Date__c</fullName>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Firmed__c.field-meta.xml
<CustomField>
    <fullName>Firmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Firmed?</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inventory Item doesn&#39;t have BOM</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Has_BOM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity to Manufacture</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Labor_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labor_Cost__c</fullName>
    <label>Labor Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Planned Material Cost</label>
    <summarizedField>Work_Order_Item__c.Planned_Cost__c</summarizedField>
    <summaryForeignKey>Work_Order_Item__c.Work_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Work in progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
                <isActive>false</isActive>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Picklist Generated</fullName>
                <isActive>false</isActive>
                <label>Picklist Generated</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>received_partially</fullName>
                <isActive>false</isActive>
                <label>Received Partially</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <formula>Actual_Issued_Material_Cost__c  /  Received_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Type__c</fullName>
    <label>Work Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WO-Service</fullName>
            </value>
            <value>
                <fullName>WO-Manufactured</fullName>
            </value>
            <value>
                <fullName>WO-Disassembly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/Work_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Work Order Item</label>
    <nameField>
        <displayFormat>WOI-{0000}</displayFormat>
        <label>Work Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/GenerateWorkOderItems.cls
public class GenerateWorkOderItems {
    
    @TestVisible public ApexPages.StandardController standardController;
    @TestVisible Public Work_Order__c workOder{get;set;}
    @TestVisible public String workOrderId {get;set;}
    @TestVisible public List<String> createdWOIs {get; set;}
    @TestVisible public List<ItemWrapper> items {get; set;}
    @TestVisible public string recipeId {get; set;}
    @TestVisible public List<SelectOption> recipies {get; set;}
    @TestVisible public string  recip {get; set;}
    @TestVisible public string  Recipe {get; set;}
    @TestVisible public Double  quantity {get; set;}
    
    public GenerateWorkOderItems(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.workOder = (Work_Order__c)standardController.getRecord();
        this.workOder =[SELECT Id,Work_Order_Type__c,Inventory_Item__r.Id,Actual_End_Date__c ,Expected_End_Date__c  ,Inventory_Item_Quantity__c,
                        Inventory_Item__c ,Labor_Cost__c  , Material_Cost__c,Firmed__c,Work_Order__c,
                        Site__c, Start_Date__c,Status__c, Inventory_Item__r.Currency_Config__c ,
                        Inventory_Item__r.unit_cost__c, Inventory_Item__r.Has_BOM__c, Inventory_Item__r.Count_of_non_empty_Recipes__c
                        FROM Work_Order__c
                        WHERE Id =: this.workOder.Id ];
        createdWOIs = new List<String>();
        recipies = getRecipies();
        String recipeId;
        this.workOrderId = this.workOder.Id;
        this.quantity = this.workOder.Inventory_Item_Quantity__c;
        items = getItms();
        

        
        
    }
    @TestVisible public List<SelectOption> getRecipies() {
        List<SelectOption> recipeOption = new List<SelectOption>();
        SelectOption defopt = new SelectOption('NA', 'Default BOM');
        recipeOption.add(defopt);
        
        @TestVisible List<Inventory_Item_Recipe__c> recipies = [Select Id, Name, Count_of_Items__c, Parent_Item__c 
                                                                From Inventory_Item_Recipe__c
                                                                WHERE Parent_Item__c =: this.workoder.Inventory_Item__r.Id];
        for(Inventory_Item_Recipe__c recip : recipies){
            SelectOption option = new SelectOption(recip.Id, recip.Name);
            recipeOption.add(option);
        }
        
        return recipeOption;
    }
    
    @TestVisible public void setRecs() {  
        this.recipeId = Recipe;
        changeListWithSelectedRecipe(Recipe);     
    }
    
    public void changeListWithSelectedRecipe(String recipeId){
        
        items = new List<ItemWrapper>();
        
        @TestVisible List<Inventory_Item_Recipe_Item__c> lineItems = [SELECT id,Name , Inventory_Item__c, BOM_Factor__c,Inventory_Item_Recipe__c, Inventory_Item__r.Currency_Config__c ,Quantity_Per__c, Inventory_Item__r.unit_cost__c
                                                                      FROM Inventory_Item_Recipe_Item__c 
                                                                      WHERE  Inventory_Item_Recipe__c =: recipeId
                                                                     ];
        
        if(lineItems.size() == 0){
            
            
            @TestVisible List<Inventory_Item_BOM__c> bomLineItems = [SELECT id,Name , BOM_Item__c,BOM_Factor__c, BOM_Item__r.Currency_Config__c , Parent_Item__c,Quantity_Per__c, BOM_Item__r.unit_cost__c
                                                                     FROM Inventory_Item_BOM__c 
                                                                     WHERE  Parent_Item__c =: this.workOder.Inventory_Item__c
                                                                    ];
            if(bomLineItems.size() == 0){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'The Inventory Item on this Work Order does not have New BOM Items'));
                
            }
            for(Inventory_Item_BOM__c lineItem : bomLineItems){
                ItemWrapper wrapper = new ItemWrapper(lineItem, workOrderId,quantity);
                items.add(wrapper);
            }
        }
        else{
            for(Inventory_Item_Recipe_Item__c lineItem : lineItems){
                
                ItemWrapper wrapper = new ItemWrapper( lineItem, workOrderId,quantity);
                items.add(wrapper);
            } 
            
        }
        
        
    }
    
    @TestVisible public List<ItemWrapper> getItms(){
        List<ItemWrapper> itms=null;
        if(itms == null) {
            itms=new List<ItemWrapper>();
            
            String workOrderId = this.workOder.Id;
            
            List<Inventory_Item_Recipe__c> recipe = [SELECT Id, Name, Count_of_Items__c, Parent_Item__c
                                                     FROM Inventory_Item_Recipe__c
                                                     WHERE Id =: recipeId];
            if(recipe != null && recipe.size()>0 ){
                
                
                
                
                
                @TestVisible List<Inventory_Item_Recipe_Item__c> lineItems = [SELECT id,Name , Inventory_Item__c, BOM_Factor__c,Inventory_Item_Recipe__c, Inventory_Item__r.Currency_Config__c ,Quantity_Per__c, Inventory_Item__r.unit_cost__c
                                                                              FROM Inventory_Item_Recipe_Item__c 
                                                                              WHERE  Inventory_Item_Recipe__c =: recipe.get(0).Id 
                                                                             ];
                
                if(lineItems.size() == 0){
                    
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Recipe does not have Items'));
                    return null;
                }
                
                for(Inventory_Item_Recipe_Item__c lineItem : lineItems){
                    
                    ItemWrapper wrapper = new ItemWrapper( lineItem, workOrderId,quantity);
                    itms.add(wrapper);
                }
                
            }
            else {
                
                
                
                @TestVisible List<Inventory_Item_BOM__c> lineItems = [SELECT id,Name , BOM_Item__c, BOM_Item__r.Currency_Config__c , BOM_Factor__c,Parent_Item__c,Quantity_Per__c, BOM_Item__r.unit_cost__c
                                                                      FROM Inventory_Item_BOM__c 
                                                                      WHERE  Parent_Item__c =: this.workOder.Inventory_Item__c
                                                                     ];
                if(lineItems.size() == 0){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'The Inventory Item on this Work Order does not have BOM Items'));
                    return null;
                }
                for(Inventory_Item_BOM__c lineItem : lineItems){
                    ItemWrapper wrapper = new ItemWrapper(lineItem, workOrderId,this.quantity);
                    itms.add(wrapper);
                }
                
            }
            
        }
        return itms;
    }
    
    
    public List<ItemWrapper> getLines(){
        List<ItemWrapper> linesWrapper=new List<ItemWrapper>();
        
        for(ItemWrapper lw:items){
            
            linesWrapper.add(lw);
            
        }
        return linesWrapper;
    } 
    
    public List<Work_Order_Item__c> getCreatedWOIs(){ 
        List<Work_Order_Item__c> workOderItemList =[SELECT id
                                                    FROM Work_Order_Item__c
                                                    WHERE id IN :this.createdWOIs];
        
        return workOderItemList;
    }        
    
    public PageReference generateWOItems(){
        
        List<ItemWrapper> selectedLines = getLines();
        
        if(selectedLines.size()>0){
            
            List<Work_Order_Item__c> WOIs = new List<Work_Order_Item__c>();
            
            List<id> idString = new List<id>();
            
            //get account from WO items
            for(ItemWrapper lw: selectedLines){
                lw.woItem.Work_Order__c=workOrderId;
                System.debug('WoId=>'+workOrderId);
                WOIs.add(lw.woItem);
            }
            
            insert WOIs;
            
            workOder.Status__c = 'Work in progress'; 
            update workOder;
            
            
            return new PageReference('/' + workOder.Id);
        }
        else{
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'The Inventory Item on this Work Order does not have BOM Items'));
            return null;    
        }
        
        
    }
   
    
    public PageReference FirmWorkOder() {
        
        workOder.Status__c = 'Firmed';
        workOder.Firmed__c = true;
        
        update  workOder;
        
        
        return new PageReference('/' + workOder.Id);
        
    }
    
    
    public class ItemWrapper{
        public Double quantity {get; set;} 
        public String workOrderId {get; set;}             
        public Work_Order_Item__c woItem {get;set;}
        @TestVisible public String rec {get; set;}
        @TestVisible public String Recipe {get; set;}
        @TestVisible public List<SelectOption> recipies {get; set;}
        @TestVisible public string  Line {get; set;}
        @TestVisible public string  recip {get; set;}
        
        
        
        //This is the contructor method
        public ItemWrapper(Inventory_Item_Recipe_Item__c line, String workOrderId, Double quantity) {
            
            
            
            //Work_Order_Item__c wItems = [SELECT Id,Inventory_Item__c FROM Work_Order_Item__c WHERE  Name =: line.Inventory_Item__c];
            
            //if(wItems == null){
            
            woItem = new Work_Order_Item__c();
            
            woItem.Work_Order__c = workOrderId;
            
            woItem.Currency__c = line.Inventory_Item__r.Currency_Config__c;
            woItem.Unit_Cost__c = line.Inventory_Item__r.unit_cost__c;
            woItem.Inventory_Item__c = line.Inventory_Item__c;
            
            if(woItem.Planned_Material_Cost__c == null && line.BOM_Factor__c == 'Linear'){
                woItem.Planned_Material_Cost__c = line.Quantity_Per__c * quantity;
                woItem.BOM_Quantity__c = line.Quantity_Per__c * quantity;
            }else if(woItem.Planned_Material_Cost__c == null && line.BOM_Factor__c != 'Linear'){
                woItem.Planned_Material_Cost__c = line.Quantity_Per__c;
                woItem.BOM_Quantity__c = line.Quantity_Per__c;
            }
            
            /*Work_Order__c wk =[SELECT Id,Status__c FROM Work_Order__c WHERE Id =: workOrderId ];
wk.Status__c = 'Picklist Generated';
*/
            //}
        }
        
        public ItemWrapper(Inventory_Item_BOM__c line, String workOrderId,Double qty) {
            
            //Work_Order_Item__c wItems = [SELECT Id,Inventory_Item__c FROM Work_Order_Item__c WHERE  Inventory_Item__c =: line.BOM_Item__c];
            
            //if(wItems == null){
            System.debug('DEBUG::::'+qty);   
            woItem = new Work_Order_Item__c();
            
            woItem.Work_Order__c = workOrderId;
            woItem.BOM_Quantity__c = line.Quantity_Per__c;
            woItem.Currency__c = line.BOM_Item__r.Currency_Config__c;
            woItem.Unit_Cost__c = line.BOM_Item__r.unit_cost__c;
            woItem.Inventory_Item__c = line.BOM_Item__c;
            
            if(woItem.Planned_Material_Cost__c == null && line.BOM_Factor__c == 'Linear' /*&& quantity != null*/){
                woItem.Planned_Material_Cost__c = line.Quantity_Per__c * qty;
                woItem.BOM_Quantity__c = line.Quantity_Per__c * qty;
            }else if(woItem.Planned_Material_Cost__c == null && line.BOM_Factor__c != 'Linear'){
                woItem.Planned_Material_Cost__c = line.Quantity_Per__c;
                woItem.BOM_Quantity__c = line.Quantity_Per__c;
            }
            
            
            //}
            
            
        }
    }
}