sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/count__c.field-meta.xml
<CustomField>
    <fullName>count__c</fullName>
    <label>count</label>
    <summarizedField>Inventory_Item_Location__c.Count__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <description>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</description>
    <inlineHelpText>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</inlineHelpText>
    <label>Item Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stock</fullName>
            </value>
            <value>
                <fullName>Non Stock</fullName>
                <default>true</default>
                <label>Non Stock</label>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/Inventory_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Item Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Batch__c.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Batch__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/re_order_quantity__c.field-meta.xml
<CustomField>
    <fullName>re_order_quantity__c</fullName>
    <label>re-order quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <description>Inventory Locations (Warehouse Locations)</description>
    <label>Inventory Site</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/Item_Location_Lot__c.object-meta.xml
<CustomObject>
    <label>Item Location Lot</label>
    <nameField>
        <label>Inventory Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Location Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Item_Location__c</fullName>
    <label>Inventory Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Item Location Lots (Batches)</relationshipLabel>
    <relationshipName>Item_Location_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Lot_Name__c.field-meta.xml
<CustomField>
    <fullName>Lot_Name__c</fullName>
    <label>Lot Name</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>17</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/OpportunityShipControllerTest.cls
@isTest(SeeAllData=true)

private class OpportunityShipControllerTest {
    
    static testMethod void TestOpportunityShipController() {
        //create two accounts
        Account ac=new Account(Name='Acc',CurrencyIsoCode='KES' );                        
        insert ac;
        //create Contact
        Contact con=new Contact(lastname='Onyando',Sex__c='Male');
        insert con;
        //get application management recordtype id
        List<RecordType> rt=[SELECT id FROM RecordType WHERE Name='Agricultural Product Sales - Closing'];
        
        List<Opportunity> opList=new List<Opportunity>();
        //Create two Opportunities
        
        Opportunity opp =new Opportunity(
            RecordTypeId=rt.get(0).id,
            Name='x',
            AccountId=ac.ID,
            StageName='Sale Open',
            CloseDate=Date.today(),
            Primary_Salesperson__c=con.ID
        );
        insert opp;
        
        Product2 product2 = [SELECT Id, Name, Use_Inventory__c, Inventory_Product__c,rstk__Product_rs_addprod__c
                             FROM Product2
                             WHERE Use_Inventory__c = true 
                             AND Inventory_Product__c != null 
                             LIMIT 1
                            ];
        
        Inventory_item__c item = [Select Id, Name
                                  FROM Inventory_item__c
                                  WHERE Id = :product2.Inventory_Product__c                                  
                                 ];
        item.Item_Type__c = 'Stock';
        update item;
        
        Inventory_Location__c invloc = new Inventory_Location__c(
            Name = 'Kilimani'
        );
        insert invloc;
        
        Inventory_Item_Location__c loc = new Inventory_Item_Location__c();
        loc.Name = invloc.Name;
        loc.Location__c = invloc.Id;
        loc.Location_Name__c = '18181';
        //Batch__c = batch.Id,
        loc.Inventory_Item__c = item.Id;
        //re_order_quantity__c = 5,
        //Count__c = 99
        insert loc;
        
        Item_Location_Lot__c lot2 = new Item_Location_Lot__c();
        lot2.Lot_Name__c = 'Lot 19';
        lot2.Quantity__c = 909;
        lot2.Item_Location__c = loc.Id;
        
        List<PricebookEntry> pbeList = [
            SELECT Id, Product2Id FROM PricebookEntry
            WHERE Product2Id = :product2.Id
            AND Pricebook2.isStandard=true
        ];
        
        Map<Id,Id> prodToPbe = new Map<Id,Id>();
        
        for (PricebookEntry pbEntry: pbeList) {
            prodToPbe.put(pbEntry.Product2Id, pbEntry.Id);
        }
        
        OpportunityLineItem lineItem = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId  = prodToPbe.get(product2.Id),
            Quantity = 5,
            Inventory_Item_Location__c = loc.Id,
            TotalPrice = 5555
        );
         insert lineItem;
        
        User u = [Select Id,Alias FROM User WHERE Alias = 'dev'];

        System.runAs(u) {
            
            PageReference pageRef = Page.OpportunityShip;
            
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(opp);
            OpportunityShipController controller = new OpportunityShipController(sc);
            
            controller.selectAll();
            controller.getProducts();
            controller.getSites();
            
            for(OpportunityShipController.ProductWrapper  thisListItem :controller.products) {
                
                thisListItem.site=invloc.Id;
                thisListItem.location= loc.Id;
                thisListItem.setLots();
                thisListItem.setLots();
                thisListItem.selectLot();
                thisListItem.setLocations();
                thisListItem.lot = lot2.Id;
                thisListItem.selectedLot = lot2;
                thisListItem.product.Quantity_Shipped__c = 1;
                thisListItem.shipQuantity = thisListItem.product.Quantity_Shipped__c;
            }
            	
            controller.selectAll();
            controller.getProducts();
            controller.getSites();
            controller.shipFromInventory();
            //controller.unselectAll();
            
            for(OpportunityShipController.ProductWrapper  thisListItem :controller.products) {
                thisListItem.site=null;
                thisListItem.location= null;
                thisListItem.lot = null;
                thisListItem.selectedLot = null;
                
                thisListItem.setLots();
                thisListItem.setLots();
                thisListItem.selectLot();
                thisListItem.setLocations();
            }
            
            controller.shipFromInventory();
            controller.unselectAll();
        }
    }
}