sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Commodity_Code_Type__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Code_Type__c</fullName>
    <formula>Item_Group__r.Commodity_Code__c</formula>
    <label>Commodity Code Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <inlineHelpText>Count of items in stock In all locations</inlineHelpText>
    <label>Inventory Stock</label>
    <summarizedField>Inventory_Item_Location__c.Location_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_UoM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Inventory Items (Inventory UoM)</relationshipLabel>
    <relationshipName>Inventory_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <description>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</description>
    <inlineHelpText>Defines how the item is accounted for. Stock items hit inventory journals indirect items are expensed</inlineHelpText>
    <label>Item Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stock</fullName>
            </value>
            <value>
                <fullName>Non Stock</fullName>
                <default>true</default>
                <label>Non Stock</label>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/Inventory_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Item Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Max_Location_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Location_Quantity__c</fullName>
    <label>Max Location Quantity</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/Inventory_Location_Move__c.object-meta.xml
<CustomObject>
    <label>Inventory Location Move</label>
    <nameField>
        <displayFormat>IMV-{0000}</displayFormat>
        <label>Inventory Location Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Moves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Location Moves</relationshipLabel>
    <relationshipName>Inventory_Location_Moves</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Location_From__c.field-meta.xml
<CustomField>
    <fullName>Location_From__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Location to move inventory from</description>
    <label>Location From</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Item_Location__c.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Location Moves</relationshipLabel>
    <relationshipName>Inventory_Location_Moves</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Location_Lot_From__c.field-meta.xml
<CustomField>
    <fullName>Location_Lot_From__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>From Location Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item_Location_Lot__c.Item_Location__c</field>
            <operation>equals</operation>
            <valueField>$Source.Location_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Inventory Location Moves</relationshipLabel>
    <relationshipName>Inventory_Location_Moves</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Location_Lot_To__c.field-meta.xml
<CustomField>
    <fullName>Location_Lot_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Location Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item_Location_Lot__c.Item_Location__c</field>
            <operation>equals</operation>
            <valueField>$Source.Location_To__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Inventory Location Moves (Location Lot To)</relationshipLabel>
    <relationshipName>Inventory_Location_Moves1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Location_To__c.field-meta.xml
<CustomField>
    <fullName>Location_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Location to move inventory to</description>
    <label>Location To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Item_Location__c.Inventory_Item__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Location_From__c</field>
            <operation>notEqual</operation>
            <valueField>Inventory_Item_Location__c.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Location Moves (Location To)</relationshipLabel>
    <relationshipName>Inventory_Location_Moves1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Location_Move__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in the transaction</description>
    <label>Quantity</label>
    <precision>13</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/Item_Location_Lot__c.object-meta.xml
<CustomObject>
    <label>Item Location Lot</label>
    <nameField>
        <label>Inventory Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Location Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Item_Location__c</fullName>
    <label>Inventory Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Item Location Lots (Batches)</relationshipLabel>
    <relationshipName>Item_Location_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Lot_Name__c.field-meta.xml
<CustomField>
    <fullName>Lot_Name__c</fullName>
    <label>Lot Name</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>17</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Gross_Value__c.field-meta.xml
<CustomField>
    <fullName>Gross_Value__c</fullName>
    <formula>Unit_Net_Price__c  +  Net_VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Value</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_UOM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UOM__c</fullName>
    <formula>Inventory_Item__r.Inventory_UoM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <label>Unit Item Cost</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Unit_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Net_Price__c</fullName>
    <formula>IF(Vatable__c = true,
   IF(VAT_Inclusive__c = true,
         Item_Cost__c  /( (VALUE(TEXT(VAT_Percentage__c))+100)/100 ) ,
         Item_Cost__c 
      ),
     Item_Cost__c   
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Net Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateTransactionsTriggerTest.cls
@isTest(SeeAllData=true)

public class CreateTransactionsTriggerTest {
    
    static testMethod void moveItemTest(){
        
        List<User> u = [Select Id,Alias FROM User WHERE Alias = 'dev'];
        
        System.runAs(u.get(0)) {
            List<Inventory_item__c> item = [Select Id, Name, Item_Group__c,Inventory_Stock__c,Inventory_UoM__c
                                  FROM Inventory_item__c WHERE Inventory_Stock__c >= 3 
                                  AND Commodity_Code_Type__c = 'Manufactured'
                                 ];
            
            if(item.size() > 0){
                
                item.get(0).Item_Type__c = 'Stock';
                update item;
                
                Inventory_Location__c loc1 = new Inventory_Location__c(
                    Name = 'Mukuru 2345'
                );
                insert loc1;
                
                Inventory_Location__c loc2 = new Inventory_Location__c(
                    Name = 'Mukuru 1234'
                );
                insert loc2;
                
                Inventory_Item_Location__c itmloc1 = new Inventory_Item_Location__c(
                    Name = loc1.Name,
                    Location_Name__c = '008980',
                    Location__c = loc1.Id,
                    Inventory_Item__c = item.get(0).Id,
                    Max_Location_Quantity__c = 100
                );
                
                insert itmloc1;
            
                Inventory_Item_Location__c itmloc2 = new Inventory_Item_Location__c(
                    Name = loc2.Name,
                    Location_Name__c = '00809',
                    Location__c = loc2.Id,
                    Inventory_Item__c = item.get(0).Id,
                    Max_Location_Quantity__c = 100
                );
            
            	insert itmloc2;
            
            	Item_Location_Lot__c lot1 = new Item_Location_Lot__c();
                lot1.Lot_Name__c = 'Lot 18';
                lot1.Quantity__c = 90909;
                lot1.Item_Location__c = itmloc1.Id;
            
                insert lot1;
                
                lot1.Quantity__c = 9090;
                
                update lot1;
                
                Item_Location_Lot__c lot2 = new Item_Location_Lot__c();
                lot2.Lot_Name__c = 'Lot 19';
                lot2.Quantity__c = 909;
                lot2.Item_Location__c = itmloc2.Id;
            
                insert lot2;
                        
                Inventory_Location_Move__c locmv = new Inventory_Location_Move__c();
                locmv.Inventory_Item__c = item.get(0).Id;
                locmv.Location_From__c = itmloc1.Id;
                locmv.Location_To__c = itmloc2.Id;
                locmv.Quantity__c = 3;
                locmv.Location_Lot_From__c = lot1.Id;
                locmv.Location_Lot_To__c = lot2.Id;
        
                insert locmv;
                
                
                
                List<Inventory_item__c> items = [Select Id, Name, Inventory_UoM__c, Item_Group__c,Inventory_Stock__c
                                                 FROM Inventory_item__c WHERE Inventory_Stock__c >= 3 
                                                 AND Commodity_Code_Type__c != 'Manufactured' LIMIT 1
                                                 ];
                
                if(items.size() > 0){
                    
                    items.get(0).Item_Type__c = 'Stock';
                	update items;
                    
                    List<Purchase_Order_Item__c> poI = [SELECT Id, Unit_Net_Price__c,Name, Inventory_Item__c,Gross_Value__c,Item_Cost__c,
                                                        Item_Description__c,Net_VAT__c,Primary_Vendor__c,Purchase_UoM__c,Vendor__c,Vatable__c,
                                                        VAT_Percentage__c,VAT_Inclusive__c, Currency__c
                                                        FROM Purchase_Order_Item__c WHERE Primary_Vendor__c = true
                                                        AND Purchase_UoM__c =: items.get(0).Inventory_UoM__c
                                                        LIMIT 1
                                                       ];
                    
                    if(poI.size() > 0){
                        poI.get(0).Inventory_Item__c = items.get(0).Id;
                        poI.get(0).UOM_Conversion_Factor__c = 1;
                       // update poI;
                        
                        Inventory_Location__c loc = new Inventory_Location__c(
                            Name = 'Mukuru 2345'
                        );
                        insert loc;
            
                        Inventory_Location__c lo = new Inventory_Location__c(
                            Name = 'Mukuru 1234'
                        );
                        insert lo;
            
                        Inventory_Item_Location__c itmloc = new Inventory_Item_Location__c(
                            Name = loc.Name,
                            Location_Name__c = '008980',
                            Location__c = loc.Id,
                            Inventory_Item__c = items.get(0).Id,
                            Max_Location_Quantity__c = 100
                        );
                        
                        insert itmloc;
                       
                    	Item_Location_Lot__c lot = new Item_Location_Lot__c();
                        lot.Lot_Name__c = 'Lot 18';
                        lot.Quantity__c = 90909;
                        lot.Item_Location__c = itmloc.Id;
            
            			insert lot;
                    }
                }
            }
        }
    }
}