sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>c2g__codaCompany__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Default_Site__c.field-meta.xml
<CustomField>
    <fullName>Default_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Has_BOM__c.field-meta.xml
<CustomField>
    <fullName>Has_BOM__c</fullName>
    <formula>OR(
  BOM_Count__c  &gt; 0,
  Count_of_non_empty_Recipes__c &gt; 0
 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has BOM</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Company__c.field-meta.xml
<CustomField>
    <fullName>Item_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Source__c.field-meta.xml
<CustomField>
    <fullName>Item_Source__c</fullName>
    <label>Item Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Policy_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Policy_Quantity__c</fullName>
    <label>Policy Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/Inventory_Replenishment_Tracker__c.object-meta.xml
<CustomObject>
    <description>Object for tracking replenishment requests for stock items. Tracks using Work Orders and PRs</description>
    <label>Inventory Replenishment Tracker</label>
    <nameField>
        <displayFormat>IRT-{000000}</displayFormat>
        <label>Inventory Replenishment Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Replenishment Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Replenishment Trackers</relationshipLabel>
    <relationshipName>Inventory_Replenishment_Trackers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Quantity_Pending__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Pending__c</fullName>
    <label>Quantity Pending</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Replenishment_Tracker__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Inventory Replenishment Trackers</relationshipLabel>
    <relationshipName>Inventory_Replenishment_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inventory Item doesn&#39;t have BOM</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Has_BOM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity to Manufacture</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Work in progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
                <isActive>false</isActive>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Picklist Generated</fullName>
                <isActive>false</isActive>
                <label>Picklist Generated</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>received_partially</fullName>
                <isActive>false</isActive>
                <label>Received Partially</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Type__c</fullName>
    <label>Work Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WO-Service</fullName>
            </value>
            <value>
                <fullName>WO-Manufactured</fullName>
            </value>
            <value>
                <fullName>WO-Disassembly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/WorkOrderWorkBenchControllerTest.cls
@isTest(seeAllData=true)
public class WorkOrderWorkBenchControllerTest{
    
    static testMethod void WorkOrderWorkBenchControllerTest(){
        List<Inventory_item__c> items = [Select Id,Policy_Quantity__c,Default_Site__c,Item_Company__c
                                         FROM Inventory_item__c
                                         WHERE Item_Group__c != null 
                                         AND Has_BOM__c = true 
                                         AND Item_Source__c = 'Manufactured'
                                         AND Policy_Quantity__c!=null
                                         LIMIT 1
                                        ];
        
        if(items.size() > 0){
            List<RecordType> manufactureRecordType = [SELECT id FROM RecordType
                                                      WHERE Name = 'Work Order Replenishment'
                                                      AND SObjectType = 'Inventory_Replenishment_Tracker__c'];
            
            Work_Order__c wo = new Work_Order__c(
                Inventory_Item__c = items.get(0).id,
                Inventory_Item_Quantity__c = items.get(0).Policy_Quantity__c,
                Site__c = items.get(0).Default_Site__c,
                Company__c = items.get(0).Item_Company__c,
                Work_Order_Type__c = 'WO-Manufactured',
                Status__c = 'Planned'
            );
            insert wo;
            
            Inventory_Replenishment_Tracker__c tracker = new Inventory_Replenishment_Tracker__c(
                recordTypeId = manufactureRecordType.get(0).id,
                Inventory_Item__c = wo.Inventory_Item__c,
                Work_Order__c = wo.id,
                Quantity_Pending__c = wo.Inventory_Item_Quantity__c 
            );
            
            insert tracker;
            
            //Create controller
            WorkOrderWorkBenchController woWorkBnchCtrl = new WorkOrderWorkBenchController();
            
            woWorkBnchCtrl.getStatuses();
            woWorkBnchCtrl.selectedStatus = 'Planned';
            woWorkBnchCtrl.refreshList();
            woWorkBnchCtrl.rList.get(0).selected = true;
            woWorkBnchCtrl.firmRequests();
            
            woWorkBnchCtrl.selectedStatus = 'Firmed';
            woWorkBnchCtrl.refreshList();
            woWorkBnchCtrl.rList.get(0).selected = true;
            woWorkBnchCtrl.cancelRequests();    
        }
    }
}