sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Has_BOM__c.field-meta.xml
<CustomField>
    <fullName>Has_BOM__c</fullName>
    <formula>OR(
  BOM_Count__c  &gt; 0,
  Count_of_non_empty_Recipes__c &gt; 0
 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has BOM</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <inlineHelpText>Count of items in stock In all locations</inlineHelpText>
    <label>Inventory Stock</label>
    <summarizedField>Inventory_Item_Location__c.Location_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Company__c.field-meta.xml
<CustomField>
    <fullName>Item_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Source__c.field-meta.xml
<CustomField>
    <fullName>Item_Source__c</fullName>
    <label>Item Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Minimum_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Quantity__c</fullName>
    <label>Minimum Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Pending_Replenishment_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Pending_Replenishment_Quantity__c</fullName>
    <label>Pending Replenishment Quantity</label>
    <summarizedField>Inventory_Replenishment_Tracker__c.Quantity_Pending__c</summarizedField>
    <summaryFilterItems>
        <field>Inventory_Replenishment_Tracker__c.Status__c</field>
        <operation>equals</operation>
        <value>Planned, Firmed, Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Replenishment_Tracker__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Planning_Policy__c.field-meta.xml
<CustomField>
    <fullName>Planning_Policy__c</fullName>
    <label>Planning Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reorder Point</fullName>
            </value>
            <value>
                <fullName>No MRP Planning</fullName>
            </value>
            <value>
                <fullName>Lot for Lot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Policy_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Policy_Quantity__c</fullName>
    <label>Policy Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Reorder_Point__c.field-meta.xml
<CustomField>
    <fullName>Reorder_Point__c</fullName>
    <label>Reorder Point</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Requires_Replenishment__c.field-meta.xml
<CustomField>
    <fullName>Requires_Replenishment__c</fullName>
    <formula>AND(
   (Inventory_Stock__c + Pending_Replenishment_Quantity__c) &lt;  Reorder_Point__c ,
    ISPICKVAL(Planning_Policy__c, &quot;Reorder Point&quot;),
    OR(
       ISPICKVAL( Item_Source__c, &quot;Purchased&quot;),
       ISPICKVAL( Item_Source__c, &quot;Manufactured&quot;)
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requires Replenishment</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/InventoryItemsReplenisherTest.cls
@isTest(seeAllData = true)
public class InventoryItemsReplenisherTest{
    
    public static TestMethod void InventoryItemsReplenisherTest(){
    
         List<Inventory_item__c> itemsBelowThreshold = [SELECT Planning_Policy__c
                                                        FROM Inventory_Item__c 
                                                        WHERE Requires_Replenishment__c = true];
                                                        
        for(Inventory_item__c items : itemsBelowThreshold ){
            items.Planning_Policy__c = 'No MRP Planning';
        }
        
        if(itemsBelowThreshold.size() > 0){
            update itemsBelowThreshold;
        }
                                                        
    
         List<Inventory_item__c> itemsToManufactore = [Select Id,Policy_Quantity__c,Reorder_Point__c,Minimum_Quantity__c,Item_Company__c,
                                                       Planning_Policy__c,Inventory_Stock__c,Pending_Replenishment_Quantity__c
                                                       FROM Inventory_item__c
                                                       WHERE Item_Group__c != null 
                                                       AND Has_BOM__c = true 
                                                       AND Item_Source__c = 'Manufactured'];
           
                                       
          if(itemsToManufactore.size() > 0){
              Inventory_item__c item = itemsToManufactore.get(0);
              
              item.Reorder_Point__c= item.Inventory_Stock__c + item.Pending_Replenishment_Quantity__c + 10;
              item.Policy_Quantity__c = 150;
              item.Planning_Policy__c = 'Reorder Point';
              
              update item;
          }
          
          List<Inventory_item__c> itemsToProcure = [Select Id,Policy_Quantity__c,Minimum_Quantity__c,Item_Company__c,
                                                    Planning_Policy__c,Inventory_Stock__c,Pending_Replenishment_Quantity__c
                                                    FROM Inventory_item__c
                                                    WHERE Item_Group__c != null  
                                                    AND Item_Source__c = 'Purchased'
                                                    AND ID IN (SELECT inventory_item__c FROM Purchase_Order_Item__c WHERE Vendor_Type__c = 'Primary')
                                                    LIMIT 1];
                                         
          if(itemsToProcure.size() > 0){
              Inventory_item__c item = itemsToProcure.get(0);
              
              item.Reorder_Point__c= item.Inventory_Stock__c + item.Pending_Replenishment_Quantity__c + 10;
              item.Policy_Quantity__c = 150;
              item.Planning_Policy__c = 'Reorder Point';
              
              update item;
          }
          
          //Replenish Inventory
          InventoryItemsReplenisherScheduler sc = new InventoryItemsReplenisherScheduler ();
         
         //Schedule
          InventoryItemsReplenisherScheduler.scheduleThis(null);
          sc.execute(null);
    }
}