sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/Case_Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Case Opportunity Item</label>
    <nameField>
        <displayFormat>COPP-{0000}</displayFormat>
        <label>Case Opportunity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Opportunity Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Rstk_Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Rstk_Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rstk Inventory Item</label>
    <referenceTo>Rootstock_Inventory_Item__c</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Item</label>
    <nameField>
        <label>Opportunity Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Deactivate_Item__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to deactivate an item</description>
    <inlineHelpText>Check this box to deactivate an item</inlineHelpText>
    <label>Deactivate Item</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Default Quantity</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <label>Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Structure Package</fullName>
            </value>
            <value>
                <fullName>Paint Package</fullName>
            </value>
            <value>
                <fullName>Toilet Support Package</fullName>
            </value>
            <value>
                <fullName>Location Support Package</fullName>
            </value>
            <value>
                <fullName>Upstructure Package</fullName>
            </value>
            <value>
                <fullName>Pit Conversion Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package</fullName>
            </value>
            <value>
                <fullName>Basic FLT Package - Upstructure</fullName>
            </value>
            <value>
                <fullName>BIB Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Hybrid__c.field-meta.xml
<CustomField>
    <fullName>Hybrid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Items used in hybrid toilet</description>
    <label>Hybrid</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Opportunity Items</relationshipLabel>
    <relationshipName>Opportunity_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Manual_Add__c.field-meta.xml
<CustomField>
    <fullName>Manual_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Items with this value need to be added manually</description>
    <label>Manual Add</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Item__c/fields/Structure_Version__c.field-meta.xml
<CustomField>
    <fullName>Structure_Version__c</fullName>
    <label>Structure Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V2</fullName>
            </value>
            <value>
                <fullName>V3</fullName>
            </value>
            <value>
                <fullName>V2-V3 Hybrid</fullName>
            </value>
            <value>
                <fullName>Pit Conversion</fullName>
            </value>
            <value>
                <fullName>Basic FLT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/Rootstock_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>A copy of rootstock items to be used in SF opportunity</description>
    <label>Rootstock Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rootstock Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Rootstock Inventory Items</relationshipLabel>
    <relationshipName>Rootstock_Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AddCaseEngineeringItemsController.cls
public class AddCaseEngineeringItemsController {
    
    private ApexPages.StandardController standardController;
    public Integer noOfFLTs {get; set;}
    public Integer upstructures {get; set;}
    
    public List<SelectOption> fltVersions{
        get {
            List<String> versions = new List<String> { 'V2', 'V3', 'V2-V3 Hybrid'};
            fltVersions = new List<SelectOption>();
            for(String temp : versions){
                fltVersions.add(new SelectOption(temp, temp));
            }
            return fltVersions;
        }
        set;
    }
    
    public String fltVersion {get; set;}
        
    public AddCaseEngineeringItemsController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        //default number of toilets to 1
        this.noOfFLTs=1;
        this.upstructures=0;
    }

    public PageReference createItems() {
        
        Opportunity opp = (Opportunity) standardController.getRecord();
        Integer fltCount = this.noOfFLTs;
        Integer upstructure = this.upstructures;
        
        if(!opp.Structure_Items_Added__c){
            
            List<Opportunity_Item__c> oppItems = new List<Opportunity_Item__c>();
            
            if(fltVersion.equals('V2-V3 Hybrid')){
                oppItems = [SELECT Id, Grouping__c, InventoryItem__c, Default_Quantity__c
                            FROM Opportunity_Item__c 
                            WHERE (Grouping__c = 'Structure Package' AND Hybrid__c = true AND Manual_Add__c = false AND Deactivate_Item__c=false)
                               OR (Grouping__c = 'Paint Package' AND Hybrid__c = true AND Manual_Add__c = false AND Deactivate_Item__c=false)
                               OR (Grouping__c = 'Substructure Package' AND Hybrid__c = true AND Manual_Add__c = false AND Deactivate_Item__c=false)
                               OR (Grouping__c = 'Upstructure Package' AND Hybrid__c = true AND Manual_Add__c = false AND Deactivate_Item__c=false)];
                               
                              
            }else{
                oppItems = [SELECT Id, Grouping__c, InventoryItem__c, Default_Quantity__c
                            FROM Opportunity_Item__c 
                            WHERE (Structure_Version__c = :fltVersion AND Grouping__c = 'Structure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = :fltVersion AND Grouping__c = 'Paint Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = :fltVersion AND Grouping__c = 'Substructure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = :fltVersion AND Grouping__c = 'Upstructure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = null AND Grouping__c = 'Structure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = null AND Grouping__c = 'Paint Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = null AND Grouping__c = 'Substructure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)
                                OR  (Structure_Version__c = null AND Grouping__c = 'Upstructure Package' AND Manual_Add__c = false AND Deactivate_Item__c=false)];
            }

            
                                                         
            List<Case_Opportunity_Item__c> caseItems = new List<Case_Opportunity_Item__c>();
            
            if(oppITems.size() > 0 && fltCount > 0){
                
                Map<id,Opportunity_Item__c> idMap=new Map<id,Opportunity_Item__c>();
                List<id> idList=new List<String>();
                
                for(Opportunity_Item__c item : oppItems){
                    idMap.put(item.InventoryItem__c, item);
                    idList.add(item.InventoryItem__c);
                }
                
                List<Rootstock_Inventory_Item__c> rstkItems=[SELECT ID,InventoryItem__c FROM Rootstock_Inventory_Item__c 
                                                         WHERE InventoryItem__c IN :idList];
                
                for(Rootstock_Inventory_Item__c item : rstkItems){
                
                    if(idMap.get(item.InventoryItem__c).Grouping__c== 'Upstructure Package'){
                        
                        if(upstructure != null && upstructure > 0){
                            Case_Opportunity_Item__c upsItem = new Case_Opportunity_Item__c();
                            upsItem.Opportunity__c = opp.Id;
                            upsItem.Rstk_Inventory_Item__c = item.id;
                            upsItem.Quantity__c = (idMap.get(item.InventoryItem__c).Default_Quantity__c * upstructure);
                            
                            caseItems.add(upsItem);
                        }
                        
                    } else {
                       Case_Opportunity_Item__c opItem = new Case_Opportunity_Item__c(
                                Opportunity__c = opp.Id,
                                Rstk_Inventory_Item__c = item.id,
                                Quantity__c = (idMap.get(item.InventoryItem__c).Default_Quantity__c * fltCount)
                            ); 
                        caseItems.add(opItem);
                    }
                }
            }
            
            if(caseItems.size() > 0){
                insert caseItems;
                
                opp.Structure_Items_Added__c = true;
                update opp;
            }
            
            // Redirect to the opportunity Record
             return new PageReference('/' + opp.Id);
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This process has already been run'));
        }
        return null;
    }
}