sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/Case_Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Case Opportunity Item</label>
    <nameField>
        <displayFormat>COPP-{0000}</displayFormat>
        <label>Case Opportunity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Opportunity Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <formula>Rstk_Inventory_Item__r.InventoryItem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Item</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Item_Division__c.field-meta.xml
<CustomField>
    <fullName>Item_Division__c</fullName>
    <formula>Rstk_Inventory_Item__r.InventoryItem__r.Item_Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Division</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Rstk_Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Rstk_Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rstk Inventory Item</label>
    <referenceTo>Rootstock_Inventory_Item__c</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Work_Order_Created__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Work Order Created</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>c2g__codaCompany__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Work_Order__c/Opportunity_Work_Order__c.object-meta.xml
<CustomObject>
    <label>Opportunity Work Order</label>
    <nameField>
        <displayFormat>OW-{0000}</displayFormat>
        <label>Opportunity Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Work Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Work_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Work Orders</relationshipLabel>
    <relationshipName>Opportunity_Work_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>rstk__wocst__c</referenceTo>
    <relationshipLabel>Opportunity Work Orders</relationshipLabel>
    <relationshipName>Opportunity_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Work_Order__c/fields/Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Type__c</fullName>
    <label>Work Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Structure</fullName>
            </value>
            <value>
                <fullName>Business in a Box</fullName>
            </value>
            <value>
                <fullName>Pit Conversion</fullName>
            </value>
            <value>
                <fullName>Basic FLT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Work_Order__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Opportunity Work Orders</relationshipLabel>
    <relationshipName>Opportunity_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/Rootstock_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>A copy of rootstock items to be used in SF opportunity</description>
    <label>Rootstock Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rootstock Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <formula>InventoryItem__r.Item_Company__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Master</label>
    <referenceTo>rstk__icitem__c</referenceTo>
    <relationshipLabel>Opportunity Inventory ItemsRootstock</relationshipLabel>
    <relationshipName>Opportunity_Inventory_ItemsRootstock</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Rootstock Inventory Items</relationshipLabel>
    <relationshipName>Rootstock_Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Settings__c/Sanergy_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default organization wide settings</description>
    <label>Sanergy Settings</label>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inventory Item doesn&#39;t have BOM</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Has_BOM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Inventory_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity to Manufacture</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Work in progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
                <isActive>false</isActive>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Picklist Generated</fullName>
                <isActive>false</isActive>
                <label>Picklist Generated</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>received_partially</fullName>
                <isActive>false</isActive>
                <label>Received Partially</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order__c/fields/Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Type__c</fullName>
    <label>Work Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WO-Service</fullName>
            </value>
            <value>
                <fullName>WO-Manufactured</fullName>
            </value>
            <value>
                <fullName>WO-Disassembly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/Work_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Work Order Item</label>
    <nameField>
        <displayFormat>WOI-{0000}</displayFormat>
        <label>Work Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/fields/BOM_Quantity__c.field-meta.xml
<CustomField>
    <fullName>BOM_Quantity__c</fullName>
    <label>BOM Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Work_Order_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CaseOppWorkOrdersController.cls
public class CaseOppWorkOrdersController{
    
    private ApexPages.StandardController standardController;
    
    public CaseOppWorkOrdersController(ApexPages.StandardController standardController){
        this.standardController = standardController;
    }
    
    public PageReference createOrders() {
        
        Opportunity opp = (Opportunity) standardController.getRecord();
        
        Map<String, Sanergy_Settings__c> settings = Sanergy_Settings__c.getAll();
        //String slkDivision = settings.get('SLK Division Id').Value__c;
        String fliDivision = settings.get('FLIK Division Id').Value__c;
        String flimaintenanceCaseItem = settings.get('FLI Maintenance Cases').Value__c;
        //String slkmaintenanceCaseItem = settings.get('SLK Maintenance Cases').Value__c;
        String inventorySiteMukuru = settings.get('Inventory Site - Mukuru').Value__c;        
        String dimension1;
        
        // Get Dimension 1
        List<c2g__codaDimension1__c> dimensions = [SELECT Id,Name
                                                   FROM c2g__codaDimension1__c
                                                   WHERE Name='Fresh Life Operations- Maintenance'
                                                  ];
        
        // Get Case Opportunity Items
        List<Case_Opportunity_Item__c> items = [SELECT Id, Name,Rstk_Inventory_Item__r.Company_Id__c,
                                                Rstk_Inventory_Item__r.InventoryItem__c, Item_Division__c,
                                                Quantity__c
                                                FROM Case_Opportunity_Item__c
                                                WHERE Opportunity__c = :opp.Id 
                                                AND Work_Order_Created__c=false
                                                AND Item_Division__c='Fresh Life Initiative Limited'];
        
        if(items.size() > 0){
            
            Map<String, List<Case_Opportunity_Item__c>> itemMap = new Map<String, List<Case_Opportunity_Item__c>>();
            
            for(Case_Opportunity_Item__c item : items){
                List<Case_Opportunity_Item__c> itemList = itemMap.get(item.Rstk_Inventory_Item__r.Company_Id__c);
                
                if(itemList != null){
                    itemList.add(item);
                } else {
                    itemList = new  List<Case_Opportunity_Item__c>();
                    itemList.add(item);
                    itemMap.put(item.Rstk_Inventory_Item__r.Company_Id__c, itemList);
                }
                
                item.Work_Order_Created__c=true;
            }
            
            if(itemMap.size() > 0){
                
                Set<String> keys = itemMap.keySet();
                
                for(String key: keys){
                    
                    List<Case_Opportunity_Item__c> itemList = itemMap.get(key);
                    
                    if(itemList.size() > 0){
                        String itemId = flimaintenanceCaseItem;
                        
                        if(key.equals(fliDivision)){
                            itemId = flimaintenanceCaseItem;
                        }
                        
                        // Create Work Order
                        Work_Order__c wo = new Work_Order__c();
                        wo.Inventory_Item__c = itemId;
                        wo.Site__c = inventorySiteMukuru;
                        wo.Inventory_Item_Quantity__c = 1;
                        wo.Company__c= key;
                        wo.Status__c = 'Planned';
                        INSERT wo;
                        
                        
                        List<Work_Order_Item__c> wo_comps = new List<Work_Order_Item__c>();
                        Map<String, Double> mergedItems = new Map<String, Double>();
                        
                        for(Case_Opportunity_Item__c itms : itemList){
                            
                            Double qty = mergedItems.get(itms.Rstk_Inventory_Item__r.InventoryItem__c);
                            
                            if(qty == null){
                                qty = itms.Quantity__c;
                            } else{
                                qty = qty + itms.Quantity__c;
                            }
                            
                            mergedItems.put(itms.Rstk_Inventory_Item__r.InventoryItem__c, qty);
                        }
                        
                        if(mergedItems != null && mergedItems.size()> 0){
                            
                            Set<String> ids = mergedItems.keySet();
                            
                            for(String itmid: ids){
                                
                                Double quantity = mergedItems.get(itmid);
                                
                                if(quantity != null && quantity > 0){
                                    
                                    // Create Work Order Item
                                    Work_Order_Item__c cmp = new Work_Order_Item__c();
                                    cmp.Work_Order__c = wo.Id;
                                    cmp.Inventory_Item__c = itmid;
                                    cmp.BOM_Quantity__c = quantity;
                                    
                                    wo_comps.add(cmp);
                                }
                            }
                        }
                        
                        if(wo_comps.size() > 0){
                            System.debug(JSON.serialize(wo_comps));
                            INSERT wo_comps;
                        }
                        
                        //Create Opportunity_Work_Order__c
                        Opportunity_Work_Order__c wOrder = new Opportunity_Work_Order__c();
                        wOrder.Opportunity__c = opp.Id;
                        wOrder.WorkOrder__c= wo.Id;
                        wOrder.Work_Order_Type__c = 'Structure';
                        INSERT wOrder;
                        
                        // Loop through c2g__codaDimension1__c
                        for(c2g__codaDimension1__c dimension : dimensions){
                            // Check if Work order type = Structure                                    
                            if(dimension.Name=='Fresh Life Operations- Maintenance' && wOrder.Work_Order_Type__c=='Structure'){
                                dimension1 = dimension.Id;                    
                            }
                        }                                    
                        
                        //Update Work Order
                        wo.Dimension_1__c=dimension1;
                        UPDATE wo;                        
                        
                    }
                }// End for loop
                
                opp.StageName='Work Order Created';
                UPDATE opp;
                UPDATE items;
            }
            
            // Redirect to the opportunity Record
            return new PageReference('/' + opp.Id);
        }
        else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'There are no Case Opportunity Items to create Work Orders for.'));
        }        
        return null;
    }
    
}