sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/Case_Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Case Opportunity Item</label>
    <nameField>
        <displayFormat>COPP-{0000}</displayFormat>
        <label>Case Opportunity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Opportunity Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Rstk_Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Rstk_Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rstk Inventory Item</label>
    <referenceTo>Rootstock_Inventory_Item__c</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Cost__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <formula>Rstk_Inventory_Item__r.UOM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/Rootstock_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>A copy of rootstock items to be used in SF opportunity</description>
    <label>Rootstock Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rootstock Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <formula>InventoryItem__r.Inventory_UoM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateCaseOpportunityItemListController.cls
public class CreateCaseOpportunityItemListController{
     
     //class to hold items  
     public class OpportunityItems 
        {  
            public String itemName      {get; set;}       
            public String uom            {get; set;}       
            public Decimal quantity      {get; set;}
            public Decimal unitCost       {get; set;}
            public Decimal totalCost      {get; set;}    
            public OpportunityItems (){} //empty constructor                    
        }     
        
    
    Opportunity op;
    public List<OpportunityItems> items {get; set;}    
    
    //contructor
    public CreateCaseOpportunityItemListController(ApexPages.StandardController controller)
    {
        items = new List<OpportunityItems>();          
        op= (Opportunity)controller.getRecord();    //Get Opportunity from controller.
        for (Case_Opportunity_Item__c caseItem : [Select Rstk_Inventory_Item__r.name, UOM__c, Quantity__c,Total_Cost__c,Cost__c from Case_Opportunity_Item__c where Opportunity__c= :op.Id])    
        {
            OpportunityItems item= new OpportunityItems();  
            item.itemName= caseItem.Rstk_Inventory_Item__r.name;
            item.uom= caseItem.UOM__c;
            item.quantity= caseItem.Quantity__c;
            item.unitCost= caseItem.Cost__c;
            item.totalCost= caseItem.Total_Cost__c;
            items.add(item);
        }
        
       
    }
    public void UpdateOpportunityStage(){
        //change opportunty stage to pending Approval
        op.StageName='Pending Approval';
        update op;
    }
}