sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/Case_Opportunity_Item__c.object-meta.xml
<CustomObject>
    <label>Case Opportunity Item</label>
    <nameField>
        <displayFormat>COPP-{0000}</displayFormat>
        <label>Case Opportunity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Opportunity Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <formula>Rstk_Inventory_Item__r.InventoryItem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Item</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Opportunity_Item__c/fields/Rstk_Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Rstk_Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rstk Inventory Item</label>
    <referenceTo>Rootstock_Inventory_Item__c</referenceTo>
    <relationshipLabel>Case Opportunity Item</relationshipLabel>
    <relationshipName>Case_Opportunity_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/Rootstock_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>A copy of rootstock items to be used in SF opportunity</description>
    <label>Rootstock Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rootstock Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Master</label>
    <referenceTo>rstk__icitem__c</referenceTo>
    <relationshipLabel>Opportunity Inventory ItemsRootstock</relationshipLabel>
    <relationshipName>Opportunity_Inventory_ItemsRootstock</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Rootstock_Inventory_Item__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Rootstock Inventory Items</relationshipLabel>
    <relationshipName>Rootstock_Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CaseOppWorkOrdersControllerTest.cls
@isTest(seeAllData=true)
private class CaseOppWorkOrdersControllerTest{
    /*---------------------------------Test for the Application management----------------------------------*/
    static testMethod void CaseOppWorkOrdersControllerTest() {
        
        //get a maintenance case opportunity
        List<Opportunity> op=[SELECT ID FROM Opportunity WHERE RecordTypeID IN
                              (SELECT ID FROM RecordType WHERE Name ='Maintenance Cases')
                              LIMIT 1];
        
        
        //get an inventory item
        List<Inventory_Item__c> item=[SELECT ID FROM Inventory_Item__c LIMIT 2];
        
        //create a rootstock inventory item record
        Rootstock_Inventory_Item__c rItem = new Rootstock_Inventory_Item__c();
        rItem.InventoryItem__c=item.get(0).id;
        INSERT rItem;
        
        Rootstock_Inventory_Item__c rItem2 = new Rootstock_Inventory_Item__c();
        rItem2.InventoryItem__c=item.get(1).id;
        INSERT rItem2;
        
        // Create a case opportunity item
        Case_Opportunity_Item__c caseOppItem = new Case_Opportunity_Item__c();
        caseOppItem.Quantity__c=4;
        caseOppItem.Rstk_Inventory_Item__c=rItem.id;
        caseOppItem.Opportunity__c=op.get(0).id;
        INSERT caseOppItem;
        
        //change item
        caseOppItem.Rstk_Inventory_Item__c=rItem2.id;
        UPDATE caseOppItem;
        
        //Add products
        PageReference pageRef = Page.Create_Case_Opp_Work_Orders;
        Test.setCurrentPage(pageRef);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(op.get(0));
        CaseOppWorkOrdersController oppController = new CaseOppWorkOrdersController(sc);
        oppController.createOrders();
    }
}