sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/Sanergy_Department_Unit__c.object-meta.xml
<CustomObject>
    <description>Sanergy Department Unit</description>
    <label>Sanergy Department Unit</label>
    <nameField>
        <label>Sanergy Department Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Department Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sanergy_Department_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department_Unit__c/fields/Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Unit_Code__c</fullName>
    <label>Unit Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AllowanceUpdaterTest.cls
@isTest(SeeAllData=True)
public class AllowanceUpdaterTest {
    static testMethod void basicTest(){
        List<Sanergy_Department_Unit__c> departmentUnit = [select id,approver__c,Unit_Code__c
                                                          from Sanergy_Department_Unit__c
                                                          where Approver__c !=null
                                                          limit 1
                                                          ];
        if(departmentUnit.size()>0){
            List<User> newApprover = [select Id
                                   from User 
                                   where id !=: departmentUnit.get(0).Approver__c
                                   AND isActive = true
                                   limit 1
                                  ];
            if(newApprover.size()>0){
                departmentUnit.get(0).Approver__c = newApprover.get(0).id;
				departmentUnit.get(0).Unit_Code__c = 'IT';                
                update departmentUnit;
            }            
        }
            
    }
}