sfSandBoxCode/force-app/main/default/objects/Recipe__c/Recipe__c.object-meta.xml
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recipe__c/recordTypes/Recipe.recordType-meta.xml
<RecordType>
    <fullName>Recipe</fullName>
    <active>true</active>
    <label>Recipe</label>
</RecordType>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/Recipe_Items__c.object-meta.xml
<CustomObject>
    <label>Recipe Item</label>
    <nameField>
        <label>Recipe Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Quantity_Recipe_line_item__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Recipe_line_item__c</fullName>
    <formula>Ratio__c * Recipe__r.FLI_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Recipe line item</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Ratio__c.field-meta.xml
<CustomField>
    <fullName>Ratio__c</fullName>
    <label>Ratio</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Recipe Items</relationshipLabel>
    <relationshipName>Recipe_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/Windrow_Batch__c.object-meta.xml
<CustomObject>
    <description>Windrow Batches to be added to the Windrows</description>
    <label>Windrow Batch</label>
    <nameField>
        <label>Windrow Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Windrow Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/fields/FLI_Waste_Quantity_kgs__c.field-meta.xml
<CustomField>
    <fullName>FLI_Waste_Quantity_kgs__c</fullName>
    <label>FLI Waste Quantity(kgs)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Windrow Batches</relationshipLabel>
    <relationshipName>Windrow_Batches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch_Line_Item__c/Windrow_Batch_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Windrow Batch Items added to the windrow</description>
    <label>Windrow Batch Line Item</label>
    <nameField>
        <label>Windrow Batch Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Windrow Batch Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch_Line_Item__c/fields/Quantity_Required_Kg__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Required_Kg__c</fullName>
    <description>Total Quantity Added in Kg</description>
    <inlineHelpText>Total Quantity Added in Kg</inlineHelpText>
    <label>Quantity Required(Kg)</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch_Line_Item__c/fields/Recipe_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipe_Item_Name__c</fullName>
    <label>Recipe Item Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch_Line_Item__c/fields/Windrow_Batch__c.field-meta.xml
<CustomField>
    <fullName>Windrow_Batch__c</fullName>
    <description>Windrow Batch</description>
    <inlineHelpText>Windrow Batch</inlineHelpText>
    <label>Windrow Batch</label>
    <referenceTo>Windrow_Batch__c</referenceTo>
    <relationshipLabel>Windrow Batch Line Items</relationshipLabel>
    <relationshipName>Windrow_Batch_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateBatchItemFromRecipeItems.cls
public class CreateBatchItemFromRecipeItems {
    
    public ApexPages.StandardController standardController;
    public  Windrow_Batch__c windrowBatch{get; set;}
    public List<RecipeItems> itemList {get; set;}
    //public Double weight{get; set;}
    
    public CreateBatchItemFromRecipeItems(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.windrowBatch = (Windrow_Batch__c)standardController.getRecord();
        this.windrowBatch = [select id, name, Recipe__c, FLI_Waste_Quantity_kgs__c
                            from Windrow_Batch__c where id =: this.windrowBatch.Id];
    	itemList = new List<RecipeItems>();

        
        List<Recipe_Items__c> items = [SELECT Id,Name, Item_Name__c, Quantity_Recipe_line_item__c, Ratio__c, Recipe__c
                                                     FROM Recipe_Items__c where Recipe__c =:  this.windrowBatch.Recipe__c
                                                                                                       
                                      ];

        for(Recipe_Items__c item:items){
            RecipeItems wr = new RecipeItems(item);
           itemList.add(wr);
        }
    } 
    
       public PageReference selectAll() {
        if(itemList != null){
            for(RecipeItems lg:itemList){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(itemList != null){
            for(RecipeItems lg:itemList){
                lg.selected=false;                
            }
        }
        return null;
    }
    
    public PageReference  processSelected() {
        
         if(itemList != null && itemList.size() > 0){
            
            integer issued = 0;
            integer expected = 0;
            
            for(RecipeItems item : itemList){
                
                if(item.selected ){
                    
                    expected +=1;

                    item.batchItem.Quantity_Required_Kg__c =  this.windrowBatch.FLI_Waste_Quantity_kgs__c * item.item.Ratio__c;
                    item.batchItem.Windrow_Batch__c = this.windrowBatch.Id;
                    insert item.batchItem;
                                        
                   
                } issued +=1;
            }
        
            if(expected == issued){
                return new PageReference('/' + this.windrowBatch.Id);
            } else {
                return new PageReference('/' + this.windrowBatch.Id);
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'Some Items Were not Issued');
                ApexPages.addmessage(msg);
                return null;
            }
            
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Kindly confirm that the selected recipe has items'));
            return null;
        }
        return null;
    }
    
    public class RecipeItems{
        
        public Windrow_Batch_Line_Item__c batchItem {get; set;}
        public Recipe_Items__c item {get; set;}
        public Boolean selected {get; set;}

        public  RecipeItems(Recipe_Items__c line) {
            item = line;
            
            batchItem = new Windrow_Batch_Line_Item__c();
           
            batchItem.Recipe_Item_Name__c = line.Name;
            this.selected = true;
        }
    }
}