sfSandBoxCode/force-app/main/default/objects/Recipe__c/Recipe__c.object-meta.xml
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/Recipe_Items__c.object-meta.xml
<CustomObject>
    <label>Recipe Item</label>
    <nameField>
        <label>Recipe Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Quantity_Recipe_line_item__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Recipe_line_item__c</fullName>
    <formula>Ratio__c * Recipe__r.FLI_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Recipe line item</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Ratio__c.field-meta.xml
<CustomField>
    <fullName>Ratio__c</fullName>
    <label>Ratio</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recipe_Items__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Recipe Items</relationshipLabel>
    <relationshipName>Recipe_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/Windrow_Batch__c.object-meta.xml
<CustomObject>
    <description>Windrow Batches to be added to the Windrows</description>
    <label>Windrow Batch</label>
    <nameField>
        <label>Windrow Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Windrow Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/fields/FLI_Waste_Quantity_kgs__c.field-meta.xml
<CustomField>
    <fullName>FLI_Waste_Quantity_kgs__c</fullName>
    <label>FLI Waste Quantity(kgs)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Windrow_Batch__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Windrow Batches</relationshipLabel>
    <relationshipName>Windrow_Batches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/BatchItemFromRecipeItemTest.cls
@isTest(SeeAllData=true)
public class BatchItemFromRecipeItemTest {
    static testMethod void BatchItemTest(){
         List<Recipe_Items__c> recipeItem = [SELECT Id,Name, Item_Name__c, Quantity_Recipe_line_item__c, Ratio__c, Recipe__c
                                                    FROM Recipe_Items__c WHERE  Recipe__c != null
                                            Limit 1];
        if(recipeItem.size()>0){
         List<Windrow_Batch__c> windrowBatch = [select id, name, Recipe__c, FLI_Waste_Quantity_kgs__c
                            							from Windrow_Batch__c Limit 1];
         if(windrowBatch.size()>0){
             windrowBatch.get(0).Recipe__c  = recipeItem.get(0).Recipe__c;
             windrowBatch.get(0).FLI_Waste_Quantity_kgs__c = 1000;
             update windrowBatch;
             
                PageReference pageRef = Page.CreateBatchItemFromRecipeItem;
            
                Test.setCurrentPage(pageRef);
                ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(windrowBatch.get(0));
                CreateBatchItemFromRecipeItems controller = new CreateBatchItemFromRecipeItems(sc);
                controller.selectAll();
                controller.processSelected();
                controller.unselectAll();
         }
         }
    }
}