sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Type__c</fullName>
    <description>Type of franchise that the FLO runs.</description>
    <inlineHelpText>Type of franchise that the FLO runs. Selected by the marketing team after the toilet is launched.</inlineHelpText>
    <label>Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial-Open market</fullName>
            </value>
            <value>
                <fullName>Commercial-Residential</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Plot</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-School</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Plot</fullName>
            </value>
            <value>
                <fullName>Hybrid-School</fullName>
            </value>
            <value>
                <fullName>Competitor Location</fullName>
            </value>
            <value>
                <fullName>Demo Toilet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Last_FLT__c.field-meta.xml
<CustomField>
    <fullName>Last_FLT__c</fullName>
    <label>Last FLT</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/No_of_Open_toilets__c.field-meta.xml
<CustomField>
    <fullName>No_of_Open_toilets__c</fullName>
    <defaultValue>0</defaultValue>
    <description>No. of toilets that are open in this location</description>
    <label>No. of Open toilets</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Area</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition__c/Location_Demolition__c.object-meta.xml
<CustomObject>
    <description>Toilets that have been demolished in a given location</description>
    <label>Location Demolition</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Location Demolition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Demolitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition__c/fields/Demolished_Location__c.field-meta.xml
<CustomField>
    <fullName>Demolished_Location__c</fullName>
    <description>Demolished Location</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Demolitions</relationshipLabel>
    <relationshipName>Location_Demolitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition__c/fields/Firm_Toilets__c.field-meta.xml
<CustomField>
    <fullName>Firm_Toilets__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once checked, toilets cant be added</description>
    <inlineHelpText>Once checked, toilets cant be added</inlineHelpText>
    <label>Firm Toilets</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_Toilets__c/Location_Demolition_Toilets__c.object-meta.xml
<CustomObject>
    <label>Location Demolition Toilet</label>
    <nameField>
        <label>Location Demolition Toilets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Demolition Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_Toilets__c/fields/Close_Toilet__c.field-meta.xml
<CustomField>
    <fullName>Close_Toilet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the toilet as closes</description>
    <inlineHelpText>If this field is checked, the status of this toilet will change to Closed</inlineHelpText>
    <label>Close Toilet</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_Toilets__c/fields/Location_Demolition__c.field-meta.xml
<CustomField>
    <fullName>Location_Demolition__c</fullName>
    <label>Location Demolition</label>
    <referenceTo>Location_Demolition__c</referenceTo>
    <relationshipLabel>Location Demolition Toilets</relationshipLabel>
    <relationshipName>Location_Demolition_Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_Toilets__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The toilet</description>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Location Demolition Toilets</relationshipLabel>
    <relationshipName>Location_Demolition_Toilets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_Toilets__c/fields/Toilet_Status__c.field-meta.xml
<CustomField>
    <fullName>Toilet_Status__c</fullName>
    <label>Toilet Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demolished Indefinitely</fullName>
            </value>
            <value>
                <fullName>Demolished - To be rebuilt</fullName>
            </value>
            <value>
                <fullName>Demolished - To be relocated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub-Area</label>
    <nameField>
        <label>Sub-Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <description>Date of first day of business</description>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When new Toilet records are created via Opportunity Product Line Items, this field is automatically populated.</description>
    <label>Sub-Area (del)</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/LocationDemolitionValidationTest.cls
@isTest 
private class LocationDemolitionValidationTest {
    static testMethod void validateLocationDemolitionInsert() {
        
        // Create Location  
        Location__c loc = new Location__c();
        loc.Name = 'NRB-20';
        loc.Last_FLT__c = 0;
        loc.Franchise_Type__c = 'Hybrid-Plot';
        loc.Sub_Area__c = 'a09D000000JZ1eH';//subArea.Id;--Diamond
        INSERT loc;
        
        // Create Location  
        Location__c loc2 = new Location__c();
        loc2.Name = 'NRB-21';
        loc2.Last_FLT__c = 0;
        loc2.Franchise_Type__c = 'Hybrid-Plot';
        loc2.Sub_Area__c = 'a09D000000JZ1rd';//subArea.Id;--Diamond
        INSERT loc2;
        
        Location__c locRetrieved=[SELECT ID, No_of_Open_toilets__c
                                  FROM Location__c
                                  WHERE Name='NRB-20'];
        
        System.assertEquals(locRetrieved.No_of_Open_toilets__c , 0);
        
        
        //insert Account
        Account Ac=new Account(
            
            Name='Acc',
            CurrencyIsoCode='KES' 
        );                        
        insert Ac;
        Account AcRetrieved=[SELECT ID
                             FROM Account
                             WHERE Name='Acc'];
        
        
        
        //insert Contact
        Contact con=new Contact(
            
            lastname='Onyando',
            Sex__c='Male'
        );
        insert con;
        Contact conRetrieved=[SELECT ID
                              FROM Contact
                              WHERE lastname='Onyando'];
        
        
        //insert Opportunity
        Opportunity op=new Opportunity(
            Name='ops',
            AccountId=AcRetrieved.ID,
            StageName='Sale Open',
            CloseDate=Date.today(),
            Primary_Salesperson__c=conRetrieved.ID
            
        );
        
        //Run test as TEMP RS        
        User u = [Select Id,Alias FROM User WHERE Alias = 'dev'];
        System.runAs(u) {            
            INSERT op;
        }//End System.runAs(u)        
        
        Toilet__c toilet=new Toilet__c(
            Name='NRB-20.1',
            Location__c=loc.ID,
            Opening_Date__c=Date.today(),
            Opportunity__c=op.ID,
            Operational_Status__c='Open',
            Current_Specific_Status__c='Open - New',
            Collection_Route__c='KR Collection Center'
        );
        
        INSERT toilet;
        
        Toilet__c toilet2=new Toilet__c(
            Name='NRB-21.1',
            Location__c=loc2.ID,
            Opening_Date__c=Date.today(),
            Opportunity__c=op.ID,
            Operational_Status__c='Open',
            Current_Specific_Status__c='Open - New',
            Collection_Route__c='KR Collection Center'
        );
        
        INSERT toilet2;       
        
        List<Location_Demolition__c>  LD_List=new List<Location_Demolition__c>();
        
        
        //insert location demolition
        Location_Demolition__c locDemo=new Location_Demolition__c(
            
            Demolished_Location__c=locRetrieved.ID
        );
        
        //insert location demolition
        Location_Demolition__c locDemo2=new Location_Demolition__c(
            
            Demolished_Location__c=locRetrieved.ID,
            Firm_Toilets__c=true
        );
        
        //insert location demolition
        Location_Demolition__c locDemo3=new Location_Demolition__c(
            
            Demolished_Location__c=loc2.ID
            
        );
        
        LD_List.add(locDemo);
        
        LD_List.add(locDemo3);
        
        insert LD_List;
        
        
        
        
        //insert Location Demolition Toilet
        Location_Demolition_Toilets__c ldt=new Location_Demolition_Toilets__c(
            Toilet__c=toilet.ID,
            Location_Demolition__c=locDemo.ID,
            CurrencyIsoCode='KES',
            Close_Toilet__c=true
        );
        
        
        insert ldt;
        
        
        
        Integer count=[SELECT count()
                       FROM Location_Demolition_Toilets__c
                      ];
        
        System.assertEquals(count,1);
        
        try
        {
            
            locDemo.Firm_Toilets__c=true;
            update locDemo; 
            Location_Demolition_Toilets__c ldt_firmed=new Location_Demolition_Toilets__c(
                Toilet__c=toilet2.ID,
                Location_Demolition__c=locDemo.ID,
                CurrencyIsoCode='KES'
            );
            
            insert ldt_firmed;
            
            //throw new MyException('An exception should have been thrown by the trigger but was not.'); // 1. If we get to this line it means an error was not added and the test class should throw an exception here. 2. MyException class extends Exception.
            System.debug('Error not thrown');
        }
        catch(Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
            System.Assert(e.getMessage().contains('New toilets cannot be added if Toilets have been firmed'));
        }
        
        
        
        try
        {
            
            Location_Demolition_Toilets__c ldt_diffLoc=new Location_Demolition_Toilets__c(
                Toilet__c=toilet2.ID,
                Location_Demolition__c=locDemo3.ID,
                CurrencyIsoCode='KES'
            );
            
            insert ldt_diffLoc;
            
            //throw new MyException('An exception should have been thrown by the trigger but was not.'); // 1. If we get to this line it means an error was not added and the test class should throw an exception here. 2. MyException class extends Exception.
            System.debug('Error not thrown');
        }
        catch(Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
            System.Assert(e.getMessage().contains('This toilet is not in the specified location'));
        }
        
        try
        {
            
            Location_Demolition_Toilets__c ldt_duplicate=new Location_Demolition_Toilets__c(
                Toilet__c=toilet.ID,
                Location_Demolition__c=locDemo.ID,
                CurrencyIsoCode='KES',
                Toilet_Status__c='Demolished Indefinitely'
            );
            
            insert ldt_duplicate;
            
            //throw new MyException('An exception should have been thrown by the trigger but was not.'); // 1. If we get to this line it means an error was not added and the test class should throw an exception here. 2. MyException class extends Exception.
            System.debug('Error not thrown');
        }
        catch(Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
            //System.Assert(e.getMessage().contains('You cannot insert the same toilet more than once in a Location Demolition'));
        }
        
        
        
        try
        {
            
            locDemo.Firm_Toilets__c=true;
            update locDemo;
            
            delete ldt;
            
            //throw new MyException('An exception should have been thrown by the trigger but was not.'); // 1. If we get to this line it means an error was not added and the test class should throw an exception here. 2. MyException class extends Exception.
            System.debug('Error not thrown');
        }
        catch(Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
            System.Assert(e.getMessage().contains('Location Demolition Toilets cannot be deleted if Toilets have been firmed'));
        }
    }
}