sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Closure_Type__c.field-meta.xml
<CustomField>
    <fullName>Closure_Type__c</fullName>
    <label>Closure Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Explanation_1__c.field-meta.xml
<CustomField>
    <fullName>Explanation_1__c</fullName>
    <label>Explanation 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Along power line</fullName>
            </value>
            <value>
                <fullName>Along road reserve</fullName>
            </value>
            <value>
                <fullName>Along pipeline</fullName>
            </value>
            <value>
                <fullName>River reserve</fullName>
            </value>
            <value>
                <fullName>Road expansion</fullName>
            </value>
            <value>
                <fullName>With neighbors</fullName>
            </value>
            <value>
                <fullName>With landlords</fullName>
            </value>
            <value>
                <fullName>Community member(s)</fullName>
            </value>
            <value>
                <fullName>Local government</fullName>
            </value>
            <value>
                <fullName>Consumables are too expensive</fullName>
            </value>
            <value>
                <fullName>Complaint of strict hygiene</fullName>
            </value>
            <value>
                <fullName>FLO non-adherence</fullName>
            </value>
            <value>
                <fullName>Tenants refused to pay landlord</fullName>
            </value>
            <value>
                <fullName>Tenants vacated</fullName>
            </value>
            <value>
                <fullName>Too expensive - personal reason</fullName>
            </value>
            <value>
                <fullName>Cannibalization</fullName>
            </value>
            <value>
                <fullName>No operator</fullName>
            </value>
            <value>
                <fullName>Connected to sewer</fullName>
            </value>
            <value>
                <fullName>Pit latrines</fullName>
            </value>
            <value>
                <fullName>Public toilet</fullName>
            </value>
            <value>
                <fullName>Infrequent collection</fullName>
            </value>
            <value>
                <fullName>Personal interaction with FLI</fullName>
            </value>
            <value>
                <fullName>Government demolition</fullName>
            </value>
            <value>
                <fullName>FLO moved</fullName>
            </value>
            <value>
                <fullName>Change of ownership</fullName>
            </value>
            <value>
                <fullName>Residential upgrading</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <description>Date of first day of business</description>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Reason_1__c.field-meta.xml
<CustomField>
    <fullName>Reason_1__c</fullName>
    <label>Closure Reason 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Government Demolition</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Found another toilet option</fullName>
            </value>
            <value>
                <fullName>Service Related</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Test_Field__c.field-meta.xml
<CustomField>
    <fullName>Test_Field__c</fullName>
    <label>Test Field</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet_Type__c.field-meta.xml
<CustomField>
    <fullName>Toilet_Type__c</fullName>
    <label>Toilet Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/Pull_Toilets_To_Account_Test.cls
@isTest(SeeAllData=true)
public class Pull_Toilets_To_Account_Test {
    static testMethod void test_Pulling_Of_Toilets(){
       LIST<Toilet__c> openToilet=[SELECT Id,Test_Field__c,Operational_Status__c FROM Toilet__c 
                                WHERE  Operational_Status__c='Open' AND Test_Field__c=null LIMIT 10];
        
        if(openToilet.size()>0){
            //System.debug('TOILET OPEN');
            for(Toilet__c t:openToilet){
               t.Operational_Status__c='Closed';
                t.Closure_Type__c='Closed-By FLI';
                t.Reason_1__c = 'Dispute';
                t.Explanation_1__c='With neighbors';
            }
            update openToilet;
        }
        Toilet__c toilet=new Toilet__c();
        toilet.Name='KM-8.11';
        toilet.Opening_Date__c=date.today();
        toilet.Opportunity__c='006D000000euD2R';
        toilet.Location__c='a0hD00000091OH8';
        toilet.Operational_Status__c='Open';
        toilet.Current_Specific_Status__c='Open-New';
        toilet.Collection_Route__c='CLOSED';
        toilet.Toilet_Type__c='Demo';
        
        insert toilet;

    }

}