sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Add_on_Project__c.field-meta.xml
<CustomField>
    <fullName>Add_on_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Included in add on project?</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_ReadWeightCollectionsTest.cls
@isTest(SeeAllData=true)
public class REST_ReadWeightCollectionsTest{
    static testMethod void collectionDataTest() {
        List<Toilet__c> toiletList = [SELECT id,name,Collection_Route__c 
                                       FROM Toilet__c
                                       WHERE Location__r.Add_on_Project__c= true
                                       AND Operational_Status__c = 'Open'
                                       AND Collection_Route__c != null
                                       LIMIT 1];
                                       
        if(toiletList.size() > 0){
            
             String[] data = new String[] {toiletList.get(0).Collection_Route__c};
             String jsonString = System.JSON.serialize(data);
             
             if(data != null){
                 REST_ReadWeightCollections.collectionData(jsonString );
             }
             
             //try with unserializable string to catch error
                REST_ReadWeightCollections.collectionData(null);
        
        }
    }
}