sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/GPS_Latitude__c.field-meta.xml
<CustomField>
    <fullName>GPS_Latitude__c</fullName>
    <label>GPS Latitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/GPS_Longitude__c.field-meta.xml
<CustomField>
    <fullName>GPS_Longitude__c</fullName>
    <label>GPS Longitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_Toilets.cls
@RestResource(urlMapping='/toilets')
global with sharing class REST_Toilets{
    
   @HttpGet
    global static List<Toilet> getToilets() {
    
        List<Toilet> toilets = new List<Toilet>();
        
        List<Toilet__c> sfToilets = [SELECT Id, Name, Location__c, Location__r.Name,
                                     Location__r.GPS_Latitude__c, Location__r.GPS_Longitude__c,Operational_Status__c
                                     FROM Toilet__c];
        
        if(sfToilets != null && sfToilets.size()> 0){
            
            for(Toilet__c sfToilet : sfToilets){
            
                Toilet tl = new Toilet();
                
                tl.guid = sfToilet.Id;
                tl.toiletName = sfToilet.Name;
                tl.locationId = sfToilet.Location__c;
                tl.locationName = sfToilet.Location__r.Name;
                tl.latitude = sfToilet.Location__r.GPS_Latitude__c;
                tl.longitude = sfToilet.Location__r.GPS_Longitude__c;
                tl.operationalStatus = sfToilet.Operational_Status__c;
            
                toilets.add(tl);
            }
        }
        
        return toilets;
    }
    
    global class Toilet {        
        public String guid;
        public String toiletName;
        public String locationId;
        public String locationName;
        public Decimal latitude;
        public Decimal longitude;
        public String operationalStatus;
    }
}