sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT( Sub_Area__r.Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Type__c</fullName>
    <description>Type of franchise that the FLO runs.</description>
    <inlineHelpText>Type of franchise that the FLO runs. Selected by the marketing team after the toilet is launched.</inlineHelpText>
    <label>Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial-Open market</fullName>
            </value>
            <value>
                <fullName>Commercial-Residential</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Plot</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-School</fullName>
            </value>
            <value>
                <fullName>Non-Commercial-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Institution</fullName>
            </value>
            <value>
                <fullName>Hybrid-Plot</fullName>
            </value>
            <value>
                <fullName>Hybrid-School</fullName>
            </value>
            <value>
                <fullName>Competitor Location</fullName>
            </value>
            <value>
                <fullName>Demo Toilet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Area</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/Opportunity_Toilet_Location__c.object-meta.xml
<CustomObject>
    <description>The locations there opportunities set up toilets</description>
    <label>Opportunity Toilet Location</label>
    <nameField>
        <displayFormat>OTL-{0000}</displayFormat>
        <label>Opportunity Toilet Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Toilet Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Opportunity Toilet Locations</relationshipLabel>
    <relationshipName>Opportunity_Toilet_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/No_of_FLI_FLTs__c.field-meta.xml
<CustomField>
    <fullName>No_of_FLI_FLTs__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of FLI funded FLTs</description>
    <inlineHelpText>The number of FLI funded FLTs</inlineHelpText>
    <label>No. of FLI FLTs</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/No_of_Kiva_FLTs__c.field-meta.xml
<CustomField>
    <fullName>No_of_Kiva_FLTs__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of KIVA funded FLTs</description>
    <inlineHelpText>The number of KIVA funded FLTs</inlineHelpText>
    <label>No. of Kiva FLTs</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/No_of_Toilets__c.field-meta.xml
<CustomField>
    <fullName>No_of_Toilets__c</fullName>
    <label>No. of Toilets</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Toilet Locations</relationshipLabel>
    <relationshipName>Opportunity_Toilet_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_Toilet_Location__c/fields/Payment_Option__c.field-meta.xml
<CustomField>
    <fullName>Payment_Option__c</fullName>
    <label>Payment Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Upfront</fullName>
            </value>
            <value>
                <fullName>Kiva</fullName>
            </value>
            <value>
                <fullName>Kiva &amp; FLI</fullName>
            </value>
            <value>
                <fullName>FLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub-Area</label>
    <nameField>
        <label>Sub-Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kwa Ruben</fullName>
            </value>
            <value>
                <fullName>Kwa Njenga</fullName>
            </value>
            <value>
                <fullName>Viwandani</fullName>
            </value>
            <value>
                <fullName>Imara Daima</fullName>
            </value>
            <value>
                <fullName>Kware</fullName>
            </value>
            <value>
                <fullName>Gikomba</fullName>
            </value>
            <value>
                <fullName>Makadara</fullName>
            </value>
            <value>
                <fullName>Kamkunji</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Kayaba</fullName>
            </value>
            <value>
                <fullName>Mabroukie</fullName>
            </value>
            <value>
                <fullName>Mathare</fullName>
            </value>
            <value>
                <fullName>Embakasi West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(  Location__r.Sub_Area__r.Area__c  )</formula>
    <label>Area</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <description>Date of first day of business</description>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When new Toilet records are created via Opportunity Product Line Items, this field is automatically populated.</description>
    <label>Sub-Area (del)</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/OpportunityTestClassAddProducts2Year.cls
@isTest(SeeAllData=true)
private class OpportunityTestClassAddProducts2Year {
/*
     static testMethod void CreateToiletSaleOpportunity_Add2YearPayment() {
           //insert Account
       Account Ac=new Account(
                              Name='Acc',
                              CurrencyIsoCode='KES' 
                               );                        
       insert Ac;
       Account AcRetrieved=[SELECT ID
                   FROM Account
                   WHERE Name='Acc'];
                   
                   
       //insert second Account
       Account AcNew=new Account(
                              
                              Name='AccNew',
                              CurrencyIsoCode='KES' 
                               );                        
       insert AcNew;
       Account AcNewRetrieved=[SELECT ID
                   FROM Account
                   WHERE Name='AccNew'];
                    
       
       
       //insert Contact
       Contact con=new Contact(
                              
                                 lastname='Onyando',
                                 Sex__c='Male'
                               );
      insert con;
      Contact conRetrieved=[SELECT ID
                            FROM Contact
                            WHERE lastname='Onyando'];
       
       Id standardpricebookId = Test.getStandardPricebookId();
        //create pricebook
       Pricebook2 pricebook=new Pricebook2(
                                   Name='FLT Sales - Credit 2 Year'
                                   );
       insert pricebook;

       
       //insert Opportunity
       Opportunity op=new Opportunity(
                                       Name='ops',
                                       AccountId=AcRetrieved.ID,
                                       StageName='Deposit Paid',
                                       CloseDate=Date.today(),
                                       Primary_Salesperson__c=conRetrieved.ID,
                                       GR_Approval_Status__c='Approved',
                                       AM_Approval_Status__c='Approved',
                                       Deposit_Paid_Date__c=Date.Today(),
                                       Financing_Method__c='Credit',
                                       Specific_Financing_Method__c='2 Year Loan',
                                       Expected_Deposit_Amount__c=12000,
                                       No_of_FLTs__c=2,
                                       CM_Deposit__c=true,
                                       Pricebook2Id=pricebook.ID,
                                       Existing_FLO__c=false);
                                       
       Insert op;
       String OpID=op.ID;
       
       
       //create products
       List<Product2> prod=new List<Product2>();
       Product2 prodToilet=new Product2(
                                Name='COMPLETE FLT',
                                IsActive=true
                               );
                               
       Product2 prodSeco2Year=new Product2(
                                Name='Supplementary-New FLO',
                                IsActive=true                               );
                               
    
       
       prod.add(prodToilet);
       prod.add(prodSeco2Year);
        
       
       insert prod;
       
       
       //create standard pricebook entries
       List<PricebookEntry> Standardpbentry=new List<PricebookEntry>();
       
       PricebookEntry StandardpbentryComplete=new PricebookEntry(
                                               UnitPrice=40000,
                                               Pricebook2Id=standardpricebookId,
                                               IsActive=true,
                                               Product2Id=prodToilet.ID,
                                               UseStandardPrice = false
                                           );
      PricebookEntry StandardpbentryprodSeco2Year=new PricebookEntry(
                                               UnitPrice=15000,
                                               Pricebook2Id=standardpricebookId,
                                               IsActive=true,
                                               Product2Id=prodSeco2Year.ID,
                                               UseStandardPrice = false
                                           );
      
        Standardpbentry.add(StandardpbentryComplete);
        Standardpbentry.add(StandardpbentryprodSeco2Year);
        insert Standardpbentry;

       
       //create pricebook entries
       List<PricebookEntry> pbentry=new List<PricebookEntry>();
       
       PricebookEntry pbentryComplete=new PricebookEntry(
                                               UnitPrice=40000,
                                               Pricebook2Id=pricebook.ID,
                                               IsActive=true,
                                               Product2Id=prodToilet.ID,
                                               UseStandardPrice = false
                                           );
      PricebookEntry pbentryprodSeco2Year=new PricebookEntry(
                                               UnitPrice=-5000,
                                               Pricebook2Id=pricebook.ID,
                                               IsActive=true,
                                               Product2Id=prodSeco2Year.ID,
                                               UseStandardPrice = false

                                           );
      
        pbentry.add(pbentryComplete);
        pbentry.add(pbentryprodSeco2Year);
        insert pbentry;
        
        Sub_Area__c sa=new Sub_Area__c(Name='SA1',
                                          Area__c='Tassia');
           insert sa;
           //insert Location
           Location__c loc=new Location__c(
                                           Name='KB1',
                                           Franchise_Type__c='Hybrid-Plot',
                                           CurrencyIsoCode='KES',
                                           Sub_Area__c=sa.ID);
           insert loc;
           Toilet__c toilet=new Toilet__c(
                                       Name='KB1.1',
                                       Location__c=loc.ID,
                                       Opening_Date__c=Date.today(),
                                       Opportunity__c=op.ID,
                                       Operational_Status__c='Open',
                                       Current_Specific_Status__c='Open - New',
                                       Collection_Route__c='KR Collection Center'
                                       );
          insert toilet;
           
       
        Test.startTest();
          Opportunity_Toilet_Location__c OTL1=new Opportunity_Toilet_Location__c(
           Opportunity__c=Op.ID,
           Location__c=loc.id,
           Payment_Option__c='Kiva',
           No_of_Toilets__c=2,
           No_of_Kiva_FLTs__c=2,
           No_of_FLI_FLTs__c=0);
           
           
          Opportunity_Toilet_Location__c OTL2=new Opportunity_Toilet_Location__c(
           Opportunity__c=Op.ID,
           Payment_Option__c='Kiva',
           Location__c=loc.id,
           No_of_Toilets__c=1,
           No_of_Kiva_FLTs__c=1,
           No_of_FLI_FLTs__c=0);

          List<Opportunity_Toilet_Location__c>  OTL_List=new List<Opportunity_Toilet_Location__c>();
          OTL_List.add(OTL1);    
          OTL_List.add(OTL2);   
             
          insert OTL_List;
          
          OTL1.Firm__c=true; 
          OTL2.Firm__c=true; 
          update OTL_List; 
          
           AggregateResult[] count=[SELECT SUM(Quantity) 
                         FROM OpportunityLineItem 
                         WHERE (Opportunity_Toilet_Location__c=:OTL1.ID OR Opportunity_Toilet_Location__c=:OTL2.ID)
                         AND is_a_toilet__c=true];
          
          for (AggregateResult ar : count)  {
                //System.debug('Before firming '+ ar.get('expr0'));
                System.Assert(ar.get('expr0')==3);
           }
                                     
           
        
        Test.stopTest() ;
  
     }
     
   static testMethod void CreateToiletSaleOpportunity_addProductsOneYear_ExistingFLO() {
                     //insert Account
       Account Ac=new Account(
                              Name='Acc',
                              CurrencyIsoCode='KES' 
                               );                        
       insert Ac;
       Account AcRetrieved=[SELECT ID
                   FROM Account
                   WHERE Name='Acc'];
                   
                   
       //insert second Account
       Account AcNew=new Account(
                              
                              Name='AccNew',
                              CurrencyIsoCode='KES' 
                               );                        
       insert AcNew;
       Account AcNewRetrieved=[SELECT ID
                   FROM Account
                   WHERE Name='AccNew'];
                    
       
       
       //insert Contact
       Contact con=new Contact(
                              
                                 lastname='Onyando',
                                 Sex__c='Male'
                               );
      insert con;
      Contact conRetrieved=[SELECT ID
                            FROM Contact
                            WHERE lastname='Onyando'];
       
       Id standardpricebookId = Test.getStandardPricebookId();
        //create pricebook
       Pricebook2 pricebook=new Pricebook2(
                                   Name='FLT Sales - Credit 1 Year'
                                   );
       insert pricebook;

       
       //insert Opportunity
       Opportunity op=new Opportunity(
                                       Name='ops',
                                       AccountId=AcRetrieved.ID,
                                       StageName='Deposit Paid',
                                       CloseDate=Date.today(),
                                       Primary_Salesperson__c=conRetrieved.ID,
                                       GR_Approval_Status__c='Approved',
                                       AM_Approval_Status__c='Approved',                                       
                                       Deposit_Paid_Date__c=Date.Today(),
                                       Financing_Method__c='Credit',
                                       Specific_Financing_Method__c='1 Year Loan',
                                       Expected_Deposit_Amount__c=12000,
                                       No_of_FLTs__c=2,
                                       CM_Deposit__c=true,
                                       Pricebook2Id=pricebook.ID,
                                       Existing_FLO__c=true);
                                       
       Insert op;
       String OpID=op.ID;
       
       
       
       
             
       
       //create products
       List<Product2> prod=new List<Product2>();
       Product2 prodToilet=new Product2(
                                Name='COMPLETE FLT',
                                IsActive=true
                               );
                               
       Product2 prodSecoNew=new Product2(
                                Name='Supplementary-New FLO',
                                IsActive=true                               );
                               
       Product2 prodSecoSame=new Product2(
                                Name='Supplementary-Existing FLO',
                                IsActive=true                               );
       
       prod.add(prodToilet);
       prod.add(prodSecoNew);
       prod.add(prodSecoSame);  
       
       insert prod;
       
       
       //create standard pricebook entries
       List<PricebookEntry> Standardpbentry=new List<PricebookEntry>();
       
       PricebookEntry StandardpbentryComplete=new PricebookEntry(
                                               UnitPrice=40000,
                                               Pricebook2Id=standardpricebookId,
                                               IsActive=true,
                                               Product2Id=prodToilet.ID,
                                               UseStandardPrice = false
                                           );
      PricebookEntry StandardpbentrySecoNew=new PricebookEntry(
                                               UnitPrice=15000,
                                               Pricebook2Id=standardpricebookId,
                                               IsActive=true,
                                               Product2Id=prodSecoNew.ID,
                                               UseStandardPrice = false

                                           );
      PricebookEntry StandardpbentrySecoSame=new PricebookEntry(
                                               UnitPrice=10000,
                                               Pricebook2Id=standardpricebookId,
                                               IsActive=true,
                                               Product2Id=prodSecoSame.ID,
                                               UseStandardPrice = false

                                           );
        Standardpbentry.add(StandardpbentryComplete);
        Standardpbentry.add(StandardpbentrySecoNew);
        Standardpbentry.add(StandardpbentrySecoSame);
        insert Standardpbentry;

       
       //create pricebook entries
       List<PricebookEntry> pbentry=new List<PricebookEntry>();
       
       PricebookEntry pbentryComplete=new PricebookEntry(
                                               UnitPrice=40000,
                                               Pricebook2Id=pricebook.ID,
                                               IsActive=true,
                                               Product2Id=prodToilet.ID,
                                               UseStandardPrice = false
                                           );
      PricebookEntry pbentrySecoNew=new PricebookEntry(
                                               UnitPrice=15000,
                                               Pricebook2Id=pricebook.ID,
                                               IsActive=true,
                                               Product2Id=prodSecoNew.ID,
                                               UseStandardPrice = false

                                           );
      PricebookEntry pbentrySecoSame=new PricebookEntry(
                                               UnitPrice=10000,
                                               Pricebook2Id=pricebook.ID,
                                               IsActive=true,
                                               Product2Id=prodSecoSame.ID,
                                               UseStandardPrice = false

                                           );
        pbentry.add(pbentryComplete);
        pbentry.add(pbentrySecoNew);
        pbentry.add(pbentrySecoSame);
        insert pbentry;
        Sub_Area__c sa=new Sub_Area__c(Name='SA1',
                                          Area__c='Tassia');
           insert sa;
           //insert Location
           Location__c loc=new Location__c(
                                           Name='KB1',
                                           Franchise_Type__c='Hybrid-Plot',
                                           CurrencyIsoCode='KES',
                                           Sub_Area__c=sa.ID);
           insert loc;
           Toilet__c toilet=new Toilet__c(
                                       Name='KB1.1',
                                       Location__c=loc.ID,
                                       Opening_Date__c=Date.today(),
                                       Opportunity__c=op.ID,
                                       Operational_Status__c='Open',
                                       Current_Specific_Status__c='Open - New',
                                       Collection_Route__c='KR Collection Center'
                                       );
          insert toilet;
           
       
        Test.startTest();
          Opportunity_Toilet_Location__c OTL1=new Opportunity_Toilet_Location__c(
           Opportunity__c=Op.ID,
           Payment_Option__c='Kiva',
           Location__c=loc.id,
           No_of_Toilets__c=2,
           No_of_Kiva_FLTs__c=2,
           No_of_FLI_FLTs__c=0);
           
           
          Opportunity_Toilet_Location__c OTL2=new Opportunity_Toilet_Location__c(
           Opportunity__c=Op.ID,
           Payment_Option__c='Kiva',
           Location__c=loc.id,
           No_of_Toilets__c=1,
           No_of_Kiva_FLTs__c=1,
           No_of_FLI_FLTs__c=0);

          List<Opportunity_Toilet_Location__c>  OTL_List=new List<Opportunity_Toilet_Location__c>();
          OTL_List.add(OTL1);    
          OTL_List.add(OTL2);   
             
          insert OTL_List;
          
          OTL1.Firm__c=true; 
          OTL2.Firm__c=true; 
          update OTL_List; 
          
           AggregateResult[] count=[SELECT SUM(Quantity) 
                         FROM OpportunityLineItem 
                         WHERE (Opportunity_Toilet_Location__c=:OTL1.ID OR Opportunity_Toilet_Location__c=:OTL2.ID)
                         AND is_a_toilet__c=true];
          
          for (AggregateResult ar : count)  {
                //System.debug('Before firming '+ ar.get('expr0'));
                System.Assert(ar.get('expr0')==3);
           }
        
        Test.stopTest() ;

       }
       
       */
     
}