sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/PTS_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Procurement Request Line Item</label>
    <nameField>
        <displayFormat>PR-LI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Line Item</label>
    <referenceTo>Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Procurement Request Line Items</relationshipLabel>
    <relationshipName>Procurement_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/PTS_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PTS_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PTS Line Item</label>
    <referenceTo>PTS_Line_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/GeneratePreviousPOsPRAndIssuancesTest.cls
@isTest(seeAllData=true)
public class GeneratePreviousPOsPRAndIssuancesTest{

     static testMethod void GeneratePreviousPOsPRAndIssuancesTest() {
     
         
         //get an PR Line item
         List<Purchase_Order_Line_Item__c> POLineItem = [SELECT ID FROM Purchase_Order_Line_Item__c LIMIT 1];
         if(POLineItem.size()>0){
             
             //get an PO Line item
         	List<PTS_Line_Item__c> PRLineItem = [SELECT ID FROM PTS_Line_Item__c LIMIT 1];
         	if(POLineItem.size()>0){
                
        		PageReference pageRef1 = Page.Previous5InventoryIssuancesOnPO;
        		Test.setCurrentPage(pageRef1);
        		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(POLineItem.get(0));
        		GeneratePreviousPOsPRsAndPOItemsOnPO prevItemsOnPO = new GeneratePreviousPOsPRsAndPOItemsOnPO(sc);
        		prevItemsOnPO.getPurchaseOrderLineItemList();
                prevItemsOnPO.getProcurementRequestLineItemList();
                prevItemsOnPO.getinventoryTransactionList();
                
                PageReference pageRef2 = Page.PreviousInventoryIssuancesOnPR;
        		Test.setCurrentPage(pageRef2);
        		ApexPages.Standardcontroller sc2 = new ApexPages.Standardcontroller(PRLineItem.get(0));
        		GeneratePreviousPOsPRsAndPOItemsOnPR prevItemsOnPR = new GeneratePreviousPOsPRsAndPOItemsOnPR(sc2);
        		prevItemsOnPO.getPurchaseOrderLineItemList();
                prevItemsOnPO.getProcurementRequestLineItemList();
                prevItemsOnPO.getinventoryTransactionList();
            }
         }
     }
}