sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/PTS_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Procurement Request Line Item</label>
    <nameField>
        <displayFormat>PR-LI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Line Item</label>
    <referenceTo>Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Procurement Request Line Items</relationshipLabel>
    <relationshipName>Procurement_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Quantity of item being requested</inlineHelpText>
    <label>Inventory Request Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>the position of affairs at a particular time</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Item Request Approval</fullName>
            </value>
            <value>
                <fullName>Pending Sourcing</fullName>
            </value>
            <value>
                <fullName>Pending Quote Approval</fullName>
            </value>
            <value>
                <fullName>Pending Procurement Approval</fullName>
            </value>
            <value>
                <fullName>Pending Director Approval</fullName>
            </value>
            <value>
                <fullName>Requires Re-Approval</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Pending Purchase Order</fullName>
            </value>
            <value>
                <fullName>Purchase Order Created</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending User Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price Estimate</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Vatable__c.field-meta.xml
<CustomField>
    <fullName>Vatable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does the item cost have VAT?</inlineHelpText>
    <label>Vatable?</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Invoice_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked as long as the the item has an active Invoice assigned</description>
    <label>Invoice Assigned</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/PTS_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PTS_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PTS Line Item</label>
    <referenceTo>PTS_Line_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Accepted__c</fullName>
    <label>Quantity Accepted</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>All items Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Items Partially Received</fullName>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Variation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Variation_Notes__c</fullName>
    <label>Variation Notes</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Vatable__c.field-meta.xml
<CustomField>
    <fullName>Vatable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this checkbox if the Unit Price is subject to VAT. Otherwise leave unselected.</inlineHelpText>
    <label>Item VATable?</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/PRandPOLineEditValidationTest.cls
@isTest(SeeAllData = true)
public class PRandPOLineEditValidationTest {
    static testMethod void testPOLineEditValidation(){
        
      try {
         List<Purchase_Order_Line_Item__c> poLine = [SELECT Id,Invoice_Assigned__c, Name,Status__c,PTS_Line_Item__c
                                                   FROM Purchase_Order_Line_Item__c
                                                   WHERE Status__c = 'Open' Limit 3];
        if(poLine.size()>0){
           /* poLine.get(0).Invoice_Assigned__c = false;
            poLine.get(0).Vatable__c = false;
            poLine.get(0).Variation_Notes__c = 'n';
            update poLine;
            
            poLine.get(0).Invoice_Assigned__c = true;
            poLine.get(0).Vatable__c = true;
            update poLine;*/
            
            poLine.get(0).Invoice_Assigned__c = true;
            poLine.get(0).Status__c = 'Cancelled';
            poLine.get(0).Variation_Notes__c = 'n';
            update poLine;
            
            poLine.get(0).Invoice_Assigned__c = false;
            poLine.get(0).Status__c = 'Cancelled';
            poLine.get(0).Variation_Notes__c = 'n';
            update poLine;
            
            poLine.get(0).Variation_Notes__c = 'open';
            poLine.get(0).Vatable__c = true;
            update poLine;
           
        }
       List<Purchase_Order_Line_Item__c> poLine2 = [SELECT Id,Unit_Price__c,Invoice_Assigned__c, Name,Status__c,PTS_Line_Item__c
                                                   FROM Purchase_Order_Line_Item__c
                                                   WHERE Status__c = 'Open' Limit 3];
        if(poLine.size()>0){
           
            poLine2.get(0).Status__c = 'Cancelled';
            poLine2.get(0).Quantity_Accepted__c = 2;
            poLine2.get(0).Unit_Price__c = 1000;
            poLine2.get(0).Invoice_Assigned__c = false;
            update poLine2;
           
        }
          } catch (Exception e) {
                 e.getMessage();
            }
            
        }
    static testMethod void testPRLineEditValidation(){
        
      try {
         
          List<PTS_Line_Item__c> prLine = [SELECT Id,Item__c, Name,Status__c,Quantity__c
                                             From PTS_Line_Item__c
                                             WHERE Status__c = 'Open' Limit 3];
            if(prLine.size()>0){
                prLine.get(0).Status__c = 'Cancelled';
                update prLine;
                prLine.get(0).Item__c = 'item x';
                update prLine;
             }
            } catch (Exception e) {
                 e.getMessage();
            }
            
        }
}