sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Closure_Type__c.field-meta.xml
<CustomField>
    <fullName>Closure_Type__c</fullName>
    <label>Closure Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Status_Change_date__c.field-meta.xml
<CustomField>
    <fullName>Current_Status_Change_date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date when the current status changed</description>
    <label>Current Status Change date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status_Description__c</fullName>
    <formula>CASE ( TEXT(Current_Specific_Status__c) ,
&quot;Closed - By FLI&quot; ,&quot;Toilet closure initiated by FLI/Sanergy. It should remain in this status only for 90 days otherwise an alert should be sent to AMs and SOps Manager&quot;,
&quot;Closed - By FLO&quot;, &quot;Short term toilet closure (&lt;90 days) initiated by FLO&quot;,
&quot;Closed by FLO&quot;, &quot;Toilet closure initiated by FLO&quot;,
&quot;Closed - Debranded&quot;,&quot;FLO has completed toilet payments but is not willing to renew&quot;,
&quot;Closed - Demolished&quot;,&quot;Toilet demolished by a third party other than FLI/Sanergy&quot;,
&quot;Closed - Relocated&quot;,&quot;If a Toilet is removed from a location, physically taken to a new location&quot;,
&quot;Closed - Repossessed&quot;,&quot;FLI repossessed structure, squat plate and waste containers when the FLO defaults in payments&quot;,
&quot;Closed by FLI&quot;,&quot;Toilet closure initiated by FLI&quot;,
&quot;Closed - Resold&quot;,&quot;Applies to all FLTs that have been sold to a different FLO&quot;,
&quot;Open - Company-Owned&quot;,&quot;FLT Owned by FLI after FLO has defaulted and it is a viable location&quot;,
&quot;Open - New&quot;,&quot;Newly launched operational FLT&quot;,
&quot;Open - Re-installed&quot;,&quot;Refers to FLT installed after a demolition and the FLO gets an alternative land or location within same area or different area&quot;,
&quot;Open - Re-opened&quot;,&quot;FLT Re-opened&quot;,
&quot;Open - Relocated&quot;,&quot;Same FLO relocating FLT within same or different area of operation. The same Location ID maintained OR Same FLO relocating FLT to another location and acquiring a NEW FLT tag.&quot;,
&quot;Open - Resold&quot;,&quot;FLT resold to another FLO&quot;,
&quot;Unknown Status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Operational Status Description</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/recordTypes/Sanergy.recordType-meta.xml
<RecordType>
    <fullName>Sanergy</fullName>
    <active>true</active>
    <description>Sanergy Toilet</description>
    <label>Sanergy</label>
</RecordType>

sfSandBoxCode/force-app/main/default/classes/ToiletsClosedReminder.cls
global class ToiletsClosedReminder implements Database.Batchable<sObject>, Database.Stateful{
    
    String query2;
    
    // Start notification 90 days after toilet is closed
    Date d2 = date.today() - 90;
    
    //Status for closed toilets
    String status2 = 'Closed';
    
    //Closure type - Temporary
    String closureType2 = 'Temporary';
    
    List<ClosedToiletsReminder> closedToiletsReminder = new List<ClosedToiletsReminder>();    
    
    // Get all Toilets that were closed 90 days ago
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        query2 = 'SELECT Id,Name,Opportunity__r.Account.Name,Account_Name__c,' +
            ' Operational_Status__c,Current_Specific_Status__c,Closure_Type__c,' +
            ' Current_Status_Change_date__c,Operational_Status_Description__c' +
            ' FROM Toilet__c' +
            ' WHERE Operational_Status__c =: status2' +
            ' AND Closure_Type__c =: closureType2' +
            ' AND Current_Status_Change_date__c =: d2';
        
        return Database.getQueryLocator(query2);
    }
    
    // Get all Toilets that were closed
    global void execute(Database.BatchableContext bc, List<Toilet__c> scope){
        
        // Loop through the list of Contracts
        for(Toilet__c t : scope){
            
            ClosedToiletsReminder toiletsReminder = new ClosedToiletsReminder();            
            toiletsReminder.id = t.Id;
            toiletsReminder.toiletName = t.Name;
            toiletsReminder.accountName = t.Opportunity__r.Account.Name;
            toiletsReminder.operationalStatus = t.Operational_Status__c;
            toiletsReminder.typeOfClosure = t.Closure_Type__c;
            toiletsReminder.currentSpecificStatus = t.Current_Specific_Status__c;
            toiletsReminder.currentStatusChangeDate = t.Current_Status_Change_date__c;            
            
            // Add closed toilets to the list
            closedToiletsReminder.add(toiletsReminder);
        }                
    }
    
    global void finish(Database.BatchableContext bc){
        
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status,CreatedBy.Email
                          FROM AsyncApexJob 
                          WHERE Id = :bc.getJobId()];
        
        // Create a list to hold the emails we'll send
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        
        for(ClosedToiletsReminder ct : closedToiletsReminder){
            
            String siteURL = 'https://sanergy.my.salesforce.com/';
            
            // Create an instance of the Messaging.SingleEmailMessage class.
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            String[] toAddresses = new String[] {'dev@saner.gy','florence@saner.gy','jgithinji@saner.gy','sifuna@saner.gy','rose.kavuli@saner.gy'};
            email.setToAddresses(toAddresses);
            email.setSenderDisplayName('Sanergy - Salesforce');
            email.setSubject('90 Days Reminder on Toilets Closed(Temporary) - Toilet No: ' + ct.toiletName);           		   
            email.setHtmlBody
                ('<p>Hi,</p>'+
                 '<p>Toilet No: <em><strong>' +  ct.toiletName + ' </strong></em> for <strong><em> ' + ct.accountName + ' </strong></em> was closed <strong><em>90 days ago</strong></em>.</p>' +
                 '<p>This is a reminder for you to follow up on this toilet.</p>' +
                 '<h4>SUMMARY</h4>' +
                 '<hr/>'+           
                 '<p><strong>Toilet No: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>' +  ct.toiletName + '</p>' +
                 '<p><strong>Account Name: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>' +  ct.accountName  + '</p>' +
                 '<p><strong>Operational Status: &nbsp;&nbsp;</strong>' +  ct.operationalStatus + '</p>' +
                 '<p><strong>Closure Type: &nbsp;&nbsp;</strong>' +  ct.typeOfClosure + '</p>' +
                 '<p><strong>Current Specific Status: &nbsp;&nbsp;&nbsp;</strong>' +  ct.currentSpecificStatus + '</p>' +
                 '<p><strong>Current Status Change Date: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>' +  ct.currentStatusChangeDate + '</p>'+
                 '<p>For more details visit ' + siteURL + ct.id + ' </p>' +
                 '<hr/>'+
                 '<p style="color:red; font-size:70%;">Job Status: ' + a.Status + '</p>');
            
            emails.add(email);
        }        
        Messaging.sendEmail(emails);        
        
        System.debug(emails);
    }    
    
    // Request data
    public class ClosedToiletsReminder{
        public String id;
        public String toiletName;        
        public String accountName;
        public String operationalStatus;
        public String typeOfClosure;
        public String currentSpecificStatus;
        public Date currentStatusChangeDate;
    }
}