sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/Waste_Collection_Schedule__c.object-meta.xml
<CustomObject>
    <label>Waste Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Waste Collection Schadule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waste Collection Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <label>Collection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>Do Not Collect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Solid_Waste_Weight__c.field-meta.xml
<CustomField>
    <fullName>Solid_Waste_Weight__c</fullName>
    <label>Solid Waste Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Waste Collection Schedules</relationshipLabel>
    <relationshipName>Waste_Collection_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Urine_Weight__c.field-meta.xml
<CustomField>
    <fullName>Urine_Weight__c</fullName>
    <label>Urine Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_WriteCollections.cls
@RestResource(urlMapping='/write_collections')
global with sharing class REST_WriteCollections {
    //Incoming data from 
       global class fieldData{
        global String toilet;
        global String collection;
        global Date collectionDate;
        global Double solidWeight;
        global Double urineWeight;        
    }
    global class Response{
        String toilet;
        String collection;
        Date collectionDate;
        Double solidWeight;
        Double urineWeight;
        String message;
        Boolean success;
    }
    //Write to the collections object
    @HttpPost
    global static Response collectionData(String jsonRequest){
        Response response = new Response();
        fieldData data = (fieldData) System.JSON.deserialize(jsonRequest, fieldData.class);
        if(data!=null){
            try{
                //Data mapping goes here
                Waste_Collection_Schedule__c newWcs=new Waste_Collection_Schedule__c();
                
                newWcs.Toilet__c=data.toilet;
                newWcs.Collection__c=data.collection;
                newWcs.Collection_Date__c=data.collectionDate;
                newWcs.Solid_Waste_Weight__c=data.solidWeight;
                newWcs.Urine_Weight__c=data.urineWeight;
                insert newWcs;
                //Reponse to the fieldClient
                response.success=true;
                response.toilet=data.toilet;
                response.collection=data.collection;
                response.collectionDate=data.collectionDate;                
                response.solidWeight=data.solidWeight;
                response.urineWeight=data.urineWeight;
              
                
            }catch(exception e){
                response.success=false;
                response.message=e.getMessage();
            }
        }else{
            response.message='ERROR:Insert Failed Due To Empty Request';
            response.success=false;
        }return response;
    }

}