sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/FLT_Collection_Schedule__c.object-meta.xml
<CustomObject>
    <description>Store information on FLT Collection Schedules</description>
    <label>FLT Collection Schedule</label>
    <nameField>
        <label>FLT Collection Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FLT Collection Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Missed_Collection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Missed_Collection_Reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missed Collection Reason</label>
    <referenceTo>Missed_Collection_Reason__c</referenceTo>
    <relationshipLabel>FLT Collection Schedule</relationshipLabel>
    <relationshipName>FLT_Collection_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Planned_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Collection_Date__c</fullName>
    <description>Planned Collection Date</description>
    <label>Planned Collection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Route_Name__c.field-meta.xml
<CustomField>
    <fullName>Route_Name__c</fullName>
    <description>Route Name</description>
    <label>Route Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Schedule_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Status__c</fullName>
    <label>Schedule Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Closed by FLI</fullName>
            </value>
            <value>
                <fullName>Closure Chosen by FLO</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>DC school is closed</fullName>
            </value>
            <value>
                <fullName>Demolished</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Periodic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Solid_Waste_Weight__c.field-meta.xml
<CustomField>
    <fullName>Solid_Waste_Weight__c</fullName>
    <label>Solid Waste Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>FLT Collection Schedule</relationshipLabel>
    <relationshipName>FLT_Collection_Schedule</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Toilet_Name__c.field-meta.xml
<CustomField>
    <fullName>Toilet_Name__c</fullName>
    <formula>Toilet__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Toilet Name</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Urine_Weight__c.field-meta.xml
<CustomField>
    <fullName>Urine_Weight__c</fullName>
    <label>Urine Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/Missed_Collection_Reason__c.object-meta.xml
<CustomObject>
    <label>Missed Collection Reason</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collection Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_WriteFLTCollectionSchedule.cls
@RestResource(urlMapping='/write_flt_collection_schedule')
global with sharing class REST_WriteFLTCollectionSchedule {
      //Incoming data from 
       global class FieldData{
           global String guid;
           global Date scheduleDate;
           global String toiletId;
           global String missedCollectionId;
           global Double solidWeight;
           global Double urineWeight;
           global String scheduleStatus;
           global String route;
    }
    global class Response{
        String guid;
        Date scheduleDate;
        String toiletId;
        Double solidWeight;
        Double urineWeight;
        Boolean completed;
        String message;
    }
    //Write to the collections object
    @HttpPost
    global static List<Response> collectionData(List<FieldData> schedules){
        
        List<Response> responses = new List<Response>();
        
        if(schedules!=null && schedules.size() > 0){
            for(FieldData schedule: schedules){
                
                FLT_Collection_Schedule__c sched = null;
                
                if(schedule.guid != null){
                    sched=[SELECT Id,Toilet_Name__c,Route_Name__c,
                               Schedule_Status__c,Urine_Weight__c,
                               Solid_Waste_Weight__c,
                               Missed_Collection_Reason__c,Toilet__c,
                               Completed__c,Planned_Collection_Date__c
                           FROM FLT_Collection_Schedule__c
                           WHERE Id=:schedule.guid
                           AND Completed__c=false];
                    
                    sched.Solid_Waste_Weight__c = schedule.solidWeight;
                    sched.Urine_Weight__c = schedule.urineWeight;
                    sched.Missed_Collection_Reason__c = schedule.missedCollectionId;
                    sched.Schedule_Status__c = schedule.scheduleStatus;
                    
                    update sched;
                    
                } else {
                    sched = new FLT_Collection_Schedule__c();
                    
                    sched.Planned_Collection_Date__c = schedule.scheduleDate;
                    sched.Toilet__c = schedule.toiletId;
                    sched.Missed_Collection_Reason__c = schedule.missedCollectionId;
                    sched.Solid_Waste_Weight__c = schedule.solidWeight;
                    sched.Urine_Weight__c = schedule.urineWeight;
                    sched.Schedule_Status__c = schedule.scheduleStatus; 
                    sched.Completed__c = true;
                    
                    insert sched;
                }
                
                Response response = new Response();
                
                response.guid = sched.Id;
                response.toiletId = sched.Toilet_Name__c;
                response.scheduleDate = sched.Planned_Collection_Date__c; 
                response.solidWeight = sched.Solid_Waste_Weight__c;
                response.urineWeight = sched.Urine_Weight__c;
                response.completed = sched.Completed__c;
                
                responses.add(response);
            }
        }
        
        return responses;
    }
}