sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/FLT_Collection_Schedule__c.object-meta.xml
<CustomObject>
    <description>Store information on FLT Collection Schedules</description>
    <label>FLT Collection Schedule</label>
    <nameField>
        <label>FLT Collection Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FLT Collection Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Missed_Collection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Missed_Collection_Reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missed Collection Reason</label>
    <referenceTo>Missed_Collection_Reason__c</referenceTo>
    <relationshipLabel>FLT Collection Schedule</relationshipLabel>
    <relationshipName>FLT_Collection_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Planned_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Collection_Date__c</fullName>
    <description>Planned Collection Date</description>
    <label>Planned Collection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Route_Name__c.field-meta.xml
<CustomField>
    <fullName>Route_Name__c</fullName>
    <description>Route Name</description>
    <label>Route Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Schedule_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Status__c</fullName>
    <label>Schedule Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Closed by FLI</fullName>
            </value>
            <value>
                <fullName>Closure Chosen by FLO</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>DC school is closed</fullName>
            </value>
            <value>
                <fullName>Demolished</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Periodic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Solid_Waste_Weight__c.field-meta.xml
<CustomField>
    <fullName>Solid_Waste_Weight__c</fullName>
    <label>Solid Waste Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>FLT Collection Schedule</relationshipLabel>
    <relationshipName>FLT_Collection_Schedule</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Toilet_Name__c.field-meta.xml
<CustomField>
    <fullName>Toilet_Name__c</fullName>
    <formula>Toilet__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Toilet Name</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FLT_Collection_Schedule__c/fields/Urine_Weight__c.field-meta.xml
<CustomField>
    <fullName>Urine_Weight__c</fullName>
    <label>Urine Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/Missed_Collection_Reason__c.object-meta.xml
<CustomObject>
    <label>Missed Collection Reason</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collection Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/recordTypes/Sanergy.recordType-meta.xml
<RecordType>
    <fullName>Sanergy</fullName>
    <active>true</active>
    <description>Sanergy Toilet</description>
    <label>Sanergy</label>
</RecordType>

sfSandBoxCode/force-app/main/default/classes/REST_FLTCollectionScheduleTest.cls
@isTest(SeeAllData=true)
public class REST_FLTCollectionScheduleTest {
    static testMethod void testMissedCollectons() {
        //make API request
        System.RestContext.request = new RestRequest();
        RestContext.request.requestURI = 'https://ffa-sanergy.cs14.force.com/services/apexrest/read_collections';
                
        System.RestContext.response = new RestResponse();
        
        List<String> items = new List<String>();
        List<REST_ReadMissedCollectionReasons.dataHolder> recs = REST_ReadMissedCollectionReasons.getAll();
           //to add code coverage, call the getters of the util class
        REST_ReadMissedCollectionReasons.dataHolder rrecs=new REST_ReadMissedCollectionReasons.dataHolder();
        
                 
          rrecs.getId();
          rrecs.getName();
          rrecs.getdataNeeded();
		  rrecs.getTeamToInvestigate();
          rrecs.getMissedCollectionCode();
          rrecs.getActionTaken();
          rrecs.getMissedCollectionReason();
          rrecs.getCollection();
    }
           
        static testMethod void testReadSchedules() {
        //make API request
        System.RestContext.request = new RestRequest();
        RestContext.request.requestURI = 'https://ffa-sanergy.cs14.force.com/services/apexrest/inv_item_locations';
                
        System.RestContext.response = new RestResponse();
        
        List<String> items = new List<String>();
        List<FLT_Collection_Schedule__c> itms=[SELECT ID,Planned_Collection_Date__c 
                                    FROM FLT_Collection_Schedule__c WHERE Planned_Collection_Date__c!=null
                                    AND Id!=null   LIMIT 1];
                                    
        items.add(itms.get(0).Planned_Collection_Date__c.format());
                     
        REST_ReadFLTCollectionSChedule.AndroidDate andDate=new REST_ReadFLTCollectionSChedule.AndroidDate();
        andDate.scheduleDate=itms.get(0).Planned_Collection_Date__c;
            
        String dateString=System.JSON.serialize(andDate);
            
        List<REST_ReadFLTCollectionSChedule.Response> recs = REST_ReadFLTCollectionSChedule.collectionData(dateString);
            
        }
    static testMethod void testWriteMissedCollections(){
        //Write to REST_WriteCollections          
          
         REST_WriteMissedCollectionReasons.fieldData  adt = new  REST_WriteMissedCollectionReasons.fieldData();
        
            adt.collection='';
           	adt.codeNumber='';
            adt.actionTaken='';
           	adt.dataNeeded='';
           	adt.teamToInvestigate='';
            String s;           
            String jsonString=JSON.serialize(adt);
        	String jString=JSON.serialize(s);
                      
        REST_WriteMissedCollectionReasons wss=new REST_WriteMissedCollectionReasons();
        REST_WriteMissedCollectionReasons.Response resp=REST_WriteMissedCollectionReasons.collectionData(jsonString);
        REST_WriteMissedCollectionReasons.Response res=REST_WriteMissedCollectionReasons.collectionData(jString);
    }
    static testMethod void testWriteFLTSchedules(){
        //Write to REST_WriteCollections          
          
        /* REST_WriteFLTCollectionSchedule.FieldData  adt = new  REST_WriteFLTCollectionSchedule.FieldData();
                 
           adt.solidWeight=0;
           adt.urineWeight=0;        
             
            String jsonString=JSON.serialize(adt);*/
        
            List< REST_WriteFLTCollectionSchedule.FieldData> schedules = new List< REST_WriteFLTCollectionSchedule.FieldData>();
            
        	REST_WriteFLTCollectionSchedule.FieldData filedData=new REST_WriteFLTCollectionSchedule.FieldData();
        	LIST<FLT_Collection_Schedule__c> sched=[SELECT Id,Toilet_Name__c,Route_Name__c,Schedule_Status__c,Urine_Weight__c,Solid_Waste_Weight__c,Missed_Collection_Reason__c,Toilet__c,Completed__c,Planned_Collection_Date__c 
                                                           FROM FLT_Collection_Schedule__c
                                                          WHERE Id!=null  AND Completed__c=false
                                                   LIMIT 1];
        	filedData.guid=sched.get(0).Id;
        	filedData.solidWeight=0;
        	filedData.urineWeight=0;
        
        	schedules.add(filedData);
        
                	
        REST_WriteFLTCollectionSchedule wss=new REST_WriteFLTCollectionSchedule();
        List<REST_WriteFLTCollectionSchedule.Response> resp=REST_WriteFLTCollectionSchedule.collectionData(schedules);
       
    }
   
}