sfSandBoxCode/force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Card__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Card Type</label>
    <referenceTo>Card_Type__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Card__c/fields/Toilets__c.field-meta.xml
<CustomField>
    <fullName>Toilets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Card_Type__c/Card_Type__c.object-meta.xml
<CustomObject>
    <label>Card Type</label>
    <nameField>
        <label>Card Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/REST_Cards.cls
@RestResource(urlMapping='/cards')
global with sharing class REST_Cards {
    
   @HttpGet
    global static List<Card> getCards() {
    
        List<Card> cards = new List<Card>();
        
        List<Card__c> sfCards = [SELECT Id, Name, Card_Type__c, Description__c, Serial_Number__c, Toilets__c FROM Card__c];
        
        if(sfCards != null && sfCards.size()> 0){
            
            for(Card__c sfCard : sfCards){
            
                Card cr = new Card();                
                cr.guid = sfCard.Id;
                cr.cardTypeGuid = sfCard.Card_Type__c;
                cr.name = sfCard.Name;
                cr.description = sfCard.Description__c;
                cr.toiletGuid = sfCard.Toilets__c;
                cr.serialNumber = sfCard.Serial_Number__c;
            
                cards.add(cr);
            }
        }
        
        return cards;
    }
    
    @HttpPost
    global static Response saveCards(String jsonRequest) {
        Response response;
        try{
            List<Card> cards = (List<Card>) System.JSON.deserialize(jsonRequest, List<Card>.class);  
                   
            if(cards != null && cards.size() > 0){            
                List<Card__c> cardsToSave = new List<Card__c>();
                
                for(Card card:cards){
                
                    Card__c cardToSave = new Card__c();
                    cardToSave.id = card.guid;
                    cardToSave.Card_Type__c= card.cardTypeGuid;
                    cardToSave.Description__c = card.description;
                    cardToSave.Serial_Number__c = card.serialNumber;
                    cardToSave.Toilets__c = card.toiletGuid;
                    
                    cardsToSave.add(cardToSave);
                }
                
                
                if(cardsToSave.size() > 0){
                    upsert cardsToSave;
                }
                
                for(Card__c savedCard : cardsToSave){
                    for(Card initCard : cards){
                        if(initCard.serialNumber == savedCard.Serial_Number__c){
                           initCard.guid = savedCard.Id; 
                        }
                    }
                }
            }
            
             response = new Response();
             response.success = true;
             response.data = cards;
        }catch(Exception e){
             response = new Response();
             response.success = false;
             response.message = e.getMessage();
             System.debug('Error: '+e);
        }
        
        return response;
    }
    
    global class Response{
       public boolean success;
       public String message;
       public List<Card> data;
    }
    
    global class Card {
        public long id;        
        public String guid;
        public String cardTypeGuid;
        public String name;
        public String description;
        public String toiletGuid;
        public String serialNumber;
    }
}