sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/SA_Presentations__c.object-meta.xml
<CustomObject>
    <description>Used to create leads and track presentations made by FL Sales Associates.</description>
    <label>SA Presentation</label>
    <nameField>
        <label>Presentations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SA Presentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Area</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>SA Presentations</relationshipLabel>
    <relationshipName>SA_Presentations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub-Area</label>
    <nameField>
        <label>Sub-Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/CreateLeadFromSAPresentationsTest.cls
@istest(seeAllData=true)
public class CreateLeadFromSAPresentationsTest {
      //test for CreateLeadFromSAPresentations trigger
    static testMethod void CreateLeadFromSAPresentationsTest() {
        
         SA_Presentations__c ld=new SA_Presentations__c(
                Company__c='s',
          	    Last_Name__c='John', 
                First_name__c='Somebody',
                Phone__c='0701234567'
               // Sub_Area__c='Jogoo Road'                                             
            );
            
            insert ld;     
        
        test.StartTest();
        PageReference pageRef = Page.CreateLeadFromSAP;
        Test.setCurrentPage(pageRef);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(ld);
        CreateLeadFromSAPresentation controller = new CreateLeadFromSAPresentation(sc);
        controller.createLead();
        test.StopTest(); 
    }
    
}