sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/SA_Presentations__c.object-meta.xml
<CustomObject>
    <description>Used to create leads and track presentations made by FL Sales Associates.</description>
    <label>SA Presentation</label>
    <nameField>
        <label>Presentations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SA Presentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/First_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Contact_Date__c</fullName>
    <label>First Presentation Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hotspot</fullName>
                <default>true</default>
                <label>Hotspot</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Salesperson personal network</fullName>
            </value>
            <value>
                <fullName>Farm Star marketing event</fullName>
            </value>
            <value>
                <fullName>Other agricultural event</fullName>
            </value>
            <value>
                <fullName>Farm Star marketing materials</fullName>
            </value>
            <value>
                <fullName>Cold call</fullName>
            </value>
            <value>
                <fullName>Media spotlight</fullName>
            </value>
            <value>
                <fullName>Referral - Existing Customer</fullName>
            </value>
            <value>
                <fullName>Referral - Sanergy team</fullName>
            </value>
            <value>
                <fullName>Referral - Other</fullName>
            </value>
            <value>
                <fullName>Field Officer</fullName>
            </value>
            <value>
                <fullName>Sales activation activity</fullName>
            </value>
            <value>
                <fullName>Referral from chief / chairperson</fullName>
            </value>
            <value>
                <fullName>Referral from existing FLO</fullName>
            </value>
            <value>
                <fullName>Referral from other</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Tupperware Party</fullName>
            </value>
            <value>
                <fullName>Community forum</fullName>
            </value>
            <value>
                <fullName>Market storming</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Lead reached out to us</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/Name_of_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Referrer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SA Presentations (Name of Referrer)</relationshipLabel>
    <relationshipName>Name_of_Referrer</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/Presented_to__c.field-meta.xml
<CustomField>
    <fullName>Presented_to__c</fullName>
    <label>Presented to:</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Caretaker</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Commercial Not Renting Land</fullName>
            </value>
            <value>
                <fullName>Commercial Renting Land</fullName>
            </value>
            <value>
                <fullName>Head Teacher</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/SA_Name__c.field-meta.xml
<CustomField>
    <fullName>SA_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SA Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SA Presentations</relationshipLabel>
    <relationshipName>SA_Presentations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/SA_Presentations__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Area</label>
    <referenceTo>Sub_Area__c</referenceTo>
    <relationshipLabel>SA Presentations</relationshipLabel>
    <relationshipName>SA_Presentations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sub_Area__c/Sub_Area__c.object-meta.xml
<CustomObject>
    <label>Sub-Area</label>
    <nameField>
        <label>Sub-Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/CreateLeadFromSAPresentation.cls
public class CreateLeadFromSAPresentation {
   
    private ApexPages.StandardController standardController;
    
    public CreateLeadFromSAPresentation(ApexPages.StandardController standardController){
        this.standardController = standardController;
    }
    
    
    public PageReference createLead() {
        SA_Presentations__c sAP= (SA_Presentations__c) standardController.getRecord();
        
      
        if(sAP.Last_Name__c==null ||sAP.Company__c==null  ){
        
         Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Kindly ensure that Campany and Last name fields are filled.'));
          return null;
        
        }
       
        else{
            
            
            //create new Lead
            Lead ld=new Lead(
               Company=sAP.Company__c,
          	    Status='Open',
         	    LastName=sAP.Last_Name__c, 
                FirstName=sAp.First_name__c,
                Phone=sAp.Phone__c,
                Sub_Area_Lookup__c=sAP.Sub_Area__c,
                LeadSource=sAp.Lead_Source__c,
                Referrer__c=sAp.Name_of_Referrer__c,
                Primary_Salesperson__c=sAP.SA_Name__c,
                First_Contact_Date__c=sAP.First_Contact_Date__c,
                Presented_to__c=sAP.Presented_to__c
                
                               
            );
            
            insert ld;          
           
       
            return new PageReference('/' + sAP.Id);
        }
    }

}