sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Task__c/Asset_Maintenance_Task__c.object-meta.xml
<CustomObject>
    <description>Object to hold the asset maintenance tasks</description>
    <label>Asset Maintenance Task</label>
    <nameField>
        <label>Asset Maintenance Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Maintenance Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Asset_Maintenance_Task__c/fields/Requesting_Company__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Company__c</fullName>
    <formula>Asset_Maintenance_Schedule__r.Sanergy_Asset__r.Requesting_Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requesting Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/Asset_Service_Item__c.object-meta.xml
<CustomObject>
    <description>Holds po items for sanergy assets maintenances</description>
    <label>Asset Service Item</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Asset  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Purchase_Order_Item__r.Company_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inventory item does not belong to fresh life</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Item_Company__r.lookup_ID__c</field>
            <operation>equals</operation>
            <value>a19D00000026xHv</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Asset Service Items</relationshipLabel>
    <relationshipName>Asset_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Inventory_Uom__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Uom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Inventory UoM</description>
    <label>Inventory Uom</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Asset Service Items</relationshipLabel>
    <relationshipName>Asset_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>Purchase_Order_Item__r.Item_Description__c</formula>
    <label>Service Item_Description</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>lookup to purchase order item</description>
    <label>Purchase Order Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>Purchase_Order_Item__c.Inventory_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Purchase_Order_Item__c.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>$Source.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Asset Service Items</relationshipLabel>
    <relationshipName>Asset_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/Uom_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Uom_Conversion_Factor__c</fullName>
    <formula>Purchase_Order_Item__r.UOM_Conversion_Factor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Uom Conversion Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Asset_Service_Item__c/fields/vendor__c.field-meta.xml
<CustomField>
    <fullName>vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Service Items</relationshipLabel>
    <relationshipName>Asset_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>c2g__codaCompany__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_UoM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Inventory Items (Inventory UoM)</relationshipLabel>
    <relationshipName>Inventory_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/UoM_conversion_factor__c.field-meta.xml
<CustomField>
    <fullName>UoM_conversion_factor__c</fullName>
    <label>UoM conversion factor</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/Maintenance_Service_Items__c.object-meta.xml
<CustomObject>
    <description>Object to hold asset maintenance  p.o items</description>
    <label>Maintenance Service Item</label>
    <nameField>
        <displayFormat>SI-{0000000}</displayFormat>
        <label>Maintenance Service Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Asset_Maintenance_Task__c.field-meta.xml
<CustomField>
    <fullName>Asset_Maintenance_Task__c</fullName>
    <description>Lookup to Asset Maintenance task</description>
    <label>Asset Maintenance Task</label>
    <referenceTo>Asset_Maintenance_Task__c</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Asset_Service_Item__c.field-meta.xml
<CustomField>
    <fullName>Asset_Service_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Service Item</label>
    <referenceTo>Asset_Service_Item__c</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Purchase_Order_Item__r.Company_Name__c</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price__c</fullName>
    <label>Cost Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Inventory_UoM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>Purchase_Order_Item__r.Item_Description__c</formula>
    <label>Item Description</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Item</label>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>RecordType</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Unit_Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Item_Cost__c</fullName>
    <label>Unit Item Cost</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Uom_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Uom_Conversion_Factor__c</fullName>
    <formula>Purchase_Order_Item__r.UOM_Conversion_Factor__c</formula>
    <label>Uom Conversion Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Maintenance_Service_Items__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Maintenance Service Items</relationshipLabel>
    <relationshipName>Maintenance_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Inventory_Item__r.Item_Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_UOM__c.field-meta.xml
<CustomField>
    <fullName>Inventory_UOM__c</fullName>
    <formula>Inventory_Item__r.Inventory_UoM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory UOM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>The description of the Item</description>
    <inlineHelpText>The description of the Item. This is the name that will be displayed on Purchase Order Documents, etc</inlineHelpText>
    <label>Item Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/UOM_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>UOM_Conversion_Factor__c</fullName>
    <description>The factor by which the UOM is converted from purchase to inventory</description>
    <inlineHelpText>Purchase Quantity * UOM Conversion Factor = Inventory Quantity to receive</inlineHelpText>
    <label>UOM Conversion Factor</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/AddServiceItems.cls
public class AddServiceItems {
    
    //variables
    public List<Purchase_Order_Item__c> purchase_order_item {get;set;}
    public Asset_Maintenance_Task__c amt;
    public ApexPages.StandardController controller;
    Public Integer quantity{get;set;}
    public Maintenance_Service_Items__c del;
    Public Asset_Service_Item__c mainIt {get;set;}
    //Public Asset_Service_Item__c service {get;set;}
    
    
    public List<Maintenance_Service_Items__c> addattendeeList  {get;set;}
    public List<Maintenance_Service_Items__c> delattendeeList {get;set;}
    public List<Maintenance_Service_Items__c> attendeeList  {get;set;}
    public Integer totalCount {get;set;}
    public Integer rowIndex {get;set;}
    Public string specifications{get;set;}
    Public Decimal costPrice{get;set;}
    
    //Maintenance Service Items
    //Maintenance_Service_Items__c maintenance_service = new Maintenance_Service_Items__c();
    
    public List<Maintenance_Service_Items__c> delAttendees {get; set;} 
    
    //constructor
    Public AddServiceItems(ApexPages.StandardController standardController){
        
        amt = (Asset_Maintenance_Task__c)standardController.getRecord();
        
        amt = [SELECT NAME, ID ,Requesting_Company__c
               FROM Asset_Maintenance_Task__c 
               WHERE Id =: amt.Id
              ];  
        
        attendeeList = [SELECT Name,Asset_Maintenance_Task__c,Asset_Service_Item__c,Asset_Service_Item__r.Name,Cost_Price__c,Company__c,Inventory_Item__c,Inventory_UoM__c,
                        Item_Description__c,Purchase_Order_Item__c,Quantity__c,RecordType__c,Specification__c,Unit_Item_Cost__c,Uom_Conversion_Factor__c,
                        Vendor__c
                        FROM Maintenance_Service_Items__c 
                        WHERE Id =: amt.Id];
        
        //System.debug(amt.Requesting_Company__c);
        
        totalCount = attendeeList.size();
        
        delattendeeList = new List<Maintenance_Service_Items__c>();
        delattendees = new List<Maintenance_Service_Items__c>();
        
        //getAllPOitems();
        //getItems();
    }
    
    //adding a row
    public void addRow(){
        
         //System.debug('BEFORE --------> ' + attendeeList);
        //addattendeeList = new List<Maintenance_Service_Items__c>();
        attendeeList.add(new Maintenance_Service_Items__c());
       // System.debug('AFTER --------> '+attendeeList);
  
    }
    //saving the list of items
    public PageReference save(){
        system.debug('ATTENDEE KIST'+ attendeeList);
        
        attendeeList.add(new Maintenance_Service_Items__c(Asset_Maintenance_Task__c = amt.Id,Quantity__c = quantity));
        
        upsert attendeeList;
        delete delattendeeList;
        return (new ApexPages.StandardController(amt)).view();
        
    } 
    //Delete a row from the added items
    public void deleteRow(){
        
        rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        System.debug('rowbe deleted ' + rowIndex );
        System.debug('rowm to be deleted '+attendeeList[rowIndex]);
        del = attendeeList.remove(rowIndex);
        delattendeeList.add(del);
        
    }
    
    //method to autopopulate
    public void autopopulate(){
        
        //get the asset service item of the row
        for(Maintenance_Service_Items__c itm : attendeeList){
            
            //query to get theee details required
            mainIt = [SELECT Id, Name,Inventory_Uom__c,Inventory_Item__c,Purchase_Order_Item__c 
                      FROM Asset_Service_Item__c
                      WHERE Id =: itm.Asset_Service_Item__c
                      
                     ]; 
            //Asset_Service_Item__c mainIt = new Asset_Service_Item__c();
            //System.debug('Main it >>>>' + mainIt +'itm.Id' + itm.ID  );
            //attendeeList.add(new Maintenance_Service_Items__c(Asset_Maintenance_Task__c = amt.Id));
        }  
        
        
    }
    
}