sfSandBoxCode/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country</description>
    <inlineHelpText>Country</inlineHelpText>
    <label>Country</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <description>Date Available</description>
    <inlineHelpText>Date Available</inlineHelpText>
    <label>Date Available</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <inlineHelpText>Email</inlineHelpText>
    <label>Email</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Resume</description>
    <inlineHelpText>Resume</inlineHelpText>
    <label>Resume</label>
    <type>Url</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/Recruitment_Requisition__c.object-meta.xml
<CustomObject>
    <label>Recruitment Requisition</label>
    <nameField>
        <label>Recruitment Requisition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/REST_RecruitmentCandidate.cls
@RestResource(urlMapping='/recruitment_candidate')
global with sharing class REST_RecruitmentCandidate {

    @HttpPost
    global static Response saveCandidate(String jsonRequest) {
        Response response;
        try{
            
            System.debug(jsonRequest);
            
            List<Candidate> candidates = (List<Candidate>) System.JSON.deserialize(jsonRequest, List<Candidate>.class);  
                   
            if(candidates != null && candidates.size() > 0){
                
                List<Candidate__c> applications = new List<Candidate__c>();
                
                for(Candidate candidate : candidates){
                
                    Candidate__c candidateToSave = new Candidate__c(
                        Recruitment_Requisition__c = candidate.guid,
                        First_Name__c = candidate.firstName,
                        Last_Name__c = candidate.lastName,
                        Email__c = candidate.email,
                        Phone_Number__c = candidate.phoneNumber,
                        Date_Available__c = candidate.dateAvailable,
                        Country__c = candidate.country,
                        Resume__c = candidate.resume
                    );
                    
                    applications.add(candidateToSave);
                }
                
                
                if(applications.size() > 0){
                    
                    insert applications;
                    
                     response = new Response();
                     response.success = true;
                }
            }
            
        }catch(Exception e){
             response = new Response();
             response.success = false;
             response.message = e.getMessage();
        }
        
        return response;
    }
    
    global class Response{
       public boolean success;
       public String message;
       public List<Candidate> data;
    }
    
    global class Candidate {
               
        public long id;        
        public String guid;
        public String firstName;
        public String lastName;
        public String email;
        public Date dateAvailable;
        public String country;
        public String resume;
        public String phoneNumber;
    }
}