sfSandBoxCode/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Candidate_Status__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Status__c</fullName>
    <label>Candidate Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Notification</fullName>
            </value>
            <value>
                <fullName>Pending Offer Acception</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country</description>
    <inlineHelpText>Country</inlineHelpText>
    <label>Country</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <description>Date Available</description>
    <inlineHelpText>Date Available</inlineHelpText>
    <label>Date Available</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <inlineHelpText>Email</inlineHelpText>
    <label>Email</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Resume</description>
    <inlineHelpText>Resume</inlineHelpText>
    <label>Resume</label>
    <type>Url</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Store details of Sanergy Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_List</valueSetName>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Developments</fullName>
            </value>
            <value>
                <fullName>By-Product Sales</fullName>
            </value>
            <value>
                <fullName>By-Products Development</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Directors</fullName>
            </value>
            <value>
                <fullName>Engineering Operations</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Government Relations</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Insights and Innovations</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Logistics and Operations</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing and Branding</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Quality Health Safety &amp; Environment</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales and Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Line Manager</description>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Line_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/Employee_Role__c.object-meta.xml
<CustomObject>
    <label>Employee Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Sanergy_Department__c</referenceTo>
    <relationshipLabel>Employee Roles</relationshipLabel>
    <relationshipName>Employee_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Roles</relationshipLabel>
    <relationshipName>Employee_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Google Maps Required</description>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/Recruitment_Requisition__c.object-meta.xml
<CustomObject>
    <label>Recruitment Requisition</label>
    <nameField>
        <label>Recruitment Requisition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <formula>Proposed_Employee_required_Date__c + ( ( 365 / 12 ) * Duration_of_Fixed_term_Contract_Months__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Duration_of_Fixed_term_Contract_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_of_Fixed_term_Contract_Months__c</fullName>
    <label>Duration of Fixed term Contract (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Recruitment Requisitions</relationshipLabel>
    <relationshipName>Recruitment_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Recruitment Requisitions (Line Manager)</relationshipLabel>
    <relationshipName>Recruitment_Requisitions4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sameer</fullName>
                <default>true</default>
                <label>Sameer</label>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mathare</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Proposed_Employee_required_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Employee_required_Date__c</fullName>
    <label>Proposed Employee required Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/Sanergy_Department__c.object-meta.xml
<CustomObject>
    <description>Sanergy Departments</description>
    <label>Sanergy Department</label>
    <nameField>
        <label>Sanergy Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sanergy Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Department__c/recordTypes/Sanergy.recordType-meta.xml
<RecordType>
    <fullName>Sanergy</fullName>
    <active>true</active>
    <label>Sanergy</label>
</RecordType>

sfSandBoxCode/force-app/main/default/classes/SendEmailToCandidateAfterApproval.cls
public class SendEmailToCandidateAfterApproval {
    
    //create standard controller
    private ApexPages.StandardController controller;
    
    //Candidate
    public Candidate__c candidate {get; set;}    
    private List<Candidate__c> candidates {get; set;}
    
    // Constructor
    public SendEmailToCandidateAfterApproval(ApexPages.StandardController controller){               
        this.controller = controller;                
        candidate = (Candidate__c)controller.getRecord();
		candidate = [SELECT Id,Name,Recruitment_Requisition__c,First_Name__c,Last_Name__c,
                     Phone_Number__c,Email__c,Date_Available__c,Candidate_Status__c,
                     Country__c,Resume__c,Recruitment_Requisition__r.Employee_Role__r.Name,
                     Recruitment_Requisition__r.Employee_Role__r.Department__r.Name,
                     Recruitment_Requisition__r.Employee_Role__r.Line_Manager__r.Name,
                     Recruitment_Requisition__r.Proposed_Employee_required_Date__c,
                     Recruitment_Requisition__r.Contract_End_Date__c,
                     Recruitment_Requisition__r.Duration_of_Fixed_term_Contract_Months__c,
					 Recruitment_Requisition__r.Location__c                     
                     FROM Candidate__c
                     WHERE Id =: candidate.Id];       
            
        System.debug('CANDIDATE: ' + candidate);
    }

	// Get Candidate
    public List<Candidate__c> getItems() {
        
        candidates= new List<Candidate__c>();
        
        if(candidate.Candidate_Status__c=='Pending Notification'){
            
            List<Candidate__c> lineItems = [SELECT Id,Name,	Recruitment_Requisition__c,First_Name__c,Last_Name__c,
                                            Phone_Number__c,Email__c,Date_Available__c,Candidate_Status__c,
                                            Country__c,Resume__c,Recruitment_Requisition__r.Employee_Role__r.Name,
                                            Recruitment_Requisition__r.Employee_Role__r.Department__r.Name,
                                            Recruitment_Requisition__r.Employee_Role__r.Line_Manager__r.Name,
                                            Recruitment_Requisition__r.Proposed_Employee_required_Date__c,
                                            Recruitment_Requisition__r.Contract_End_Date__c,
                                            Recruitment_Requisition__r.Duration_of_Fixed_term_Contract_Months__c,
                                            Recruitment_Requisition__r.Location__c
                                          	FROM Candidate__c
                                            WHERE Id =: candidate.Id];
            
            for(Candidate__c lineItem : lineItems){
                candidates.add(lineItem);
            }
        }
        return candidates;
    }
    
    //Create Email Notification to notify candidate
    public PageReference createEmailNotification(){
        
        // List of emails to send
  		List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
        
        if(candidate.Email__c != null && candidate.Candidate_Status__c=='Pending Notification'){
            // Create a new Email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
            // Send email to recipient
            List<String> sendTo = new List<String>();
            sendTo.add(candidate.Email__c);
            mail.setToAddresses(sendTo);
            
            // Set the email sender
            mail.setReplyTo('info@saner.gy');
            mail.setSenderDisplayName('SANERGY'); 
            
            // Set people to be BCCed
            //List<String> bccTo = new List<String>();
            //bccTo.add('michael.kamau@saner.gy');
            //mail.setBccAddresses(bccTo);
            
            //flag to false to stop inserting activity history
            mail.setSaveAsActivity(false);             
            
            // Create the email body
            mail.setSubject('OFFER LETTER');
            String body = '<p>Dear ' + candidate.First_Name__c + ' ' + candidate.Last_Name__c + ',</p>';           
            body += '<p>At Sanergy, we bring on teammates who deeply share our commitment to transformative change in the communities in which';
            body += 'we work,and to living out our values: Relentless pursuit of excellence, Pragmatic innovation, Collaboration among our'; 
            body += 'team and customers,Providing enduring value for our customers, and Authenticity in all that we do.</p>';
            body += '<p>We think you are exactly that type of teammate.</p>';
            body += '<p>We are excited to offer you the position of <b>' + candidate.Recruitment_Requisition__r.Employee_Role__r.Name + '</b>.';
            body += 'You will find detailed information about the role below, but first, we want to highlight some key benefits of working at Sanergy.</p>';
            body += 'You will hold key responsibilities, critical for the growth and success of Sanergy. You will be able to leverage your current';
            body += 'strengths and be challenged to develop new skills. You will have opportunities to advance your technical and leadership skills.';
            body += 'You will be surrounded by 250 teammates who are innovative, passionate, and results-driven. You will get to tackle some of the';
            body += 'most pressing challenges of our time as we build healthy, prosperous communities for everyone, forever.';
            body += '<p><b>Role: </b>' + candidate.Recruitment_Requisition__r.Employee_Role__r.Name + '</p>';
            body += '<p><b>Team: </b>' + candidate.Recruitment_Requisition__r.Employee_Role__r.Department__r.Name + '</p>';
            body += '<p><b>Reporting to: </b>' + candidate.Recruitment_Requisition__r.Employee_Role__r.Line_Manager__r.Name + '</p>';
            body += '<p><b>Term: </b>Your probationary contract will commence on ' + candidate.Recruitment_Requisition__r.Proposed_Employee_required_Date__c;
            body += 'and end on ' + candidate.Recruitment_Requisition__r.Contract_End_Date__c + '; and upon successful completion of probation, you will be issued with ';
            body += 'a <b>' + candidate.Recruitment_Requisition__r.Duration_of_Fixed_term_Contract_Months__c + '</b> months contract.';
            body += '<p><b>Place of Work: </b>Your primary place of work is <b>' + candidate.Recruitment_Requisition__r.Location__c + '</b>, but you may need to '; 
            body += 'report to work anywhere in <b>[COUNTY(ies)]</b> when required.</p>';
            body += '<p><b>Benefits: </b> Group personal accident cover and group life, Medical, Pension </p>';
            body += '<p><b>Paid Leave: </b>For every 12-month period, you will have 21 working days of paid leave, 7 working days of paid sick ';
            body += 'leave and 7 working days of sick leave with half pay, 3 working days of exam leave, 90 calendar days of maternity and ';
            body += '14 calendar days of paternity leave</p>';
            body += '<p>A detailed job description is attached to this letter for your review.This offer is contingent upon you submitting '; 
            body += 'the required documentation and signing a formal contract of employment.</p>';
            body += '<p>Join us, </p><br/>';
            body += '<p style="font-weight: bold; font-style: italic;">SANERGY</p>';
            body += '<p style="font-weight: bold; font-style: italic;"><sub>Building healthy,prosperous communities</sub></p>';      		
            mail.setHtmlBody(body);
            
            //Add email to the list
            mails.add(mail);            

        }
        // Send email
        Messaging.sendEmail(mails);
        
        //Update Candidate Status
        candidate.Candidate_Status__c = 'Pending Offer Acception';
        UPDATE candidate;
        
        return new PageReference('/'+ candidate.Id);
    }    
    
}