sfSandBoxCode/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Candidate_Rating__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Rating__c</fullName>
    <description>Candidate rating on a score of 1-5</description>
    <inlineHelpText>Candidate rating on a score of 1-5</inlineHelpText>
    <label>Candidate Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Candidate_Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Star_Rating__c</fullName>
    <formula>IMAGE( IF( ISPICKVAL( Candidate_Rating__c , &#39;1&#39;) , &quot;/img/samples/stars_100.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;2&#39;) , &quot;/img/samples/stars_200.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;3&#39;) , &quot;/img/samples/stars_300.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;4&#39;) , &quot;/img/samples/stars_400.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;5&#39;) , &quot;/img/samples/stars_500.gif&quot;, &quot;/img/samples/stars_100.gif&quot;))))) , &quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Candidate Star Rating</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <description>Date Available</description>
    <inlineHelpText>Date Available</inlineHelpText>
    <label>Date Available</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/Candidate_Evaluation_Stage__c.object-meta.xml
<CustomObject>
    <label>Candidate Evaluation Stage</label>
    <nameField>
        <displayFormat>CES-{0000000}</displayFormat>
        <label>Candidate Evaluation Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Evaluation Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Candidate Evaluation Stages</relationshipLabel>
    <relationshipName>Candidate_Evaluation_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Candidate_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate Evaluation</label>
    <referenceTo>Candidate_Requisition__c</referenceTo>
    <relationshipLabel>Candidate Evaluation Stages</relationshipLabel>
    <relationshipName>Candidate_Evaluation_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Candidate_Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Star_Rating__c</fullName>
    <formula>IMAGE( IF( ISPICKVAL( Candidate_Rating__c , &#39;1&#39;) , &quot;/img/samples/stars_100.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;2&#39;) , &quot;/img/samples/stars_200.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;3&#39;) , &quot;/img/samples/stars_300.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;4&#39;) , &quot;/img/samples/stars_400.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;5&#39;) , &quot;/img/samples/stars_500.gif&quot;, &quot;/img/samples/stars_100.gif&quot;))))) , &quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Candidate Star Rating</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <label>Date Available</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Evaluation_Status__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Status__c</fullName>
    <label>Evaluation Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/In_Offer__c.field-meta.xml
<CustomField>
    <fullName>In_Offer__c</fullName>
    <label>In Offer</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/In_Review__c.field-meta.xml
<CustomField>
    <fullName>In_Review__c</fullName>
    <label>In Review</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Evaluation_Stage__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipLabel>Candidate Evaluation Stages</relationshipLabel>
    <relationshipName>Candidate_Evaluation_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/Candidate_Requisition__c.object-meta.xml
<CustomObject>
    <label>Candidate Evaluation</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Candidate Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Candidate_Rating__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Rating__c</fullName>
    <label>Candidate Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Candidate_Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Star_Rating__c</fullName>
    <formula>IMAGE( IF( ISPICKVAL( Candidate_Rating__c , &#39;1&#39;) , &quot;/img/samples/stars_100.gif&quot;, 
IF( ISPICKVAL( Candidate_Rating__c , &#39;2&#39;) , &quot;/img/samples/stars_200.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;3&#39;) , &quot;/img/samples/stars_300.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;4&#39;) , &quot;/img/samples/stars_400.gif&quot;,
IF( ISPICKVAL( Candidate_Rating__c , &#39;5&#39;) , &quot;/img/samples/stars_500.gif&quot;, &quot;/img/samples/stars_100.gif&quot;))))) , &quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Candidate Star Rating</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/In_Offer__c.field-meta.xml
<CustomField>
    <fullName>In_Offer__c</fullName>
    <label>In Offer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents Check</fullName>
            </value>
            <value>
                <fullName>References Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/In_Review__c.field-meta.xml
<CustomField>
    <fullName>In_Review__c</fullName>
    <label>In Review</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Longlisted</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Phone Interview</fullName>
            </value>
            <value>
                <fullName>Face to Face Interview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Recruitment_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruitment Requisition</label>
    <referenceTo>Recruitment_Requisition__c</referenceTo>
    <relationshipName>Candidate_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Evaluation Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Longlisted</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Offer</fullName>
                <isActive>false</isActive>
                <label>In Offer</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Candidate_Requisition__c/fields/Years_Of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_Of_Experience__c</fullName>
    <label>Years Of Experience</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/Recruitment_Requisition__c.object-meta.xml
<CustomObject>
    <label>Recruitment Requisition</label>
    <nameField>
        <label>Recruitment Requisition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/classes/CandidateEvaluation.cls
public class CandidateEvaluation {
    
    //Create standard controller
    private ApexPages.StandardController controller;
    
    //Candidate Evaluation
    public Candidate_Requisition__c candidateEvaluation {get; set;} 
    
    //Candidate Evaluation Stage
    public Candidate_Evaluation_Stage__c candidateEvaluationStage {get; set;}
    public List<CandidateEvaluationStage> candidateEvaluationStageList {get; set;}     
    
    // Constructor
    public CandidateEvaluation(ApexPages.StandardController controller){               
        this.controller = controller;
        candidateEvaluation = (Candidate_Requisition__c)controller.getRecord();
        candidateEvaluationStage = new Candidate_Evaluation_Stage__c();
        getCandidateEvaluationStages();
        getAllEvaluationStages();        
    }
    
    //Update Candidate Evaluation
    public PageReference updateCandidateEvaluation(){
        
        //Create Instance of Candidate Requisition
        candidateEvaluation.Recruitment_Requisition__c = candidateEvaluation.Recruitment_Requisition__c;
        candidateEvaluation.Candidate_Rating__c = candidateEvaluation.Candidate_Rating__c;
        candidateEvaluation.Date_Available__c = candidateEvaluation.Date_Available__c;
        candidateEvaluation.Years_Of_Experience__c = candidateEvaluation.Years_Of_Experience__c;
        candidateEvaluation.Status__c = candidateEvaluation.Status__c;
        candidateEvaluation.In_Review__c = candidateEvaluation.In_Review__c;
        candidateEvaluation.In_Offer__c = candidateEvaluation.In_Offer__c;
        candidateEvaluation.Comments__c = candidateEvaluation.Comments__c;
        UPDATE candidateEvaluation;
        
        return new PageReference('/'+ candidateEvaluation.Id);
    }
    
    // Get Candidate Evaluation Stage
    public List<CandidateEvaluationStage> getCandidateEvaluationStages(){
        System.debug('candidateEvaluation.Name: '+ candidateEvaluation.Name);
        
        if(candidateEvaluation.Name != null){
            
            candidateEvaluationStageList = new List<CandidateEvaluationStage>();
            
            List<Candidate_Evaluation_Stage__c> lineItems = [SELECT Id,Name,Recruitment_Requisition__c,Recruitment_Requisition__r.Name,
                                                             Evaluation_Status__c,Candidate_Rating__c,Candidate_Star_Rating__c,Date_Available__c,
                                                             In_Offer__c,In_Review__c,Years_Of_Experience__c,Candidate__c,Candidate__r.Name,
                                                             Comments__c
                                                             FROM Candidate_Evaluation_Stage__c 
                                                             WHERE Candidate_Evaluation__c =: candidateEvaluation.Id
                                                             ORDER BY Name ASC];
            
            for(Candidate_Evaluation_Stage__c lineItem : lineItems){                
                //Add all records to the list
                candidateEvaluationStageList.add(new CandidateEvaluationStage(lineItem));
            }
            System.debug('CANDIDATE EVALUATION STAGE: ' + candidateEvaluationStageList);
        }
        return candidateEvaluationStageList;
    }
    
    public PageReference getAllEvaluationStages() {
        getCandidateEvaluationStages();     
        return null;
    }    
    
    // Candidate Evaluation Stage wrapper class
    public class CandidateEvaluationStage{        
        public Candidate_Evaluation_Stage__c evaluationStage {get; set;}
        
        //Constructor
        public CandidateEvaluationStage(Candidate_Evaluation_Stage__c stage) {
            evaluationStage = stage;
        }
    }    
}