sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/EPR_Payable_Item__c.object-meta.xml
<CustomObject>
    <label>EPR Payable Item</label>
    <nameField>
        <displayFormat>EPR ITEM-{0000}</displayFormat>
        <label>EPR Payable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPR Payable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (Dim 3)</relationshipLabel>
    <relationshipName>EPR_Payable_Items4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/Fleet_Request__c.object-meta.xml
<CustomObject>
    <label>Fleet Request</label>
    <nameField>
        <displayFormat>Fleet-{0000}</displayFormat>
        <label>Fleet Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Fleet Requests</relationshipLabel>
    <relationshipName>Fleet_Requests3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Request__c/fields/Requesting_Employee__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Fleet Requests</relationshipLabel>
    <relationshipName>Fleet_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/Fleet_Requests__c.object-meta.xml
<CustomObject>
    <description>Trip legs for fleet requests</description>
    <label>Trip Leg</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Trip Leg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trip Legs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <description>Date of Departure</description>
    <label>Departure Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request__c</fullName>
    <label>Fleet Request</label>
    <referenceTo>Fleet_Request__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Fleet_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Request_Status__c</fullName>
    <label>Fleet Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Open</fullName>
                <default>true</default>
                <label>Request Open</label>
            </value>
            <value>
                <fullName>Quote in Progress</fullName>
            </value>
            <value>
                <fullName>Pending TL Approval</fullName>
            </value>
            <value>
                <fullName>TL Approved</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Trip Completed</fullName>
            </value>
            <value>
                <fullName>Trip Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Grant_Funding_Availale_Dim_4__c.field-meta.xml
<CustomField>
    <fullName>Grant_Funding_Availale_Dim_4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grant Funding Availale (Dim 4)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Location_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Dim_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location (Dim 2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Fleet_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Other_Destination__c.field-meta.xml
<CustomField>
    <fullName>Other_Destination__c</fullName>
    <label>Other Destination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Other_Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Other_Pickup_Location__c</fullName>
    <label>Other Pickup Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilimani</fullName>
            </value>
            <value>
                <fullName>Kinanie</fullName>
            </value>
            <value>
                <fullName>Mukuru</fullName>
            </value>
            <value>
                <fullName>Nairobi</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Recommended_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sanergy Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Recommended_Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Requesting_Department</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Employee__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Requesting_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sanergy_Asset__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vehicles</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sanergy_Asset__c</referenceTo>
    <relationshipName>Fleet_Legs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/Sanergy_Asset__c.object-meta.xml
<CustomObject>
    <description>Sanergy Assets</description>
    <label>Sanergy Asset</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Sanergy Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanergy Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <description>Vehicle registration number</description>
    <inlineHelpText>Vehicle registration number</inlineHelpText>
    <label>Registration Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Sanergy_Asset__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <description>Motor Vehicle assets</description>
    <label>Vehicle</label>
</RecordType>

sfSandBoxCode/force-app/main/default/classes/ListVehicleTripSchedules.cls
public class ListVehicleTripSchedules{
        
    //create standard controller
    private ApexPages.StandardController standardController;
    
    //Initialize object
    Fleet_Requests__c fr=null;
    
    //initialize list of vehicles
    List<Sanergy_Asset__c> vehicles=[SELECT Registration_Number__c,name,id
                                     FROM Sanergy_Asset__c
                                     WHERE RecordType.name='Vehicles'];
    String selectedVehice=null;

    
    public List<LegsWrapper> tripLegs{get; set;}
    
    //constructor
    public ListVehicleTripSchedules(ApexPages.StandardController controller){
        this.standardController=controller;
        fr=(Fleet_Requests__c) standardController.getRecord();
    }
    
    public List<SelectOption> getVehicles() {
        List<SelectOption> options = new List<SelectOption>();
        
        for(Sanergy_Asset__c vehicle: vehicles){
            options.add(new SelectOption(vehicle.id,vehicle.Registration_Number__c));
        }
        return options;
    }
    
    public String getSelectedVehice() {
        return this.selectedVehice;
    }


    public void setSelectedVehice(String selectedVehice) {
        this.selectedVehice= selectedVehice;
    }


   public PageReference processSelected() {
        tripLegs= new List<LegsWrapper>();
        for(Fleet_Requests__c r: [SELECT Id,Grant_Funding_Availale_Dim_4__c,Dim_3__c,
                                  Location_Dim_2__c,Fleet_Request__r.Requesting_Department__c, Recommended_Vendor__r.name, 
                                  Fleet_Request_Status__c, Name, Fleet_Request__r.name,Vehicle__r.Registration_Number__c,
                                  Fleet_Request__r.Requesting_Employee__r.name, Pickup_Location__c, Other_Pickup_Location__c,
                                  Destination__c, Other_Destination__c, Departure_Date__c, Departure_Time__c,
                                  Reason_for_Trip__c, Total_Actual_Cost__c, EPR_Payable_Item__c
                                  FROM Fleet_Requests__c
                                  WHERE Vehicle__c =:this.selectedVehice
                                  AND Departure_Date__c >= :Date.today()
                                  ]) {
            
          tripLegs.add(new LegsWrapper(r));
            
        }
        return null;
    }
    
    public PageReference selectVehicle() {
        if(this.selectedVehice!=null){
            this.fr.Vehicle__c =this.selectedVehice;
            update this.fr;
        }
         return new PageReference('/' + this.fr.Id);
    }
    
   

    // This is our wrapper/container class. A container class is a class, a data structure, or an abstract data type whose instances are collections of other objects. In this example a wrapper class contains both the standard salesforce object Contact and a Boolean value
    public class LegsWrapper{
        public Fleet_Requests__c tripLegs {get; set;}
        public Boolean selected {get; set;}
        public String departure{get; set;}
        public String destination{get; set;}
        public String dateFrom{get; set;}
        

        //This is the contructor method. When we create a new cContact object we pass a Contact that is set to the con property. We also set the selected value to false
        public LegsWrapper(Fleet_Requests__c legs) {
            tripLegs= legs;
            selected = true;
            departure= legs.Pickup_Location__c!='Other'? legs.Pickup_Location__c : legs.Other_Pickup_Location__c;
            destination= legs.Destination__c!='Other'? legs.Destination__c: legs.Other_Destination__c;
            dateFrom=String.valueOf(legs.Departure_Date__c)+' : '+String.valueOf(legs.Departure_Time__c);
        }
    }

}