sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Created&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Contract Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Last_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Last_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last Invoice</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Payment_Variance__c.field-meta.xml
<CustomField>
    <fullName>Payment_Variance__c</fullName>
    <label>Payment Variance</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Purchase_Order_Item__c.Vendor__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Accepted__c</fullName>
    <label>Quantity Accepted</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <label>Quantity Requested</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Receipt_Variance__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Variance__c</fullName>
    <label>Receipt Variance</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>All items Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Items Partially Received</fullName>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Unit_Gross_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Gross_Price__c</fullName>
    <formula>Unit_Net_Price__c +  VAT_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Gross Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/VI_Avg_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>VI_Avg_Unit_Price__c</fullName>
    <description>The Avg Price of the Reconciled Amount Paid and the Reconciled Total Qty</description>
    <formula>IF(VI_Recon_Total__c * VI_Recon_Qty_s__c =  0  , 0,VI_Recon_Total__c  /  VI_Recon_Qty_s__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>IF(VI_Recon_Total__c * VI_Recon_Qty_s__c =  0  , 0,VI_Recon_Total__c  /  VI_Recon_Qty_s__c)</inlineHelpText>
    <label>VI Avg Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/Vendor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Vendor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Expected_Total__c.field-meta.xml
<CustomField>
    <fullName>Expected_Total__c</fullName>
    <label>Expected Total</label>
    <summarizedField>Vendor_Invoice_Purchase_Order_Line_Item__c.Total_Cost__c</summarizedField>
    <summaryForeignKey>Vendor_Invoice_Purchase_Order_Line_Item__c.Vendor_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Payment_Variance__c.field-meta.xml
<CustomField>
    <fullName>Payment_Variance__c</fullName>
    <label>Payment Variance</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Receipt_Variance__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Variance__c</fullName>
    <label>Receipt Variance</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Reconciled_Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Reconciled_Invoice_Total__c</fullName>
    <label>Reconciled Invoice Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Reconciled_Received_Value__c.field-meta.xml
<CustomField>
    <fullName>Reconciled_Received_Value__c</fullName>
    <label>Reconciled Total Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Vendor Invoice stages</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Items Received</fullName>
            </value>
            <value>
                <fullName>Pin Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Sum_VI_Items_Received_Value__c.field-meta.xml
<CustomField>
    <fullName>Sum_VI_Items_Received_Value__c</fullName>
    <label>Sum VI Items Received Value</label>
    <summarizedField>Vendor_Invoice_Items__c.Receive_Quantity__c</summarizedField>
    <summaryForeignKey>Vendor_Invoice_Items__c.Vendor_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <summarizedField>Vendor_Invoice_Payment__c.Payment_Cost__c</summarizedField>
    <summaryForeignKey>Vendor_Invoice_Payment__c.Vendor_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/Vendor_Invoice_Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Purchase Order Line Item</label>
    <nameField>
        <displayFormat>VIPOLI-{0000000000}</displayFormat>
        <label>VI PO Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Item_Received_Total__c.field-meta.xml
<CustomField>
    <fullName>Item_Received_Total__c</fullName>
    <label>Item Received Total</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Item_Total__c.field-meta.xml
<CustomField>
    <fullName>Item_Total__c</fullName>
    <label>Item Total</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Item_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Unit_Cost__c</fullName>
    <label>Reconciled Item Unit Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Item_Vat__c.field-meta.xml
<CustomField>
    <fullName>Item_Vat__c</fullName>
    <label>Reconciled Item Vat</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Purchase_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line_Item__c</fullName>
    <label>PO Line Item</label>
    <referenceTo>Purchase_Order_Line_Item__c</referenceTo>
    <relationshipLabel>VIPO Line Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Reconciled_Item_Quantity_Received__c.field-meta.xml
<CustomField>
    <fullName>Reconciled_Item_Quantity_Received__c</fullName>
    <label>Reconciled Item Quantity Received</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Requested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Requested_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>AP Matched</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Purchase_Order_Line_Item__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/POLIMapping.cls
public class POLIMapping {
/*    public ApexPages.StandardController standardController;
    public Vendor_Invoice__c vi{get;set;}
    public Integer rowCount{get;set;}
//    public List<ItemWrapper>items{get;set;}
    public List<PoliWrapper>poItems{get;set;}
    public List<Vendor_Invoice_Purchase_Order_Line_Item__c> VIPOitems{get;set;}
    public Purchase_Order_Line_Item__c poli{get;set;}
    public List<Purchase_Order_Line_Item__c> poliList;
    
    public POLIMapping(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        // ApexPages.currentPage().getParameters().get('id')
        // get the vi  items of the current vendor invoice
        this.vi = (Vendor_Invoice__c)standardController.getRecord();
        this.vi = [SELECT ID,Name,Expected_Total__c,Receipt_Variance__c,Payment_Variance__c,Invoice_Total__c,
                   Total_Payments__c,Reconciled_Invoice_Total__c,Reconciled_Received_Value__c,Sum_VI_Items_Received_Value__c
                   FROM Vendor_Invoice__c
                   WHERE id =: this.vi.Id
                  ];
        system.debug('vENDOR iNVOICE' + this.vi);
     //  getItems();
        
        Rows();
        getpoItems();
        
    }

    //get the list of vendor invoice purchase order line items
 public List<Vendor_Invoice_Purchase_Order_Line_Item__c> getItems(){
        
      //  items = new List<ItemWrapper>();
        
        VIPOitems = [SELECT ID,Name,Item_Received_Total__c,
                     Item_Total__c,Item_Unit_Cost__c,Item_Vat__c,
                     Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Name,
                     Purchase_Order_Line_Item__r.Quantity_Requested__c,
                     Purchase_Order_Line_Item__r.Quantity_Accepted__c,
                     Purchase_Order_Line_Item__c,Requested_Quantity__c,
                     Status__c,Total_Cost__c,Vendor_Invoice__c,
                     Reconciled_Item_Quantity_Received__c,
                     Last_Invoice__c,Payment_Variance__c,Receipt_Variance__c
                     FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                     WHERE Vendor_Invoice__c =: this.vi.Id
                    ];
         
        return  VIPOitems;   
    }

    //get the purchase order line items that hav ebeen selected for reconciliation 
    public List<PoliWrapper> getpoItems(){
        
              VIPOitems = [SELECT ID,Name,Item_Received_Total__c,
                     Item_Total__c,Item_Unit_Cost__c,Item_Vat__c,
                     Purchase_Order_Line_Item__r.Purchase_Order_Item__r.Name,
                     Purchase_Order_Line_Item__r.Quantity_Requested__c,
                     Purchase_Order_Line_Item__r.Quantity_Accepted__c,
                     Purchase_Order_Line_Item__c,Requested_Quantity__c,
                     Status__c,Total_Cost__c,Vendor_Invoice__c,
                     Reconciled_Item_Quantity_Received__c,
                     Last_Invoice__c,Payment_Variance__c,Receipt_Variance__c
                     FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                     WHERE Vendor_Invoice__c =: this.vi.Id
                    ];
        
        List<String> poliIds = new List<String>();

              for(Vendor_Invoice_Purchase_Order_Line_Item__c vendorInvoice: VIPOitems){
                poliIds.add(vendorInvoice.Purchase_Order_Line_Item__c);
            }
      
        poItems = new List<PoliWrapper>();
        
       // for(Vendor_Invoice_Purchase_Order_Line_Item__c item: VIPOitems ){  
            poliList = [SELECT ID,Name,Last_Invoice__c,VI_Avg_Unit_Price__c,Item__c,
                        Unit_Gross_Price__c,Payment_Variance__c,Receipt_Variance__c,Purchase_Order_Item__r.Name,
                        Quantity_Requested__c,Quantity_Accepted__c,Po_line_Receipt_Status__c,Status__c	
                        FROM Purchase_Order_Line_Item__c 
                        WHERE ID IN : poliIds
                        AND (Last_Invoice__c = TRUE
                             AND Status__c != 'Closed')
                       ]; 
            
            for(Purchase_Order_Line_Item__c lst:poliList){
                //PoliWrapper wrap = new PoliWrapper(lst);
                //poItems.add(wrap);
                poItems.add(new PoliWrapper(lst));    
            }
        //} 
        
        return poItems;
    }
    
    // Get the number of Rows 
    public Integer Rows(){
        AggregateResult [] Results = [SELECT COUNT(ID)no
                                      FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                                      WHERE Vendor_Invoice__c =: this.vi.Id
                                     ];
        rowCount = integer.valueOf(Results[0].get('no'));
        return rowCount;
    }
    //save method
    public PageReference save(){
        upsert vi;       
       // upsert VIPOitems;
      System.debug('RETERTERTETETETETE' +poliList);

        
        upsert poliList; 
        
     
      //  getpoItems();
     System.debug('RETERTERTETETETETE' +poliList);

        return Page.POLIMapping;
        //  return (new ApexPages.StandardController(vi)).view();
        //return new PageReference('/' + vi.Id);
        
    }
    
    
    public void ReconcilePOLI(){
                //getpoItems();
        //getpoItems();
        for(PoliWrapper poItm: getpoItems()){
             poliList = [SELECT ID,Name,Last_Invoice__c,VI_Avg_Unit_Price__c,Item__c,
                        Unit_Gross_Price__c,Payment_Variance__c,Receipt_Variance__c,Purchase_Order_Item__r.Name,
                        Quantity_Requested__c,Quantity_Accepted__c,Po_line_Receipt_Status__c,Status__c	
                        FROM Purchase_Order_Line_Item__c 
                        WHERE ID =: poItm.polineItems.id
                       ];
            
            
            upsert poliList; 
            //System.debug('RETERTERTETETETETE' + poItm.paymentVariance2);
              //  poliList.get(0).Payment_Variance__c = poItm.paymentVariance2;
          
        }
        System.debug('qwwqeqweweqewqe ' +poliList);

       // system.debug('polist'+poliList );
        
        //return (new ApexPages.StandardController(vi)).view(); 
    }
    
    //wrapper class
  /*  public PageReference CalculateTotals(){
        
        VIPOitems = [SELECT ID,Name,Item_Received_Total__c,
                     Item_Total__c,Item_Unit_Cost__c,Item_Vat__c,
                     Purchase_Order_Line_Item__c,Requested_Quantity__c,
                     Reconciled_Line_Total__c,
                     Status__c,Total_Cost__c,Vendor_Invoice__c
                     FROM Vendor_Invoice_Purchase_Order_Line_Item__c
                     WHERE Vendor_Invoice__c =: vi.Id
                    ];       
        
        for (Vendor_Invoice_Purchase_Order_Line_Item__c item : VIPOitems){
            for(ItemWrapper itm : getItems()){
                item.Item_Total__c = (itm.vipoli.Item_Unit_Cost__c);
            }
            ItemWrapper wrapper = new ItemWrapper(item);
            items.add(wrapper);
        }
        
        //getItems();
        return null;
        
    }
    //Vendor Invoice Purchase Order Line Items Wrapper Class 
   public class ItemWrapper{
        public Vendor_Invoice_Purchase_Order_Line_Item__c vipoli{get;set;}
        public Boolean selected {get; set;}
        
        public ItemWrapper(Vendor_Invoice_Purchase_Order_Line_Item__c vipolitems){
            selected = false;
            vipoli = vipolitems;
        }
        
    }*/
    //Purcahse Order line item wrapper class
  /*  public class PoliWrapper{
        public Purchase_Order_Line_Item__c polineItems{get;set;}
     //  public String paymentVariance2 {get;set;}
       // public String receiptVariance2 {get;set;}
        
        public PoliWrapper(Purchase_Order_Line_Item__c poL){
            polineItems =  poL;
        }
    }
    */
}