sfSandBoxCode/force-app/main/default/objects/Employee_Role__c/Employee_Role__c.object-meta.xml
<CustomObject>
    <label>Employee Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/Fleet_Requests__c.object-meta.xml
<CustomObject>
    <description>Trip legs for fleet requests</description>
    <label>Trip Leg</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Trip Leg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trip Legs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Fleet_Requests__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Requesting_Department</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/Recruitment_Requisition__c.object-meta.xml
<CustomObject>
    <label>Recruitment Requisition</label>
    <nameField>
        <label>Recruitment Requisition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Employee_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Employee_Role__c</referenceTo>
    <relationshipLabel>Recruitment Requisitions</relationshipLabel>
    <relationshipName>Recruitment_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Recruitment_Requisition__c/fields/Requesting_Department__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Teamlead__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Recruitment Requisitions</relationshipLabel>
    <relationshipName>Recruitment_Requisitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_RecruitmentRequisition.cls
@RestResource(urlMapping='/recruitment_requisition')
global with sharing class REST_RecruitmentRequisition {

    @HttpGet
    global static List<Requisition> getRequisitions() {
    
        List<Requisition> requisitions = new List<Requisition>();
        
        List<Recruitment_Requisition__c> sfRequisitions = [SELECT Id, Name FROM Recruitment_Requisition__c];
        
        if(sfRequisitions != null && sfRequisitions.size()> 0){
            
            for(Recruitment_Requisition__c sfRequisition : sfRequisitions){
            
                Requisition req = new Requisition();                
                req.guid = sfRequisition.Id;
                req.name = sfRequisition.Name;
            
                requisitions.add(req);
            }
        }
        
        return requisitions;
    }
    
    @HttpPost
    global static Response getRequisition(String jobId) {
        Response response = new Response();
        
        try{
            
            if(jobId != null && jobId.length() > 0){
                
                List<Recruitment_Requisition__c> sfRequisitions = [SELECT Id, Name, Employee_Role__c, Requesting_Department__c,
                                                                   Employee_Role__r.Name, Requesting_Department__r.Name
                                                                   FROM Recruitment_Requisition__c
                                                                   WHERE Id = :jobId
                                                                  ];

                List<Requisition> requisitions = new List<Requisition>();
                
                if(sfRequisitions != null && sfRequisitions.size()> 0){
                    
                    for(Recruitment_Requisition__c sfRequisition : sfRequisitions){
                        
                        Requisition req = new Requisition();                
                        req.guid = sfRequisition.Id;
                        req.name = sfRequisition.Name;
                        req.role = sfRequisition.Employee_Role__r.Name;
                        req.department = sfRequisition.Requesting_Department__r.Name;
                        
                        requisitions.add(req);
                    }
                }
                response.success = true;
            	response.data = requisitions;
            }
        } catch(Exception e){
            response.success = false;
            response.message = e.getMessage();
        }
        return response;
    }
        
    global class Response {
       public boolean success;
       public String message;
       public List<Requisition> data;
    }
    
    global class Requisition {
        public long id;        
        public String guid;
        public String name;
        public String role;
        public String department;
    }
}