sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/Missed_Collection_Reason__c.object-meta.xml
<CustomObject>
    <label>Missed Collection Reason</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collection Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Code_Number__c.field-meta.xml
<CustomField>
    <fullName>Code_Number__c</fullName>
    <label>Code Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Collect__c.field-meta.xml
<CustomField>
    <fullName>Collect__c</fullName>
    <label>Collect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Data_Needed__c.field-meta.xml
<CustomField>
    <fullName>Data_Needed__c</fullName>
    <label>Data Needed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Case(Code_Number__c,
&quot;1&quot;,&quot;Low usage- FLT not used&quot;,
&quot;2&quot;,&quot;Toilet Overflowed&quot;,
&quot;3&quot;,&quot;Closed by Sanergy&quot;,
&quot;4&quot;,&quot;Toilet Locked&quot;,
&quot;5&quot;,&quot;Unscheduled&quot;,
&quot;6&quot;,&quot;School Closed&quot;,
&quot;7&quot;,&quot;Workman missed collection&quot;,
&quot;8&quot;,&quot;FLO request skip or special schedule&quot;,
&quot;9&quot;,&quot;Church or Institution Closed&quot;,
&quot;10&quot;,&quot;Research Toilet&quot;,
&quot;11&quot;,&quot;Other&quot;,
&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Team_To_Investigate__c.field-meta.xml
<CustomField>
    <fullName>Team_To_Investigate__c</fullName>
    <label>Team To Investigate</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOPS</fullName>
            </value>
            <value>
                <fullName>LOG</fullName>
            </value>
            <value>
                <fullName>SOPS AND LOG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_ReadMissedCollectionReasons.cls
@RestResource(urlMapping='/read_missed_collection_reasons')
global with sharing class REST_ReadMissedCollectionReasons {
   
  @HttpPost
  global static List<dataHolder> getAll() {
      //list of DimensionHolder class
      List<dataHolder> DH=new List<dataHolder>();

   LIST<Missed_Collection_Reason__c> MCRs=[SELECT Id,Action_Taken__c,Data_Needed__c,Team_To_Investigate__c,Collect__c,Description__c,Code_Number__c,Name 
                                            FROM Missed_Collection_Reason__c
                                            WHERE isActive__c = true]; 

     
      
        for(Missed_Collection_Reason__c wca:MCRs){
            dataHolder newReason=new dataHolder();
            newReason.setId(wca.Id);
            newReason.setName(wca.Name);
            newReason.setMissedCollectionReason(wca.Description__c);
            newReason.setMissedCollectionCode(wca.Code_Number__c);
            newReason.setActionTaken(wca.Action_Taken__c);
            newReason.setDataNeeded(wca.Data_Needed__c);
            newReason.setCollection(wca.Collect__c);
            newReason.setTeamToInvestigate(wca.Team_To_Investigate__c);
                        
            DH.add(newReason);
        }
      return DH;
     }
    //utility class to help with serialization of JSON
          global class dataHolder{
                String Id;
                String name;
                String codeNumber;
                String description;
                String collection;
                String actionTaken;
                String dataNeeded;
                String teamToInvestigate;
               
                              
            
            public dataHolder(){
                Id='';
                name = '';
                codeNumber='';
                description='';
                collection='';
                dataNeeded='';
                actionTaken='';
                teamToInvestigate='';
                
                
           }
            
            public void setId(String Id){
                this.Id = Id;
            }
            public void setName(String Name){
                this.Name = Name;
            }
            public void setMissedCollectionCode(String codeNumber){
                this.codeNumber=codeNumber;
            }
            
            public void setMissedCollectionReason(String description){
                this.description = description;
            }
            public void setTeamToInvestigate(String teamToInvestigate){
                this.teamToInvestigate = teamToInvestigate;
            }
            public void setCollection(String collection){
                this.collection = collection;
            }
            public void setActionTaken(String actionTaken){
                this.actionTaken=actionTaken;
            }
            
            public void setDataNeeded(String dataNeeded){
                this.dataNeeded = dataNeeded;
            }  
           
            public String getId(){
                return this.Id;
            }
            public String getName(){
                return this.Name;
            }
            public String getMissedCollectionCode(){
                return this.codeNumber;
            }                         
            public String getMissedCollectionReason(){
                return this.description;
            }
             public String getTeamToInvestigate(){
                return this.teamToInvestigate;
            }
            public String getActionTaken(){
                return this.actionTaken;
            }
            public String getDataNeeded(){
                return this.dataNeeded;
            }                         
            public String getCollection(){
                return this.collection;
            }
          
      }
}