sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/Missed_Collection_Reason__c.object-meta.xml
<CustomObject>
    <label>Missed Collection Reason</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collection Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/Waste_Collection_Schedule__c.object-meta.xml
<CustomObject>
    <label>Waste Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Waste Collection Schadule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waste Collection Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <label>Collection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>Do Not Collect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Missed_Collection_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Missed_Collection_Explanation__c</fullName>
    <label>Missed Collection Explanation</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Missed_Collection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Missed_Collection_Reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missed Collection Reason</label>
    <referenceTo>Missed_Collection_Reason__c</referenceTo>
    <relationshipLabel>Waste Collection Schedules</relationshipLabel>
    <relationshipName>Waste_Collection_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Solid_Waste_Weight__c.field-meta.xml
<CustomField>
    <fullName>Solid_Waste_Weight__c</fullName>
    <label>Solid Waste Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Waste Collection Schedules</relationshipLabel>
    <relationshipName>Waste_Collection_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Waste_Collection_Schedule__c/fields/Urine_Weight__c.field-meta.xml
<CustomField>
    <fullName>Urine_Weight__c</fullName>
    <label>Urine Weight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_WriteWeightCollections.cls
@RestResource(urlMapping='/write_weight_collections')
global with sharing class REST_WriteWeightCollections {
   
   
   
    //Incoming data from 
   global class FieldData{
        global String guid;
        global Date scheduleDate;
        global String toiletId;
        global String toiletName;
        global String missedCollectionId;
        global String missedCollectionExplanation;
        global Double solidWeight;
        global Double urineWeight;
        global String scheduleStatus;
        global String route;
        global Boolean completed;
        global String message;
        global Boolean success;       
    }
    
    global class Response{
        String message;
        Boolean success;
    }
    
    
    //Write to the collections object
    @HttpPost
    global static Response weightData(String jsonRequest){
        
        Response response = new Response();
        
        List<Waste_Collection_Schedule__c> wasteCollectionWeights = new List<Waste_Collection_Schedule__c>();
        
        try{
            List<FieldData> incomingData = (List<FieldData>)System.JSON.deserialize(jsonRequest, List<FieldData>.class);
            
            for(FieldData data : incomingData){
                //Data mapping goes here
                Waste_Collection_Schedule__c newWcs=new Waste_Collection_Schedule__c();
                
                newWcs.Toilet__c=data.toiletId;
                newWcs.Collection__c=data.scheduleStatus;
                newWcs.Collection_Date__c=data.scheduleDate;
                newWcs.Solid_Waste_Weight__c=data.solidWeight;
                newWcs.Urine_Weight__c=data.urineWeight;
                newWcs.Missed_Collection_Reason__c=data.missedCollectionId;
                newWcs.Missed_Collection_Explanation__c=data.missedCollectionExplanation;
                wasteCollectionWeights.add(newWcs); 
            }
            
            if(wasteCollectionWeights.size() > 0){
                insert wasteCollectionWeights;
                
                //Create Response
                response.success=true;
                response.message='success';
            }
            else{
                //Create Response
                response.success=false;
                response.message='Error: No record was saved';
            }
        }catch(Exception e){
            //Create Response
                response.success=false;
                response.message='Error: '+e.getMessage();
        }
        
        return response;
    }

}