sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/Missed_Collection_Reason__c.object-meta.xml
<CustomObject>
    <label>Missed Collection Reason</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collection Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Code_Number__c.field-meta.xml
<CustomField>
    <fullName>Code_Number__c</fullName>
    <label>Code Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Collect__c.field-meta.xml
<CustomField>
    <fullName>Collect__c</fullName>
    <label>Collect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Data_Needed__c.field-meta.xml
<CustomField>
    <fullName>Data_Needed__c</fullName>
    <label>Data Needed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Missed_Collection_Reason__c/fields/Team_To_Investigate__c.field-meta.xml
<CustomField>
    <fullName>Team_To_Investigate__c</fullName>
    <label>Team To Investigate</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOPS</fullName>
            </value>
            <value>
                <fullName>LOG</fullName>
            </value>
            <value>
                <fullName>SOPS AND LOG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_WriteMissedCollectionReasons.cls
@RestResource(urlMapping='/write_missed_collection_reasons')
global with sharing class REST_WriteMissedCollectionReasons {
	//Incoming data from 
       global class fieldData{
           
       global String codeNumber;
       global String collection;
       global String actionTaken;
       global String dataNeeded;
       global String teamToInvestigate;                     
    }
    global class Response{
        String codeNumber;
        String collection;
        String actionTaken;
        String dataNeeded;
        String teamToInvestigate;
        String message;
        Boolean success;
    }
    //Write to the collections object
    @HttpPost
    global static Response collectionData(String jsonRequest){
        Response response = new Response();
        fieldData data = (fieldData) System.JSON.deserialize(jsonRequest, fieldData.class);
        if(data!=null){
            try{
                //Data mapping goes here
                Missed_Collection_Reason__c newWcs=new Missed_Collection_Reason__c();
                
                 newWcs.Collect__c=data.collection;
           		 newWcs.Code_Number__c=data.codeNumber;
           		 newWcs.Action_Taken__c=data.actionTaken;
           		 newWcs.Data_Needed__c=data.dataNeeded;
           		 newWcs.Team_To_Investigate__c=data.teamToInvestigate;
                 
                insert newWcs;
                //Reponse to the fieldClient
                response.success=true;
                response.collection=data.collection;
                response.codeNumber=data.codeNumber;
                response.actionTaken=data.actionTaken;                
                response.dataNeeded=data.dataNeeded;
                response.teamToInvestigate=data.teamToInvestigate;
               
              
                
            }catch(exception e){
                response.success=false;
                response.message=e.getMessage();
            }
        }else{
            response.message='ERROR:Insert Failed Due To Empty Request';
            response.success=false;
        }return response;
    }
}