sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/Electronic_Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Electronic Payment Request</label>
    <nameField>
        <displayFormat>EPR-{0000}</displayFormat>
        <label>Electronic Payment Request name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Cash_Entry__c.field-meta.xml
<CustomField>
    <fullName>Cash_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cash Entry</label>
    <referenceTo>c2g__codaCashEntry__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/department__c.field-meta.xml
<CustomField>
    <fullName>department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>xx</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/EPR_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EPR_Request_Type__c</fullName>
    <formula>TEXT(EPR_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EPR Request Type</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Gross_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Payment_Amount__c</fullName>
    <label>Gross Payment Amount</label>
    <summarizedField>EPR_Payable_Item__c.Gross_price__c</summarizedField>
    <summaryForeignKey>EPR_Payable_Item__c.EPR__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Vendor Invoice Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Payable_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Payable_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PIN</label>
    <referenceTo>c2g__codaPurchaseInvoice__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
                <default>true</default>
                <label>Check</label>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>IBFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prepayment</fullName>
            </value>
            <value>
                <fullName>Cash Advance</fullName>
            </value>
            <value>
                <fullName>Employee Reimbursement</fullName>
            </value>
            <value>
                <fullName>Payment on Invoice</fullName>
            </value>
            <value>
                <fullName>Special Procurement</fullName>
            </value>
            <value>
                <fullName>FLO Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <description>The date when the payment is required</description>
    <label>Actual EPR Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Line Manager Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_and_Payment_Currencies_match__c.field-meta.xml
<CustomField>
    <fullName>Vendor_and_Payment_Currencies_match__c</fullName>
    <description>Value will be true is the vendor currency is the same as the payment currency</description>
    <formula>TEXT(Currency__c)=TEXT(CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Value will be true is the vendor currency is the same as the payment currency</inlineHelpText>
    <label>Vendor and Payment Currencies match</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Company__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Vendor, Sanergy Employee Accounts, Sanergy Toilet Sale - FLO, Sanergy Funders, Sanergy Fresh Fit Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Currency__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Currency__c</fullName>
    <formula>Vendor_Company__r.c2g__CODAAccountTradingCurrency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Currency</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Invoice Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Vendor Invoice does not belong to the Vendor Company you specified</errorMessage>
        <filterItems>
            <field>$Source.Vendor_Company__c</field>
            <operation>equals</operation>
            <valueField>Vendor_Invoice__c.Vendor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/EPR_Payable_Item__c.object-meta.xml
<CustomObject>
    <label>EPR Payable Item</label>
    <nameField>
        <displayFormat>EPR ITEM-{0000}</displayFormat>
        <label>EPR Payable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPR Payable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/EPR__c.field-meta.xml
<CustomField>
    <fullName>EPR__c</fullName>
    <label>Electronic Payment Request</label>
    <referenceTo>Electronic_Payment_Request__c</referenceTo>
    <relationshipLabel>EPR Payable Items</relationshipLabel>
    <relationshipName>EPR_Payable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The General Ledger Account</description>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (GLA)</relationshipLabel>
    <relationshipName>EPR_Payable_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Grant_Funding_Availale_dim4__c.field-meta.xml
<CustomField>
    <fullName>Grant_Funding_Availale_dim4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grant Funding Availale (Dim 4)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3) AND 4</booleanFilter>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim4</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (Grant Funding Availale)</relationshipLabel>
    <relationshipName>EPR_Payable_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Gross_price__c.field-meta.xml
<CustomField>
    <fullName>Gross_price__c</fullName>
    <formula>Quantity__c  *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateCashEntryFromEPR.cls
public class CreateCashEntryFromEPR {
    private ApexPages.StandardController standardController;
    private String id;
    public id cshEntryID {get; set;}
    public List<c2g__codaCashEntry__c> cashEntry {get; set;}
    Electronic_Payment_Request__c epr;
    public String companyGUID {get; set;}
    public String companyName {get; set;}
    private String companyNameInitials {get; set;}
    
    public CreateCashEntryFromEPR (ApexPages.StandardController standardController){
        this.standardController = standardController;
        epr=(Electronic_Payment_Request__c)standardController.getRecord();
        this.epr=[SELECT id, Name, Cash_Entry__c,Payable_Invoice__c,Payment_Method__c,Notes__c,Vendor_Company__c,Confirmation_Number__c,
                  Vendor_Currency__c,Payment_Type__c,Scheduled_Payment_Date__c,Invoice_Number__c,Company__c, department__c,
                  Vendor_Invoice_Number__c, Status__c, Gross_Payment_Amount__c, EPR_Request_Type__c, Vendor_and_Payment_Currencies_match__c
                  FROM Electronic_Payment_Request__c
                  WHERE ID=:epr.id];
    }
    
    private Boolean CheckFFAUserCompany(){
        //check the Company associated with the EPR
        List<String> FFAConfigCompanyName = SanergyUtils.GetFFAConfigCompanyName(epr.Company__c);
        system.debug('Company__c 11' + FFAConfigCompanyName);
        if(FFAConfigCompanyName != NULL){
            this.CompanyGUID =  FFAConfigCompanyName[1];
            this.CompanyName = FFAConfigCompanyName[0];
        }
        
        //proceed if one company found and company names are the same
        if(c2g.CODAAPICompany_2_0.GetCurrentCompanies(null).size() == 1 &&
           this.companyName == c2g.CODAAPICompany_2_0.GetCurrentCompanies(null)[0] //check if Companies match
          ){
              return TRUE; //confirm current company is same as what user is currently in
          }
        else{
            //not Found
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Cannot create Cash Entry, ensure FFA Company selected is the same as that of the EPR'));
            return FALSE;
        }
    }
    
    public PageReference createCashEntryWithLines(){
        if (CheckFFAUserCompany() == TRUE){
            Electronic_Payment_Request__c epr=(Electronic_Payment_Request__c)standardController.getRecord();
            this.epr=[SELECT Cash_Entry__c,Payable_Invoice__c,Payment_Method__c,Notes__c,Vendor_Company__c,Confirmation_Number__c,
                      Vendor_Currency__c,Payment_Type__c,Scheduled_Payment_Date__c,Invoice_Number__c,Company__c, department__c,
                      Vendor_Invoice_Number__c, Status__c, Gross_Payment_Amount__c, EPR_Request_Type__c, Vendor_and_Payment_Currencies_match__c
                      FROM Electronic_Payment_Request__c
                      WHERE ID=:epr.id];
            
            if(this.epr.Cash_Entry__c==null){
                
                String company=this.epr.Company__c;
                String bankName;
                
                //If company is Sanergy
                if(company=='Sanergy Ltd'){
                    //if payment is Check or EFT
                    if(this.epr.Payment_Method__c=='Check' || this.epr.Payment_Method__c=='EFT'){
                        if(this.epr.Vendor_Currency__c=='KES'){
                            bankName='SL - SCB - KES';
                        }
                        else if(this.epr.Vendor_Currency__c=='USD'){
                            bankName='SL - PBR - USD';
                        }
                        else if(this.epr.Vendor_Currency__c=='EUR'){
                            bankName='SL - PBR - EUR';
                        }
                        else if(this.epr.Vendor_Currency__c=='GBP'){
                            bankName='SL - PBR - GBP';
                        }
                    }
                    //if payment is Electronic.
                    else if(this.epr.Payment_Method__c=='Electronic' || this.epr.Payment_Method__c=='ACH'){
                        bankName='SL - SCB - KES';
                    }   
                }
                
                //If company is Fresh Life
                else if(company=='Fresh Life Initiative Ltd'){
                    //if payment is Check or EFT
                    if(this.epr.Payment_Method__c=='Check' || this.epr.Payment_Method__c=='EFT'){
                        if(this.epr.Vendor_Currency__c=='KES'){
                            bankName='FLI - SCB - KES';
                        }
                        else if(this.epr.Vendor_Currency__c=='USD'){
                            bankName='FLI - PBR - USD';
                        }
                        else if(this.epr.Vendor_Currency__c=='EUR'){
                            bankName='FLI - PBR - EUR';
                        }
                        else if(this.epr.Vendor_Currency__c=='GBP'){
                            bankName='FLI - PBR - GBP';
                        }
                    }
                    //if payment is Electronic.
                    else if(this.epr.Payment_Method__c=='Electronic' || this.epr.Payment_Method__c=='ACH'){
                        bankName='FLI - SCB - KES';
                    }
                }
                
                //If company is Sanergy FP
                else if(company=='Sanergy Inc (FP)'){
                    bankName='FP Checking';
                }
                
                //If company is Sanergy NP
                else if(company=='Sanergy Inc (NP)'){
                    bankName='NP Checking';
                }
                
                List<c2g__codaBankAccount__c> bankAcc=[SELECT Id,c2g__BankAccountCurrency__c 
                                                       FROM c2g__codaBankAccount__c
                                                       WHERE Name=:bankName];
                
                if(bankAcc.size()>0){
                    c2g__codaCashEntry__c cashEntry=new c2g__codaCashEntry__c(
                        c2g__Type__c='Payment',
                        c2g__BankAccount__c=bankAcc.get(0).id,
                        c2g__CashEntryCurrency__c=bankAcc.get(0).c2g__BankAccountCurrency__c ,
                        c2g__Reference__c=this.epr.Confirmation_Number__c,
                        c2g__PaymentMethod__c=this.epr.Payment_Method__c,
                        c2g__Description__c=this.epr.Notes__c,
                        EPR__c=this.epr.id
                    );
                    
                    try{
                        insert cashEntry;
                        cshEntryID = cashEntry.id;
                        List<EPR_Payable_Item__c> EPR_Line=[SELECT Item__c,Quantity__c,Gross_price__c, GLA__c,Grant_Funding_Availale_dim4__c,Location_Dim2__c,Department_dim1__c
                                                            FROM EPR_Payable_Item__c
                                                            WHERE EPR__c=:this.epr.id]; 
                        
                        List<c2g__codaCashEntryLineItem__c> cashEntryLine=new List<c2g__codaCashEntryLineItem__c>();
                        
                        for(EPR_Payable_Item__c eprLineItem:EPR_Line){
                            c2g__codaCashEntryLineItem__c cEntryLine=new c2g__codaCashEntryLineItem__c(
                                c2g__Account__c=this.epr.Vendor_Company__c,
                                c2g__AccountReference__c=this.epr.Confirmation_Number__c,
                                c2g__AccountPaymentMethod__c=this.epr.Payment_Method__c,
                                c2g__CashEntryValue__c=eprLineItem.Gross_price__c ,
                                c2g__CashEntry__c=cashEntry.id
                            );
                            
                            cashEntryLine.add(cEntryLine);       
                        }
                        insert cashEntryLine;
                        
                        this.epr.Cash_Entry__c=cashEntry.id;
                        
                        update this.epr;             
                        return  new PageReference('/' + epr.Id); 
                        
                    }catch(Exception e){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                        return null;
                    }
                }
                else{
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Could not get a matching bank account'));
                    return null;
                } 
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This EPR already has a Cash Entry record!'));
                return null;
            }   
        }else{
            //Multiple Companies found
            return NULL;
        }
    }
}