sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/Electronic_Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Electronic Payment Request</label>
    <nameField>
        <displayFormat>EPR-{0000}</displayFormat>
        <label>Electronic Payment Request name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/department__c.field-meta.xml
<CustomField>
    <fullName>department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>xx</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Vendor Invoice Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prepayment</fullName>
            </value>
            <value>
                <fullName>Cash Advance</fullName>
            </value>
            <value>
                <fullName>Employee Reimbursement</fullName>
            </value>
            <value>
                <fullName>Payment on Invoice</fullName>
            </value>
            <value>
                <fullName>Special Procurement</fullName>
            </value>
            <value>
                <fullName>FLO Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Preferred_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Payment_Method__c</fullName>
    <label>Preferred Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>No Preference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <description>The date when the payment is required</description>
    <label>Actual EPR Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Line Manager Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Team_Lead_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_Approval_Status__c</fullName>
    <label>Team Lead Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Company__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Vendor, Sanergy Employee Accounts, Sanergy Toilet Sale - FLO, Sanergy Funders, Sanergy Fresh Fit Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Invoice Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Vendor Invoice does not belong to the Vendor Company you specified</errorMessage>
        <filterItems>
            <field>$Source.Vendor_Company__c</field>
            <operation>equals</operation>
            <valueField>Vendor_Invoice__c.Vendor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/EPR_Payable_Item__c.object-meta.xml
<CustomObject>
    <label>EPR Payable Item</label>
    <nameField>
        <displayFormat>EPR ITEM-{0000}</displayFormat>
        <label>EPR Payable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPR Payable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Department_dim1__c.field-meta.xml
<CustomField>
    <fullName>Department_dim1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department (Dim 1)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (Department)</relationshipLabel>
    <relationshipName>EPR_Payable_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (Dim 3)</relationshipLabel>
    <relationshipName>EPR_Payable_Items4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/EPR__c.field-meta.xml
<CustomField>
    <fullName>EPR__c</fullName>
    <label>Electronic Payment Request</label>
    <referenceTo>Electronic_Payment_Request__c</referenceTo>
    <relationshipLabel>EPR Payable Items</relationshipLabel>
    <relationshipName>EPR_Payable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Location_Dim2__c.field-meta.xml
<CustomField>
    <fullName>Location_Dim2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location (Dim 2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items</relationshipLabel>
    <relationshipName>EPR_Payable_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/fields/Delegate_s_Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Delegate_s_Threshold_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delegate&#39;s Threshold Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/fields/Teamlead__c.field-meta.xml
<CustomField>
    <fullName>Teamlead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teamlead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FFA_Config_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/BulkApprovalControllerTest_Lite.cls
@isTest(seeAllData = true)
public class BulkApprovalControllerTest_Lite {
    public static TestMethod void BulkApprovalControllerTester_Lite(){
        //Get dim1                              
        
        
        //Get Company
        List<FFA_Config_Object__c> company= [SELECT id FROM FFA_Config_Object__c WHERE type__c='company'AND Name = 'Sanergy Limited'and isActive__c=true LIMIT 1];       
        
        //Get the location
        List<FFA_Config_Object__c> location=[SELECT id FROM FFA_Config_Object__c WHERE Type__c='dim2'  AND isActive__c=true LIMIT 1];         
      
        //Get gla
        List<FFA_Config_Object__c> gla= [SELECT id FROM FFA_Config_Object__c WHERE type__c='gla' AND (Name='2000 - Accounts Payable Control' OR Name='2050 - Accrued Accounts Payable Control')AND isActive__c=true LIMIT 2];

        //Get DIM 1-4 
        List<FFA_Config_Object__c> department = [SELECT Id,Name,Type__c,isActive__c,Delegate_s_Threshold_Amount__c,Teamlead__c FROM FFA_Config_Object__c WHERE Type__c = 'dim1'AND Name LIKE 'Information Technology'AND isActive__c = true LIMIT 1];       
        List<FFA_Config_Object__c> dim2 = [SELECT Id,Name,Type__c,isActive__c FROM FFA_Config_Object__c WHERE Type__c = 'dim2' AND isActive__c = true LIMIT 1];  
        List<FFA_Config_Object__c> dim3=[SELECT id FROM FFA_Config_Object__c WHERE Type__c='dim3'  AND isActive__c=true LIMIT 1];
        List<FFA_Config_Object__c> dim4 = [SELECT Id,Name,Type__c,isActive__c FROM FFA_Config_Object__c WHERE Type__c = 'dim4' AND isActive__c = true LIMIT 1];                       
        
        //Create Account
        Account account1 = new Account();
        account1.Name='John Doe';
        account1.CurrencyIsoCode = 'KES';
        account1.RecordTypeId = '012D0000000KE7iIAG';//Sanergy Employee Accounts
        INSERT account1;
        
        System.debug('account1 = ' + account1);  		
        
        //create EPR
        Electronic_Payment_Request__c epr=new Electronic_Payment_Request__c();
        epr.department__c=department.get(0).Id;
        epr.Company__c='Sanergy Ltd';
        epr.Vendor_Company__c = account1.Id;
        epr.Invoice_Number__c='INVOICE1234'; 
        //epr.Vendor_Invoice_Number__c = vi.Id;
        epr.Scheduled_Payment_Date__c=Date.today();              
        epr.Payment_Type__c='Prepayment';
        epr.Preferred_Payment_Method__c = 'Check';
        epr.Status__c='Open';
        epr.Team_Lead_Approval_Status__c=null;          
        INSERT epr;      

        //Create EPR Line items
        EPR_Payable_Item__c eprPayable=new EPR_Payable_Item__c();
        eprPayable.EPR__c=epr.id;
        eprPayable.Item__c='test Item';
        eprPayable.Unit_Price__c=department.get(0).Delegate_s_Threshold_Amount__c+1;
        eprPayable.Quantity__c=1;
        eprPayable.Department_dim1__c=department.get(0).Id;
        eprPayable.Location_Dim2__c=location.get(0).Id;
        eprPayable.Dim_3__c=dim3.get(0).Id;
        eprPayable.Grant_Funding_Availale_dim4__c=dim4.get(0).Id;
        eprPayable.GLA__c=gla.get(0).Id;    
        INSERT eprPayable;
        
         // Get the EPR we just updated            
        Approval.ProcessSubmitRequest appEpr = new Approval.ProcessSubmitrequest();
        appEpr.setObjectId(epr.Id);                
        Approval.ProcessResult result1 = Approval.process(appEpr);
        
         //Reassign to current user
        Set<Id> AppObjectIds = new Set<Id>();
        AppObjectIds.add(epr.id);
        List<ProcessInstanceWorkItem> pi = [SELECT Id, ActorId FROM ProcessInstanceWorkItem 
                                      WHERE ProcessInstance.TargetObjectId IN : AppObjectIds];
        //loop through and assign to current user
        for(ProcessInstanceWorkItem item: pi){
            item.ActorId = UserInfo.getUserId();
        }
        
        UPDATE pi;
        
        PageReference pageRef = Page.BulkApprovalController;
        Test.setCurrentPage(pageRef);
        //create instance of BulkApprovalController controller
        BulkApprovalController controller = new BulkApprovalController();
 
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperEPRs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
       }      
                    
       
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperSPRs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getMaintenanceTaskWrapper()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperRecruitRequisition()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperEmpRoles()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }       
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperELRs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperPRs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperPRLINEs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
        }
        /*
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperFLEET()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
        }
        
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperJOBs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
        }
		*/
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperPOs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }
        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperPOIs()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
            
        }

        for(BulkApprovalController.ApprovalsWrapper w : controller.getWrapperALLOWANCES()){
            w.selectedApprovalOption = 'Approve';
            pageRef.getParameters().put('objectType', w.objectType);
            controller.save();
        }        
       // Test.stopTest();
        //get approvals
        controller.getWrapperALLOWANCES();
        //mark allowances reject
        controller.markAllAllowancesRej();
        
        //mark allowances approve
        controller.markAllAllowancesApp();
        controller.getPURCHASE_ORDER_ITEM();        
        controller.getEPR_NAME();
        controller.getPR_NAME();
        controller.getPR_LINE_NAME();
        //controller.getFLEET_NAME();
        //controller.getCONTRACTOR_JOB_NAME();
        controller.getSTAFF_ALLOWANCES_NAME();
        controller.getPURCHASE_ORDER_NAME(); 
        
        controller.getSPECIAL_PROCUREMENT_NAME();
        controller.getRECRUITMENT_REQUISITION();
        controller.getEMPLOYEE_Role();
        controller.getASSET_MAINTENANCE_TASK();
        
        //Approve Allowances
        controller.saveAllowanceActions();
        
        controller.save();
        controller.a();
        //controller.b();
        //controller.c();
        //controller.d();
        //controller.e();
        
        //}
    }
}