sfSandBoxCode/force-app/main/default/objects/Location_Demolition__c/Location_Demolition__c.object-meta.xml
<CustomObject>
    <description>Toilets that have been demolished in a given location</description>
    <label>Location Demolition</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Location Demolition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Demolitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demolished Toilet Addition</fullName>
                <default>true</default>
                <label>Demolished Toilet Addition</label>
            </value>
            <value>
                <fullName>Authority Reporting</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_History_Record__c/Location_Demolition_History_Record__c.object-meta.xml
<CustomObject>
    <label>Location Demolition History Record</label>
    <nameField>
        <displayFormat>LDHR-{0000}</displayFormat>
        <label>Location Demolition History Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Demolition History Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_History_Record__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The event that needs to be captured</description>
    <label>Event</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Demolition_History_Record__c/fields/Location_Demolition__c.field-meta.xml
<CustomField>
    <fullName>Location_Demolition__c</fullName>
    <label>Location Demolition</label>
    <referenceTo>Location_Demolition__c</referenceTo>
    <relationshipLabel>Location Demolition History Records</relationshipLabel>
    <relationshipName>Location_Demolition_History_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateLocationDemolitionHistoryRecords.cls
public class CreateLocationDemolitionHistoryRecords{
    
    public static void createRecord(String event, String stage, String LD_ID){
        Location_Demolition_History_Record__c LDHR=new Location_Demolition_History_Record__c(
                                                                    Event__c=event,
                                                                    Location_Demolition__c=LD_ID,
                                                                    Stage__c=stage );
                                                                    
        insert LDHR;
    }
}