sfSandBoxCode/force-app/main/default/objects/Opportunity_History_Records__c/Opportunity_History_Records__c.object-meta.xml
<CustomObject>
    <description>The history records of the opportunity object</description>
    <label>Opportunity History Record</label>
    <nameField>
        <displayFormat>OHR-{0000}</displayFormat>
        <label>Opportunity History Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity History Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Opportunity_History_Records__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_History_Records__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_History_Records__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity History Records</relationshipLabel>
    <relationshipName>Opportunity_History_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Opportunity_History_Records__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateOpportunityHistoryRecords.cls
public class CreateOpportunityHistoryRecords{
 
  //function to create new Opportunity History Records
  public static void createRecord(String Opportunity, String Recordtype, String Event){
  
  
  Opportunity_History_Records__c OHR=new Opportunity_History_Records__c(
                                                                         Date__c=Datetime.now(),
                                                                         Event__c=Event,
                                                                         Opportunity__c=Opportunity,
                                                                         Record_Type__c=Recordtype
                                                                            );
                                                                            
     insert OHR;
  
  }
 }