sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/Vendor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Vendor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/VI_Company__c.field-meta.xml
<CustomField>
    <fullName>VI_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Company this VI Belongs to</description>
    <inlineHelpText>Company this VI Belongs to</inlineHelpText>
    <label>VI Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select a valid Company</errorMessage>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Vendor Invoices</relationshipLabel>
    <relationshipName>Vendor_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/VI_Status__c.field-meta.xml
<CustomField>
    <fullName>VI_Status__c</fullName>
    <label>VI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Physical Receipt</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>AP Matched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/Vendor_Invoice_Items__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice Item</label>
    <nameField>
        <displayFormat>VII-{0000000}</displayFormat>
        <label>Vendor Invoice Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice_Items__c/fields/Vendor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice__c</fullName>
    <label>Vendor Invoice</label>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Vendor Invoice Items</relationshipLabel>
    <relationshipName>Vendor_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/FirmVendorInvoice.cls
public class FirmVendorInvoice {

    @TestVisible Public Vendor_Invoice__c vi{get;set;}
    @TestVisible public ApexPages.StandardController standardController;
    
    
    public FirmVendorInvoice(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.vi = (Vendor_Invoice__c)standardController.getRecord();
        /*
        this.vi =
            [
                SELECT Id, VI_Status__c, VI_Company__c
                FROM Vendor_Invoice__c
                WHERE Id =: this.vi.Id 
            ];
		*/
    }
    
    public PageReference FirmVI() {
        //insert VI Company at this stage
        //if the first VII, set the VI company to the Company on the VII
        /*
        AggregateResult [] aggVI = 
            [SELECT Company__c, Company__r.Name CompanyName, COUNT(id)VICOs
             FROM Vendor_Invoice_Items__c
             WHERE Vendor_Invoice__c =: this.vi.Id
             AND CreatedDate >= 2020-01-01T00:00:00Z
             GROUP BY Company__c, Company__r.Name
            ];
        //if one record found and company matches vii company firm the VI
        if(aggVI.size() > 0 && aggVI.size() == 1 ){
            //vi.VI_Company__c = (String)aggVI[0].get('Company__c');
            vi.VI_Status__c = 'Firmed';
            UPDATE vi;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'VI has been Firmed'));
        }
        else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Company on the VI must match that of the VI Items'));
        }
        */
        return NULL;   
    }   
}