sfSandBoxCode/force-app/main/default/objects/FFA_Config_Object__c/FFA_Config_Object__c.object-meta.xml
<CustomObject>
    <description>This is a junction object which enables a normal user to choose, dimension 1,2,3 and 4 , as well as GLA accounts</description>
    <label>FFA Config Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FFA Config Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/Renconciling_Object__c.object-meta.xml
<CustomObject>
    <label>SPR Reconciliation</label>
    <nameField>
        <displayFormat>RECON-{000000}</displayFormat>
        <label>Renconciling Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPR Reconciliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/DIM1__c.field-meta.xml
<CustomField>
    <fullName>DIM1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DIM1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>SPR Reconciliations</relationshipLabel>
    <relationshipName>SPR_Reconciliations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/Expense_Description__c.field-meta.xml
<CustomField>
    <fullName>Expense_Description__c</fullName>
    <label>Expense Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GLA</label>
    <referenceTo>c2g__codaGeneralLedgerAccount__c</referenceTo>
    <relationshipLabel>SPR Reconciliations</relationshipLabel>
    <relationshipName>SPR_Reconciliations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/Item_Amount__c.field-meta.xml
<CustomField>
    <fullName>Item_Amount__c</fullName>
    <label>Item Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/KRA_Pin__c.field-meta.xml
<CustomField>
    <fullName>KRA_Pin__c</fullName>
    <label>KRA Pin</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/Special_Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Payment_Request__c</fullName>
    <label>Special Payment Request</label>
    <referenceTo>Special_Procurement__c</referenceTo>
    <relationshipLabel>SPR Reconciliations</relationshipLabel>
    <relationshipName>SPR_Reconciliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/Transaction_Charge__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Charge__c</fullName>
    <label>Transaction Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Renconciling_Object__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/Special_Procurement__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request</label>
    <nameField>
        <displayFormat>SPR-{00000000}</displayFormat>
        <label>Special Procurement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Approve_Reconciliation__c.field-meta.xml
<CustomField>
    <fullName>Approve_Reconciliation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approve Reconciliation</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Dim_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim2</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Dim_3__c.field-meta.xml
<CustomField>
    <fullName>Dim_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dim 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim3</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/EPR_Created__c.field-meta.xml
<CustomField>
    <fullName>EPR_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPR Created</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements4</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Payable_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Payable_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PIN</label>
    <referenceTo>c2g__codaPurchaseInvoice__c</referenceTo>
    <relationshipLabel>Special Payment Requests</relationshipLabel>
    <relationshipName>Special_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>IBFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Reconciled_Balance__c.field-meta.xml
<CustomField>
    <fullName>Reconciled_Balance__c</fullName>
    <description>If Recon &gt; 0 Bal = Total Payments - Total Recons else Recon = 0 then get higher of Payments made or Total Recons</description>
    <formula>IF( Reconciled_Total__c &gt; 0, Total_Payments__c - Reconciled_Total__c 
, MAX( Total_Payments__c , Reconciled_Total__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Recon &gt; 0 Bal = Total Payments - Total Recons else Recon = 0 then get higher of Payments made or Total Recons</inlineHelpText>
    <label>Reconciled Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Requesting_Company__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requesting Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>company</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipName>Special_Procurements1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <label>Scheduled Payment Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Total_Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Requested__c</fullName>
    <description>The total amount that has been requested on the line items</description>
    <inlineHelpText>The total amount that has been requested on the line items</inlineHelpText>
    <label>Total Amount Requested</label>
    <summarizedField>Special_Procurement_Line_Item__c.Total_Unapproved_Value__c</summarizedField>
    <summaryForeignKey>Special_Procurement_Line_Item__c.Special_Procurement__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Total_Approved_EPR_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_EPR_Value__c</fullName>
    <label>Total Approved EPR Value</label>
    <summarizedField>Special_Procurement_Payment__c.Total_EPR__c</summarizedField>
    <summaryForeignKey>Special_Procurement_Payment__c.Special_Procurement__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Special_Procurements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/fields/Vendor_Currency__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Currency__c</fullName>
    <formula>Vendor__r.c2g__CODAAccountTradingCurrency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Currency</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Supplier__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>MPesa</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreatePinFromSPR.cls
public class CreatePinFromSPR {
    
    private ApexPages.StandardController standardController;
    Special_Procurement__c spr;
    //Renconciling_Object__c sprRecon;
    public Boolean disableCreatePIN {get; set;}
    
    public CreatePinFromSPR(ApexPages.StandardController standardController){
        this.standardController = standardController;
        spr = (Special_Procurement__c)standardController.getRecord();
        spr = 
            [
                SELECT Name,GLA__c,Dim_2__c,Dim_3__c,Payable_Invoice__c,Payable_Invoice__r.Name,Requesting_Company__c,Requesting_Company__r.Name,
                Vendor__c, EPR_Created__c, Vendor_Currency__c,Payment_Method__c,Scheduled_Payment_Date__c,
                Approve_Reconciliation__c,Total_Approved_EPR_Value__c
                FROM Special_Procurement__c 
                WHERE ID =: spr.Id    
            ];
        
        //confirm we have the info to create the PIN
        if (spr.Payable_Invoice__c == null && spr.EPR_Created__c == TRUE && spr.Approve_Reconciliation__c == TRUE && spr.Payment_Method__c != ''){
            disableCreatePIN = FALSE;
        }
        else
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'To create the PIN; PIN = NULL, EPR Created = TRUE, Payment Method = Selected, Approve Reconciliation = TRUE'));
            disableCreatePIN = TRUE;
        }
    }
    
    public PageReference CreatePin(){
        if (spr.Payable_Invoice__c == null && spr.EPR_Created__c == TRUE && spr.Approve_Reconciliation__c == true && spr.Payment_Method__c != ''){
            system.debug('SPR CCCOMPANY' + spr.Requesting_Company__r.Name);
            
            String company= spr.Requesting_Company__r.Name;
            String bankName;
            
            //If company is Sanergy
            if(company=='Sanergy Limited'){
                system.debug('CooOMPANY' + company + ' '+ bankName);
                
                //if payment is Check or EFT
                if(spr.Payment_Method__c=='Check' || spr.Payment_Method__c=='EFT'){
                    system.debug('Bank Name' + company + ' '+ bankName);
                    if(spr.Vendor_Currency__c=='KES'){
                        bankName='SL - PBH - KES';
                    }
                    else if(spr.Vendor_Currency__c=='USD'){
                        bankName='SL - PBR - USD';
                    }
                    else if(spr.Vendor_Currency__c=='EUR'){
                        bankName='SL - PBR - EUR';
                    }
                    else if(spr.Vendor_Currency__c=='GBP'){
                        bankName='SL - PBR - GBP';
                    }
                }
                //if payment is Electronic.
                else if(spr.Payment_Method__c=='Electronic'){
                    bankName='SL - SCB - KES';
                    system.debug('Bank Name' + company + ' '+ bankName);
                    
                }   
            }
            
            //If company is Fresh Life
            else if(company=='Fresh Life Initiative Limited'){
                //if payment is Check or EFT
                if(spr.Payment_Method__c=='Check' || spr.Payment_Method__c=='EFT'){
                    if(spr.Vendor_Currency__c=='KES'){
                        bankName='FLI - PBH - KES';
                    }
                    else if(spr.Vendor_Currency__c=='USD'){
                        bankName='FLI - PBR - USD';
                    }
                    else if(spr.Vendor_Currency__c=='EUR'){
                        bankName='FLI - PBR - EUR';
                    }
                    else if(spr.Vendor_Currency__c=='GBP'){
                        bankName='FLI - PBR - GBP';
                    }
                }
                //if payment is Electronic.
                else if(spr.Payment_Method__c=='Electronic'){
                    bankName='FLI - SCB - KES';
                }  
            }  
            
            //If company is Sanergy FP
            else if(company=='Sanergy Inc (FP)'){
                bankName='FP Checking';
            }
            
            //If company is Sanergy NP
            else if(company=='Sanergy Inc (NP)'){
                bankName='NP Checking';
            }   
            
            List<c2g__codaBankAccount__c > bankAcc=[SELECT Id,c2g__BankAccountCurrency__c 
                                                    FROM c2g__codaBankAccount__c
                                                    WHERE Name=:bankName];            
            
            
            if(bankAcc.size() > 0){
                system.debug('BANK ACC' +' '+ bankAcc.get(0).c2g__BankAccountCurrency__c);
                
                c2g__codaPurchaseInvoice__c PIN=new c2g__codaPurchaseInvoice__c();
                PIN.c2g__Account__c= spr.Vendor__c;
                PIN.c2g__InvoiceDate__c=Date.Today();
                PIN.c2g__DueDate__c= spr.Scheduled_Payment_Date__c;
                PIN.c2g__AccountInvoiceNumber__c=spr.Name;
                // PIN.c2g__InvoiceCurrency__c=bankAcc.get(0).c2g__BankAccountCurrency__c;
                
                INSERT PIN; 
                
                spr.Payable_Invoice__c=PIN.ID;
                UPDATE spr;
                
                system.debug('PIN' + spr.Payable_Invoice__c);
                system.debug('SPR' + spr);
                
                List<Renconciling_Object__c> sprRecon = 
                    [
                        SELECT id, Date__c, Expense_Description__c, GLA__c,Total_Reconciled__c,
                        DIM1__c,Item_Amount__c,Supplier__c,Special_Payment_Request__c,Special_Payment_Request__r.Reconciled_Balance__c,
                        Transaction_Charge__c,VAT__c,KRA_Pin__c,Special_Payment_Request__r.Total_Amount_Requested__c,Special_Payment_Request__r.Dim_2__c,
                        Special_Payment_Request__r.Dim_3__c,Special_Payment_Request__r.Total_Approved_EPR_Value__c
                        from Renconciling_Object__c 
                        where Special_Payment_Request__c  =: spr.Id
                    ];
                
                List<c2g__codaPurchaseInvoiceExpenseLineItem__c> PIN_Line=new List<c2g__codaPurchaseInvoiceExpenseLineItem__c>();
                for(Renconciling_Object__c sprR: sprRecon){
                    
                    c2g__codaPurchaseInvoiceExpenseLineItem__c pinLine=new c2g__codaPurchaseInvoiceExpenseLineItem__c(
                        c2g__PurchaseInvoice__c=PIN.ID,
                        ffap__SetGLAToDefault__c=false,
                        c2g__LineDescription__c=sprR.Expense_Description__c,
                        c2g__NetValue__c=sprR.Total_Reconciled__c,
                        c2g__TaxValue1__c = sprR.VAT__c,
                        ffap__SetTaxCodeToDefault__c=false,
                        ffap__CalculateTaxValueFromRate__c=true,
                        ffap__DeriveTaxRateFromCode__c=true,
                        c2g__GeneralLedgerAccount__c=sprR.GLA__c,
                        c2g__Dimension1__c=sprR.DIM1__c
                    );
                    
                    PIN_Line.add(pinLine);
                    
                }
                INSERT PIN_LINE;
                system.debug('SPRLINE' + PIN_LINE);
                
                
                spr.Payable_Invoice__c=PIN.ID;
                UPDATE PIN;
            }     
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'PIN Successfully Created'));
        }
        else
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'To create the PIN; PIN = NULL, EPR Created = TRUE, Payment Method = Selected, Approve Reconciliation = TRUE'));
        }
        
        return NULL;
    }
    
    
}