sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/Casuals_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Assignment Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/EPR__c.field-meta.xml
<CustomField>
    <fullName>EPR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EPR</label>
    <referenceTo>Electronic_Payment_Request__c</referenceTo>
    <relationshipLabel>Assignment Timesheets</relationshipLabel>
    <relationshipName>Assignment_Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/EPR_Created__c.field-meta.xml
<CustomField>
    <fullName>EPR_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPR Created</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateEPRFromTimesheetTest.cls
@isTest(seeAllData = true)
public class CreateEPRFromTimesheetTest{
     static testMethod void CreateEPRFromTimesheetTest(){
        List<Casuals_Timesheet__c> timesheet =[SELECT Id
                                               FROM Casuals_Timesheet__c 
                                               WHERE EPR_Created__c = false
                                               AND EPR__c = null
                                               ORDER BY Name DESC
                                               LIMIT 1];
        
        if(timesheet.size() > 0){
            PageReference pageReff = Page.CreateEPRFromTimesheet;
            Test.setCurrentPage(pageReff);
            ApexPages.Standardcontroller cont = new ApexPages.Standardcontroller(timesheet.get(0));
            CreateEPRFromTimesheet createEPR= new CreateEPRFromTimesheet (cont); 
            createEPR.createEPR();
        }   
    }
}