sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/Collection_Data__c.object-meta.xml
<CustomObject>
    <label>Waste Data</label>
    <nameField>
        <label>Waste Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waste Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <formula>TEXT(Toilet__r.Collection_Route__c)</formula>
    <label>Collection Route</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/fields/Feces_kg__c.field-meta.xml
<CustomField>
    <fullName>Feces_kg__c</fullName>
    <label>Feces (kg)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Toilet__r.Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Waste Data</relationshipLabel>
    <relationshipName>Collection_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Collection_Data__c/fields/Urine_kg__c.field-meta.xml
<CustomField>
    <fullName>Urine_kg__c</fullName>
    <label>Urine (kg)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Collection_Route__c.field-meta.xml
<CustomField>
    <fullName>Collection_Route__c</fullName>
    <label>Collection Route</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>Ruben Collection Spot</fullName>
            </value>
            <value>
                <fullName>KR Collection Center</fullName>
            </value>
            <value>
                <fullName>Paradise Collection Center</fullName>
            </value>
            <value>
                <fullName>Simba Cool</fullName>
            </value>
            <value>
                <fullName>KN Collection Center</fullName>
            </value>
            <value>
                <fullName>Truck Round 1</fullName>
            </value>
            <value>
                <fullName>Kingstone</fullName>
            </value>
            <value>
                <fullName>Tuk Tuk</fullName>
            </value>
            <value>
                <fullName>Kayaba Collection Center</fullName>
            </value>
            <value>
                <fullName>Limuru - Mabroukie</fullName>
            </value>
            <value>
                <fullName>Kiambiu Collection Center</fullName>
            </value>
            <value>
                <fullName>Mathare Collection Center</fullName>
            </value>
            <value>
                <fullName>Tassia collection center</fullName>
            </value>
            <value>
                <fullName>Kariobangi south collection spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Current_Specific_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Specific_Status__c</fullName>
    <description>Current Specific Status of the Toilet</description>
    <inlineHelpText>Current Specific Status of the Toilet</inlineHelpText>
    <label>Current Specific Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Operational_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Closed - By FLI</fullName>
            </value>
            <value>
                <fullName>Closed - By FLO</fullName>
            </value>
            <value>
                <fullName>Closed - Debranded</fullName>
            </value>
            <value>
                <fullName>Closed - Demolished</fullName>
            </value>
            <value>
                <fullName>Closed - QA Check</fullName>
            </value>
            <value>
                <fullName>Closed - Relocated</fullName>
            </value>
            <value>
                <fullName>Closed - Repossessed</fullName>
            </value>
            <value>
                <fullName>Closed - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Company-Owned</fullName>
            </value>
            <value>
                <fullName>Open - New</fullName>
            </value>
            <value>
                <fullName>Open - Re-installed</fullName>
            </value>
            <value>
                <fullName>Open - Re-opened</fullName>
            </value>
            <value>
                <fullName>Open - Relocated</fullName>
            </value>
            <value>
                <fullName>Open - Resold</fullName>
            </value>
            <value>
                <fullName>Open - Rebranded</fullName>
            </value>
            <value>
                <fullName>Open - Reopened</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <description>Date of first day of business</description>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Operational_Status__c.field-meta.xml
<CustomField>
    <fullName>Operational_Status__c</fullName>
    <description>Whether the toilet is currently open or closed.</description>
    <label>Operational Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Launch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/TestCalculateUsersForToiletTrigger.cls
/*
 *
 */
 
@isTest
private class TestCalculateUsersForToiletTrigger {
    
    static Integer getDayOfWeek(Date dt)
    {
        Integer daysBetween = DateTime.valueOfGmt('1990-07-1 00:00:00').dateGMT().daysBetween(dt);
        Integer remainder = Math.mod(daysBetween, 7);
        
        return remainder ;
    }

    static Date getNearestSunday(Date currentDate) {
        Date adjustedStartOfWeek = null;
        
        if(getDayOfWeek(currentDate) == 0) {
            adjustedStartOfWeek = currentDate;
        } else if(getDayOfWeek(currentDate) == 1) {
            adjustedStartOfWeek = currentDate.addDays(-1);
        } else if(getDayOfWeek(currentDate) == 2) {
            adjustedStartOfWeek = currentDate.addDays(-2);
        } else if(getDayOfWeek(currentDate) == 3) {
            adjustedStartOfWeek = currentDate.addDays(-3);
        } else if(getDayOfWeek(currentDate) == 4) {
            adjustedStartOfWeek = currentDate.addDays(-4);
        } else if(getDayOfWeek(currentDate) == 5) {
            adjustedStartOfWeek = currentDate.addDays(-5);
        } else if(getDayOfWeek(currentDate) == 6) {
            adjustedStartOfWeek = currentDate.addDays(-6);
        }
        return adjustedStartOfWeek;
    }
    
    static testmethod void testTrigger() {
        
        Location__c loc = new Location__c(Name = 'TS');
        insert loc;
        
        Toilet__c toilet1 = new Toilet__c(Location__c = loc.Id, Operational_Status__c='Open',
                                       Current_Specific_Status__c='Open - New',Name = 'TS-1.1', Collection_Route__c = 'CLOSED', Opening_Date__c = Date.today().addMonths(-2)) ;
        Toilet__c toilet2 = new Toilet__c(Location__c = loc.Id, Name = 'TS-2.1', Operational_Status__c='Open',
                                       Current_Specific_Status__c='Open - New', Collection_Route__c = 'CLOSED', Opening_Date__c = Date.today().addMonths(-2)) ;
        insert new Toilet__c[]{toilet1, toilet2};
        
        Date referenceDate = getNearestSunday(Date.today());
        
        Collection_Data__c toilet1CollData1 = new Collection_Data__c(Toilet__c = toilet1.Id, Name = 'Test Waste',
                                                                     Feces_kg__c = 12, Urine_kg__c = 11, Collection_Date__c = referenceDate.addDays(-3));
                                                                     
        Collection_Data__c toilet1CollData2 = new Collection_Data__c(Toilet__c = toilet1.Id, Name = 'Test Waste',
                                                                     Feces_kg__c = 9, Urine_kg__c = 8, Collection_Date__c = referenceDate.addDays(-9));
                                                                     
        Collection_Data__c toilet2CollData1 = new Collection_Data__c(Toilet__c = toilet1.Id, Name = 'Test Waste',
                                                                     Feces_kg__c = 4, Urine_kg__c = 5, Collection_Date__c = referenceDate.addDays(-4)); 
        
        Collection_Data__c toilet2CollData2 = new Collection_Data__c(Toilet__c = toilet1.Id, Name = 'Test Waste',
                                                                     Feces_kg__c = 2, Urine_kg__c = 1, Collection_Date__c = referenceDate.addDays(-17));  
                                                                     
        insert new Collection_Data__c[]{toilet1CollData1 , toilet1CollData2, toilet2CollData1, toilet2CollData2 };
        
        toilet2CollData1.Feces_kg__c = 5 ;
        toilet1CollData2.Collection_Date__c = referenceDate.addDays(-10);
        
        update new Collection_Data__c[]{toilet2CollData1, toilet1CollData2};
        
    }

}