sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/Treatment_Block__c.object-meta.xml
<CustomObject>
    <label>Treatment Block</label>
    <nameField>
        <displayFormat>TB-{0000}</displayFormat>
        <label>Treatment Blocks</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Block_size__c.field-meta.xml
<CustomField>
    <fullName>Block_size__c</fullName>
    <label>Block size (Hectares)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Crops_trialing_on__c.field-meta.xml
<CustomField>
    <fullName>Crops_trialing_on__c</fullName>
    <label>Crops trialing on</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Evergrow_Rate__c.field-meta.xml
<CustomField>
    <fullName>Evergrow_Rate__c</fullName>
    <inlineHelpText>Please insert Evergrow Application Rate in KG&#39;s per hectare.</inlineHelpText>
    <label>Evergrow Rate (kgs/hectare)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Trial__c.field-meta.xml
<CustomField>
    <fullName>Trial__c</fullName>
    <label>Trial</label>
    <referenceTo>Trial__c</referenceTo>
    <relationshipLabel>Treatment Blocks</relationshipLabel>
    <relationshipName>Treatment_Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Treatment Block</fullName>
                <default>true</default>
                <label>Treatment Block</label>
            </value>
            <value>
                <fullName>Control Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Treatment_Block__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <label>Variety</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/Trial__c.object-meta.xml
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Agricultural Products Customers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trials</relationshipLabel>
    <relationshipName>Trials</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Initial_trial_re_trial__c.field-meta.xml
<CustomField>
    <fullName>Initial_trial_re_trial__c</fullName>
    <label>Initial trial/re-trial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial trial</fullName>
            </value>
            <value>
                <fullName>re-trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Paid_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Paid_Unpaid__c</fullName>
    <label>Paid/Unpaid</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Trial_block_size__c.field-meta.xml
<CustomField>
    <fullName>Trial_block_size__c</fullName>
    <label>Size of each Treatment block (hectares)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Trial_end_date__c.field-meta.xml
<CustomField>
    <fullName>Trial_end_date__c</fullName>
    <label>Trial end date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Trial_start_date__c.field-meta.xml
<CustomField>
    <fullName>Trial_start_date__c</fullName>
    <label>Trial start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/fields/Trial_status__c.field-meta.xml
<CustomField>
    <fullName>Trial_status__c</fullName>
    <label>Trial status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-trial</fullName>
                <default>true</default>
                <label>Pre-trial</label>
            </value>
            <value>
                <fullName>Ready for Delivery</fullName>
            </value>
            <value>
                <fullName>Planted</fullName>
            </value>
            <value>
                <fullName>Harvesting</fullName>
            </value>
            <value>
                <fullName>Closed Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial__c/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <label>Trial</label>
</RecordType>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/Trial_Harvest__c.object-meta.xml
<CustomObject>
    <label>Trial Harvest</label>
    <nameField>
        <displayFormat>TH-{000}</displayFormat>
        <label>Trial Harvests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Harvests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Harvest_date__c.field-meta.xml
<CustomField>
    <fullName>Harvest_date__c</fullName>
    <label>Harvest date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Treatment_Block__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Block__c</fullName>
    <label>Treatment Block</label>
    <referenceTo>Treatment_Block__c</referenceTo>
    <relationshipLabel>Trial Harvests</relationshipLabel>
    <relationshipName>Trial_Harvests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Trial__c.field-meta.xml
<CustomField>
    <fullName>Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trial</label>
    <referenceTo>Trial__c</referenceTo>
    <relationshipLabel>Trial Harvests</relationshipLabel>
    <relationshipName>Trial_Harvests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <label>Variety</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Harvest__c/fields/Yield__c.field-meta.xml
<CustomField>
    <fullName>Yield__c</fullName>
    <inlineHelpText>The weight in Kilogrammes</inlineHelpText>
    <label>Yield (KGs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Observation__c/Trial_Observation__c.object-meta.xml
<CustomObject>
    <label>Trial Observation</label>
    <nameField>
        <displayFormat>TRIAL-OBSV-{0000}</displayFormat>
        <label>Trial Observation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Observations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Trial_Observation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trial Observations</relationshipLabel>
    <relationshipName>Trial_Observations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Observation__c/fields/Observation_date__c.field-meta.xml
<CustomField>
    <fullName>Observation_date__c</fullName>
    <label>Observation date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Observation__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <label>Observations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Trial_Observation__c/fields/Trial__c.field-meta.xml
<CustomField>
    <fullName>Trial__c</fullName>
    <label>Trial</label>
    <referenceTo>Trial__c</referenceTo>
    <relationshipLabel>Trial Observations</relationshipLabel>
    <relationshipName>Trial_Observations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/TrialWorkflowTriggersTest.cls
@isTest
public class TrialWorkflowTriggersTest{
/*
This test class is made to test the triggers used within the Trial sales workflow.
_________________________________________________________________________________
|Object                | Triggger                                                 |
---------------------------------------------------------------------------------
|Trial                 | CreateTrialOppoortunity                                  |
|Trial Harvest         | CreateHarvestLookupToTrial                               |
|Trial Observation     | UdpateAccountOnTrialObservation                          |
|Treatment Blocks      | CreateControlBlock                                       |
---------------------------------------------------------------------------------
*/

    //test the creation of trial harvests
    public static testMethod void testTrialWorkflowTriggers() {
        
        //get RecordType
        List<RecordType> recType=[SELECT ID
                                  FROM RecordType  
                                  WHERE Name='Sanergy Agricultural Products Customers'];
                                  
        if(recType.size()>0){
        
         //insert account
         Account ac=new Account(
                          Name='test account',
                          CurrencyIsoCode='KES' ,
                          RecordTypeId=recType.get(0).id
         );
         insert ac;
         
        
         //insert trial
         Trial__c trial=new Trial__c(
             Account__c=ac.id,
             Trial_start_date__c=date.today(),
             Trial_end_date__c=date.today().addMonths(2),
             Trial_block_size__c='200',
             Trial_status__c='Pre-trial',
             Initial_trial_re_trial__c='Initial trial',
             Paid_Unpaid__c='Paid'
             
         );
         insert trial;
         
         //create Treatment block
         Treatment_Block__c tb=new Treatment_Block__c(
             Trial__c=trial.id,
             Crops_trialing_on__c='Test Crop',
             Variety__c='Variety',
             Type__c='Treatment Block',
             Block__c='Text Number',
             Block_size__c=200,
             Evergrow_Rate__c=200
         );
         
         insert tb;
         
         
         //create Trial Harvest
         Trial_Harvest__c th=new Trial_Harvest__c(
             Treatment_Block__c=tb.id,
             Date_of_Visit__c=date.today(),
             Harvest_date__c=date.today(),
             Yield__c=200
         );
         
         insert th;
         
         //create observation record
         Trial_Observation__c to=new Trial_Observation__c(
             Trial__c=trial.id,
             Observation_date__c=date.today(),
             Observations__c='Sample Observations'
         );
         
         insert to;
         
        }
        else{
            System.debug('Trial Not Created');
        
        }
       
    }
}