sfSandBoxCode/force-app/main/default/objects/Group_Details__c/Group_Details__c.object-meta.xml
<CustomObject>
    <label>Group Detail</label>
    <nameField>
        <displayFormat>GDTS-{0000}</displayFormat>
        <label>Group Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Config_Account__c.field-meta.xml
<CustomField>
    <fullName>Config_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Config Account</label>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Group Details</relationshipLabel>
    <relationshipName>Group_GLAs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Credit_Debit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Debit__c</fullName>
    <label>Credit / Debit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Inventory_Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Group__c</fullName>
    <label>Inventory Item Group</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipName>Group_GLAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVLOCADJ</fullName>
            </value>
            <value>
                <fullName>LOCMOVE</fullName>
            </value>
            <value>
                <fullName>PORCPT</fullName>
            </value>
            <value>
                <fullName>SOSHIP</fullName>
            </value>
            <value>
                <fullName>WOISS</fullName>
            </value>
            <value>
                <fullName>INVLOCADD</fullName>
            </value>
            <value>
                <fullName>CYCLECNT</fullName>
            </value>
            <value>
                <fullName>INVLOCSCRP</fullName>
            </value>
            <value>
                <fullName>WORCPT</fullName>
            </value>
            <value>
                <fullName>WOCLOSE</fullName>
            </value>
            <value>
                <fullName>WOISSEXP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <inlineHelpText>Count of items in stock In all locations</inlineHelpText>
    <label>Inventory Stock</label>
    <summarizedField>Inventory_Item_Location__c.Location_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory_Item_Location__c.Inventory_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Inventory Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Item_Location__c.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/Item_Inventory_Count__c.object-meta.xml
<CustomObject>
    <label>Item Inventory Count</label>
    <nameField>
        <displayFormat>AIC-{0000}</displayFormat>
        <label>Inventory Counts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Inventory Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Count_Value__c.field-meta.xml
<CustomField>
    <fullName>Count_Value__c</fullName>
    <formula>Physical_Count__c  *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Count Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>Inventory_Item__r.Currency_Config__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Inventory_Count__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Count__c</fullName>
    <label>Inventory Count</label>
    <referenceTo>Inventory_Count__c</referenceTo>
    <relationshipLabel>Item Inventory Counts</relationshipLabel>
    <relationshipName>Item_Inventory_Counts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Item Inventory Counts</relationshipLabel>
    <relationshipName>Item_Inventory_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Inventory_Stock__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Stock__c</fullName>
    <label>Inventory Stock</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Item_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Item Inventory Counts</relationshipLabel>
    <relationshipName>Item_Inventory_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Item_Lot__c.field-meta.xml
<CustomField>
    <fullName>Item_Lot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Item_Location__c</field>
            <operation>equals</operation>
            <valueField>Item_Location_Lot__c.Item_Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Item Inventory Counts</relationshipLabel>
    <relationshipName>Item_Inventory_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Physical_Count__c.field-meta.xml
<CustomField>
    <fullName>Physical_Count__c</fullName>
    <label>Physical Count</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Quantity_Variance__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Variance__c</fullName>
    <formula>Inventory_Stock__c  -  Physical_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Stock_Value__c.field-meta.xml
<CustomField>
    <fullName>Stock_Value__c</fullName>
    <formula>Inventory_Stock__c  *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stock Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>Inventory_Item__r.unit_cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/UoM__c.field-meta.xml
<CustomField>
    <fullName>UoM__c</fullName>
    <formula>Inventory_Item__r.Inventory_UoM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UoM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Value_Variance__c.field-meta.xml
<CustomField>
    <fullName>Value_Variance__c</fullName>
    <formula>Stock_Value__c  -  Count_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Value Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Inventory_Count__c/fields/Variance_Check__c.field-meta.xml
<CustomField>
    <fullName>Variance_Check__c</fullName>
    <formula>Lot_Quantity__c - Quantity_Variance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Check</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/ProcessCountVarianceController.cls
public class ProcessCountVarianceController{

    private ApexPages.StandardController standardController;
    private Inventory_Count__c inventoryCount;
    private List<CountWrapper> items {get; set;}

    public ProcessCountVarianceController(ApexPages.StandardController controller) {
        this.standardController = controller;
        this.inventoryCount = (Inventory_Count__c )standardController.getRecord();
    }
    
    public List<CountWrapper> getItems() {
        
        if(items == null) {
            items= new List<CountWrapper>();
            
            List<Item_Inventory_Count__c> counts = [Select Id, Name,Inventory_Item__c, Inventory_Stock__c, Physical_Count__c,
                                                    Quantity_Variance__c, UoM__c, Currency__c, Unit_Price__c, Stock_Value__c, 
                                                    Count_Value__c, Value_Variance__c, Item_Location__c, Item_Lot__c,
                                                    Inventory_Item__r.Name,
                                                    Inventory_Item__r.Item_Group__c
                                                    From Item_Inventory_Count__c
                                                    WHERE Inventory_Count__c = :inventoryCount.Id
                                                    AND Variance_Check__c >= 0
                                                    AND Processed__c = false
                                                   ];
            
            for(Item_Inventory_Count__c count : counts){
                CountWrapper itm = new CountWrapper(count);
                items.add(itm);
            }
        }
        return items;
    }
    
     public PageReference selectAll() {
         
        if(items != null){
            for(CountWrapper lg:items){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(items != null){
            for(CountWrapper lg:items){
                lg.selected=false;                
            }
        }
        return null;
    }
    
    public PageReference updateInventoryCounts(){
        
        if(items != null && items.size() > 0){

            integer processed = 0;
            
            for(CountWrapper item : items){
                
                if(item.selected){
                    String transactionId = null;
                        						
                    List<Group_Details__c> glas = [SELECT Id, Name, Credit_Debit__c, Config_Account__r.Lookup_Id__c
                                                   FROM Group_Details__c
                                                   WHERE Inventory_Item_Group__c = :item.item.Inventory_Item__r.Item_Group__c
                                                   AND Transaction_ID__c = 'CYCLECNT'
                                                   AND Is_GL_Account__c = true
                                                  ];
                    
                    Group_Details__c creditGl = null;
                    Group_Details__c debitGl = null;
                    
                    for(Group_Details__c gla : glas){
                        if(gla.Credit_Debit__c == 'Credit'){
                            creditGl = gla;
                        } else if(gla.Credit_Debit__c == 'Debit'){
                            debitGl = gla;
                        }
                    }
                    
                    if(debitGl != null && creditGl != null){
                        
                        String impact = 'I';
                        Group_Details__c glCred = creditGl;
                        Group_Details__c glDebit = debitGl;
                        Double quantity = item.item.Quantity_Variance__c;
                            
                        if(item.item.Quantity_Variance__c > 0){
                            impact = 'D';
                            glCred = debitGl;
                            glDebit = creditGl;
                        } else {
                            quantity = item.item.Quantity_Variance__c * -1;
                        }
                        
                        if(quantity > 0){
                            
                            Inventory_Transaction__c trans = new Inventory_Transaction__c(
                                Item__c = item.item.Inventory_Item__c,
                                Transaction_ID__c = 'CYCLECNT',
                                Transaction_Quantity__c = quantity,
                                Quantity_Impact__c = impact,
                                Location__c = item.item.Item_Location__c,
                                Location_Lot__c = item.item.Item_Lot__c,                        
                                Item_Unit_Price__c = item.item.Unit_Price__c,                        
                                Debit_Account__c = glDebit.Config_Account__r.Lookup_Id__c,
                                Credit_Account__c = glCred.Config_Account__r.Lookup_Id__c
                            );
                            
                        	insert trans;
                        }
                                                
                        item.item.Processed__c = true;
                        update item.item;
                        
                        processed ++;
                    } else {
                        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'The item configuration for ' + item.item.Inventory_Item__c + ' is missing either credit or debit GL Accounts');
                        ApexPages.addmessage(msg);
                        return null;
                    }
                }
            }
            
            if(processed > 0){
                return new PageReference('/' + inventoryCount.Id); 
            } else {
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No Items were Processed')); 
               return null;
            }
        }
         return null;
    }
        
    public class CountWrapper{
        
        public Boolean selected {get; set;}
        public Item_Inventory_Count__c item {get; set;}              
        
        public CountWrapper(Item_Inventory_Count__c itm) {
            item = itm;
        }
    }
}