sfSandBoxCode/force-app/main/default/objects/Group_Details__c/Group_Details__c.object-meta.xml
<CustomObject>
    <label>Group Detail</label>
    <nameField>
        <displayFormat>GDTS-{0000}</displayFormat>
        <label>Group Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Config_Account__c.field-meta.xml
<CustomField>
    <fullName>Config_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Config Account</label>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Group Details</relationshipLabel>
    <relationshipName>Group_GLAs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Credit_Debit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Debit__c</fullName>
    <label>Credit / Debit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Inventory_Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item_Group__c</fullName>
    <label>Inventory Item Group</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipName>Group_GLAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Is_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_GL_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is GL Account</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Group_Details__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVLOCADJ</fullName>
            </value>
            <value>
                <fullName>LOCMOVE</fullName>
            </value>
            <value>
                <fullName>PORCPT</fullName>
            </value>
            <value>
                <fullName>SOSHIP</fullName>
            </value>
            <value>
                <fullName>WOISS</fullName>
            </value>
            <value>
                <fullName>INVLOCADD</fullName>
            </value>
            <value>
                <fullName>CYCLECNT</fullName>
            </value>
            <value>
                <fullName>INVLOCSCRP</fullName>
            </value>
            <value>
                <fullName>WORCPT</fullName>
            </value>
            <value>
                <fullName>WOCLOSE</fullName>
            </value>
            <value>
                <fullName>WOISSEXP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item__c/fields/Item_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commodity Code</label>
    <referenceTo>Inventory_Item_Group__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/Inventory_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Item Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Item Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Item_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Site</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Item Locations</relationshipLabel>
    <relationshipName>Inventory_Item_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Inventory Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Item_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Unit_Price__c</fullName>
    <description>Unit Price For the Transaction</description>
    <label>Item Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Item__c</field>
            <operation>equals</operation>
            <valueField>Inventory_Item_Location__c.Inventory_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Location_Lot__c.field-meta.xml
<CustomField>
    <fullName>Location_Lot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item_Location_Lot__c.Item_Location__r.Inventory_Item__c</field>
            <operation>equals</operation>
            <valueField>$Source.Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item_Location_Lot__c</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventory Transactions</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <description>Indicates what transaction this is i.e. Inventory Adjust, Work Order Issue, Purchase Order Receipt</description>
    <inlineHelpText>INVLOCADJ (Inventory Adjust), WOISS (Work Order Issue), PORCPT (Purchase Order Receipt) , SOSHIP (Sales Order Shipment), LOCMOVE (Location Move), CYCLECNT (Cycle Count), INVLOCADD (Inventory Location Add), INVLOCSCRP (Inventory Location Scrap)</inlineHelpText>
    <label>Transaction ID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVLOCADJ</fullName>
            </value>
            <value>
                <fullName>LOCMOVE</fullName>
            </value>
            <value>
                <fullName>PORCPT</fullName>
            </value>
            <value>
                <fullName>PORCPTRVS</fullName>
            </value>
            <value>
                <fullName>PORVRS</fullName>
            </value>
            <value>
                <fullName>SOSHIP</fullName>
            </value>
            <value>
                <fullName>SORVRS</fullName>
            </value>
            <value>
                <fullName>WOISS</fullName>
            </value>
            <value>
                <fullName>WOISSRVS</fullName>
            </value>
            <value>
                <fullName>WORVRS</fullName>
            </value>
            <value>
                <fullName>CYCLECNT</fullName>
            </value>
            <value>
                <fullName>INVLOCADD</fullName>
            </value>
            <value>
                <fullName>INVLOCSCRP</fullName>
            </value>
            <value>
                <fullName>WORCPT</fullName>
            </value>
            <value>
                <fullName>WORCPTRVS</fullName>
            </value>
            <value>
                <fullName>WOISSEXP</fullName>
            </value>
            <value>
                <fullName>WOISSEXPRVS</fullName>
            </value>
            <value>
                <fullName>WOCLOSE</fullName>
            </value>
            <value>
                <fullName>INVISSUE</fullName>
            </value>
            <value>
                <fullName>UNITPRICECHANGE</fullName>
            </value>
            <value>
                <fullName>SOISS</fullName>
                <isActive>false</isActive>
                <label>SOISS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Inventory_Transaction__c/fields/Transaction_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Quantity__c</fullName>
    <inlineHelpText>The quantity affecting the transaction</inlineHelpText>
    <label>Transaction Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/Item_Location_Lot__c.object-meta.xml
<CustomObject>
    <label>Item Location Lot</label>
    <nameField>
        <label>Inventory Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Location Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Item_Location__c.field-meta.xml
<CustomField>
    <fullName>Item_Location__c</fullName>
    <label>Inventory Item Location</label>
    <referenceTo>Inventory_Item_Location__c</referenceTo>
    <relationshipLabel>Item Location Lots (Batches)</relationshipLabel>
    <relationshipName>Item_Location_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Item_Location_Lot__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>17</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/OpportunityShipController.cls
public class OpportunityShipController {
    
    @TestVisible  private ApexPages.StandardController standardController;
    @TestVisible  private Opportunity opportunity;
    @TestVisible public List<DeliveryNoteWrapper> wrpDeliveryItems {get; set;}
    Public List<ProductWrapper> products {get; set;}
    public List<Inventory_Transaction__c> invItems {get; set;}
    public OpportunityShipController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        this.opportunity = (Opportunity)standardController.getRecord();
        getProducts();
        getInvItemsForDeliveryNote();
        /*
this.opportunity = 
[
SELECT Id, Name, Account, CloseDate
FROM Opportunity
WHERE Id := opportunity.Id
];
*/
    }
    
    public PageReference selectAll() {
        if(products!=null){
            for(ProductWrapper prod : products){
                prod.selected=true;
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(products!=null){
            for(ProductWrapper prod : products){
                prod.selected=false;
            }
        }
        return null;
    }
    
    @TestVisible public List<ProductWrapper> getProducts() {
        if(products == null) {
            products= new List<ProductWrapper>();
            
            @TestVisible List<OpportunityLineItem> lineItems = 
                [
                    SELECT Id, Name, Inventory_Item_Location__c, Quantity,
                    UnitPrice, TotalPrice, Product2Id, Issued__c, Quantity_Shipped__c
                    From OpportunityLineItem
                    WHERE OpportunityId = :opportunity.Id AND Issued__c = false
                ];
            
            for(OpportunityLineItem lineItem : lineItems){
                ProductWrapper wrapper = new ProductWrapper(lineItem);
                products.add(wrapper);
            } 
        }
        return products;
    }
    
    public PageReference shipFromInventory(){
        if(products != null && products.size() > 0){
            integer selected = 0;
            
            for(ProductWrapper prod : products){
                if(prod.selected && !prod.product.Issued__c){
                    if(prod.product2 != null && prod.product2.Use_Inventory__c == true && prod.product2.Inventory_Product__c != null){
                        List<Group_Details__c> glas = [SELECT Id, Name, Credit_Debit__c, Config_Account__r.Lookup_Id__c
                                                       FROM Group_Details__c
                                                       WHERE Inventory_Item_Group__c = :prod.product2.Inventory_Product__r.Item_Group__c
                                                       AND Transaction_ID__c = 'SOSHIP'
                                                       AND Is_GL_Account__c = true
                                                      ];
                        
                        Group_Details__c creditGl = null;
                        Group_Details__c debitGl = null;
                        
                        for(Group_Details__c gla : glas){
                            if(gla.Credit_Debit__c == 'Credit'){
                                creditGl = gla;
                            } else if(gla.Credit_Debit__c == 'Debit'){
                                debitGl = gla;
                            }
                        }
                        
                        if(debitGl != null && creditGl != null){
                            @TestVisible Inventory_Transaction__c trans = new Inventory_Transaction__c(
                                Item__c = prod.product2.Inventory_Product__c,
                                Opportunity__C = opportunity.Id,
                                Transaction_ID__c = 'SOSHIP',
                                Location__c = prod.location,
                                Location_Lot__c = prod.lot,
                                Transaction_Quantity__c = prod.shipQuantity,
                                Item_Unit_Price__c = prod.product2.Inventory_Product__r.unit_cost__c,
                                Quantity_Impact__c = 'D',
                                Debit_Account__c = debitGl.Config_Account__r.Lookup_Id__c,
                                Credit_Account__c = creditGl.Config_Account__r.Lookup_Id__c,
                                Dimension_1__c = prod.product2.Inventory_Product__r.Item_Group__r.Dimension_1__r.lookup_ID__c,
                                Dimension_2__c = prod.product2.Inventory_Product__r.Item_Group__r.Dimension_2__r.lookup_ID__c,
                                Dimension_3__c = prod.product2.Inventory_Product__r.Item_Group__r.Dimension_3__r.lookup_ID__c,
                                Dimension_4__c = prod.product2.Inventory_Product__r.Item_Group__r.Dimension_4__r.lookup_ID__c,
                                Comments__c = opportunity.Name
                            );
                            
                            try{
                                insert trans;
                            }catch(Exception e){
                                ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
                                return null;
                            }
                            
                            prod.product.Quantity_Shipped__c += prod.shipQuantity;
                            if(prod.product.Quantity_Shipped__c == prod.product.Quantity){
                                prod.product.Issued__c = true;
                            }
                            
                            update prod.product;
                            
                            selected ++;
                        } else {
                            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'The item configuration does not have both credit and debit GL Accounts');
                            ApexPages.addmessage(msg);
                        }
                        
                    } else {
                        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'The item is not an inventory item');
                        ApexPages.addmessage(msg);
                    }
                }
            }
            
            if(selected > 0){
                return new PageReference('/' + opportunity.Id);  
            } else{
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'None of the items selected were issued');
                ApexPages.addmessage(msg);
            }
        }
        return null;
    }
    
    public List<DeliveryNoteWrapper> getInvItemsForDeliveryNote(){
        //get Items that have been Issued to shipped
        wrpDeliveryItems = new List<DeliveryNoteWrapper>();
        invItems = new List<Inventory_Transaction__c>();
        invItems =
            [
                SELECT Id, Name, CreatedDate, Item__r.Name,Transaction_Quantity__c,Item__r.Inventory_UoM__r.Name
                FROM Inventory_Transaction__c
                WHERE Opportunity__C =: opportunity.Id
            ];
        system.debug('invItems = ' + invItems);
        Integer intCounter = 0;
        for(Inventory_Transaction__c item : invItems){
            intCounter = intCounter + 1;
            wrpDeliveryItems.add(new DeliveryNoteWrapper(intCounter, item));
        }
        return wrpDeliveryItems;
    }
    
    @TestVisible public List<SelectOption> getSites() {
        List<SelectOption> sites= new List<SelectOption>();
        SelectOption defopt = new SelectOption('NA', '----------');
        sites.add(defopt);
        
        @TestVisible List<Inventory_Location__c> locations = [Select Id, Name, Description__c
                                                              From Inventory_Location__c
                                                             ];
        for(Inventory_Location__c location : locations){
            SelectOption option = new SelectOption(location.Id, location.Name);
            sites.add(option);
        }
        
        return sites;
    }
    
    @TestVisible public class ProductWrapper{
        @TestVisible public OpportunityLineItem product {get; set;}
        @TestVisible public Product2 product2 {get; set;}
        @TestVisible public String site {get; set;}
        @TestVisible public String location {get; set;}
        @TestVisible public String lot {get; set;}
        @TestVisible public Item_Location_Lot__c selectedLot {get; set;}
        @TestVisible public Boolean selected {get; set;}
        @TestVisible public List<SelectOption> locations {get; set;}
        @TestVisible public List<SelectOption> lots {get; set;}
        @TestVisible public Decimal pendingQuantity {get; set;}
        @TestVisible public Decimal shipQuantity {get; set;}
        
        @TestVisible public ProductWrapper(OpportunityLineItem prod) {
            product = prod;
            selected = true;
            
            product2 = [SELECT Id, Name, Use_Inventory__c, Inventory_Product__c, Inventory_Product__r.Name,
                        Inventory_Product__r.unit_cost__c,Inventory_Product__r.Item_Group__c,
                        Inventory_Product__r.Item_Group__r.Dimension_1__r.lookup_ID__c,
                        Inventory_Product__r.Item_Group__r.Dimension_2__r.lookup_ID__c,
                        Inventory_Product__r.Item_Group__r.Dimension_3__r.lookup_ID__c,
                        Inventory_Product__r.Item_Group__r.Dimension_4__r.lookup_ID__c
                        FROM Product2
                        WHERE Id = :prod.Product2Id
                       ];
            
            if(prod.Quantity_Shipped__c == null){
                prod.Quantity_Shipped__c = 0;
            }    
            this.pendingQuantity = prod.Quantity - prod.Quantity_Shipped__c;            
            this.shipQuantity = this.pendingQuantity;
        }
        
        @TestVisible public void setLocations() {
            locations = new List<SelectOption>();
            SelectOption defopt = new SelectOption('NA', '----------');
            locations.add(defopt);
            
            if(site != null && !site.equals('NA')){
                List<Inventory_Item_Location__c> locs = [Select Id, Name
                                                         From Inventory_Item_Location__c
                                                         WHERE Inventory_Item__c = :this.product2.Inventory_Product__c
                                                         AND Location__c = :this.site
                                                        ];
                
                for(Inventory_Item_Location__c location : locs){
                    SelectOption option = new SelectOption(location.Id, location.Name);
                    locations.add(option);
                }
            }
        }
        
        @TestVisible public void setLots() {
            lots = new List<SelectOption>();
            SelectOption defopt = new SelectOption('NA', '----------');
            lots.add(defopt);
            
            if(location != null && !location.equals('NA')){
                List<Item_Location_Lot__c> lts = [Select Id, Name
                                                  From Item_Location_Lot__c
                                                  WHERE Item_Location__c = :this.location
                                                 ];
                
                for(Item_Location_Lot__c lot : lts){
                    SelectOption option = new SelectOption(lot.Id, lot.Name);
                    lots.add(option);
                }
            }
        }
        
        @TestVisible public void selectLot() {
            if(lot != null && !lot.equals('NA')){
                selectedLot = [Select Id, Name,Quantity__c
                               From Item_Location_Lot__c
                               WHERE id = :this.lot
                              ];
            }
        }
    }    
    
    public class DeliveryNoteWrapper{
        //Inventory Items to be delivered
        public Integer invItemIndex {get; set;}
        public Inventory_Transaction__c invItem {get; set;}
        public DeliveryNoteWrapper(Integer intIndex, Inventory_Transaction__c inv){
            invItemIndex = intIndex;
            invItem = inv;
        }
    }
}