sfSandBoxCode/force-app/main/default/objects/Inventory_UoM__c/Inventory_UoM__c.object-meta.xml
<CustomObject>
    <label>Inventory UoM</label>
    <nameField>
        <label>UoM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory UoMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>The description of the Item</description>
    <inlineHelpText>The description of the Item. This is the name that will be displayed on Purchase Order Documents, etc</inlineHelpText>
    <label>Item Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_UoM__c.field-meta.xml
<CustomField>
    <fullName>Purchase_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Purchase Order Items (Purchase UoM)</relationshipLabel>
    <relationshipName>Purchase_Order_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Unit_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Net_Price__c</fullName>
    <formula>IF(Vatable__c = true,
   IF(VAT_Inclusive__c = true,
         Item_Cost__c  /( (VALUE(TEXT(VAT_Percentage__c))+100)/100 ) ,
         Item_Cost__c 
      ),
     Item_Cost__c   
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Net Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <label>Vendor Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Vendor_Description__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Description__c</fullName>
    <label>Vendor Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement__c/Special_Procurement__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request</label>
    <nameField>
        <displayFormat>SPR-{00000000}</displayFormat>
        <label>Special Procurement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/Special_Procurement_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Special Payment Request Line Item</label>
    <nameField>
        <displayFormat>SPR-LI-{0000000}</displayFormat>
        <label>Special Procurement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Payment Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Net_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Amount__c</fullName>
    <formula>Unit_Net_Price__c *  Quantity_Requested__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The total quote amount less VAT</inlineHelpText>
    <label>Net Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Item</label>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Special Payment Request Line Items</relationshipLabel>
    <relationshipName>Special_Payment_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <description>Quantity to be requested</description>
    <inlineHelpText>Quantity to be requested</inlineHelpText>
    <label>Quantity Requested</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Special_Procurement__c.field-meta.xml
<CustomField>
    <fullName>Special_Procurement__c</fullName>
    <description>Relationship between Special Procurement  &amp; Special Procurement Line Item</description>
    <label>Special Procurement</label>
    <referenceTo>Special_Procurement__c</referenceTo>
    <relationshipName>Special_Procurement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Total Price which has been approved</description>
    <inlineHelpText>The Total Price which has been approved</inlineHelpText>
    <label>Total Approved Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Total_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_VAT__c</fullName>
    <formula>Unit_VAT_Amount__c *  Quantity_Requested__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A final price after deducting all discounts and rebates.</inlineHelpText>
    <label>Total VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Special_Procurement_Line_Item__c/fields/Unit_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Net_Price__c</fullName>
    <formula>IF(Vatable__c = true, 
IF(VAT_Inclusive__c = true, 
Unit_Price__c /( (VALUE(TEXT(VAT_Percentage__c))+100)/100 ) , 
Unit_Price__c 
), 
Unit_Price__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/GenerateSPRPODocument.cls
public class GenerateSPRPODocument {
  
    public Special_Procurement__c spr {get; set;}
    
    private ApexPages.StandardController standardController;
    
    public List<Special_Procurement_Line_Item__c> sprLineItems {get; set;}
    
    public List<String> terms {get; set;}
    
    public Decimal itemSubtotal {get; set;}
    public Decimal totalTax {get; set;}
    public Decimal totalAmount {get; set;}
    public static Integer rank=1;
    @TestVisible public String sprCreatedDate {get; set;}
    
    public List<SPRLineWrapper> sprlineWrapper {get; set;}
   
    
    public GenerateSPRPODocument(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        sprlineWrapper =new List<SPRLineWrapper>();
        
        //initialize models
        spr =(Special_Procurement__c )standardController.getRecord(); 
        
        this.sprLineItems = [SELECT id, Purchase_Order_Item__r.Item_Description__c,Quantity_Requested__c,
                             Purchase_Order_Item__r.Vendor_Code__c,
                             Purchase_Order_Item__r.Purchase_UoM__r.Name, Unit_Price__c ,Item__c,
                             Purchase_Order_Item__r.Vendor_Description__c,Total_Price__c, Unit_Net_Price__c ,
                             Net_Total_Amount__c, Total_VAT__c
                             FROM Special_Procurement_Line_Item__c
                             WHERE Special_Procurement__c =:spr.id];
       
        terms=new List<String>();
                            
        itemSubtotal =0; 
        totalTax =0;
        totalAmount=0;
        
        init(this.sprLineItems);
        system.debug('spr ID:' + spr.id +'*** spr date' + spr.CreatedDate);
        
        if(this.sprCreatedDate == NULL){
            this.sprCreatedDate = System.now().format('YYYY-MM-DD');
        } else
        {
           this.sprCreatedDate = spr.CreatedDate.format('YYYY-MM-DD'); 
        }
        //buildTermsAndConditions();
    }
    
     private void init(List<Special_Procurement_Line_Item__c> spr_line){
        for(Special_Procurement_Line_Item__c sprLine : spr_line){
            this.itemSubtotal += sprLine.Total_Price__c; 
            this.totalTax += sprLine.Total_VAT__c.setScale(2);
            this.totalAmount += sprLine.Total_Price__c;
            
            SPRLineWrapper sprw=new SPRLineWrapper(sprLine );
            this.SPRLineWrapper.add(sprw);
            
        }
    }
    
    /*
    private void buildTermsAndConditions(){
        for(SPRLineWrapper sprline: this.sprlineWrapper){
            if(sprline.sprLineItem.Terms_Conditions__c!=null){
                this.terms.add('#'+sprline.rnk+' - '+sprline.sprLineItem.Terms_Conditions__c);
            }
        }
    }
*/


    
    
    public class SPRLineWrapper{
    
        public Special_Procurement_Line_Item__c sprLineItem {get; set;}
        public Integer rnk  {get; set;}
        
        public SPRLineWrapper(Special_Procurement_Line_Item__c sprline){
            this.sprLineItem=sprline;
            rnk=rank;
            rank++;
        }
    } 
}