sfSandBoxCode/force-app/main/default/objects/Inventory_UoM__c/Inventory_UoM__c.object-meta.xml
<CustomObject>
    <label>Inventory UoM</label>
    <nameField>
        <label>UoM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory UoMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>Purchase Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>The description of the Item</description>
    <inlineHelpText>The description of the Item. This is the name that will be displayed on Purchase Order Documents, etc</inlineHelpText>
    <label>Item Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_UoM__c.field-meta.xml
<CustomField>
    <fullName>Purchase_UoM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase UoM</label>
    <referenceTo>Inventory_UoM__c</referenceTo>
    <relationshipLabel>Purchase Order Items (Purchase UoM)</relationshipLabel>
    <relationshipName>Purchase_Order_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Unit_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Net_Price__c</fullName>
    <formula>IF(Vatable__c = true,
   IF(VAT_Inclusive__c = true,
         Item_Cost__c  /( (VALUE(TEXT(VAT_Percentage__c))+100)/100 ) ,
         Item_Cost__c 
      ),
     Item_Cost__c   
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Net Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <label>Vendor Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Item__c/fields/Vendor_Description__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Description__c</fullName>
    <label>Vendor Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Purchase_Order_Item__c.Vendor__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <label>Quantity Requested</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Total_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Net_Price__c</fullName>
    <formula>Unit_Net_Price__c *  Quantity_Requested__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Price, exclusive of VAT if applicable</inlineHelpText>
    <label>Total Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Total_VAT_Amount__c +  Total_Net_Price__c</formula>
    <inlineHelpText>Total amount inclusive of VAT if applicable</inlineHelpText>
    <label>Total Gross Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Unit_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Net_Price__c</fullName>
    <formula>IF(VAT_inclusive__c = true, 
   Unit_Price__c /(  (VALUE(TEXT(VAT_Percentage__c))+100)/100   ) ,
   Unit_Price__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/UoM__c.field-meta.xml
<CustomField>
    <fullName>UoM__c</fullName>
    <formula>Purchase_Order_Item__r.Purchase_UoM__r.Name</formula>
    <label>UoM</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>IF(Vatable__c = true, 
  IF( VAT_inclusive__c = true, 
                       Unit_Price__c - (Unit_Price__c /((VALUE(TEXT(VAT_Percentage__c))+100)/100)) ,
                       Unit_Price__c * (VALUE(TEXT(VAT_Percentage__c))/100)) , 
   0
)</formula>
    <inlineHelpText>Total VAT Amount</inlineHelpText>
    <label>Unit VAT Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/GeneratePODocument.cls
public class GeneratePODocument{
  
    public Purchase_Order__c po {get; set;}
    
    private ApexPages.StandardController standardController;
    
    public List<Purchase_Order_Line_Item__c> poLineItems {get; set;}
    
    public List<String> terms {get; set;}
    
    public Decimal itemSubtotal {get; set;}
    public Decimal totalTax {get; set;}
    public Decimal totalAmount {get; set;}
    public static Integer rank=1;
    
    public List<PoLineWrapper> polineWrapper {get; set;}
   
    
    public GeneratePODocument(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        polineWrapper =new List<PoLineWrapper>();
        
        //initialize models
        po =(Purchase_Order__c )standardController.getRecord(); 
        
        this.poLineItems = [SELECT Purchase_Order_Item__r.Item_Description__c, Quantity_Requested__c,Purchase_Order_Item__r.Vendor_Code__c,
                            Purchase_Order_Item__r.Purchase_UoM__r.Name,Unit_Price__c,Item__c,UoM__c,Purchase_Order_Item__r.Vendor_Description__c,
                            Total_Price__c, Terms_Conditions__c,Unit_Net_Price__c ,Total_Net_Price__c
                            FROM Purchase_Order_Line_Item__c
                            WHERE Purchase_Order__c=:po.id];
       
        terms=new List<String>();
                            
        itemSubtotal =0; 
        totalTax =0;
        totalAmount=0;
        
        init(this.poLineItems);
        
        buildTermsAndConditions();
       
    }
    
    private void init(List<Purchase_Order_Line_Item__c> po_line){
        for(Purchase_Order_Line_Item__c poLine : po_line){
            this.itemSubtotal += poLine.Total_Price__c; 
            //this.totalTax += (poLine.VAT_Amount__c * poLine.Quantity_Requested__c).setScale(2);
            this.totalAmount += poLine.Total_Price__c;
            
            PoLineWrapper pow=new PoLineWrapper(poLine );
            this.polineWrapper.add(pow);
            
        }
    }
    
    private void buildTermsAndConditions(){
        for(PoLineWrapper poline: this.polineWrapper){
            if(poline.poLineItem.Terms_Conditions__c!=null){
                this.terms.add('#'+poline.rnk+' - '+poline.poLineItem.Terms_Conditions__c);
            }
        }
    }
    
   
    
    public class PoLineWrapper{
    
        public Purchase_Order_Line_Item__c poLineItem {get; set;}
        public Integer rnk  {get; set;}
        
        public PoLineWrapper(Purchase_Order_Line_Item__c poline){
            this.poLineItem=poline;
            rnk=rank;
            rank++;
        }
    } 
}