sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/Case_Timeliness__c.object-meta.xml
<CustomObject>
    <label>Case Timelines</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Agreed_Upon_Time_For_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Upon_Time_For_Resolution__c</fullName>
    <inlineHelpText>Time in days</inlineHelpText>
    <label>Agreed Upon Time For Resolution(Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Priority_Level__c</fullName>
    <label>Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/DecisionIfOppStageIsBillingOrClosedtest.cls
@isTest(SeeAllData=true)
private class DecisionIfOppStageIsBillingOrClosedtest{


     /*------------------Test Class for ValidatCaseClosureAgainstWO_SO Trigger------------------------- */  
      static testMethod void DecisionIfOppStageIsBillingOrClosedtest() {
      
          //get maintenence case recordtype
          List<RecordType> rType=[SELECT ID FROM RecordType
                                            WHERE Name='Maintenance Cases'];
          
          
          //get an account                                  
          List<Account> acc=[SELECT ID FROM Account WHERE Type='Customer' LIMIT 1];
          
          //get a location and a toilet
          List<Toilet__c> toilet=[SELECT Id, Location__c FROM Toilet__c LIMIT 1];
           
          List<Toilet__c> t = [SELECT id,Name,Location__c,location__r.name,Opportunity__r.AccountId
                                           FROM Toilet__c 
                         WHERE Location__c !='' Limit 1];
     System.debug('Toilet: '+t.get(0).name+'  Location: '+t.get(0).location__r.name);
     
          List<Case_Timeliness__c> tm = [SELECT Name,Agreed_Upon_Time_For_Resolution__c,Priority_Level__c,Case_Category__c
                                           FROM Case_Timeliness__c
                                    WHERE Case_Category__c='Logistics' Limit 1];
          
          //create a maintenance case opportunity
          Opportunity op=new Opportunity(
              name='x',
              AccountId=t.get(0).Opportunity__r.AccountId,
              recordTypeId=rType.get(0).id,
              CloseDate=Date.today(),
              StageName='Open',
              Billed_Entity__c='FLO'
              
          );
          
          insert op;
          
           //Create a Case
           Case ces=new Case(); 
     ces.Case_Type__c=tm.get(0).Id;    
     ces.Status='Open';
     ces.Case_Root_Cause__c='Logistics error'; 
     ces.Toilet__c=t.get(0).Id;
     ces.Location__c=t.get(0).Location__c;
   //ces.Date_Reported__c=DateTime.now(); 
     ces.Case_Opportunity__c=op.Id;  
     insert ces;  
         /* Case c=new Case(
              Case_ID__c='031 - Squat Support',
              Type='Feature Request',
              Reason='Other',
              Origin='Fresh Life Operator',
              Location__c=toilet.get(0).location__c,
              Toilet__c=toilet.get(0).id,
             // Date_Reported__c=Date.today(),
              Status='Open',
              Priority='Medium',
              Case_opportunity__c=op.id
          );
          
          insert c; */
           
   
          ces.Status='Closed';
          update ces;
                                      
             
      }
}