sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/Case_Timeliness__c.object-meta.xml
<CustomObject>
    <label>Case Timelines</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Active_On_USSD__c.field-meta.xml
<CustomField>
    <fullName>Active_On_USSD__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active On USSD</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Agreed_Upon_Time_For_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Upon_Time_For_Resolution__c</fullName>
    <inlineHelpText>Time in days</inlineHelpText>
    <label>Agreed Upon Time For Resolution(Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Priority_Level__c</fullName>
    <label>Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/USSD_Case_Categories__c.field-meta.xml
<CustomField>
    <fullName>USSD_Case_Categories__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USSD Case Categories</label>
    <referenceTo>Ussd_Cate_C__c</referenceTo>
    <relationshipLabel>Cases Timelines</relationshipLabel>
    <relationshipName>Cases_Timelines</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/USSD_Category_Text__c.field-meta.xml
<CustomField>
    <fullName>USSD_Category_Text__c</fullName>
    <formula>USSD_Case_Categories__r.category_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USSD Category Text</label>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/USSD_TEXT__c.field-meta.xml
<CustomField>
    <fullName>USSD_TEXT__c</fullName>
    <label>USSD TEXT</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Ussd_Cate_C__c/Ussd_Cate_C__c.object-meta.xml
<CustomObject>
    <label>USSD Case Categories</label>
    <nameField>
        <displayFormat>USSD-CAT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>USSD Case Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Ussd_Cate_C__c/fields/USSD_Row_Number__c.field-meta.xml
<CustomField>
    <fullName>USSD_Row_Number__c</fullName>
    <description>Row Number to be displayed on USSD</description>
    <inlineHelpText>Row Number to be displayed on USSD</inlineHelpText>
    <label>USSD Row Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/REST_CaseTimelines.cls
//Get all Case Timelines for a specific Case Category
@RestResource(urlMapping='/api/casecategory/*/casetimelines')
global with sharing class REST_CaseTimelines {
    
    @HttpGet
    global static List<CaseTimelines> getCaseTimeliness() {
        
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        
        //String caseCategoryId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);        
        String caseCategoryId = request.requestURI.substringBetween('/api/casecategory/','/casetimelines');
        
        List<CaseTimelines> caseTimelines = new List<CaseTimelines>();
        
        //Get Case Timeliness
        List<Case_Timeliness__c> results =  [SELECT Id, Name, USSD_TEXT__c,USSD_Category_Text__c,Active_On_USSD__c,
                                             Case_Category__c,Agreed_Upon_Time_For_Resolution__c,Priority_Level__c,
                                             USSD_Case_Categories__c,USSD_Case_Categories__r.USSD_Row_Number__c
                                             FROM Case_Timeliness__c
                                             WHERE USSD_Case_Categories__c =: caseCategoryId
                                             ORDER BY USSD_Case_Categories__r.USSD_Row_Number__c ASC];        
        
        if(results != null && results.size()> 0){
            
            for(Case_Timeliness__c timeline : results){
                
                //Case Timeliness
                CaseTimelines caseTimeline = new CaseTimelines();                
                caseTimeline.guid = timeline.Id;
                caseTimeline.caseTimelineName = timeline.Name;
                caseTimeline.shortenedCaseTimelineName = timeline.USSD_TEXT__c;
                caseTimeline.displayCaseTimelineNameOnAndroid = timeline.Active_On_USSD__c;
                caseTimeline.maximumDaysToResolveCase = timeline.Agreed_Upon_Time_For_Resolution__c;
                caseTimeline.priorityLevel = timeline.Priority_Level__c;
                caseTimeline.caseCategoryId = timeline.USSD_Case_Categories__c;
                caseTimeline.caseCategoryName = timeline.USSD_Category_Text__c;
                caseTimeline.caseCategoryRowNumber = timeline.USSD_Case_Categories__r.USSD_Row_Number__c;
                caseTimelines.add(caseTimeline);
            }
        }
        
        System.debug('CASE TIMELINES: = ' + caseTimelines);                
        
        return caseTimelines;
    }
    
    global class CaseTimelines {        
        public String guid;
        public String caseTimelineName;
        public String shortenedCaseTimelineName;
        public Boolean displayCaseTimelineNameOnAndroid;        
        public Decimal maximumDaysToResolveCase;
        public String priorityLevel;        
        public String caseCategoryId;
        public String caseCategoryName;
        public Decimal caseCategoryRowNumber;
        
    }    
    
}