sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/Case_Timeliness__c.object-meta.xml
<CustomObject>
    <label>Case Timelines</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Case_Timeliness__c/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location where one or more Fresh Life toilets are located</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location__c/fields/of_Toilets__c.field-meta.xml
<CustomField>
    <fullName>of_Toilets__c</fullName>
    <label># of Toilets</label>
    <summaryForeignKey>Toilet__c.Location__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Team__c/Location_Team__c.object-meta.xml
<CustomObject>
    <description>Shows Team Assigned to a Location</description>
    <label>Location Team</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Location_Team__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Relates Teams to Locations</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Team</relationshipLabel>
    <relationshipName>Location_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Team__c/fields/Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Member_Role__c</fullName>
    <description>Role of the Assigned Person</description>
    <inlineHelpText>What is the Role of the Assigned Team Member</inlineHelpText>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Marketing Associate</fullName>
            </value>
            <value>
                <fullName>Assistant Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Location_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team Member assigned  to Location</description>
    <inlineHelpText>Select the Team Member assigned to this Location</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Location_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/Toilet__c.object-meta.xml
<CustomObject>
    <label>Toilet</label>
    <nameField>
        <label>Toilet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toilets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the toilet</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Toilet__c/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Toilet</label>
    <referenceTo>Toilet__c</referenceTo>
    <relationshipLabel>Toilets</relationshipLabel>
    <relationshipName>Toilets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CaseFieldOfficerTriggerTest.cls
@isTest(seealldata=true)
public class CaseFieldOfficerTriggerTest {
 static testMethod void testInstance(){
     
 // Generate test model
     
    List<Location_Team__c> loc = [SELECT Member_Role__c,Team_Member__c,Location__c, Location__r.of_Toilets__c
                                           FROM Location_Team__c
                                            WHERE Location__r.of_Toilets__c > 0
                                            AND (Member_Role__c='Associate'
                                            OR Member_Role__c='Assistant Manager')
                                            LIMIT 10];     
                                            
    List<Toilet__c> t = [SELECT id,Name,Location__c,location__r.name
                         FROM Toilet__c 
                         WHERE Location__c= :loc.get(0).Location__c
                         Limit 1];
     System.debug('Toilet: '+t.get(0).name+'  Location: '+t.get(0).location__r.name);
    
     List<Case_Timeliness__c> tm = [SELECT Name,Case_Category__c
                                           FROM Case_Timeliness__c
                                            WHERE Case_Category__c='Logistics' Limit 10];
     Case ces=new Case(); 
     ces.Toilet__c=t.get(0).Id;
     ces.Case_Type__c=tm.get(0).Id;    
     
     ces.Case_Root_Cause__c='Logistics error'; 
     
     ces.Location__c=t.get(0).Location__c;/*
     ces.Case_Field_Officer__c='';
     ces.Case_Senior_Field_Officer__c='';   */        
     insert ces;  
    
     // Perform test logic and Assert logic
    /*for(Case c:[SELECT Location__c FROM Case WHERE ID=:ces.Id]) {

                c.Location__c = t.get(0).Location__c;

            }*/
    // update ces;
    // System.assertEquals(ces.Location__c,t.get(0).Location__c);
    
    for ( Location_Team__c lc:[SELECT Member_Role__c,Team_Member__c FROM Location_Team__c WHERE ID=:loc.get(0).Id ] ){
    
    
             if(lc.Member_Role__c=='Assistant Manager'){
                  for(Case c:[SELECT Case_Senior_Field_Officer__c FROM Case WHERE ID=:ces.Id]) {

                     c.Case_Senior_Field_Officer__c = loc.get(0).Team_Member__c;
                       update ces;

                    }
                                 
                }
         //System.assertEquals(ces.Case_Senior_Field_Officer__c,null);
         
         
            if(lc.Member_Role__c=='Associate'){
                for(Case c:[SELECT Case_Field_Officer__c FROM Case WHERE ID=:ces.Id]) {

                     c.Case_Field_Officer__c = loc.get(0).Team_Member__c;

                    }              
                           
             }
         update ces;
       //  System.assertEquals(ces.Case_Field_Officer__c,null);
        }
   }
}