sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/Casuals_Job_Assignment__c.object-meta.xml
<CustomObject>
    <label>Job Spec Assignment</label>
    <nameField>
        <displayFormat>JOB-ASSG-{000000}</displayFormat>
        <label>Job Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor-Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual__c.field-meta.xml
<CustomField>
    <fullName>Casual__c</fullName>
    <label>Contractor Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please ensure this contractor does not have any open jobs</errorMessage>
        <filterItems>
            <field>Casual__c.Grade__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Casual__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Job_Requisitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Casual_Job_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Casual_Job_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Specification</label>
    <referenceTo>Casual_Job_Line_Item__c</referenceTo>
    <relationshipLabel>Contractor-Job Assignments</relationshipLabel>
    <relationshipName>Casual_Job_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Job_Assignment__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Payment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/Casuals_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Assignment Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/EPR_Created__c.field-meta.xml
<CustomField>
    <fullName>EPR_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPR Created</label>
    <type>Checkbox</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Job_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Job_Requisition__c</fullName>
    <label>Job Assignment</label>
    <referenceTo>Casuals_Job_Assignment__c</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Legal Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Casuals_Timesheet__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Actual Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/Electronic_Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Electronic Payment Request</label>
    <nameField>
        <displayFormat>EPR-{0000}</displayFormat>
        <label>Electronic Payment Request name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sanergy Ltd</fullName>
            </value>
            <value>
                <fullName>Fresh Life Initiative Ltd</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (FP)</fullName>
            </value>
            <value>
                <fullName>Sanergy Inc (NP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/department__c.field-meta.xml
<CustomField>
    <fullName>department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requesting Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>dim1</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>XX</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>xx</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Vendor Invoice Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <description>The date when the payment is required</description>
    <label>Actual EPR Date</label>
    <type>Date</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Line Manager Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Company__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Vendor, Sanergy Employee Accounts, Sanergy Toilet Sale - FLO, Sanergy Funders, Sanergy Fresh Fit Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Electronic_Payment_Request__c/fields/Vendor_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Invoice Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Vendor Invoice does not belong to the Vendor Company you specified</errorMessage>
        <filterItems>
            <field>$Source.Vendor_Company__c</field>
            <operation>equals</operation>
            <valueField>Vendor_Invoice__c.Vendor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vendor_Invoice__c</referenceTo>
    <relationshipLabel>Electronic Payment Requests</relationshipLabel>
    <relationshipName>Electronic_Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/EPR_Payable_Item__c.object-meta.xml
<CustomObject>
    <label>EPR Payable Item</label>
    <nameField>
        <displayFormat>EPR ITEM-{0000}</displayFormat>
        <label>EPR Payable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPR Payable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/GLA__c.field-meta.xml
<CustomField>
    <fullName>GLA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The General Ledger Account</description>
    <label>GLA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>FFA_Config_Object__c.Type__c</field>
            <operation>equals</operation>
            <value>gla</value>
        </filterItems>
        <filterItems>
            <field>FFA_Config_Object__c.Name</field>
            <operation>notContain</operation>
            <value>DO NOT USE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FFA_Config_Object__c</referenceTo>
    <relationshipLabel>EPR Payable Items (GLA)</relationshipLabel>
    <relationshipName>EPR_Payable_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/EPR_Payable_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/Vendor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Vendor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Vendor Invoice stages</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Items Received</fullName>
            </value>
            <value>
                <fullName>Pin Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Vendor_Invoice__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sanergy Toilet Sale - FLO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Invoices</relationshipLabel>
    <relationshipName>Vendor_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/CreateEPRFromTimesheet.cls
public class CreateEPRFromTimesheet{
    
    //Controller
    ApexPages.StandardController controller;
    //timesheet
    Casuals_Timesheet__c timesheet {get; set;}
    
    //Constructor
    public CreateEPRFromTimesheet(ApexPages.StandardController controller){
        this.controller = controller;
        timesheet = (Casuals_Timesheet__c )controller.getRecord();
        
        timesheet=[SELECT Job_Requisition__r.Casual__r.account__c,EPR_Created__c,
                   name, Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Company__c, Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c,
                   Job_Requisition__r.Casual_Job_Line_Item__r.Location_Dim_2__c, Job_Requisition__r.Casual_Job_Line_Item__r.Dim3__c,
                    Job_Requisition__r.Casual_Job_Line_Item__r.Grant_Dim_4__c, Total_Amount__c, Job_Requisition__r.Casual_Job_Line_Item__r.GLA__c
                    FROM Casuals_Timesheet__c 
                    WHERE id =: timesheet.id];
    }
    
    //create EPR
    public PageReference createEPR(){
		// Create an instance of EPR
        Electronic_Payment_Request__c epr = new Electronic_Payment_Request__c();         
        
        if(timesheet.EPR_Created__c == false){
            
            // Select a Vendor Invoice
            List<Vendor_Invoice__c> vi = [SELECT Id,Name,Vendor__c,Status__c                                                     
                                          FROM Vendor_Invoice__c
                                          WHERE Vendor__c =: timesheet.Job_Requisition__r.Casual__r.account__c
                                          ORDER BY Name DESC                                              
                                          LIMIT 1];        
            
            // Loop through the list of Vendor Invoices
            for(Vendor_Invoice__c v : vi){
                
                //Create EPR
                epr.department__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c;
                epr.Vendor_Company__c = timesheet.Job_Requisition__r.Casual__r.account__c;
                epr.Invoice_Number__c = timesheet.name;
                epr.Company__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Company__c;
                epr.Vendor_Invoice_Number__c = vi.get(0).Id;               
                epr.Scheduled_Payment_Date__c = date.today();
                epr.Notes__c='Payment for Contractor Services as per Timesheet number '+timesheet.name;
                epr.Payment_Type__c = 'Payment on Invoice';
                
                insert epr;         
                
                // Create EPR Payable Item
                EPR_Payable_Item__c payableItem = new EPR_Payable_Item__c(            
                    epr__c=epr.id,
                    Department_dim1__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Casuals_Job__r.Department__c,
                    Location_Dim2__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Location_Dim_2__c,
                    Dim_3__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Dim3__c,
                    Grant_Funding_Availale_dim4__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.Grant_Dim_4__c, 
                    Item__c = epr.Notes__c,
                    Quantity__c = 1,
                    Unit_Price__c = timesheet.Total_Amount__c,
                    GLA__c = timesheet.Job_Requisition__r.Casual_Job_Line_Item__r.GLA__c
                    
                );
                
                insert payableItem;
                
                timesheet.EPR__c = epr.id;
                timesheet.EPR_Created__c = true;
                update timesheet;                
            }            
            return new PageReference('/'+epr.id);
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'An EPR has already been created for this timesheet record'));
            return null;
        }
       
    }
}