sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/Procurement_Tracking_Sheet__c.object-meta.xml
<CustomObject>
    <label>Procurement Request</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Procurement Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>a point, period, or step in a process or development.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Partial Receipt</fullName>
                <label>Items Partially  Received</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Maintenance Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Requesting Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QHSE Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Team_Lead_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_Approval_Status__c</fullName>
    <inlineHelpText>a condition set following approval steps</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved By Maintenance Team Lead</fullName>
            </value>
            <value>
                <fullName>Declined By Maintenance Team Lead</fullName>
            </value>
            <value>
                <fullName>Declined By Requesting Department Team Lead</fullName>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Declined By Finance</fullName>
            </value>
            <value>
                <fullName>Approved By Requesting Department Team Lead</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/PTS_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Procurement Request Line Item</label>
    <nameField>
        <displayFormat>PR-LI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Procurement_Tracking_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Procurement_Tracking_Sheet__c</fullName>
    <label>Procurement Tracking Sheet</label>
    <referenceTo>Procurement_Tracking_Sheet__c</referenceTo>
    <relationshipName>PTS_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfSandBoxCode/force-app/main/default/objects/PTS_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>the position of affairs at a particular time</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Item Request Approval</fullName>
            </value>
            <value>
                <fullName>Pending Sourcing</fullName>
            </value>
            <value>
                <fullName>Pending Quote Approval</fullName>
            </value>
            <value>
                <fullName>Pending Procurement Approval</fullName>
            </value>
            <value>
                <fullName>Pending Director Approval</fullName>
            </value>
            <value>
                <fullName>Requires Re-Approval</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Pending Purchase Order</fullName>
            </value>
            <value>
                <fullName>Purchase Order Created</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending User Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/ClonePRAndPRLineItemsController.cls
public class ClonePRAndPRLineItemsController {
    
    private ApexPages.StandardController standardController;
    public Procurement_Tracking_Sheet__c pr{get; set;}
    public Procurement_Tracking_Sheet__c PRequest{get;set;}
    public List<PTS_Line_Item__c> items{get;set;}
    public List<PTS_Line_Item__c> itemsToInsert {get;set;}
    public List<PRLineItemsWrapper> pRLineItemsWrapper {get; set;}
    ApexPages.Message myMsg;
    
    public ClonePRAndPRLineItemsController(ApexPages.StandardController standardController){
        this.standardController = standardController;
         // Record being cloned
        Procurement_Tracking_Sheet__c originalPR = (Procurement_Tracking_Sheet__c) standardController.getRecord();
        
        String soql = Utils.getCreatableFieldsSOQL('Procurement_Tracking_Sheet__c', 'Id=\'' + originalPR.Id + '\'');
        Procurement_Tracking_Sheet__c completePR = (Procurement_Tracking_Sheet__c)Database.query(soql);
         
        PRequest = completePR.clone(false, false, false, false);

        pRLineItemsWrapper = new List<PRLineItemsWrapper>();
                
        //Select Items
             String itemQry = Utils.getCreatableFieldsSOQL('PTS_Line_Item__c', 'Procurement_Tracking_Sheet__c=\'' + originalPR.Id + '\'');
             
             List<PTS_Line_Item__c> items = (List<PTS_Line_Item__c>)Database.query(itemQry);
                                         
        for(PTS_Line_Item__c item:items){
            PTS_Line_Item__c newLine = item.clone(false, false, false, false);
            PRLineItemsWrapper wr = new PRLineItemsWrapper(newLine);
            pRLineItemsWrapper.add(wr);
        }
    } 
    
     public PageReference selectAll() {
        if(pRLineItemsWrapper != null){
            for(PRLineItemsWrapper lg:pRLineItemsWrapper){
                lg.selected=true;                
            }
        }
        return null;
    }
    
    public PageReference unselectAll() {
        if(pRLineItemsWrapper != null){
            for(PRLineItemsWrapper lg:pRLineItemsWrapper){
                lg.selected=false;                
            }
        }
        return null;
    }
    
    public PageReference  processSelected() {
        
         if(pRLineItemsWrapper != null && pRLineItemsWrapper.size() > 0){
            
            integer issued = 0;
            integer expected = 0;
             try{
            	
            	PRequest.Id = null;
                PRequest.Stage__c = 'Open';
                PRequest.Team_Lead_Approval_Status__c = 'Pending';
                insert PRequest;
                 
                 itemsToInsert = new List<PTS_Line_Item__c>();

                 for(PRLineItemsWrapper item : pRLineItemsWrapper){
                     expected +=1;
                     item.newItem.Procurement_Tracking_Sheet__c = PRequest.Id;
                     item.newItem.Status__c = 'Open';                     
                     itemsToInsert.add(item.newItem);
                 }
                 insert itemsToInsert;
                 /*BatchInsertUtil batch=new BatchInsertUtil (itemsToInsert);
                 Database.executeBatch(batch, 100);*/
             //}
                 issued +=1;
                 
             }catch(Exception  e){
                 ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Error:'+e);
                 //System.debug('ERROR:'+e);
                 //ApexPages.addMessage(myMsg);
                 return null;

             }
            
        
            if(expected == issued && myMsg == null){
                return new PageReference('/' + PRequest.Id);
            } else {

                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,'Some Line Items were not edited');
                ApexPages.addmessage(msg);
                return null;
            }
            
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Kindly confirm that selected Request has Lines'));
            return null;
        }
        return null;
    }
    
    public class PRLineItemsWrapper{
        
        public PTS_Line_Item__c newitem {get; set;}
        public Boolean selected {get; set;}
        public PRLineItemsWrapper(PTS_Line_Item__c item) {
            newItem = item;
           
            this.selected = true;
        }
    }


}