sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/Procurement_Tracking_Sheet__c.object-meta.xml
<CustomObject>
    <label>Procurement Request</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Procurement Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfSandBoxCode/force-app/main/default/objects/Procurement_Tracking_Sheet__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>a point, period, or step in a process or development.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Partial Receipt</fullName>
                <label>Items Partially  Received</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Maintenance Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Requesting Team Lead Approved</fullName>
            </value>
            <value>
                <fullName>Approved By Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QHSE Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfSandBoxCode/force-app/main/default/classes/ClonePRLineItensControllerTest.cls
@isTest(seeAllData=true)
public class ClonePRLineItensControllerTest{
    static testMethod void testPRCloning(){
        List<Procurement_Tracking_Sheet__c> pr = [SELECT Id,Name, Stage__c 
                                          FROM Procurement_Tracking_Sheet__c
                                          Where Stage__c = 'Team Lead Approved' ORDER BY CreatedDate DESC LIMIT 1];
        if(pr.size()>0){
            PageReference clonePage = Page.ClonePRLinesfromCurrentPR;
            Test.setCurrentPage(clonePage);
            ApexPages.StandardController controller = new ApexPages.StandardController(pr.get(0));        
            ClonePRAndPRLineItemsController clonePR = new ClonePRAndPRLineItemsController(controller);       
            clonePR.selectAll();
            clonePR.processSelected();
            clonePR.unselectAll();
        
        }
    }
}